<div class="row">
    <?php echo $this->storesEditCombo(); ?>  
</div>
<div class="row">
<div class="col-md-4">
    <div class="control-group ">
        <label class="control-label" ><?php echo $this->translate("Type"); ?></label>
        <div class="controls">
            <?php echo $this->form->warehouse_type_update; ?>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="control-group ">
        <label class="control-label" ><?php echo $this->translate("Store/Facility"); ?></label>
        <div class="controls">
            <?php echo $this->form->store_name_update; ?>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="control-group ">
        <label class="control-label" ><?php echo $this->translate("CCM Code"); ?></label>
        <div class="controls">
            <?php echo $this->form->ccm_warehouse_id_update; ?>
        </div>
    </div>
</div>
    </div>

<?php echo $this->form->wh_id; ?>
<?php echo $this->form->office_id_edit; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->tehsil_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->warehouse_type_id_hidden; ?>

