<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Stores/Facilities (Routine)") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Stores/Facilities Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="asset_sub_type_search" action="" >
                                    <!-- Row -->


                                    <div class="row">

                                        <?php echo $this->routineCombo($this->combos); ?>

                                        <?php echo $this->form->province_id; ?>
                                        <?php echo $this->form->district_id; ?>
                                        <?php echo $this->form->tehsil_id; ?>
                                        <?php echo $this->form->parent_id; ?>

                                    </div>

                                    <div class="row">
                                        <div class="col-md-3">
                                            <label class="control-label" >&nbsp;</label>
                                            <div class="controls">
                                                <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Stores/Facilities List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="dataTables_wrapper form-inline">
                            
<!--                                <div class="col-md-3">
                                    <?php //$this->recordsPerPage($this->counter); ?>
                                </div>-->
                                <div>
                                    <div class="pull-right">
                                        <label>
                                            <a class="btn btn-primary" data-toggle="modal" href="#add-store"><?php echo $this->translate("Add Store/Facility") ?></a>
                                        </label>
                                    </div>
                                </div>
                            
                            <br><br>
                            <table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
                                <!-- Table heading -->
                                <?php
                                $fields = array(
                                    'store/facility' => 'Store/facility',
                                    'UC' => 'UC',
                                    'district' => 'District',
                                    'province' => 'Province',
                                    'status' => 'Status'
                                );
                                $this->tableHeading($this->order, $this->sort, $fields);
                                ?>
                                <!-- // Table heading END -->
                                <!-- Table body -->

                                <!-- // Table body END -->
                                <tbody>
                                    <?php
                                    $m_res = array();
                                    $i = 1;
                                     
                                    if ($this->result && count($this->result) > 0) :
                                        foreach ($this->result as $row):
                                            ?>
                                            <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                <td><?php echo $row['warehouseName']; ?></td>
                                                <td><?php echo $row['UC']; ?></td>
                                                <td><?php echo $row['districtName']; ?></td>
                                                <td><?php echo $row['provinceName']; ?></td>

                                                <td>
                                                    <?php
                                                    if ($row['status'] == 1) {
                                                        echo "Active";
                                                    } elseif ($row['status'] == 0) {
                                                        echo "In-Active";
                                                    }
                                                    ?>
                                                </td>
                                                <td><a itemid="<?php echo $row['pkId']; ?>" class="btn update-stores btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-stores"><?php echo $this->translate("Edit") ?></a>
                                                    <?php if ($this->warehouseDelete($row['pkId'])) { ?>
                                                    <?php } else { ?>
                                                        <a data-toggle="notyfy" data-bind="<?php echo $row['pkId']; ?>" data-status="<?php echo $row['status']; ?>" data-type="confirm" data-layout="top" class="btn-link btn-danger input-sm">
                                                            <?php
                                                            if ($row['status'] == 1) {
                                                                echo $this->translate("In-Active");
                                                            } elseif ($row['status'] == 0) {
                                                                echo $this->translate("Active");
                                                            }
                                                            ?>
                                                        </a>
                                                    <?php } ?>

                                                </td>

                                                <!-- // Table row END --><?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-stores/add-routine" id="add-stores">
            <div class="modal fade" id="add-store" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Add Stores/Facilities</h3>
                        </div>

                        <div class="modal-body">
                            <div class="row">
                                <?php echo $this->routineAddCombo($this->combos_1); ?>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Type"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->warehouse_type; ?>
                                        </div>
                                    </div>
                                </div>


                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Store/Facility"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->store_name_add; ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("CCM Code"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->ccm_warehouse_id; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-stores/update-routine" id="update-stores">
            <div class="modal fade" id="modal-update-stores" tabindex="-1" role="basic" aria-hidden="true" >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Stores/Facilities</h3>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer" id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->
