<?php
/**
*  Layout for Footer Reports.
*/

?>
</div>
<br>
<div style="margin-left: 200px; text-align: justify; text-justify: inter-word;">
    <ul>
        <li>
            <b> Average Monthly Consumption(AMC):</b> Average Monthly Consumption is calculated as average of aggregated consumption of the last three non-zero consumption months of vaccines and related products.
        </li>
        <li>
            <b> Months of Stock(MOS):</b> Months of Stock is the estimate of number of months the stock will last. This obtains by dividing Stock of Hand by average monthly consumption.
        </li>
        <li>
            <b>Stock on Hand(SOH):</b> Stock on Hand is the amount of product on hand in order to monitor stock positions and anticipate stock outs in advance.
        </li>

        For more acronyms <a href="<?php echo $this->baseUrl() ?>/index/acronyms">Click Here</a>

    </ul>
</div>
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

<!-- // Footer END -->
</div>
<div class="row">
    <div class="col-md-12 footer-stackholders">
        <span class="stackholders">Stakeholders</span>
    </div>
    <div class="col-md-12 bg-white" >
        <ul class="nav navbar-nav partners">
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/govt-of-pak-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/unicef-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/us-aid-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/who-logo.png" alt=""/></li>
        </ul>
    </div>
</div>

<div class="alert alert-error ">
    <div class="footer-inner">
        The presented analysis and reports are based on online reported storage and consumption data entered by >  <?php echo $this->layout()->total_user; ?> trained vLMIS operators (vaccinators and store keepers) of EPI program at the national, provinical, district and EPI center levels.
    </div>
</div>

<div class="footer">
    <div class="footer-inner">
<!--        &copy; 2014 - <?php //echo date("Y");    ?> - <a href="#">Vaccine Logistics Management System</a> - All Rights Reserved.-->
        For any comments and suggestions please write to support@lmis.gov.pk
        <a  href="http://lmis.gov.pk" style="color:white; padding-left: 700px;">
            http://lmis.gov.pk
        </a>

    </div>
    <div class="footer-tools">
        <span class="go-top">
            <i class="fa fa-angle-up"></i>
        </span>
    </div>
</div>


<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/core/app.js"></script>
<script>
    jQuery(document).ready(function() {
        App.init();
    });
</script>
<!-- END JAVASCRIPTS -->

<?php echo $this->inlineScript(); ?>

<script>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-48587374-1', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>

