<div class="sidebar">
    <div class="box-grey">
        <ul class="sidebar-list">
            <li>Are you interested in improving supply management of health commodities?</li>
            <li>Are you making informed, evidence-based decisions?</li>
            <li>Are you committed to improving collaboration among resource providers</li>
            <li>Are you playing a role in forecasting, quantification and supply planning?</li>
            <li>Are you preventing supply emergencies?</li>
        </ul>
        <p style="line-height: 140%; margin-top: 13px; font-weight: 600; font-size: 13px;">Achieving Logistics Data Visibility and Availability of Health Products at all levels through LMIS!</p>
    </div>
    <h2>Our Partners</h2>
    <div class="box-grey box">
        <ul class="partner-logos">

            <li><img src="images/govt-of-pak-logo.png" alt="" /></li>
            <li><img src="images/us-aid-logo.png" alt="" /></li>

            <li><img src="images/who-logo.png" alt="" /></li>
            <li><img src="images/unicef-logo.png" alt="" /></li>

        </ul>
    </div>
</div>