<div id="dashletMOS" style="width:540px;height:400px;position:relative">
    <div id="legendDiv" style="display:none;position:absolute;padding:5px;border-radius:5px;border:1px solid black;width:auto;height:auto;top:65%;font-size:10px;font-weight:bold;left:68%;z-index: 1000;">
        <table id='legend' style="width:100%"></table>
    </div>
    <div id='inputForm' style="width:auto;height:auto;position: absolute;top:0px;left:10%;z-index: 2000">
        <div class='col-md-12'> 
            <b>Month:</b>
            <select id='month_range' class='form-control input-inline' onchange="getFeatures()">   
            </select>  
        </div>
    </div>
    <div id='loader' style="display:none;width:25px;height:25px;position: absolute;top:30%;left:40%;z-index: 2000">
        <img  src="<?php echo $this->baseUrl(); ?>/images/ajax-loader.gif"/>
    </div>

    <div id="infoDiv" style="position:absolute;top:24%;left:2%;width:auto;height:auto;opacity : 0.85; border-radius:4px;background-color:green;color:white;text-align:center;padding: 3px;font-family: Arial;z-index:5000;"></div>
</div>