<?php
/**
 *  phtml for Ajax Item Edit
 */
?>

<div class="row">
    <div class="col-md-5">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Warehouse Type Category Name"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->wh_category_name; ?>
            </div>
        </div>
    </div>
   
</div>

<?php
echo $this->form->wh_category_id;
echo $this->form->wh_category_name_hidden;
?>
