<?php if (count($this->result) > 0) { ?>
    <div class="row">
        <div class="col-md-12">
           
                <table class="table table-striped table-bordered table-condensed" id="physicalStock">
                    <thead>
                        <tr>
                            
                            <th style="width:1%;">S.No</th>
                            <th>Product</th>
                            <th>Batch No.</th>
                            <th class="center">Expiry</th>
                            <th class="right">Current Quantity</th>
                            <th class="right">Physical Quantity</th>
                            <th class="center">VVM Stage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $count = 1;
                        foreach ($this->result as $row) {
                            ?>
                            <tr>
                             
                                <td><?php echo $count; ?></td>
                                <td align="left"><?php echo $row->getItemPackSize()->getItemName(); ?></td>
                                <td align="left"><?php echo $row->getBatchNumber(); ?></td>
                                <td align="center"><?php echo $row->getExpiryDate() != "" ? $row->getExpiryDate()->format("d/m/Y") : $row->getStockBatch()->getExpiryDate()->format("d/m/Y") ; ?></td>
                                <td align="right"><?php echo $row->getStockBatch() != "" ? $row->getStockBatch()->getQuantity() : "-"  ; ?></td>
                                <td align="right"><?php echo $row->getQuantity(); ?></td>  
                                <td align="left"><?php echo $row->getVvmStage()->getVvmStageValue(); ?></td>                                
                            </tr>
                            <?php $count++;
                        }
                        ?>
                    </tbody>
                </table>
              
               
           
        </div>
    </div>
<?php } else { ?>
    <div class="row">
        <div class="col-md-12">
            <h4>Transactions not found</h4>
        </div>
    </div>
<?php } ?>