<div class="row">
    <div class="col-md-12">
        <?php if ($this->detail_summary == 1) { ?>
        <table class="table table-striped table-bordered table-condensed" id="product_placement_detail">
            <thead>
                <tr>
                    <th class="center">
                        #
                    </th>
                    <th>
                        Cold Room
                    </th>
                   
                    <th>
                        VVM Stage
                    </th>
                    <th class="right">
                        Quantity (Vials)
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                $total = 0;
                if ($this->result != false) {
                    foreach ($this->result as $row) {
                        $total += $row['quantity'];
                        ?>
                        <tr>
                            <td class="center">
                                <?php echo $i; ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->baseUrl(); ?>/stock/stock-in-bin-vaccines?id=<?php echo $row['pk_id']; ?>&asset=<?php echo $row['asset_id']; ?>" target="_blank"><?php echo $row['asset_id']; ?></a>
                            </td>
                           
                            <td>
                                <?php echo $row['vvm_stage']; ?>
                            </td>
                            <td class="right">
                                <?php echo number_format($row['quantity']); ?>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    }
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="3" class="right">
                        Total:
                    </th>
                    <th class="right">
                        <?php echo number_format($total); ?>
                    </th>
                </tr>
            </tfoot>
        </table>
        <?php } else { ?>
         <table class="table table-striped table-bordered table-condensed" id="product_placement_detail">
            <thead>
                <tr>
                    <th class="center">
                        #
                    </th>
                    <th>
                        Cold Room
                    </th>
                    <th>
                        Batch Number
                    </th>
                    <th>
                        VVM Stage
                    </th>
                    <th class="right">
                        Quantity (Vials)
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                $total = 0;
                if ($this->result != false) {
                    foreach ($this->result as $row) {
                        $total += $row['quantity'];
                        ?>
                        <tr>
                            <td class="center">
                                <?php echo $i; ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->baseUrl(); ?>/stock/stock-in-bin-vaccines?id=<?php echo $row['pk_id']; ?>&asset=<?php echo $row['asset_id']; ?>" target="_blank"><?php echo $row['asset_id']; ?></a>
                            </td>
                            <td>
                                <?php echo $row['batch_number']; ?>
                            </td>
                            <td>
                                <?php echo $row['vvm_stage']; ?>
                            </td>
                            <td class="right">
                                <?php echo number_format($row['quantity']); ?>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    }
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="4" class="right">
                        Total:
                    </th>
                    <th class="right">
                        <?php echo number_format($total); ?>
                    </th>
                </tr>
            </tfoot>
        </table>
        <?php  } ?>
    </div>
</div>