<style>
    #content_print {
        margin-left: 55px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
</style>

<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>
<?php
$row = $this->result[0];
$transaction_number = $row['transactionNumber'];
$transaction_date = $row['transactionDate'];
$warehouse_name = $row['warehouseName'];
$comments = $row['comments'];
$reference = $row['transactionReference'];
$dispatch_by = $row['dispatchBy'];
$master_id = $row['pkId'];
?>
<div class="row">
    <div class="col-md-12">
        <table style="width:100%;">
            <tr>
                <td colspan="3" class="right"><b style="font-size: 16px;">Dispatch Voucher # <span style="font-family: Verdana; "><?php echo $transaction_number; ?></span> </b></td>
            </tr>
            <tr>
                <td><b>Date of Dispatch:</b> <?php echo date("d/m/Y", strtotime($transaction_date)); ?></td>
            </tr>
            <tr>
                <td><b>Ref. Number:</b> <?php echo (!empty($reference)) ? $reference : 'N/A'; ?></td>
                <td><b>Recipient:</b> <?php echo $warehouse_name; ?></td>
                <td class="right"><b>Transport Mode:</b> <?php echo (!empty($dispatch_by)) ? $dispatch_by : 'N/A'; ?></td>
            </tr>
        </table>
    </div>
</div>
<div class="row">
<div class="col-md-10">
    <br />
    <table id="mytable" cellpadding="2">
        <tr >
            <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
            <th rowspan="2" width="15%"><?php echo $this->translate("Item"); ?></th>
            <th rowspan="2" width="15%"><?php echo $this->translate("Batch Number"); ?></th>
            <th rowspan="2" width="15%"><?php echo $this->translate("Manufacturer"); ?></th>
            <th rowspan="2" width="10%"><?php echo $this->translate("Expiry Date"); ?></th>
            <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
            <th rowspan="2" width="9%"><?php echo $this->translate("VVM Stage"); ?></th>
        </tr>
        <tr style="background-color: #F8F8F8;">
            <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
            <th width="10%"><?php echo $this->translate("Doses Per Vials"); ?></th>
            <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
        </tr>
        <tbody>
            <?php
            $i = 0;
            if (!empty($this->result)) {
                foreach ($this->result as $val) {
                    $i++;
                    ?>
                    <tr>
                        <td align="center"><?php echo $i; ?></td>
                        <td align="left"><?php echo $val['itemName']; ?></td>	    
                        <td align="left"><?php echo $val['number']; ?></td>
                        <td align="center"><?php echo $val['stakeholderName']; ?></td>
                        <td align="center"> <?php echo date("d/m/y", strtotime($val['expiryDate'])); ?></td>
                        <td align="right"><?php echo number_format($val['quantity']); ?></td>
                        <td align="center"><?php echo $val['numberOfDoses']; ?></td>
                        <td align="right"><?php echo number_format($val['quantity'] * $val['numberOfDoses']); ?></td>
                        <td align="center"><?php echo '&nbsp;' . $val['vvmStage']; ?></td>
                    </tr>
                    <?php
                }
            }
            ?>
        </tbody>
    </table>
    <br />
</div>
</div>
<?php $query2 = $this->reports()->getSummaryList($master_id); ?>
<div class="row">
<div class="col-md-6">
    <table id="mytable" style="width:60%;" cellpadding="2">
        <!-- Table heading -->
        <thead>
            <tr>
                <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
                <th rowspan="2" align="left"><?php echo $this->translate("Item"); ?></th>
                <th colspan="2" align="center"><?php echo $this->translate("Quantity"); ?></th>
            </tr>
            <tr>
                <th align="right"><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th align="right"><?php echo $this->translate("Doses/Pcs"); ?></th>
            </tr>
        </thead>
        <!-- // Table heading END -->
        <!-- Table body -->
        <tbody>
            <!-- Table row -->
            <?php
            $total = 0;
            $i = 1;
            foreach ($query2 as $row) {
                $total = $total + $row['total_cost'];
                ?>  
                <tr>
                    <td align="center"><?php echo $i; ?></td>
                    <td align="left"><?php echo $row['item_name']; ?></td>
                    <td align="right"><?php echo number_format($row['net_received']); ?></td>
                    <td align="right"><?php echo number_format($row['total_doses']); ?></td>
                </tr>
    <?php $i++;
} ?>
            <!-- // Table row END -->
        </tbody>
        <!-- // Table body END -->
        <!-- <tfoot>
            <tr>
                <td colspan="4" class="right"><b>Total Price: </b> <b><?php //echo round(number_format($total),2);  ?> (Rs.)</b></td>
            </tr>
        </tfoot> -->
    </table> 
</div>
    </div>
<?php if (!empty($comments)) { ?>
    <p><b>Remarks:</b> <?php echo $comments; ?></p>
<?php } ?>
   <div class="row"> 
<div style="width:100%; clear:both; margin-top:30px;">
    <table width="48%" cellpadding="5" style="float:left; border:0px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Issued by: </b></td>
            <td>.........................................................</td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>.........................................................</td>
        </tr>
        <tr>
            <td>Designation:</td>
            <td>.........................................................</td>
        </tr>
        <tr>
            <td>Date:</td>
            <td>.........................................................</td>
        </tr>
    </table>
    <table width="48%" cellpadding="5" style="float:right; border:0px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Received by: </b></td>
            <td>.........................................................</td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>.........................................................</td>
        </tr>
        <tr>
            <td>Designation:</td>
            <td>.........................................................</td>
        </tr>
        <tr>
            <td>Date:</td>
            <td>.........................................................</td>
        </tr>
    </table>
</div>
       </div>

<div class="row" style="clear: both; padding-top: 20px;">
    <div class="col-md-12 center"><br><br>
        ...............................................<br>
        <b>INCHARGE STORE</b><br>
        <b><?php echo $this->department; ?></b>

    </div>
</div>
<div class="row" style="clear: both;">
    <div class="col-md-12 left">
        Print By: ..................................
    </div>
</div>
<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div> 	  

<!-- // Row END --> 

<!-- // Content END -->