
<script>
    function printContents() {
        var dispSetting = "toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes, left=100, top=25";
        var printingContents = document.getElementById("dataEntryfrm").innerHTML;

        var docprint = window.open("", "", dataEntryfrm);
        docprint.document.open();
        docprint.document.write('<html><head><title>CLR6</title>');
        docprint.document.write('</head><body onLoad="self.print(); self.close()"><center>');
        docprint.document.write(printingContents);
        docprint.document.write('</center></body></html>');
        docprint.document.close();
        docprint.focus();
    }
</script>
<!-- Content -->
<div id="content_print">

    <style>
        #content_print {
            margin-left: 50px;
            width: 624px;
        }
        table#mytable {
            border: 1px solid #e5e5e5;
            font-size: 10px;
            width: 100%;
        }
        table#mytable tr td {
            border: 1px solid #e5e5e5;
        }
        table#mytable tr th {
            border: 1px solid #e5e5e5;
        }
    </style>
    <!-- Content -->

    <style type="text/css" media="print">
        .page
        {
            -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
            filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
        }
        @media print
        {
            #printButt
            {
                display: none !important;
            }
        }
    </style>
    <style>
        *{
            font-family: sans-serif;
        }
        td{
            border: 1px solid gray;
        }
        th{
            border: 1px solid gray;
            background-color: #F1F1F1;
        }
        h2{
            text-align: center;
        }
        table{
            border-collapse: collapse;
        }
        input{
            width: 96%;
        }
        input:focus{
            border: 1px solid red;
            background-color: #FFE4E1;
        }
    </style>
    <div style="clear:both"></div>


    <div style="width: 54%;  float: left; margin-top: 24px; padding-bottom: 10px;">

        <table style="width:100%;">
            <thead>
                <tr>
                    <th class="center">Month</th>
                    <td><?php echo date('F', mktime(0, 0, 0, $this->mm, 1)); ?></td>
                    <th class="center">Year</th>
                    <td><?php echo $this->year ?></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="center">District</th>
                    <td colspan="3"><?php echo $this->district_name; ?></td>
                </tr>
                <tr>
                    <th class="center">Taluka</th>
                    <td colspan="3"><?php echo $this->tehsil_name; ?></td>
                </tr>
                <tr>
                    <th class="center">UC</th>
                    <td colspan="3"><?php echo $this->uc_name; ?></td>
                </tr>
                <tr>
                    <th class="center">EPI Center</th>
                    <td colspan="3"><?php echo $this->warehouse_name; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div style="width: 44%; float: right; padding-bottom: 10px;">
        <table style="width:100%">
            <caption><h4>MONTHLY TARGETS</h4></caption>

            <?php
            $row0 = $this->monthlyConsumtion2()->monthlyConsumtion2Targets($this->wh_id, $this->rpt_date);



            if ($this->is_new_report == 1 && count($row0) < 0) {
                ?>
                <thead>
                    <tr>
                        <td class="center">Children Live Birth</td>
                        <td><input type="text" name="children_live_birth" id="children_live_birth" class="form-control col-md-1"></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="center">Surviving Children (0-11 M)</td>
                        <td><input type="text" name="surviving_children_0_11_M" id="surviving_children_0_11_M" class="form-control col-md-1"></td>
                    </tr>
                    <tr>
                        <td class="center">Children Aged (12-23 M)</td>
                        <td><input type="text" name="children_aged_12_23_M" id="children_aged_12_23_M" class="form-control col-md-1"></td>
                    </tr>
                    <tr>
                        <td class="center">Pregnant Women</td>
                        <td><input type="text" name="pregnant_women1" id="pregnant_women1" class="form-control col-md-1"></td>
                    </tr>
                    <tr>
                        <td class="center">CBAs</td>
                        <td><input type="text" name="cba" id="cba" class="form-control col-md-1"></td>
                    </tr>
                </tbody>
            <?php } else if ($this->is_new_report == 1 && count($row0) > 0) {
                ?>
                <thead>
                    <tr>
                        <td class="center">Children Live Birth</td>
                        <td><input type="text" name="children_live_birth" id="children_live_birth" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['children_live_birth'])) ? $row0['children_live_birth'] : '0'; ?>"></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="center">Surviving Children (0-11 M)</td>
                        <td><input type="text" name="surviving_children_0_11_M" id="surviving_children_0_11_M" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['surviving_children_0_11'])) ? $row0['surviving_children_0_11'] : '0'; ?>"></td>
                    </tr>
                    <tr>
                        <td class="center">Children Aged (12-23 M)</td>
                        <td><input type="text" name="children_aged_12_23_M" id="children_aged_12_23_M" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['children_aged_12_23'])) ? $row0['children_aged_12_23'] : '0'; ?>"></td>
                    </tr>
                    <tr>
                        <td class="center">Pregnant Women</td>
                        <td><input type="text" name="pregnant_women1" id="pregnant_women1" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['pregnant_women'])) ? $row0['pregnant_women'] : '0'; ?>"></td>
                    </tr>
                    <tr>
                        <td class="center">CBAs</td>
                        <td><input type="text" name="cba" id="cba" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['cbas'])) ? $row0['cbas'] : '0'; ?>"></td>
                    </tr>
                </tbody>
            <?php } else if ($this->is_new_report == 2 && count($row0) > 0) {
                ?>
                <thead>
                    <tr>
                        <td class="center">Children Live Birth</td>
                        <td><?php echo (!empty($row0['children_live_birth'])) ? $row0['children_live_birth'] : '0'; ?></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="center">Surviving Children (0-11 M)</td>
                        <td><?php echo (!empty($row0['surviving_children_0_11'])) ? $row0['surviving_children_0_11'] : '0'; ?></td>
                    </tr>
                    <tr>
                        <td class="center">Children Aged (12-23 M)</td>
                        <td><?php echo (!empty($row0['children_aged_12_23'])) ? $row0['children_aged_12_23'] : '0'; ?></td>
                    </tr>
                    <tr>
                        <td class="center">Pregnant Women</td>
                        <td><?php echo (!empty($row0['pregnant_women'])) ? $row0['pregnant_women'] : '0'; ?></td>
                    </tr>
                    <tr>
                        <td class="center">CBAs</td>
                        <td><?php echo (!empty($row0['cbas'])) ? $row0['cbas'] : '0'; ?></td>
                    </tr>
                </tbody>
            <?php } else { ?>
                <thead>
                    <tr>
                        <td class="center">Children Live Birth</td>
                        <td><input type="text" name="children_live_birth" id="children_live_birth" class="form-control col-md-1"  value="<?php echo (!empty($row0['children_live_birth'])) ? $row0['children_live_birth'] : '0'; ?>"></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="center">Surviving Children (0-11 M)</td>
                        <td><input type="text" name="surviving_children_0_11_M" id="surviving_children_0_11_M" class="form-control col-md-1" value="<?php echo (!empty($row0['surviving_children_0_11'])) ? $row0['surviving_children_0_11'] : '0'; ?>"></td>
                    </tr>
                    <tr>
                        <td class="center">Children Aged (12-23 M)</td>
                        <td><input type="text" name="children_aged_12_23_M" id="children_aged_12_23_M" class="form-control col-md-1" value="<?php echo (!empty($row0['children_aged_12_23'])) ? $row0['children_aged_12_23'] : '0'; ?>"></td>
                    </tr>
                    <tr>
                        <td class="center">Pregnant Women</td>
                        <td><input type="text" name="pregnant_women1" id="pregnant_women1" class="form-control col-md-1" value="<?php echo (!empty($row0['pregnant_women'])) ? $row0['pregnant_women'] : '0'; ?>"></td>
                    </tr>
                   <tr>
                        <td class="center">CBAs</td>
                        <td><input type="text" name="cba" id="cba" class="form-control col-md-1" value="<?php echo (!empty($row0['cbas'])) ? $row0['cbas'] : '0'; ?>"></td>
                    </tr>
                </tbody>
            <?php } ?>
        </table>




    </div>
    <div style="clear:both;">  Filled By ___________________________Date___________________ Sign._________________     </div>
    </br>
    <table width="100%" cellpadding="3" id="mytable">
        <thead>
            <tr>
                <th rowspan="4">Product</th>
                <th rowspan="4">Opening Balance (Doses)</th>
                <th rowspan="4">Received (Doses)</th>
                <th colspan="9">Number of Children Vaccinated (0-11 Months)</th>
                <th colspan="8">Number of Children Vaccinated (12-23 Months)</th>
                <th rowspan="4">Closing Balance (Doses)</th>
                <th rowspan="4">Unusable (Doses)</th>
            </tr>
            <tr>
                <th rowspan="2">#</th>
                <th colspan="4">Fixed</th>
                <th colspan="2" rowspan="2" style="background-color: #FFCC99;" >Referral from Outside UCs*</th>
                <th colspan="2" rowspan="2">Out</br>reach</th>
                <th colspan="4">Fixed</th>
                <th colspan="2" rowspan="2" style="background-color: #FFCC99;"> Referral from Outside UCs*</th>
                <th colspan="2" rowspan="2">Out</br>reach</th>
            </tr>
            <tr>
                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>

                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>

            </tr>
            <tr>
                <th></th>
                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
                <th style="background-color: #FFCC99;">M</th>
                <th style="background-color: #FFCC99;">F</th>
                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
                <th style="background-color: #FFCC99;">M</th>
                <th style="background-color: #FFCC99;">F</th>
                <th>M</th>
                <th>F</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->items as $result):
                ?>

                <?php
                //  App_Controller_Functions::pr($row);
                if ($this->is_new_report == 1) {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->prev_month_date, $result['pk_id'], '145');
                    //$row_reff = $this->monthlyConsumtion2()->monthlyConsumtionRefferal($this->wh_id, $this->prev_month_date, $result['pk_id']);
                } else {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->rpt_date, $result['pk_id'], '145');
                    $row3 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->rpt_date, $result['pk_id'], '146');
                      $row_reff_male = $this->monthlyConsumtion2()->monthlyConsumtionRefferal($this->wh_id, $this->rpt_date, $result['pk_id'], 'Male');
                      $row_reff_female = $this->monthlyConsumtion2()->monthlyConsumtionRefferal($this->wh_id, $this->rpt_date, $result['pk_id'], 'Female');
                }

                $counter = 1;
                $nod = $result['no_of_doses'];
                $max_i;
                ?>
                <?php if ($this->is_new_report == 2) {
                    ?>
                    <?php
                    $j = 0;
                    for ($i = $result['start_no']; $i <= $result['no_of_doses']; $i++) {
                        if ($i == 0) {
                            $nod += 1;
                        }
                        ?>
                        <tr>
                            <?php if ($counter == 1) { ?>
                                <td rowspan="<?php echo $nod ?>"><?php echo $result['item_name'] ?></td>
                        <input type="hidden" name="flitm_id[]" value="<?php echo $result['pk_id']; ?>" />
                        <input type="hidden" name="doses_per_unit[]" id="<?php echo $result['pk_id']; ?>-doses" value="<?php echo $result['description']; ?>" />
                        <input type="hidden" name="start_no[]" id="<?php echo $result['pk_id']; ?>-start_no" value="<?php echo $result['start_no']; ?>" />
                        <input type="hidden" name="no_of_doses[]" id="<?php echo $result['pk_id']; ?>-no_of_doses" value="<?php echo $result['no_of_doses']; ?>" />

                        <td rowspan="<?php echo $nod ?>">
                            <?php echo (!empty($row2[0]['openingBalance'])) ? $row2[0]['openingBalance'] : '0'; ?>
                        </td>


                        <td rowspan="<?php echo $nod ?>">
                            <?php echo (!empty($row2[0]['receivedBalance'])) ? number_format($row2[0]['receivedBalance']) : '0'; ?>
                        </td>

                    <?php } ?>
                    <input type="hidden" name="vaccine_schedule_id[]" value="<?php echo ($i == 1 && $i == $nod) ? '' : $i; ?>" />
                    <td><?php echo ($i == 1 && $i == $nod) ? '' : $i; ?></td>
                    <td> <?php echo (!empty($row2[$j]['fixed_inside_uc_male']) ) ? $row2[$j]['fixed_inside_uc_male'] : '0'; ?></td>
                    <td> <?php echo (!empty($row2[$j]['fixed_inside_uc_female']) ) ? $row2[$j]['fixed_inside_uc_female'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row2[$j]['fixed_outside_uc_male']) ) ? $row2[$j]['fixed_outside_uc_male'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row2[$j]['fixed_outside_uc_female'])) ? $row2[$j]['fixed_outside_uc_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row_reff_male['total']) ) ? $row_reff_male['total'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row_reff_female['total'])) ? $row_reff_female['total'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row2[$j]['outreach_male']) ) ? $row2[$j]['outreach_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row2[$j]['outreach_female']) ) ? $row2[$j]['outreach_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['fixed_inside_uc_male'])) ? $row3[$j]['fixed_inside_uc_male'] : '0'; ?></td>
                    <td> <?php echo (!empty($row3[$j]['fixed_inside_uc_female']) ) ? $row3[$j]['fixed_inside_uc_female'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row3[$j]['fixed_outside_uc_male']) ) ? $row3[$j]['fixed_outside_uc_male'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row3[$j]['fixed_outside_uc_female'])) ? $row3[$j]['fixed_outside_uc_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['referal_male']) ) ? $row3[$j]['referal_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['referal_female']) ) ? $row3[$j]['referal_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['outreach_male']) ) ? $row3[$j]['outreach_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['outreach_female'])) ? $row3[$j]['outreach_female'] : '0'; ?>  </td>
                    <?php if ($counter == 1) { ?>
                        <td>
                            <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?>
                        </td>
                        <td> <?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?> </td>
                    <?php } ?> </tr>

                    <?php
                    $counter++;
                    $j++;
                }
                ?>


            <?php } ?>
        <?php endforeach; ?>


        </tbody>
    </table>

    <h6>TT- Coverage</h6>
    <table width="100%" cellpadding="3" id="mytable">
        <thead>
            <tr>
                <th class="center">Product</th>

                <th class="center">Opening Balance (Doses)</th>
                <th class="center">Received (Doses)</th>
                <th class="center">S. No</th>
                <th class="center">Pregnant Women</th>
                <th class="center">CBAs</th>
                <th class="center">Closing Balance (Doses)</th>
                <th class="center">Unusable (Doses)</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->items_tt as $result) {
                if ($this->is_new_report == 1) {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTt($this->wh_id, $this->prev_month_date, $result['pk_id']);
                } else {

                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTt($this->wh_id, $this->rpt_date, $result['pk_id']);
                }
                // App_Controller_Functions::pr($row2);
                ?>
                <?php
                if ($this->is_new_report == 2) {

                    $j = 0;
                    for ($i = 1; $i <= 6; $i++) {
                        ?>
                        <tr>
                            <?php
                            if ($i == 1) {
                                ?>   <td rowspan = "6" class="center"><?php echo $result['item_name'] ?></td>
                                <td rowspan = "6"> <?php echo (!empty($row2[0]['openingBalance'])) ? $row2[0]['openingBalance'] : '0'; ?></td>
                                <td rowspan = "6"> <?php echo (!empty($row2[0]['receivedBalance'])) ? number_format($row2[0]['receivedBalance']) : '0'; ?></td>     <?php
                            }
                            ?>
                            <?php
                            if ($i <= 5) {
                                ?>
                        <input type="hidden" name="vaccine_schedule_id[]" value="<?php echo $i; ?>" />
                        <td class="center"><?php echo $i ?></td>

                        <td >
                            <input type="hidden"  name="pregenant_women[]"  id="<?php echo $result['pk_id']; ?>-pregenant_women" class="pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['pregnant_women'])) ? number_format($row2[$j]['pregnant_women']) : '0'; ?>">


                            <?php echo (!empty($row2[$j]['pregnant_women'])) ? number_format($row2[$j]['pregnant_women']) : '0'; ?></td>

                        <?php
                    }
                    ?>
                    <?php
                    if ($i == 6) {
                        ?>
                        <td class="center">Total</td>
                        <td id="pregenant_women_total_view"></td>

                        <?php
                    }
                    ?>

                    <?php
                    if ($i <= 5) {
                        ?>

                        <td class="non_pregnant_women">
                            <input type="hidden"  name="non_pregnant_women[]"  id="<?php echo $result['pk_id']; ?>-non_pregenant_women" class="non_pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?>">
                            <?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?></td>

                        <?php
                        $j++;
                    }
                    ?>
                    <?php
                    if ($i == 6) {
                        ?>

                        <td  id="non_pregenant_women_total_view"></td>

                        <?php
                    }
                    ?>


                    <?php
                    if ($i == 1) {
                        ?>
                        <td rowspan="6"> <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?></td>
                        <td rowspan="6"><?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?></td><?php
                    }
                    ?>
                    </tr>
                    <?php
                }
            }
            ?>
        <?php } ?>
        </tbody>
    </table>

    <h6>Other Items</h6>
    <table width="100%" cellpadding="3" id="mytable">
        <thead>
            <tr>
                <th>Product</th>
                <th>Opening Balance (No)</th>
                <th>Received (No)</th>
                <th>Dispensed (No)</th>
                <th>Closing Balance (No)</th>
            </tr>
        </thead>
        <tbody>

            <?php
            foreach ($this->items_non_vaccinces as $result) {

                if ($this->is_new_report == 1) {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumptionNonVaccinces($this->wh_id, $this->prev_month_date, $result['pk_id']);
                } else {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumptionNonVaccinces($this->wh_id, $this->rpt_date, $result['pk_id']);
                }
                ?>

                <?php if ($this->is_new_report == 2) { ?>
                    <tr>
                        <td><?php echo $result['item_name'] ?></td>
                        <td><?php echo (!empty($row2['openingBalance'])) ? $row2['openingBalance'] : '0'; ?></td>
                        <td><?php echo (!empty($row2['receivedBalance'])) ? $row2['receivedBalance'] : '0'; ?></td>
                        <td><?php echo (!empty($row2['issueBalance'])) ? $row2['issueBalance'] : '0'; ?></td>
                        <td><?php echo (!empty($row2['closingBalance'])) ? $row2['closingBalance'] : '0'; ?></td>


                    </tr>
                <?php } ?>

                <?php
            }
            ?>
        </tbody>


    </table>
    <div style="clear:both;"></div>
    <div style="width:100%;text-align:right; margin-bottom:10px;"><button type="button" id="printButt" class="btn btn-primary" onclick="printCont()">Print</button></div>
    <div style="clear:both;"></div>
</div>