<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
</style>
<!-- Content -->
<style type="text/css" media="print">
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>

<?php if (!empty($this->arr_data['tempstocks']) && count($this->arr_data['tempstocks']) > 0) { ?>

    <?php
    //echo $this->arr_data['tempstocks']['0']['from_warehouse'];
    // exit;
    // App_Controller_Functions::pr($this->arr_data['tempstocks']); 
    ?>
    <div style="text-align:center;">
        <b style="float:left;">R.V.No.: <?php echo $this->arr_data['transaction_reference']; ?></b>
        <b style="float:right;">Receive Date: <?php echo $this->arr_data['transaction_date']; ?></b>
    </div>
    <div style="clear:both;">
        <b>Source: <?php echo $this->arr_data['tempstocks']['0']['from_warehouse']; ?></b>
    </div>

    <table id="mytable">
        <tr >
            <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
            <th rowspan="2" width="10%"><?php echo $this->translate("Product"); ?></th>
            <th rowspan="2" width="10%"><?php echo $this->translate("Batch No"); ?></th>
            <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
           
            <th rowspan="2" width="9%"><?php echo $this->translate("VVM Type"); ?></th>
            <th rowspan="2" width="9%"><?php echo $this->translate("VVM Stage"); ?></th>
            <th rowspan="2" width="12%"><?php echo $this->translate("Production Date"); ?></th>
            <th rowspan="2" width="10%"><?php echo $this->translate("Expiry Date"); ?></th>
        </tr>
        <tr style="background-color: #F8F8F8;">
            <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
            <th width="10%"><?php echo $this->translate("Doses Per Vial"); ?></th>
            <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
        </tr>
        <tbody>
            <?php
            $i = 0;
            $summary_arr = array();
            $product = '0';
            foreach ($this->arr_data['tempstocks'] as $val) {
                $i++;
                if ($product != $val['item_name']) {
                    $summary_arr[$val['item_name']]['quantity'][] = abs($val['quantity']);
                    $summary_arr[$val['item_name']]['doses'][] = ($val['description'] * abs($val['quantity']));
                    $product = $val['item_name'];
                } else {
                    $summary_arr[$val['item_name']]['quantity'][] = abs($val['quantity']);
                    $summary_arr[$val['item_name']]['doses'][] = ($val['description'] * abs($val['quantity']));
                }
                ?>
                <tr>
                    <td align="right"><?php echo $i; ?></td>
                    <td align="left"><?php echo $val['item_name']; ?></td>	    
                    <td align="right"><?php echo $val['number']; ?></td>
                    <td align="right"><?php echo $val['quantity']; ?></td>
                    <td align="right"><?php echo $val['description']; ?></td>
                    <td align="right"><?php echo $val['quantity'] * $val['description']; ?></td>
                    
                    <td align="left"><?php echo '&nbsp;' . $val['vvm_type_name']; ?></td>
                    <td align="right"><?php echo '&nbsp;' . $val['vvm_stage']; ?></td>
                    <td align="center"><?php echo date("d/m/Y", strtotime($val['production_date'])); ?></td>
                    <td align="center"> <?php echo date("d/m/Y", strtotime($val['expiry_date'])); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>

    </table>

    <h5 style="margin-top:30px;" class="heading"><?php echo $this->translate("Summary"); ?></h5>
    <table id="mytable" style="width:70%;">
        <thead>
            <tr>
                <th><?php echo $this->translate("Product"); ?></th>
                <th><?php echo $this->translate("Quantity Dose"); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($summary_arr as $product => $qty) {
                ?>
                <tr>
                    <td><?php echo $product; ?></td>
                    <td><?php echo number_format(array_sum($summary_arr[$product]['quantity'])) . ' / ' . number_format(array_sum($summary_arr[$product]['doses'])); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>


    <div class="col-md-12">
        <?php echo $this->render('stock/footer-signature.phtml') ?>
    </div>  
    <div class="col-md-12" class="widget" id="printButt">
        <div class="widget-body right">
            <input type="button" name="print" value="<?php echo $this->translate("Print"); ?>" class="btn btn-warning" onclick="javascript:printCont();" />
        </div>
    </div> 	  

<?php } ?>
<!-- // Row END --> 

<!-- // Content END -->