<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #e5e5e5;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #e5e5e5;
    }
    table#mytable tr th {
        border: 1px solid #e5e5e5;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page
    {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>

<table style="width:100%;">
    <tr>
        <td class="center" colspan="3"><b style="font-size: 16px;"><?php echo $this->print_title?>  </b></td>
    </tr>
</table>
<br />

<table id="mytable">
    <tr>
        <th rowspan="2" class="col-md-2"><?php echo $this->translate("Date") ?></th>
        <th rowspan="2" class="col-md-2"><?php echo $this->translate("Adjustment No") ?></th>
        <th rowspan="2" ><?php echo $this->translate("Ref No") ?></th>
        <th rowspan="2" ><?php echo $this->translate("Product") ?></th>
        <th rowspan="2" ><?php echo $this->translate("Batch No") ?></th>
        <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
        <th rowspan="2" class="col-md-2"><?php echo $this->translate("Adjustment Type") ?></th>
        <th rowspan="2" ><?php echo $this->translate("Comments") ?></th>
    </tr>
    <tr style="background-color: #F8F8F8;">
        <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
        <th width="10%"><?php echo $this->translate("Doses Per Vial"); ?></th>
        <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
    </tr>
    <tbody>
        <?php
        $m_res = array();
        $i = 1;
        if (count($this->result) > 0) :
            foreach ($this->result as $row):

                ?>
                <tr >
                    <td align="center"><?php echo date("d/m/Y", strtotime($row['transactionDate'])); ?></td>
                    <td align="left"><?php echo $row['transactionNumber']; ?></td>
                    <td align="left"><?php echo $row['transactionReference']; ?></td>
                    <td align="left"><?php echo $row['itemName']; ?></td>
                    <td align="right"><?php echo $row['number']; ?></td>
                    <td align="right"><?php echo abs($row['quantity']); ?></td>
                    <td align="right"><?php echo abs($row['numberOfDoses']); ?></td>
                    <td align="right"><?php echo abs($row['quantity'] * $row['numberOfDoses']); ?></td>
                    <td align="left"><?php echo $row['transactionTypeName']; ?></td>
                    <td align="left"><?php echo $row['comments']; ?></td>
                </tr>

                <!-- // Table row END --><?php
                $i++;
            endforeach;
        endif;
        ?>
    </tbody>

</table>
<br />

<div style="width:100%; clear:both; margin-top:30px;">
    <table width="100%" cellpadding="5" style="float:left; border:2px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Adjustments by</b> - Name: ____________________________</td>
        </tr>
        <tr>
            <td>Designation: __________________________________</td>
        </tr>
        <tr>
            <td>Signature: ____________________________________</td>
        </tr>
    </table>
<!--    <table width="48%" cellpadding="5" style="float:right; border:2px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Received by</b> - Name: _________________________</td>
        </tr>
        <tr>
            <td>Designation: __________________________________</td>
        </tr>
        <tr>
            <td>Signature: ____________________________________</td>
        </tr>
    </table>-->
</div>

<div class="col-md-12" class="widget">

    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print") ?></button>
    </div>
</div> 	  

