<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #e5e5e5;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #e5e5e5;
    }
    table#mytable tr th {
        border: 1px solid #e5e5e5;
    }
</style>
<!-- Content -->
<style type="text/css" media="print">
    .page {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print {
        #printButt {
            display: none !important;
        }
    }
</style>
<table style="width:100%;">
    <tr>
        <td class="center" colspan="3"><b style="font-size: 16px;"><?php echo $this->print_title?>  </b></td>
    </tr>
</table>
<br />
<?php
if (count($this->result) > 0) {
    $params = '';
    foreach ($this->params as $key => $value) {
        $params .= $key . "=" . $value . "&";
    }
    ?>
    <div class="row">
        <div class="col-md-12 right"><a title="Export to Excel" href="<?php echo $this->baseUrl(); ?>/stock/export-excel?<?php echo $params; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" /></a></div>
    </div>
<?php } ?>
<br />
<?php
if ($this->result && count($this->result) > 0) :
    foreach ($this->result as $val) {
        $productArr[$val['itemName']][] = $val;
        $locationArr[$val['warehouseName']][] = $val;
    }
endif;
?>

<?php
if ($this->val != 'none') {
    if ($this->result && count($this->result) > 0 && $this->val == 'prod') {
        //echo "<pre>";
        foreach ($productArr as $key => $data) {
            // create a simple 2-dimensional array            
            ?>
            <b><?php echo $key; ?></b>
            <table id="mytable" >
                <tr>
                    <th rowspan="2" width="6%"><?php echo $this->translate("S No") ?></th>
                    <th rowspan="2" width="12%"><?php echo $this->translate("Issue") ?><br><?php echo $this->translate("Date") ?></th>
                    <th rowspan="2" ><?php echo $this->translate("Issued To") ?></th>
                    <th rowspan="2" width="12%"><?php echo $this->translate("Batch No") ?></th>
                    <th rowspan="2" width="12%"><?php echo $this->translate("Expiry Date") ?></th>
                    <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>  
                    <th rowspan="2" width="8%"><?php echo $this->translate("VVM") ?><br><?php echo $this->translate("Stage") ?></th>
                </tr>
                <tr style="background-color: #F8F8F8;">
                    <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
                    <th width="10%"><?php echo $this->translate("Doses Per Vials"); ?></th>
                    <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
                </tr>
                <tbody>
                    <?php
                    $i = 0;
                    $totalVials = 0;
                    $totalDoses = 0;
                    foreach ($data as $val) {
                        $i++;
                        $totalVials += abs($val['quantity']);
                        $totalDoses += ($val['description'] * abs($val['quantity']));
                        ?>
                        <tr>
                            <td style="text-align:right;"><?php echo $i; ?></td>
                            <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($val['transactionDate'])); ?></td>
                            <td style="text-align:left;"><?php echo $val['warehouseName']; ?> </td>
                            <td style="text-align:left;"><?php echo $val['number']; ?></td>
                            <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($val['expiryDate'])); ?></td>
                            <td style="text-align:right;"><?php echo abs($val['quantity']); ?></td>
                            <td style="text-align:right;"><?php echo $val['description'] ?></td>
                            <td style="text-align:right;"><?php echo number_format(($val['description'] * abs($val['quantity']))); ?></td>
                            <td style="text-align:left;"><?php echo !empty($val['vvmStage']) ? $val['vvmStage'] : 'N/A'; ?></td>
                        </tr>
                        <?php
                    }
                    ?>
                    <tr>
                        <td colspan="5" style="text-align: right;"><b>Total</b></td>
                        <td style="text-align: right;"><b><?php echo number_format($totalVials); ?></b></td>
                        <td>&nbsp;</td>
                        <td style="text-align: right;"><b><?php echo number_format($totalDoses); ?></b></td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <br>
            <?php
        }
    }
    if ($this->result && count($this->result) > 0 && $this->val == 'loc') {
        //echo "<pre>";
        foreach ($locationArr as $key => $data) {
            ?>
            <b><?php echo $key; ?></b>
            <table id="mytable" >
                <tr>
                    <th rowspan="2"  width="6%"><?php echo $this->translate("S No") ?></th>
                    <th rowspan="2"  width="12%"><?php echo $this->translate("Issue") ?><br><?php echo $this->translate("Date") ?></th>
                    <th rowspan="2" ><?php echo $this->translate("Product") ?></th>
                    <th  rowspan="2"  width="12%"><?php echo $this->translate("Batch No") ?></th>
                    <th rowspan="2"  width="12%"><?php echo $this->translate("Expiry Date") ?></th>

                    <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>   
                    <th rowspan="2" width="8%"><?php echo $this->translate("VVM") ?><br><?php echo $this->translate("Stage") ?></th>

                </tr>
                <tr style="background-color: #F8F8F8;">
                    <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
                    <th width="10%"><?php echo $this->translate("Doses Per Vials"); ?></th>
                    <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
                </tr>
                <tbody>
                    <?php
                    $i = 0;
                    $totalVials = 0;
                    $totalDoses = 0;
                    foreach ($data as $val) {

                        $i++;
                        $totalVials += abs($val['quantity']);
                        $totalDoses += ($val['description'] * abs($val['quantity']));
                        ?>

                        <tr>
                            <td style="text-align:right;"><?php echo $i; ?></td>
                            <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($val['transactionDate'])); ?></td>
                            <td style="text-align:left;"><?php echo $val['itemName']; ?></td>
                            <td style="text-align:left;"><?php echo $val['number']; ?></td>
                            <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($val['expiryDate'])); ?></td>
                            <td style="text-align:right;"><?php echo number_format($val['quantity']); ?></td>
                            <td style="text-align:right;"><?php echo $val['description'] ?></td>
                            <td style="text-align:right;"><?php echo number_format(($val['description'] * abs($val['quantity']))); ?></td>
                            <td style="text-align:left;"><?php echo !empty($val['vvmStage']) ? $val['vvmStage'] : 'N/A'; ?></td>
                        </tr>
                        <?php
                    }
                    ?>
                    <tr>
                        <td colspan="5" style="text-align: right;"><b>Total</b></td>
                        <td style="text-align: right;"><b><?php echo number_format($totalVials); ?></b></td>
                        <td>&nbsp;</td>
                        <td style="text-align: right;"><b><?php echo number_format($totalDoses); ?></b></td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <?php
        }
    }
} else {
    ?>
    <table id="mytable" >
        <tr>
            <th rowspan="2" width="6%"><?php echo $this->translate("S. No.") ?></th>
            <th rowspan="2" width="12%"><?php echo $this->translate("Issue") ?><br><?php echo $this->translate("Date") ?></th>
            <th rowspan="2" ><?php echo $this->translate("Product") ?></th>
            <th rowspan="2"><?php echo $this->translate("Issued To") ?></th>
            <th rowspan="2" width="12%"><?php echo $this->translate("Batch No") ?></th>
            <th rowspan="2" width="12%"><?php echo $this->translate("Expiry Date") ?></th>
            <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
            <th rowspan="2" width="8%"><?php echo $this->translate("VVM") ?><br><?php echo $this->translate("Stage") ?></th>
        </tr>
        <tr style="background-color: #F8F8F8;">
            <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
            <th width="10%"><?php echo $this->translate("Doses Per Vials"); ?></th>
            <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
        </tr>
        <tbody>
            <?php
            $i = 0;

            $totalVials = 0;
            $totalDoses = 0;
            if ($this->result && count($this->result)):
                foreach ($this->result as $data) {

                    $i++;
                    $totalVials += abs($data['quantity']);
                    $totalDoses += ($data['description'] * abs($data['quantity']));
                    ?>
                    <tr>
                        <td style="text-align:right;"><?php echo $i; ?></td>
                        <td style="text-align:center;"><?php echo date("m/d/Y", strtotime($data['transactionDate'])); ?></td>
                        <td><?php echo $data['itemName']; ?></td>
                        <td><?php echo $data['warehouseName']; ?> </td>
                        <td style="text-align:left;"><?php echo $data['number']; ?></td>
                        <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($data['expiryDate'])); ?></td>
                        <td style="text-align:right;"><?php echo number_format($data['quantity']); ?></td>
                        <td style="text-align:right;"><?php echo $data['description'] ?></td>
                        <td style="text-align:right;"><?php echo number_format(($data['description'] * abs($data['quantity']))); ?></td>
                        <td style="text-align:left;"><?php echo !empty($data['vvmStage']) ? $data['vvmStage'] : 'N/A'; ?></td>
                    </tr>
                    <?php
                }
            endif;
            ?>
            <tr>
                <td colspan="6" style="text-align: right;"><b>Total</b></td>
                <td style="text-align: right;"><b><?php echo number_format($totalVials); ?></b></td>
                <td>&nbsp;</td>
                <td style="text-align: right;"><b><?php echo number_format($totalDoses); ?></b></td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>
    <?php
}
?>
<div style="float:left;">

    <b>Print Date:</b> <?php echo date('d/m/Y') . ' <b>by</b> ' . $this->username; ?>
</div> 
<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print") ?></button>
    </div>
</div> 	  



