<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Stock Placements"); ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <form action="" name="batch_form" method="post">
                    <select class="form-control" name="batch_id" id="batch_id">
                        <?php foreach ($this->batches as $batchid => $batchname) { ?>
                        <option value="<?php echo $batchid; ?>" <?php if($batchid == $this->batch_id) { ?> selected="" <?php }?>><?php echo $batchname; ?></option>
                        <?php } ?>
                    </select>
                    <button type="submit">Go</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table border="1" cellspacing="0" cellpadding="4" width="100%" class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <?php
                                    if (count($this->result) > 0) {
                                        ?>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Product</th>
                                            <th>Batch</th>  
                                            <th>Batch Id</th>                                          
                                            <th>Stock Qty (A)</th>
                                            <th>Placed Qty (B)</th>
                                            <th>Difference (A-B)</th>
                                        </tr>
                                        <?php
                                        $count = 1;
                                        foreach ($this->result as $row) {
                                            $diff = $row['BatchQty'] - $row['PlacedQty'];
                                            ?>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td><?php echo $row['ItemName']; ?></td>
                                                <td><?php echo $row['BatchNumber']; ?></td>
                                                <td><?php echo $row['BatchId']; ?></td>
                                                <td><?php echo $row['BatchQty']; ?></td>
                                                <td><?php echo $row['PlacedQty']; ?></td>
                                                <td><?php echo ($diff > 0 ? "Place: " : "Pick: ") . $diff; ?></td>
                                            </tr>
                                            <?php
                                            $count++;
                                        }
                                    }
                                    ?>
                                </table>
                                <br>
                                <h3>Transactions</h3>
                                <table border="1" cellspacing="0" cellpadding="4" width="100%" class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <?php
                                    if (count($this->transactions) > 0) {
                                        ?>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Voucher No.</th>
                                            <th>Voucher Date</th>  
                                            <th>Batch Id.</th> 
                                            <th>Batch No.</th>   
                                            <th>Rcv/Adj Qty (+)</th>
                                            <th>Issue/Adj Qty (-)</th>
                                            <th>Placed Qty (+)</th>
                                            <th>Pick Qty (-)</th>
                                            <th>Location Id</th>
                                            <th>Action</th>
                                        </tr>
                                        <?php
                                        $count = 1;
                                        $total_positive = 0;
                                        $total_negative = 0;
                                        $total_plc_ptv = 0;
                                        $total_plc_neg = 0;
                                        $placed_sum = array();

                                        foreach ($this->transactions as $row) {

                                            $trans_type = ($row['trans_qty'] > 0 ? "114" : "115");

                                            if ($row['trans_qty'] > 0) {
                                                $total_positive = $total_positive + $row['trans_qty'];
                                            } else {
                                                $total_negative = $total_negative + $row['trans_qty'];
                                            }

                                            if ($row['plc_qty'] > 0) {
                                                $total_plc_ptv = $total_plc_ptv + $row['plc_qty'];
                                            } else {
                                                $total_plc_neg = $total_plc_neg + $row['plc_qty'];
                                            }

                                            if (!isset($placed_sum[$row['placement_location_id']])) {
                                                $placed_sum[$row['placement_location_id']] = 0;
                                            }

                                            $placed_sum[$row['placement_location_id']] += $row['plc_qty'];
                                            ?>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td><?php echo $row['transaction_number']; ?></td>
                                                <td><?php echo $row['transaction_date']; ?></td>
                                                <td><?php echo $row['batch_id']; ?></td>
                                                <td><?php echo $row['number']; ?></td>
                                                <td ><?php if ($row['trans_qty'] > 0) echo $row['trans_qty']; ?></td>
                                                <td ><?php if ($row['trans_qty'] < 0) echo $row['trans_qty']; ?></td>
                                                <td ><?php if ($row['plc_qty'] > 0) echo $row['plc_qty']; ?></td>
                                                <td ><?php if ($row['plc_qty'] < 0) echo $row['plc_qty']; ?></td>
                                                <td><?php echo $row['asset_id'] . ":" . $placed_sum[$row['placement_location_id']]; ?></td>
                                                <td ><?php //if (empty($row['plc_qty'])) {  ?>
                                                    <form action="add-pick-place" method="post">
                                                        <select class="form-control" name="location_id" id="location_id">
                                                            <?php foreach ($this->placement_locations as $loc) { ?>

                                                                <option value="<?php echo $loc['plc_loc_id']; ?>"><?php echo $loc['asset_name']; ?></option>
                                                            <?php } ?>
                                                            <?php
                                                            if ($this->wh_id == 159 && $this->item_cat != 1) {
                                                                ?>
                                                                <option value="20318">0Temp</option>
                                                                <?php
                                                            }
                                                            ?>
                                                        </select><input name="trans_qty" value="<?php echo $row['trans_qty']; ?>"/> <button type="submit" name="pick_place">Pick/Place</button><br><br><button type="submit" name="updateplc">UPDATE Placement</button>
                                                        <input type="hidden" name="batch_id" value="<?php echo $row['batch_id']; ?>"/>
                                                        <input type="hidden" name="trans_type" value="<?php echo $trans_type; ?>"/>
                                                        <input type="hidden" name="detail_id" value="<?php echo $row['detail_id']; ?>"/>
                                                        <input type="hidden" name="vvm_stage" value="<?php echo $row['vvm_stage']; ?>"/>
                                                        <input type="hidden" name="wh_id" value="<?php echo $this->wh_id; ?>"/>
                                                        <input type="hidden" name="item_id" value="<?php echo $this->item_id; ?>"/>
                                                        <input type="hidden" name="plc_id" value="<?php echo $row['plc_id']; ?>"/>
                                                    </form><?php //}  ?></td>


                                            </tr>
                                            <?php
                                            $count++;
                                        }
                                        ?>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td><?php echo $total_positive; ?></td>
                                            <td><?php echo $total_negative; ?></td>
                                            <td><?php echo $total_plc_ptv; ?></td>
                                            <td><?php echo $total_plc_neg; ?></td>
                                        </tr>
                                        <?php
                                    } else {
                                        echo "Issue Fixed";
                                    }
                                    ?>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- // Content END -->