<style>
    h2 {
        font-family: "PT Sans Narrow",Helvetica,Arial,sans-serif;
        font-size: 22px;
        font-weight: normal;
        margin: 13px 0;
    }

    p {
        font-size: 13.5px;
        line-height: 150%;
        padding-bottom: 5px;
        text-align: left;
        margin: 0 0 10px;
    }

    a {
        font-size: 14.5px !important;
        color: #ffffff;
    }


</style>

<!-- Tabs -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="innerLR">
            <div class="widget widget-tabs widget-tabs-double"  style=" border-bottom: 1px solid #77e588; border-right: 1px solid #77e588; border-top: 1px solid #77e588; margin-bottom: -2px;  ">

                <!-- Tabs Heading -->
                <div class="widget-head">
                    <ul>
                        <li class="active"><a class="glyphicons table"  href="#vaccines"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Acronyms</span></a></li>


                    </ul>
                </div>
                <!-- // Tabs Heading END -->

                <div class="widget-body">
                    <div class="tab-content">

                        <!-- Tab content -->
                        <div id="vaccines" class="tab-pane active widget-body-regular">

                            <ul>
                                <li>	ACD - Agricultural College Dispensary	</li>
                                <li>	AH - Army Hospital	</li>
                                <li>	AHQ - Agency Head Quarter	</li>
                                <li>	AMC - Average Monthly Consumption	</li>
                                <li>	AMS - Additional Medical Superintendent	</li>
                                <li>	ASV - Assistant Superintendent Vaccination	</li>
                                <li>	BCG - Bacillus Calmette–Guérin Vaccine	</li>
                                <li>	BHU - Basic Health Unit	</li>
                                <li>	bOPV - Bivalent oral polio vaccine	</li>
                                <li>	CD - Civil Dispensary	</li>
                                <li>	CDC - Communicable Disease Control	</li>
                                <li>	CH - Civil Hospital	</li>
                                <li>	CHC - Community Health Centre	</li>
                                <li>	CMC - City Medical Centre	</li>
                                <li>	CMH - Combined Military Hospital	</li>
                                <li>	CRMO - Chief Resident Medical Officer	</li>
                                <li>	DCD - District Council Dispensary	</li>
                                <li>	DEO - District Executive Officer	</li>
                                <li>	DHQ - District Head Quarter Hospital	</li>
                                <li>	DMS - Deputy Medical Superintendent	</li>
                                <li>	DSV - District Superintendent Vaccination	</li>
                                <li>	EDO - Executive District Officer	</li>
                                <li>	EPI - Extended Program of Immunization	</li>
                                <li>	FPC - Family Planning Centre	</li>
                                <li>	FSMO - Field Supervisor Medical Officer	</li>
                                <li>	GAVI - GAVI, the Vaccine Alliance	</li>
                                <li>	GD - Government Dispensary	</li>
                                <li>	GH - Government Hospital	</li>
                                <li>	GOP - Government of Pakistan	</li>
                                <li>	Gov of Japan - Government of Japan	</li>
                                <li>	GRD - Government Rural Dispensary	</li>
                                <li>	GV - GAVI Vaccinator	</li>
                                <li>	IDB - Islamic Development Bank	</li>
                                <li>	IV - Inspector Vaccination	</li>
                                <li>	JICA - Japan International Cooperation Agency	</li>
                                <li>	LHV - Lady Health Vaccinator	</li>
                                <li>	MC - Medical Complex	</li>
                                <li>	MCD - Medical Complex Dispensary	</li>
                                <li>	MCH - Mother and Child Health Centre	</li>
                                <li>	MD - Modal Dispensary	</li>
                                <li>	MO - Medical Officer	</li>
                                <li>	MOS - Months of Stock	</li>
                                <li>	MS - Medical Superintendent	</li>
                                <li>	MT - Medical Technician	</li>
                                <li>	OPV - Oral Polio Vaccine	</li>
                                <li>	OR - Outreach	</li>
                                <li>	PC - Private Clinic	</li>
                                <li>	PH - Private Hospital	</li>
                                <li>	PPHI - Public Primary Healthcare Initiative	</li>
                                <li>	Priv. - Private	</li>
                                <li>	R.V.No. - Receive Voucher Number	</li>
                                <li>	RD - Rural Dispensary	</li>
                                <li>	RHC - Rural Health Centre	</li>
                                <li>	RHD - Rural Health Dispensary	</li>
                                <li>	SC - Senior Clerk	</li>
                                <li>	SH&NH - School, Health and Nutrition Supervisor	</li>
                                <li>	SHC - Sub Health Centre	</li>
                                <li>	SI - Sanitary Inspector	</li>
                                <li>	SIA - Supplementary Immunization Activities	</li>
                                <li>	SMO - Senior Medical Officer	</li>
                                <li>	SOH - Stock on Hand	</li>
                                <li>	SSC - Social Security Centre	</li>
                                <li>	SSD - Social Security Dispensary	</li>
                                <li>	SSH - Social Security Hospital	</li>
                                <li>	Syr. - Syringe	</li>
                                <li>	THO - Taluka Health Officer	</li>
                                <li>	THQ - Tehsil Head Quarter Hospital	</li>
                                <li>	tOPV - Trivalent oral polio vaccine	</li>
                                <li>	TSI - Tehsil Sanitary Inspector	</li>
                                <li>	UC - Union Council	</li>
                                <li>	UCMO - Union Council Medical Officer	</li>
                                <li>	UHU - Urban Health Unit	</li>
                                <li>	UNICEF - United Nations Children's Fund	</li>
                                <li>	VVM - Vaccine Vial Monitor	</li>
                                <li>	WHO - World Health Organization	</li>
                                <li>	WMO - Women Medical Officer	</li>

                            </ul>


                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="courses" class="tab-pane widget-body-regular">
                            <p>For the first time Health Services Academy (HSA) Islamabad offers
                                following courses, in conjunction with the USAID|DELIVER Project;


                            <ul>
                                <li>Three Credit Course for Supply Chain Management of Public
                                    Health Commodities</li>
                                <li>Certificate Course on Supply Chain Management of Health
                                    Commodities</li>
                            </ul>

                            <p>The courses will help to increase the participants&#39; understanding
                                of the fundamentals of logistics management and the relationship
                                between supply chain logistics and commodity security. It also will
                                strengthen the participants&#39; ability to implement improvements
                                to basic elements of their logistics systems.
                            </p>

                            <h2>Lecturer&#39;s Guide: Three Credit Course for Supply Chain
                                Management of Public Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                                            href="http://lmis.gov.pk/training_manuals/three_credit_lecturer_guide.pdf">Download</a></h2>
                            <p>The Lecture Guide for the Three Credit Course on Supply Chain
                                Management of Public Health Commodities is meant for lecturers who
                                are supposed to conduct the course. This curriculum is written
                                following Adult Learning Theory principles which emphasize more
                                interactive and participatory approaches than traditional teaching
                                techniques. Small group exercises are placed into the curriculum
                                and Lecturers are encouraged to run these activities as written
                                where ever possible. The curriculum not only provides basic
                                principles for running a logistic system but includes elements that
                                are Pakistan specific. For this course each major unit of learning
                                is referred to as a Session and each section within is referred to
                                as an Activity. This course has 17 different Sessions. Lecturers
                                are highly encouraged to read the Lecturer Preparation section at
                                the beginning of each session well before leading each session.
                                Note that Synthesis Questions are presented at the end of each
                                Session. These can be used to ensure students are grasping the key
                                concepts of each session. Unlike the Certificate course this course
                                is competency-based.</p>

                            <h2>Student Guide: Three Credit Course on Supply Chain Management of
                                Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                       href="http://lmis.gov.pk/training_manuals/three_credit_student_guide.pdf">Download</a></h2>
                            <p>The Guide is meant for use of three credit course students.</p>

                            <h2>Lecturer&#39;s Guide: Certificate Course on Supply Chain
                                Management of Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                                     href="http://lmis.gov.pk/training_manuals/certificate_course_lect_guide.pdf">Download</a></h2>

                            <p>The Lecture Guide for the Certificate Course on Supply Chain
                                Management of Public Health Commodities is meant for lecturers who
                                are supposed to conduct the course. This will become a three credit
                                course and likely expand to a larger offering in time. This
                                curriculum is written following Adult Learning Theory principles
                                which emphasize more interactive and participatory approaches than
                                traditional teaching techniques. Small group exercises are placed
                                into the curriculum and Lecturers are encouraged to run these
                                activities as written. The curriculum not only provides basic
                                principles for running a logistic system but includes elements that
                                are Pakistan specific. For this course each major unit of learning
                                is referred to as a Session and each part of a Session is referred
                                to as an Activity. This course has 16 different Sessions. Lecturers
                                are highly encouraged to read the &#39;Lecturer Preparation&#39;
                                section at the beginning of each session well before leading each
                                session.</p>

                            <h2>Student Handbook: Certificate Course on Supply Chain Management
                                of Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                          href="http://lmis.gov.pk/training_manuals/certificate_course_student_guide.pdf">Download</a></h2>

                            <p>The handbook is meant for use of certificate course students.</p>








                        </div>
                        <!-- // Tab content END -->





                    </div>
                </div>
            </div>
            <!-- // Tabs END -->
        </div>
    </div>
</div>