<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN CONTENT -->
    <div class=" page-content-wrapper">
        <div class="page-content landing-content">
        <br/>
            <div class="col-md-12 "> 
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-folder"></i>Frequently Asked Questions
                        </div>
                    </div>
                    <div class="portlet-body">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a data-toggle="tab" href="#tab_1_1">
                                    Logistics Management (Draft) </a>
                            </li>
                            <li class="">
                                <a data-toggle="tab" href="#tab_1_2">
                                    Contraceptive LMIS (Draft) </a>
                            </li>
                            <li class="">
                                <a data-toggle="tab" href="#tab_1_3">
                                    Vaccines LMIS (Draft) </a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab_1_1" class="tab-pane fade active in">
                                <ol><li><b>What is Logistics? </b> 
                                        <p>Supply chain management encompasses the planning and management of all activities involved in sourcing and procuremen&hellip;and all logistics management activities. Importantly, it also includes coordination and collaboration with channel partners, which can be suppliers, intermediaries, third party service providers, and customers. In essence, supply chain management integrates supply and demand management within and across companies.</p>
                                    </li>
                                    <li><b>Why Logistics Matters?</b>
                                        <p>The goal of a health logistics system is much larger than simply making sure a product gets where it needs to go. Ultimately, the goal of every public health logistics system is to help ensure that every customer has commodity security. Commodity security exists when every person is able to obtain and use quality essential health supplies whenever he or she needs them. A properly functioning supply chain is a critical part of ensuring commodity security&ndash;financing, policies, and commitment are also necessary.</p></li>
                                    <li><b>How Logistics helps in improving Public Health?</b>
                                        <p>Effective supply chains not only help ensure commodity security, they also help determine the success or failure of any public health program. Both in business and in the public sector, decision makers increasingly direct their attention to improving supply chains, because logistics improvements bring important, quantifiable benefits. Well-functioning supply chains benefit public health programs in important ways by&ndash;</p>
                                        <ul><li> increasing program impact</li>
                                            <li> enhancing quality of care</li>
                                            <li> improving cost effectiveness and efficiency.</li></ul></li>
                                    <li><b>What is logistics management Information system?</b>
                                        <p>It is an online web application which captures the stock indicators data from Service delivery points and informs it users about Stock positions, stock out and consumption pattern for the purpose of smooth supply of commodities by quantification and procurement of commodities.</p></li>
                                    <li><b>What is LMIS and how it is different from DHIS?</b>
                                        <p>An LMIS collects data about commodities; this information is often used for activities, such as filling routine supply orders for health facilities. DHIS collects information on the total number of patients seen or diagnosed; data from DHIS is not used as often as LMIS data&ndash; i.e., annually&ndash;and it is used for different purposes&ndash;i.e., for evaluating program impact. Logisticians emphasize the use of logistics data for making decisions about activities within the logistics cycle.</p></li>
                                </ol>

                                <p style="text-align: right;">Last Modified: 11/Mar/2014 </p>
                            </div>
                            <div id="tab_1_2" class="tab-pane fade">
                                <ol><li><b>What is Contraceptive logistics management system?</b>
                                        <p>It is an online web Logistics Management Information System (LMIS) for different products used for different birth spacing methods. This system is hosted at lmis.gov.pk and one can find it by log in under contraceptive tab. This system monthly captures different stock indicators entered by different public and Private sector stakeholders across Pakistan. This LMIS aggregates and calculate different Logistics indicators in the forms of reports and graphs.</p></li> 
                                    <li><b>Which are data entry stock indicators?</b>
                                        <p>These indicators are opening balance, stock receive, stock issue, positive/negative adjustments and closing stock.</p></li>
                                    <li><b>Data enters at what levels?</b>
                                        <p>Data enters from different stores at National, District and Sub-District levels across Pakistan.</p></li>
                                    <li><b>Data enters at what intervals?</b>
                                        <p>Data enter on monthly basis.</p> </li>
                                    <li><b>Who entered data in to Contraceptive LMIS?</b>
                                        <p>Following organizations enters the data
                                        <ol><li>	Public Sector: Public Welfare Department, Department of Health, Lady Health Worker Program, People's Primary HealthCare Initiative (PPHI), Chief Minister's Initiative for Primary Healthcare (CMIPHC)</li>
                                            <li>	Private Sector: Marie Stopes Society (MSS), Green Star Marketing, MNCH Program, Jhpiego</li>

                                            <li><b>What are the output Indicators of contraceptive LMIS?</b></li>
                                            <li>	Couple Year Protection (CYP)</li>
                                            <li>	Consumption</li>
                                            <li>	Average Monthly Consumption (AMC)</li>
                                            <li>	Stock on Hand (SoH)</li>
                                            <li>	Months of Stock (MoS)</li>
                                        </ol>
                                        </p>
                                    </li>
                                    <li><b>What is Couple Year Protection (CYP) in Contraceptive LMIS?</b>
                                        <p>The estimated protection provided by family planning (FP) services during a one-year period, based upon the volume of all contraceptives sold or distributed free of charge to clients during that period. The CYP is calculated by multiplying the quantity of each method distributed to clients by a conversion factor, to yield an estimate of the duration of contraceptive protection provided per unit of that method.</p></li>
                                    <li><b>What is Consumption in Contraceptive LMIS?</b>
                                        <p>Consumption is issue of contraceptive commodities to its end user at the Health or Social Welfare Facility.</p></li>
                                    <li><b>What is Average Monthly Consumption (AMC) in Contraceptive LMIS?</b>
                                        <p>Average Monthly Consumption is calculated as average of aggregated consumption of the last three non-zero consumption months of contraceptive Products.</p></li>
                                    <li><b>What is Stock on Hand (SoH) in Contraceptive LMIS?</b>
                                        <p>Stock on Hand is the amount of product on hand in order to monitor stock positions and anticipate stock outs in advance.</p></li>
                                    <li><b>What is Months of Stock (MoS) in Contraceptive LMIS?</b>
                                        <p>Months of Stock is the estimate of number of months the stock will last. This obtains by dividing Stock of Hand by average monthly consumption.</p></li>
                                    <li><b>What are Summary reports?</b>
                                        <p>Summary Reports are based on Logistics Indicators i.e. Couple Year Protection, Consumption, Average Monthly Consumption, Stock on Hand and Months of Stock calculated on various levels from sub District (Field) to National level.</p></li>
                                    <li><b>What is vLMIS explorer?</b>
                                        <p>The LMIS explorer enables you to view the previously submitted Monthly Consumption Report data for the selected warehouse and the specified month - year.</p></li>
                                    <li><b>Is Inventory Control System is included in Contraceptive LMIS?</b>
                                        <p>No, Warehouse Management System (WMS) is a separate software for inventory management, which is installed at Central warehouse for contraceptive products under the administration of Ministry of National Health Services, Regulations & Coordination (MoNHSRC)</p>
                                    </li></ol> <p style="text-align: right;">Last Modified: 11/Mar/2014 </p>
                            </div>
                            <div id="tab_1_3" class="tab-pane fade">
                                <ol><li><b>What is Vaccine logistics management system (vLMIS)?</b>
                                        <p>The Vaccines Logistics Management Information System This system captures different stock indicators entered by EPI Program across Pakistan. vLMIS system is an inventory control system at National Provincial, Divisional, District and Sub-District level stores and also accepts monthly vaccines and related commodity status from every EPI center in 54 district every month during pilot period. It has been designed to help, plan and manage the immunization resources and ensure that adequate quantities of vaccines are always available to meet demand at the right time, to the right place and in the right condition.</p></li>

                                    <li><b>How Inventory Management System works in vLMIS?</b>
                                        <p>Vaccines mostly imports from abroad and comes directly to either Federal or Provincial EPI stores through airplane.  It is received and records is entered into vLMIS. Later store managers issues it on First Expiry First Out (FEFO) method. The lower level stores receives vaccines and indicate it in vLMIS. They issues vaccines again to lower level till the vaccines reaches to EPI center level, where it is dispensed to children.</p></li>
                                    <li><b>How EPI centers reports the consumption of vaccines to EPI Program through vLMIS?</b>
                                        <p>Each EPI center is a part of cluster. A cluster leader collects monthly reports and enters into vLMIS on monthly basis.</p></li>
                                    <li><b>Which are data entry indicators?</b>
                                        <p>These indicators are opening balance in doses, stock receive in doses, stock dispensed in doses, how many vials used for dispensing, how many doses were unusable.</p>
                                    <li><b>Data enters at what intervals?</b>
                                        <p>Data enter on daily basis on vaccines stores and monthly basis on EPI Centers.</p></li> 
                                    <li><b>Who entered data in to Vaccines LMIS?</b>
                                        <p>EPI Program officials enters the data at various level stores and centers</p></li>
                                    <li><b>What are the output Indicators of vaccines LMIS?</b>
                                        <ul><li>	Consumption</li>
                                            <li>	Average Monthly Consumption (AMC)</li>
                                            <li>	Stock on Hand (SoH)</li>
                                            <li>	Months of Stock (MoS)</li>
                                        </ul></li>
                                    <li><b>What is Consumption in vaccines LMIS?</b>
                                        <p>Consumption is dispensation of vaccines to children at the Health Facility or EPI Centers.</p></li>
                                    <li><b>What is Average Monthly Consumption (AMC) in vaccines LMIS?</b>
                                        <p>Average Monthly Consumption is calculated as average of aggregated consumption of the last three non-zero consumption months of vaccines and related products.</p></li>
                                    <li><b>What is Stock on Hand (SoH) in vaccines LMIS?</b>
                                        <p>Stock on Hand is the amount of product on hand in order to monitor stock positions and anticipate stock outs in advance.</p></li>
                                    <li><b>What is Months of Stock (MoS) in vaccines LMIS?</b>
                                        <p>Months of Stock is the estimate of number of months the stock will last. This obtains by dividing Stock of Hand by average monthly consumption.</p></li>
                                    <li><b>What are Summary reports?</b>
                                        <p>Summary Reports are based on Logistics Indicators i.e. Couple Year Protection, Consumption, Average Monthly Consumption, Stock on Hand and Months of Stock calculated on various levels from sub District (Field) to National level.</p></li> 

                                    <li><b>What is Batch Management?</b> 
                                        <p>Batch management is order to maintain the First expiry first out process for vaccine during stock issue.</p></li>
                                    <li><b>Is Cold Chain Management Module included in vLMIS?</b>
                                        <p>Yes, vaccines stores in Cold Chain and Cold chain is a temperature-controlled supply chain. It is essential for the effectiveness of the vaccines that an unbroken cold chain with uninterrupted series of storage and distribution activities are maintained for the given temperature range. In vLMIS, the Store managers knows the Cold-chain assets information in their stores or EPI centers along its capacity and working status for each month in order to record the cold-chain maintenance data.</p></li>
                                    <li><b>What is vLMIS explorer?</b>
                                        <p>The LMIS explorer enables you to view the previously submitted Monthly Consumption Report data for the selected warehouse and the specified month - year.</p></li>

                                    <p style="text-align: right;">Last Modified: 11/Mar/2014 </p>
                            </div>

                        </div>
                        <div class="clearfix margin-bottom-20">
                        </div>                       

                    </div>
                </div>
            </div>
            <!-- BEGIN  PATNERS -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="tab-content stake-holder">stakeholders</div>
                    <div style="float:right; padding-top: 35px; padding-right: 20px;"><img src="<?php echo $this->baseUrl(); ?>/images/usa-delivered-logo.png" alt=""/></div>
                    <ul class="nav nav-tabs stake-holder-list">
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/govt-of-pak-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/unicef-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/us-aid-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/who-logo.png" alt=""/></li>
                    </ul>                    
                </div>
            </div>
            <!-- END PATNERS -->
        </div></div>