<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Cold Chain"); ?></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("New Add Refrigerator Freezer ILR Asset"); ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row margin-top-10 margin-bottom-10">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?php if (isset($_GET['success']) && $_GET['success'] == 1) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> ×</button>
                                        <strong>Data</strong> has been saved successfully!
                                    </div>
                                <?php } ?>                               
                                <form method="POST" name="asset_add" id="asset_add" action="<?php echo $this->action; ?>" >
                                    <!-- Row -->
                                    <?php echo $this->render('cold-chain/add-main.phtml'); ?>
                                    <div class="row">
                                        <!--                                        <div class="col-md-3">
                                                                                    <div class="form-group">
                                                                                        <label class="control-label" for="catalogueid" ><span class="red">*</span></label>
                                        <?php echo $this->form->catalogue_id; ?>
                                                                                        <div class="controls small-input" style="margin-top: 10px;">
                                        <?php if ($this->action == "add-refrigerator") { ?>
                                                                                                        <a class="btn btn-primary btn-small alignvmiddle" onclick="javascript:void(0);" data-toggle="modal" href="#modal-new-catalogue" title="<?php echo $this->translate("Add New Catalogue"); ?>">
                                            <?php echo $this->translate("Add"); ?>
                                                                                                        </a>
                                        <?php } ?>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>-->

                                        <div class="col-md-3">
                                            <label for="catalogueid" class="control-label"><?php echo $this->translate("Catalogue ID"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->catalogue_id; ?>&nbsp;
                                                <?php if ($this->action == "add-refrigerator") { ?>
                                                    <a title="<?php echo $this->translate("Add New Catalogue"); ?>" href="#modal-new-catalogue" data-toggle="modal" onclick="javascript:void(0);" class="btn btn-primary btn-small">
                                                        <?php echo $this->translate("Add"); ?>
                                                    </a>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="col-md-1" id="loader_catalogue_id" style="display:none;"><img src="<?php echo Zend_Registry::get('baseurl'); ?>/images/loader.gif" style="margin-top:8px; float:left" alt="" /></div>
                                        <div class="col-md-3" id="div_make">
                                            <label class="control-label" for="ccmmakeid"><?php echo $this->translate("Make"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->ccm_make_id; ?>
                                                <?php echo $this->form->ccm_make_id_hidden; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-1" id="loader_make" style="display:none;"><img src="<?php echo Zend_Registry::get('baseurl'); ?>/images/loader.gif" style="margin-top:8px; float:left" alt="" /></div>
                                        <div class="col-md-3" id="div_model">
                                            <label class="control-label" for="ccmmodelid"><?php echo $this->translate("Model"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->ccm_model_id; ?>
                                                <?php echo $this->form->ccm_model_id_hidden; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row-fluid" id="div_asset_type_ccf_free">
                                        <div class="col-md-3">
                                            <label class="control-label" for="ccmassettypeid"><?php echo $this->translate("Asset Sub Type"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->ccm_asset_type_id; ?>
                                                 
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <label class="control-label" for="cfcfree"><?php echo $this->translate("CFC Free Sticker"); ?> </label>
                                            <div class="controls widget-body uniformjs">
                                                <?php echo $this->form->cfc_free; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-6"></div>
                                    </div>
                                    <div class="row-fluid" id="div_dimension_capacity">
                                        <div class="col-md-3">
                                            <label class="control-label" for="dimensions"><?php echo $this->translate("Dimensions"); ?> (<?php echo $this->translate("Feet"); ?>)</label>
                                            <div class="controls">
                                                <?php echo $this->form->asset_dimension_length; ?>
                                                <?php echo $this->form->asset_dimension_width; ?>
                                                <?php echo $this->form->asset_dimension_height; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <label class="control-label" for="capacity"><?php echo $this->translate("Capacity"); ?> (<?php echo $this->translate("Liters"); ?>)<span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->gross_capacity_4; ?>
                                                <?php echo $this->form->gross_capacity_20; ?>
                                                <?php echo $this->form->net_capacity_4; ?>
                                                <?php echo $this->form->net_capacity_20; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-6"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label class="control-label" for="serialnumber"><?php echo $this->translate("Serial Number"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->serial_number; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <label class="control-label" for="workingsince"><?php echo $this->translate("Working Since (Year)"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->working_since; ?>
                                                <!-- hidden field for update-->
                                                <?php echo $this->form->ccm_id; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <label class="control-label" for="temperature_monitor"><?php echo $this->translate("Temperature Monitor"); ?></label> <span class="red">*</span>
                                            <div class="controls">
                                                <?php echo $this->form->temperature_monitor; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-11">&nbsp;</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-11"></div>
                                        <div class="col-md-1 pull-right">
                                            <button type="submit" class="btn btn-primary" id="save" name="save"><?php echo $this->translate("Save") ?></button>


                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- // Asset Add Popup  add-new-make-model-->
    <form name="asset_add_popup" id="asset_add_popup" action="" method="POST">
        <div class="modal fade" id="modal-new-catalogue"  tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <!--    <div id="modal-new-catalogue" class="modal hide fade in" style="display: none;" aria-hidden="false">-->
                    <!-- Modal heading -->
                    <div class="modal-header">
                        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                        <h4 class="modal-title"><?php echo $this->translate("Suggest new make and model"); ?></h4>
                    </div>
                    <!-- // Modal heading END -->
                    <input type="hidden" name="model_type" id="model_type" value="<?php echo Model_CcmAssetTypes::REFRIGERATOR; ?>">
                    <!-- Modal body -->
                    <div class="modal-body">
                        <!-- BODY HERE -->
                        <div class="row">
                            <div class="col-md-12 margin-bottom" >
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="catalogueid" ><?php echo $this->translate("Catalogue ID"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form->catalogue_id_popup; ?>
                                    </div>

                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="catalogueid" ><?php echo $this->translate("Make"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form->ccm_make_popup; ?>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="catalogueid" ><?php echo $this->translate("Model"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form->ccm_model_popup; ?>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="ccmassettypeid"><?php echo $this->translate("Asset Sub Type"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form->ccm_asset_type_id_popup; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 margin-bottom">
                                <div class="col-md-3">
                                    <label class="control-label" for="dimensions"><?php echo $this->translate("Dimensions"); ?> (<?php echo $this->translate("Feet"); ?>)</label>
                                    <div class="controls">
                                        <?php echo $this->form->asset_dimension_length_popup; ?>
                                        <?php echo $this->form->asset_dimension_width_popup; ?>
                                        <?php echo $this->form->asset_dimension_height_popup; ?>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label" for="capacity"><?php echo $this->translate("Capacity"); ?> <?php echo $this->translate("Liters"); ?><span class="red">*</span></label>
                                    <div class="controls">
                                        <?php echo $this->form->gross_capacity_4_popup; ?>
                                        <?php echo $this->form->gross_capacity_20_popup; ?>
                                        <?php echo $this->form->net_capacity_4_popup; ?>
                                        <?php echo $this->form->net_capacity_20_popup; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="control-label" for="cfcfree"><?php echo $this->translate("CFC Free Sticker"); ?> </label>
                                    <div class="controls cfc_radio">
                                        <?php echo $this->form->cfc_free; ?>
                                    </div>
                                    <label class="control-label" for="cfcfree"><?php echo $this->translate("Is PIS/PQS"); ?> </label>
                                    <div class="controls cfc_radio">
                                        <?php echo $this->form->is_pis_pqs; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="col-md-3">
                                    <label class="control-label" for="refrigerator_gas_type"><?php echo $this->translate("Refrigerator Gas Type"); ?> </label>
                                    <div class="controls">
                                        <?php echo $this->form->refrigerator_gas_type; ?>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label" for="product_price"><?php echo $this->translate("Product Price"); ?> </label>
                                    <div class="controls ">
                                        <?php echo $this->form->product_price; ?>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label" for="power_source"><?php echo $this->translate("Power Source"); ?> </label>
                                    <div class="controls">
                                        <?php echo $this->form->power_source; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--                        <div class="row">
                                                    <div class="col-md-12 margin-bottom" style="margin-top: 10px;">
                                                        <div class="col-md-6">
                                                            <div class="alert alert-error">
                                                                <button data-dismiss="alert" class="close" type="button">×</button>
                                                                <strong><?php //echo $this->translate("Warning");                      ?></strong> <?php //echo $this->translate("Suggest makes and models");                      ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="col-md-6">
                                                            <div class="alert alert-primary">
                                                                <button data-dismiss="alert" class="close" type="button">×</button>
                        <?php // echo $this->translate("For urgent approvals");  ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>-->
                    </div>
                    <!-- // Modal body END -->

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn btn-default" href="#"><?php echo $this->translate("Close"); ?></a> 
                        <button class="btn btn-primary btn-small pull-right btn-icon" type="button" id="asset_add_popup-save" name="asset_add_popup-save">
                            <?php echo $this->translate("Save"); ?>
                        </button>  


                    </div>
                    <!-- // Modal footer END -->
                </div>
            </div>
        </div>
</div>
</form>
<!-- // Asset Add Popup END  -->


