<?php
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .="<rows>";

$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$in_col = $this->in_col;
$in_rg = $this->in_rg1;
$in_type = $this->in_type1;
$sel_item = $this->sel_item;
$sel_prov = $this->prov_sel;
$counter = 1;

$rpt_date = $sel_year . '-' . str_pad($sel_month, 2, "0", STR_PAD_LEFT) . '-01';
$query_consumption = $this->reports()->reportConsumption($in_type, $rpt_date, $sel_prov, $sel_item, $in_stk);
$query_amc = $this->reports()->reportAmc($in_type, $rpt_date, $sel_prov, $sel_item, $in_stk);
$query_cb = $this->reports()->reportCb($in_type, $rpt_date, $sel_prov, $sel_item, $in_stk);

foreach ($query_consumption as $consumption) {
    $data_arr[$consumption['pk_id']]['location'] = $consumption['location_name'];
    $data_arr[$consumption['pk_id']]['cons'] = $consumption['consumption'];
}
foreach ($query_amc as $amc) {
    $data_arr[$amc['pk_id']]['amc'] = $amc['AMC'];
}
foreach ($query_cb as $cb) {
    $data_arr[$cb['pk_id']]['cb'] = $cb['CB'];
}
//App_Controller_Functions::pr($data_arr);
foreach ($data_arr as $item_id => $items) {
    $item_name = $items['location'];
    $xml_store .="<row>";
    $xml_store .= "<cell>$item_id</cell>";
    $month_num = "\"$sel_month\"";
    $year_num = "\"$sel_year\"";
    $product_name = "\"$item_id\"";

    $tmp = array();
    $tmp[] = $data_arr[$item_id]['cons'];
    $tmp[] = $data_arr[$item_id]['amc'];
    $tmp[] = $data_arr[$item_id]['cb'];
    $tmp[] = (!empty($data_arr[$item_id]['cb'])) ? round($data_arr[$item_id]['cb'] / $data_arr[$item_id]['amc'], 1) : '0';

    $sel_stk = 1;
    $sel_lvl = 4;

    $temp_var = "";
    $temp_var .= "\"$sel_month\",";
    $temp_var .= "\"$sel_year\",";
    $temp_var .= "\"$sel_item\",";
    $temp_var .= "\"$sel_prov\",";
    $temp_var .= "\"$item_id\"";

    $xml_store .="<cell><![CDATA[<a href=javascript:functionCall($temp_var)>$item_name</a>]]>^_self</cell>";
    include('ind_data_render.phtml');
    unset($tmp);
}
//foreach ($this->loc as $loc) {
//
//    $xml_store .="<row id=\"$counter\">";
//    $query_vals = $this->reports()->reportData($in_col, $in_rg, $in_type, $sel_month, $sel_year, $sel_item, 1, $loc['pk_id'], 0);
//
//    $xml_store .= "<cell>$loc[pk_id]</cell>";
//    foreach ($query_vals as $row_vals) {
//
//        $item_id = $loc['pk_id'];
//        $item_name = $loc['location_name'];
//        $sel_stk = 0;
//        $sel_lvl = 4;
//        $month_num = "\"$sel_month\"";
//        $year_num = "\"$sel_year\"";
//
//        $temp_var = "";
//        $temp_var .= "\"$sel_month\",";
//        $temp_var .= "\"$sel_year\",";
//        $temp_var .= "\"$sel_item\",";
//        $temp_var .= "\"$sel_prov\",";
//        $temp_var .= "\"$item_id\"";
//        $tmp = explode('*', $row_vals['Value']);
//
//        //<!-- begin data rending -->
//        //$sel_item = $loc['pk_id'];
//
//        $xml_store .="<cell><![CDATA[<a href=javascript:functionCall($temp_var)>$item_name</a>]]>^_self</cell>";
//
//        include ('ind_data_render.phtml');
//    }
//
//    $counter++;
//}

$xml_store .="</rows>";
//App_Controller_Functions::pr($xml_store);
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                    </td>
                </tr>                

                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>
            </table>
            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:500px;">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<input type="hidden" name="sel_year" id="sel_year"  value="<?= $sel_year ?>">
<input type="hidden" name="sel_month" id="sel_month" value="<?= date('F', mktime(0, 0, 0, $sel_month)) ?>">

<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        //mygrid.setHeader("District,#cspan,Consumption,AMC,On Hand,MOS,#cspan");
        mygrid.setHeader(",<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "District Report For Province/Region = $this->location_name  And Product = $this->item_name (" . date('F', mktime(0, 0, 0, $sel_month)) . ' ' . $sel_year . ")"; ?></div>,#cspan,#cspan,#cspan,#cspan,#cspan");
        mygrid.attachHeader("<span>District Id</span>,<span title='District Name'>District</span>,<span title='Product Consumption'>Consumption (Doses)</span>,<span title='Average Monthly Consumption'>AMC (Doses)</span>,<span title='Product On Hand'>Product On Hand (Doses)</span>,<div style='text-align:center;' title='Months of Scale'>Months of Stock (MOS)</div>,#cspan");
        mygrid.setInitWidths("150,*,*,*,*,40,100");
        mygrid.setColAlign("left,left,right,right,right,center,center");
        //mygrid.setColSorting(",,str,str,str,str,str");
        mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro");
        mygrid.setColumnHidden(0, true);
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver'); // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }

    function functionCall(month, year, prod, province, district) {
        window.location = "tehsil-report?month_sel=" + month + "&year_sel=" + year + "&prov_sel=" + province + "&stkid=1&prod_sel=" + prod + "&dist_id=" + district;
    }
</script>      
