<style>
    *{
        font-family: sans-serif;
    }
    td{
        border: 1px solid gray;
    }
    th{
        border: 1px solid gray;
        background-color: #F1F1F1;
    }
    h2{
        text-align: center;
    }
    table{
        border-collapse: collapse;
    }
    input{
        width: 96%;
    }
    input:focus{
        border: 1px solid red;
        background-color: #FFE4E1;
    }
</style>

<?php
$param = $this->param;
$query_1 = $this->reports()->getPopupDataEntry($param[0]);
foreach ($query_1 as $row) {

    $province_id = $row['province_id'];

    echo "<h4 style='margin-left:10px;'>$row[wh_name]</h4>";
    $do = 'Z' . base64_encode($row['wh_id'] . '|' . $param[0] . '|' . $param[2] . '-' . $param[1] . '-01' . '|2');


    $temp = $do;
    $previous_selected = $temp;

    $temp = base64_decode(substr($temp, 1, strlen($temp) - 1));
    $temp = explode("|", $temp);

    //****************************************************************************
    $wh_id = $temp[0]; // Warehouse ID
    $loc_id = $temp[1]; // Warehouse ID
    $RptDate = $temp[2]; //Report Date
    $isNewRpt = $temp[3]; //if value = 1 then new report
    $tt = explode("-", $RptDate);
    $yy = $tt[0]; //Reprot year
    $mm = $tt[1]; //report Month

    if ($mm == '1')
        $month = "Jan";
    if ($mm == '2')
        $month = "Feb";
    if ($mm == '3')
        $month = "Mar";
    if ($mm == '4')
        $month = "Apr";
    if ($mm == '5')
        $month = "May";
    if ($mm == '6')
        $month = "Jun";
    if ($mm == '7')
        $month = "Jul";
    if ($mm == '8')
        $month = "Aug";
    if ($mm == '9')
        $month = "Sep";
    if ($mm == '10')
        $month = "Oct";
    if ($mm == '11')
        $month = "Nov";
    if ($mm == '12')
        $month = "Dec";

    //****************************************************************************
    $query_stakeholder = $this->reports()->getStakeholderByWarehouseId($wh_id);

    $stkid = $query_stakeholder['0']['stakeholder_id'];

    if ($isNewRpt == 1) {
        $PrevMonthDate = $this->reports()->getPreviousMonthReportDate($RptDate);
    } else {
        $PrevMonthDate = $RptDate;
    }

    $reports = $this->reports()->getMonthYearByWHID($wh_id);
    $wh_lvl_query = $this->reports()->GetWarehouseLevelById($wh_id);
    $wh_lvl = $wh_lvl_query['0']['geo_level_id'];
    ?>
    <?php if ($mm >= 5 && $yy >= 2015 && $province_id == 2) { ?>
        <div class="widget">
            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading">
                    Monthly Consumption Report (<?php echo $month . "-" . $yy; ?>)
                </h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">
                <div class="span12">
                    <!-- Table -->
                    <table width="100%" cellpadding="3" id="mytable">
                        <thead >
                            <tr>
                                <th rowspan="4">Product</th>
                                <th rowspan="4">Opening Balance (Doses)</th>
                                <th rowspan="4">Received (Doses)</th>
                                <th colspan="7">Number of Children Vaccinated (0-11 Months)</th>
                                <th colspan="6">Number of Children Vaccinated (12-23 Months)</th>
                                <th rowspan="4">Closing Balance (Doses)</th>
                                <th rowspan="4">Unusable (Doses) **</th>
                            </tr>
                            <tr>
                                <th rowspan="2">#</th>
                                <th colspan="4">Fixed</th>
<!--                                <th colspan="2" rowspan="2" >Referral from Outside UCs*</th>-->
                                <th colspan="2" rowspan="2">Out</br>reach</th>
                                <th colspan="4">Fixed</th>
<!--                                <th colspan="2" rowspan="2"> Referral from Outside UCs*</th>-->
                                <th colspan="2" rowspan="2">Out</br>reach</th>
                            </tr>
                            <tr>
                                <th colspan="2">Inside UC</th>
                                <th colspan="2">Outside UC</th>

                                <th colspan="2">Inside UC</th>
                                <th colspan="2">Outside UC</th>

                            </tr>
                            <tr>
                                <th></th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
<!--                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>-->
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->monthlyConsumtion2()->items() as $result):
                                ?>

                                <?php
                                if ($this->is_new_report == 1) {
                                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($wh_id, $RptDate, $result['pk_id'], '145');
                                } else {
                                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($wh_id, $RptDate, $result['pk_id'], '145');
                                    $row3 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($wh_id, $RptDate, $result['pk_id'], '146');
                                }

                                $counter = 1;
                                $nod = $result['no_of_doses'];
                                $max_i;
                                ?>
                                <?php if ($this->is_new_report == 2) {
                                    ?>
                                    <?php
                                    $j = 0;
                                    for ($i = $result['start_no']; $i <= $result['no_of_doses']; $i++) {
                                        if ($i == 0) {
                                            $nod += 1;
                                        }
                                        ?>
                                        <tr>
                                            <?php if ($counter == 1) { ?>
                                                <td rowspan="<?php echo $nod ?>"><?php echo $result['item_name'] ?></td>
                                        <input type="hidden" name="flitm_id[]" value="<?php echo $result['pk_id']; ?>" />
                                        <input type="hidden" name="doses_per_unit[]" id="<?php echo $result['pk_id']; ?>-doses" value="<?php echo $result['description']; ?>" />
                                        <input type="hidden" name="start_no[]" id="<?php echo $result['pk_id']; ?>-start_no" value="<?php echo $result['start_no']; ?>" />
                                        <input type="hidden" name="no_of_doses[]" id="<?php echo $result['pk_id']; ?>-no_of_doses" value="<?php echo $result['no_of_doses']; ?>" />

                                        <td rowspan="<?php echo $nod ?>">
                                            <?php echo (!empty($row2[0]['openingBalance'])) ? $row2[0]['openingBalance'] : '0'; ?>
                                        </td>


                                        <td rowspan="<?php echo $nod ?>">
                                            <?php echo (!empty($row2[0]['receivedBalance'])) ? number_format($row2[0]['receivedBalance']) : '0'; ?>
                                        </td>

                                    <?php } ?>
                                    <input type="hidden" name="vaccine_schedule_id[]" value="<?php echo ($i == 1 && $i == $nod) ? '' : $i; ?>" />
                                    <td><?php echo ($i == 1 && $i == $nod) ? '' : $i; ?></td>
                                    <td> <?php echo (!empty($row2[$j]['fixed_inside_uc_male']) ) ? $row2[$j]['fixed_inside_uc_male'] : '0'; ?></td>
                                    <td> <?php echo (!empty($row2[$j]['fixed_inside_uc_female']) ) ? $row2[$j]['fixed_inside_uc_female'] : '0'; ?> </td>
                                    <td> <?php echo (!empty($row2[$j]['fixed_outside_uc_male']) ) ? $row2[$j]['fixed_outside_uc_male'] : '0'; ?> </td>
                                    <td> <?php echo (!empty($row2[$j]['fixed_outside_uc_female'])) ? $row2[$j]['fixed_outside_uc_female'] : '0'; ?>  </td>
<!--                                    <td> <?php // echo (!empty($row2[$j]['referal_male']) ) ? $row2[$j]['referal_male'] : '0'; ?>  </td>
                                    <td> <?php  //echo (!empty($row2[$j]['referal_female'])) ? $row2[$j]['referal_female'] : '0'; ?>  </td>-->
                                    <td> <?php echo (!empty($row2[$j]['outreach_male']) ) ? $row2[$j]['outreach_male'] : '0'; ?>  </td>
                                    <td> <?php echo (!empty($row2[$j]['outreach_female']) ) ? $row2[$j]['outreach_female'] : '0'; ?>  </td>
                                    <td> <?php echo (!empty($row3[$j]['fixed_inside_uc_male'])) ? $row3[$j]['fixed_inside_uc_male'] : '0'; ?></td>
                                    <td> <?php echo (!empty($row3[$j]['fixed_inside_uc_female']) ) ? $row3[$j]['fixed_inside_uc_female'] : '0'; ?> </td>
                                    <td> <?php echo (!empty($row3[$j]['fixed_outside_uc_male']) ) ? $row3[$j]['fixed_outside_uc_male'] : '0'; ?> </td>
                                    <td> <?php echo (!empty($row3[$j]['fixed_outside_uc_female'])) ? $row3[$j]['fixed_outside_uc_female'] : '0'; ?>  </td>
<!--                                    <td> <?php // echo (!empty($row3[$j]['referal_male']) ) ? $row3[$j]['referal_male'] : '0'; ?>  </td>
                                    <td> <?php  // echo (!empty($row3[$j]['referal_female']) ) ? $row3[$j]['referal_female'] : '0'; ?>  </td>-->
                                    <td> <?php echo (!empty($row3[$j]['outreach_male']) ) ? $row3[$j]['outreach_male'] : '0'; ?>  </td>
                                    <td> <?php echo (!empty($row3[$j]['outreach_female'])) ? $row3[$j]['outreach_female'] : '0'; ?>  </td>
                                    <?php if ($counter == 1) { ?>
                                        <td rowspan="<?php echo $nod ?>" >
                                            <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?>
                                        </td>
                                        <td rowspan="<?php echo $nod ?>" > <?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?> </td>
                                    <?php } ?> </tr>

                                    <?php
                                    $counter++;
                                    $j++;
                                }
                                ?>


                            <?php } ?>
                        <?php endforeach; ?>


                        </tbody>
                    </table>

                    <h6>TT- Coverage</h6>
                    <table width="100%" cellpadding="3" id="mytable">
                        <thead>
                            <tr>
                                <th class="center">Product</th>
                                <th class="center">Opening Balance (Doses)</th>
                                <th class="center">Received (Doses)</th>
                                <th class="center">S. No</th>
                                <th class="center">Pregnant Women</th>
                                <th class="center">Non-Pregnant Women(15-49) Years</th>
                                <th class="center">Closing Balance (Doses)</th>
                                <th class="center">Unusable (Doses) **</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->monthlyConsumtion2()->items_tt() as $result) {
                                if ($this->is_new_report == 1) {
                                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTt($wh_id, $RptDate, $result['pk_id']);
                                } else {
                                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTt($wh_id, $RptDate, $result['pk_id']);
                                }
                                // App_Controller_Functions::pr($row2);
                                ?>
                                <?php
                                if ($this->is_new_report == 2) {

                                    $j = 0;
                                    for ($i = 1; $i <= 6; $i++) {
                                        ?>
                                        <tr>
                                            <?php
                                            if ($i == 1) {
                                                ?>   <td rowspan = "6" class="center"><?php echo $result['item_name'] ?></td>
                                                <td rowspan = "6"> <?php echo (!empty($row2[0]['openingBalance'])) ? $row2[0]['openingBalance'] : '0'; ?></td>
                                                <td rowspan = "6"> <?php echo (!empty($row2[0]['receivedBalance'])) ? number_format($row2[0]['receivedBalance']) : '0'; ?></td>     <?php
                                            }
                                            ?>
                                            <?php
                                            if ($i <= 5) {
                                                ?>
                                        <input type="hidden" name="vaccine_schedule_id[]" value="<?php echo $i; ?>" />
                                        <td class="center"><?php echo $i ?></td>

                                        <td>
                                            <input type="hidden"  name="pregenant_women[]"  id="<?php echo $result['pk_id']; ?>-pregenant_women" class="pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['pregnant_women'])) ? number_format($row2[$j]['pregnant_women']) : '0'; ?>">


                                            <?php echo (!empty($row2[$j]['pregnant_women'])) ? number_format($row2[$j]['pregnant_women']) : '0'; ?></td>

                                        <?php
                                    }
                                    ?>
                                    <?php
                                    if ($i == 6) {
                                        ?>
                                        <td class="center">Total</td>
                                        <td id="pregenant_women_total_view"></td>

                                        <?php
                                    }
                                    ?>

                                    <?php
                                    if ($i <= 5) {
                                        ?>

                                        <td class="non_pregnant_women">
                                            <input type="hidden"  name="non_pregnant_women[]"  id="<?php echo $result['pk_id']; ?>-non_pregenant_women" class="non_pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?>">
                                            <?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?></td>

                                        <?php
                                        $j++;
                                    }
                                    ?>
                                    <?php
                                    if ($i == 6) {
                                        ?>

                                        <td  id="non_pregenant_women_total_view"></td>

                                        <?php
                                    }
                                    ?>


                                    <?php
                                    if ($i == 1) {
                                        ?>
                                        <td rowspan="6"> <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?></td>
                                        <td rowspan="6"><?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?></td><?php
                                    }
                                    ?>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                        <?php } ?>
                        </tbody>
                    </table>

                    <h6>Other Items</h6>
                    <table width="100%" cellpadding="3" id="mytable">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Opening Balance (No)</th>
                                <th>Received (No)</th>
                                <th>Dispensed (No)</th>
                                <th>Closing Balance (No)</th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php
                            foreach ($this->monthlyConsumtion2()->items_non_vaccinces() as $result) {

                                if ($this->is_new_report == 1) {
                                    $row2 = $this->monthlyConsumtion2()->monthlyConsumptionNonVaccinces($wh_id, $RptDate, $result['pk_id']);
                                } else {
                                    $row2 = $this->monthlyConsumtion2()->monthlyConsumptionNonVaccinces($wh_id, $RptDate, $result['pk_id']);
                                }
                                ?>

                                <?php if ($this->is_new_report == 2) { ?>
                                    <tr>
                                        <td><?php echo $result['item_name'] ?></td>
                                        <td><?php echo (!empty($row2['openingBalance'])) ? $row2['openingBalance'] : '0'; ?></td>
                                        <td><?php echo (!empty($row2['receivedBalance'])) ? $row2['receivedBalance'] : '0'; ?></td>
                                        <td><?php echo (!empty($row2['issueBalance'])) ? $row2['issueBalance'] : '0'; ?></td>
                                        <td><?php echo (!empty($row2['closingBalance'])) ? $row2['closingBalance'] : '0'; ?></td>


                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                        </tbody>


                    </table>
                    <!-- // Table END -->

                </div>
                <div style="clear:both;"></div>
            </div>
        </div>
    <?php } else { ?>
        <div class="widget">
            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading">
                    Monthly Consumption Report (<?php echo $month . "-" . $yy; ?>)
                </h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">
                <div class="span12">
                    <!-- Table -->
                    <table class="table table-striped table-bordered table-condensed">
                        <!-- Table heading -->
                        <thead>
                            <tr>
                                <th class="span1">
                                    Product
                                </th>
                                <th class="span2">
                                    Opening Balance
                                </th>
                                <th class="span1">
                                    Received
                                </th>
                                <th class="span1">
                                    <?php echo ( $wh_lvl == 6 ) ? "Dispensed" : "Issued"; ?>
                                </th>
                                <th class="span1">
                                    <?php echo ( $wh_lvl == 6 ) ? "Vials Used" : "Adjustment +"; ?>
                                </th>
                                <th class="span1">
                                    <?php echo ( $wh_lvl == 6 ) ? "Unusable Vials" : "Adjustment -"; ?>
                                </th>
                                <th class="span2">
                                    Closing Balance
                                </th>
                                <?php if ($wh_lvl == 6) { ?>
                                    <th class="span1">
                                        Nearest Expiry
                                    </th>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td class="span1">&nbsp;</td>
                                <td class="span1">
                                    Doses
                                </td>
                                <td class="span1">
                                    Doses
                                </td>
                                <td class="span1">
                                    Doses
                                </td>
                                <td class="span1">
                                    Vials
                                </td>
                                <td class="span1">
                                    Vials
                                </td>
                                <td class="span1">
                                    Doses
                                </td>
                                <?php if ($wh_lvl == 6) { ?>
                                    <td class="span1">&nbsp;</td>
                                <?php } ?>
                            </tr>
                        </thead>
                        <!-- // Table heading END -->
                        <!-- Table body -->
                        <tbody>
                            <!-- Table row -->
                            <?php
                            $strSql_iteminfotab = $this->reports()->getMonthlyReceiveQuantity($mm, $yy, $wh_id, $stkid);

                            $SlNo = 1;
                            $fldIndex = 0;
                            //  $ItemTableName = $TableName;
                            foreach ($strSql_iteminfotab as $rsRow1) {
                                $SlNo = ((strlen($SlNo) < 2) ? "0" . $SlNo : $SlNo);
                                $itemid = $rsRow1['itm_id'];
                                $qry = $this->reports()->getPopUpData($wh_id, $PrevMonthDate, $itemid);
                                // $qry = "SELECT * FROM tbl_wh_data WHERE `wh_id`='" . $wh_id . "' AND RptDate='" . $PrevMonthDate . "' AND `item_id`='$rsRow1[itm_id]'";

                                $rsRow2 = $qry;

                                if (!empty($rsRow2[0]['nearest_expiry'])) {
                                    $n_expiry = $rsRow2['0']['nearest_expiry'];
                                } else {
                                    $n_expiry = '';
                                }
                                ?>

                                <?php
                                if ($isNewRpt == 2) {
                                    ?>
                                    <tr class="gradeX">
                                        <td class="span1">
                                            <?php echo $rsRow1['itm_name']; ?>
                                        </td>
                                        <td style="text-align:right;">
                                            <?php echo (!empty($rsRow2[0]['opening_balance'])) ? number_format($rsRow2[0]['opening_balance']) : '0'; ?>
                                        </td>
                                        <td class="span1" style="text-align:right;">
                                            <?php echo (!empty($rsRow2[0]['received_balance'])) ? number_format($rsRow2[0]['received_balance']) : '0'; ?>
                                        </td>
                                        <td class="span1" style="text-align:right;">
                                            <?php echo (!empty($rsRow2[0]['issue_balance'])) ? number_format($rsRow2[0]['issue_balance']) : '0'; ?>
                                        </td>
                                        <td class="span1" style="text-align:right;">
                                            <?php echo (!empty($rsRow2[0]['vials_used'])) ? number_format($rsRow2[0]['vials_used']) : '0'; ?>
                                        </td>
                                        <td class="span1" style="text-align:right;">
                                            <?php echo (!empty($rsRow2[0]['adjustments'])) ? number_format(abs($rsRow2[0]['adjustments']) / $rsRow1['number_of_doses']) : '0'; ?>
                                        </td>
                                        <td class="span1" style="text-align:right;">
                                            <?php echo (!empty($rsRow2[0]['closing_balance'])) ? number_format($rsRow2[0]['closing_balance']) : '0'; ?>
                                        </td>
                                        <?php if ($wh_lvl == 6) { ?>
                                            <td class="span1" style="text-align:center;">
                                                <?php echo (!empty($n_expiry)) ? $n_expiry : '&nbsp;'; ?>
                                            </td>
                                        <?php } ?>
                                    </tr>
                                    <?php
                                }
                                ?>

                            <?php }
                            ?>
                            <!-- // Table row END -->
                        </tbody>
                        <!-- // Table body END -->
                    </table>
                    <!-- // Table END -->

                </div>
                <div style="clear:both;"></div>
            </div>
        </div>
    <?php } ?>
    <?php
}
?>
