<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table.mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table.mytable tr td {
        border: 1px solid #444;
    }
    table.mytable tr th {
        border: 1px solid #444;
    }
</style>
<!-- Content -->
<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>
<?php
if (count($this->result) > 0) {
    $dateObj = DateTime::createFromFormat('!m', $this->month);
    $monthName = $dateObj->format('F');

    if ($this->month == date("m")) {
        $monthName = date("d") . " " . $monthName;
    } else {
        $date = new DateTime($this->year . "-" . $this->month . "-01");
        $day = $date->modify('last day of this month');
        $monthName = $day->format('d') . " " . $monthName;
    }
    ?>
    <div class="row">
        <div class="col-md-12">
            <h4> <?php echo $this->print_title . " as on " . $monthName; ?>, <?php echo $this->year; ?></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-condensed mytable">
                <thead>
                    <tr>
                        <th class="center">
                            #
                        </th>
                        <th>
                            Product
                        </th>
                        <th class="right">
                            Closing Balance (Vials)
                        </th>
                        <th class="center">
                            Doses per vial
                        </th>
                        <th class="right">
                            Closing Balance (Doses)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $i = 1;
                    foreach ($this->result as $row) {
                        ?>
                        <tr>
                            <td class="center">
                                <?php echo $i; ?>
                            </td>
                            <td>
                                <?php echo $row['item_name']; ?>
                            </td>
                            <td class="right">
                                <?php echo number_format($row['cb_vials']); ?>
                            </td>
                            <td class="center">
                                <?php echo $row['doses_per_vial']; ?>
                            </td>
                            <td class="right">
                                <?php echo number_format($row['cb_doses']); ?>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div style="float:left;">
        <div class="col-md-12 left">
            <b>Printed By:</b> <?php echo $this->username ?><br> 
            <b>Print Date:</b> <?php echo date("d/m/Y"); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 right">
            <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
        </div>
    </div>
<?php } ?>