<?php
$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$counter = 1;

$sel_stk = $this->in_stk;
$sel_prov = $this->prov_sel;
$sel_dist = $this->in_dist;
$sel_indicator = $this->sel_indicator;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type = $this->in_type;
$stk_sel = $this->stk_sel;
$start_date = $this->start_date;
$end_date = $this->end_date;
$period = $this->period;
$str_indicator = $this->str_indicator;

$data_arr = array();

// Headers of the Grid
$header = 'Province Id,Province/Region';
$header1 = '#rspan,#rspan';
$cspan = '';
$width = '*,250';
$ro = 'ro,ro';
//$count = 1;
foreach ($period as $date) {
    $cspan .= ',#cspan,#cspan,#cspan';
    $header .= ',<span>' . $date->format("M-y") . '</span>,#cspan,#cspan';
    $monthArr[] = $date->format("m-Y");
    $width .= ',89,89,89';
    $ro .= ',ro,ro,ro,ro';
    //$header1 .= '#cspan';
    $header1 .= ',<span>Total UCs</span>,<span>Reported UCs</span>,#cspan';
    $str_date = $startDate = $endDate = $date->format("Y-m");
}

$query_vals_1 = $this->reports()->getReportedProvinces1();

foreach ($query_vals_1 as $row) {
    $data_arr[$row['provinceId']][] = $row['provinceName'];

    $count = 1;
    foreach ($period as $date) {
        $data_arr[$row['provinceId']][$count] = 0;
        $count++;
    }
    foreach ($period as $date) {
        $data_arr[$row['provinceId']][$count] = 0;
        $count++;
    }
    foreach ($period as $date) {
        $data_arr[$row['provinceId']][$count] = 0;
        $count++;
    }
}

$count = 1;
$total_uc = array();



foreach ($period as $date) {
    $str_date1 = $date->format("Y-m");
    $query_total = $this->reports()->gettoalUcs($str_date1);
    foreach ($query_total as $key => $row) {
        $data_arr[$row['provinceId']][$count] = $row['TotalUCs'];
        // $total_uc[$key] = $row['TotalUCs'];
    }
    // $query_vals = $this->reports()->getReportedProvinces($str_date1);

    $count += 1;
    foreach ($query_total as $row) {
        $data_arr[$row['provinceId']][$count] = $row['reported'];
        //$reported = $row['reported'];
    }
    $count += 1;
    foreach ($query_total as $row) {
        //   echo $total_uc;
        $data_arr[$row['provinceId']][$count] = $row['reportingPercentage'];
    }

    $count++;
}


$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .= "<rows>";

$sum_arr = array();

foreach ($data_arr as $dis_id => $sub_arr) {


    $xml_store .= "<row>";
    //$param1 = base64_encode($sub_arr[0] . '|' . $start_date . '|' . $end_date . '|' . $dis_id . '|' . $sub_arr[1] . '|' . '1');
    // $xml_store .= "<cell>$dis_id</cell>";
    $xml_store .= "<cell style=\"text-align:left\">$sub_arr[0]</cell>";
    // $total_uc = $sub_arr[1];
    // $xml_store .= "<cell style=\"text-align:right\">$sub_arr[1]</cell>";
    foreach ($sub_arr as $key => $value) {

        //  App_Controller_Functions::pr($sub_arr);
        if (!isset($sum_arr[$key])) {
            $sum_arr[$key] = 0;
        }
        $sum_arr[$key] += $value;
        // if ($key == 1 || $key == 4 || $key == 7) {
        $param = $dis_id;
        base64_encode($disId . '-' . $monthArr[$key - 2]);

        if (!is_numeric($value)) {

            $xml_store .= "<cell style=\"text-align:left\"><![CDATA[<a href=javascript:functionCall('$param')>$value</a>]]>^_self</cell>";
        } else {
            if ($key == 1 || $key == 4 || $key == 7) {
                $xml_store .= "<cell style=\"text-align:right\">$value </cell>";
            } else if ($key == 3 || $key == 6 || $key == 9) {
                $xml_store .= "<cell style=\"text-align:right\">$value %</cell>";
            } else {
                $xml_store .= "<cell style=\"text-align:right\"><![CDATA[<a href=javascript:functionCall('$param')>$value</a>]]>^_self</cell>";
            }
        }
        //  $xml_store .= "<cell style=\"text-align:right\"><![CDATA[<a href=javascript:functionCall('$param')>$value</a>]]>^_self</cell>";
        //  $xml_store .= "<cell style=\"text-align:right\">" . @round(($value / $total_uc) * 100) . " %</cell>";
        //  }
    }

    $xml_store .="</row>";
}
// exit;
// To show Total
array_shift($sum_arr);

$xml_store .= "<row>";
$xml_store .= "<cell></cell>";
$xml_store .= "<cell style=\"font-weight:bold\">Total</cell>";

foreach ($sum_arr as $key => $value) {
    // App_Controller_Functions::pr($sum_arr);

    if ($key == 0) {
        $total_wh = $value;
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
    } else if ($key == 1) {
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">$value</cell>";
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($value / $total_wh) * 100) . " %</cell>";
    }
    if ($key == 3) {
        $total_wh = $value;
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
    } else if ($key == 4) {
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">$value</cell>";
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($value / $total_wh) * 100) . " %</cell>";
    }
    if ($key == 6) {
        $total_wh = $value;
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
    } else if ($key == 7) {
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">$value</cell>";
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($value / $total_wh) * 100) . " %</cell>";
    }
}

$xml_store .="</row>";
$xml_store .="</rows>";

/* $in_type = 'N';
  $in_stk = 1;
  $in_year = $sel_year;
 */
?>

<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content"><h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <table width="99%">
                <tr>
                    <td colspan="2">
<?php
echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
<?php echo $this->render('inventory-management/reports-header.phtml') ?>
                    </td>
                </tr>

                <tr>
                    <td colspan="2" style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>
            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:310px;">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        //mygrid.setHeader("Province,Consumption,AMC,On Hand,MOS,#cspan");
        mygrid.setHeader(",<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo $this->report_title . ' - ' . ' As on (' . date('F', mktime(0, 0, 0, $this->month_sel)) . '-' . $this->year_sel; ?>)</div><?php echo $cspan; ?>,#cspan");
        mygrid.attachHeader("<?php echo $header; ?>");
        mygrid.attachHeader("<?php echo $header1; ?>");
        mygrid.setInitWidths("<?php echo $width; ?>");
        //mygrid.setColAlign("left,right,right,right,right,right,right,right,right,right,right,right,right");
        //mygrid.setColSorting("str,int");
        mygrid.setColTypes("<?php echo $ro; ?>");
        mygrid.setColumnHidden(0, true);
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver'); // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }

    function functionCall(param) {
        var width = 1002;
        var height = 595;
        var month = '<?php echo $sel_month ?>';
        var year = '<?php echo $sel_year ?>';
        var x = (screen.width / 2) - (width / 2);
        var y = (screen.height / 2) - (height / 2);
        window.open('reported-districts-by-uc?province=' + param + '&ending_month=' + month + '&year_sel=' + year);
    }

    function showGraph(param) {
        window.open('../graph/reported_districts.php?param=' + param, '_blank', 'scrollbars=1,width=950,height=600');
    }
</script>
