<?php
$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$counter = 1;

$sel_stk = $this->in_stk;
$sel_prov = $this->prov_sel;
$sel_dist = $this->in_dist;
$sel_indicator = $this->sel_indicator;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type = $this->in_type;
$stk_sel = $this->stk_sel;
$start_date = $this->start_date;
$end_date = $this->end_date;
$period = $this->period;
$str_indicator = $this->str_indicator;

$header = 'Product';
$header1 = '#rspan';
$cspan = '';
$width = '*';
$ro = 'ro';
$selHeader = false;
$data_arr = array();
foreach ($period as $date) {
    $str_date = $date->format("Y-m");
}
foreach ($this->item_name as $row) {

    $data_arr[$row['pkId']][] = $row['itemName'];
    $count = 1;
    $query1 = $this->reports()->getStockOnHand1();
    foreach ($query1 as $row1) {
        $data_arr[$row['pkId']][$count] = 0;
        $count++;
        if ($selHeader === false) {
            $header .= ',' . $row1['location_name'];
            $header1 .= ',#rspan';
            $cspan .= ',#cspan';
            $width .= ',100';
            $ro .= ',ro';
        }
    }

    $selHeader = true;
}

foreach ($this->item_name as $row) {

    $data_arr[$row['pkId']][] = $row['itemName'];
    $count = 1;
    $query1 = $this->reports()->getStockOnHand2($str_date, $row['pkId']);
    foreach ($query1 as $row1) {
        $data_arr[$row['pkId']][$count] = $row1['CB'];
        $count++;
    }
}
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .= "<rows>";

$sum_arr = array();

foreach ($data_arr as $item_id => $sub_arr) {

    $xml_store .= "<row>";
    $xml_store .= "<cell>$sub_arr[0]</cell>";
    foreach ($sub_arr as $key => $value) {
        if ($key > 0) {
            $xml_store .= "<cell style=\"text-align:right\">" . @number_format($value) . "</cell>";
        }
    }
    $xml_store .="</row>";
}
$xml_store .="</rows>";
?>

<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <script>
                var mygrid;
                function doInitGrid() {
                    mygrid = new dhtmlXGridObject('mygrid_container');
                    mygrid.selMultiRows = true;

                    mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "Provincial/Regional Store-Stock on Hand (doses) (" . date('F', mktime(0, 0, 0, $this->month_sel)) . ' ' . $this->year_sel . ") " ?><?php echo $cspan; ?>");
                    mygrid.attachHeader("<?php echo $header; ?>");
                    //mygrid.attachHeader("<?php //echo $header1;           ?>");
                    mygrid.setInitWidths("<?php echo $width; ?>");
                    //mygrid.setColAlign("left,right,right,right,right,right,right,right,right,right,right,right,right");
                    //mygrid.setColSorting("str,int");
                    mygrid.setColTypes("<?php echo $ro; ?>");
                    mygrid.setSkin("light");
                    // mygrid.enablePaging(true, 50, 3, "infoArea");
                    //  mygrid.setPagingSkin("toolbar", "dhx_skyblue");
                    mygrid.init();
                    mygrid.clearAll();
                    $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
                    mygrid.loadXMLString(document.getElementById('xml_string').value);
                }
            </script>
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                    </td>
                </tr>

                <tr>
                    <td colspan="2" style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>
            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:760px;">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

