<!-- Content -->


<style>

    .rotate_text
    {

    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            UC wise2
        </h3>
        <div class="row">
            <div class="col-md-12">


                <?php echo $this->render('inventory-management/reports-header.phtml') ?>


            </div>
        </div>
        <div class="col-md-12" style="overflow:auto;">
            <?php if (count($this->result) > 0) { ?>
                <?php echo $this->render('inventory-management/consumption-reports-common.phtml') ?>
                <div class="row">
                    <div class="col-md-12">
                        <table  width="100%">
                            <tr>
                                <td colspan="2">
                                    <table id="myTable" cellspacing="0" >
                                        <thead>
                                            <tr>
                                                <th style="background-color: #A4A977;" rowspan="2" class="not_rotate center">
                                                    #
                                                </th>
                                                <th style="background-color: #A4A977;" rowspan="2"  class="not_rotate center">
                                                    District
                                                </th>
                                                <th style="background-color: #A4A977;" rowspan="2" class="not_rotate center">
                                                    Taluka
                                                </th>
                                                <th style="background-color: #A4A977;" rowspan="2" class="not_rotate center">
                                                    Ucs
                                                </th>
                                                <th style="background-color: #A4A977;" rowspan="2" class="not_rotate right">
                                                    Population
                                                </th>
                                                <?php
                                                $count = 1;
                                                foreach ($this->items as $items) {
                                                    $nod = $items['no_of_doses'];
                                                    $max_i;
                                                    $col_span = 0;
                                                    for ($i = $items['start_no']; $i <= $items['no_of_doses']; $i++) {
                                                        if ($i == 0) {
                                                            $nod += 1;
                                                        }
                                                        $col_span += 5;
                                                        ?>
                                                        <th style="background-color: #C6E0B4;"  class="not_rotate" colspan="6"><?php echo $items['item_name']; ?><?php echo ($i == 1 && $i == $nod) ? '' : "(" . $i . ")"; ?></th>

                                                    <?php } ?>

                                                    <th style="background-color: #FCE4D6;" rowspan="2"><div  class="rotate_text">Received Doses</div></th>
                                            <th style="background-color: #FCE4D6;" rowspan="2"><div  class="rotate_text">Used Doses</div></th> 
                                            <th style="background-color: #FCE4D6;" rowspan="2"><div  class="rotate_text">Closed Balance</div></th> 
                                            <th style="background-color: #FCE4D6;" rowspan="2"><div  class="rotate_text">Wastage Doses</div></th>   
                                            <th  style="background-color: #FCE4D6;" rowspan="2" ><div  class="rotate_text">% Wastage</div></th>                    

                                            <?php
                                            $count++;
                                            ?>
                                        <?php } ?>
                            </tr>


                            <tr>
                                <?php
                                foreach ($this->items as $items) {
                                    $nod = $items['no_of_doses'];
                                    $max_i;
                                    $col_span = 0;
                                    for ($i = $items['start_no']; $i <= $items['no_of_doses']; $i++) {
                                        if ($i == 0) {
                                            $nod += 1;
                                        }
                                        $col_span += 5;
                                        ?>   


                                        <th  style="background-color: #C6E0B4;"><div class="rotate_text">Fixed M</div></th>
                                    <th  style="background-color: #C6E0B4;"><div class="rotate_text">Fixed F</div></th>
                                    <th  style="background-color: #C6E0B4;"><div class="rotate_text">Outreach M</div></th>
                                    <th  style="background-color: #C6E0B4;"><div class="rotate_text">Outreach F</div></th>
                                    <th  style="background-color: #C6E0B4;" ><div class="rotate_text">Total</div></th>     
                                    <th   style="background-color: #FFE699;"><div class="rotate_text">Coverage %</div></th>    
                                    <?php
                                }
                            }
                            ?>   
                            </tr>
                            </thead>
                            <tbody>
                                <?php
                                $j = 1;
                                foreach ($this->result as $row) {
                                    ?>
                                    <tr>
                                        <td class="center">
                                            <?php echo $j; ?>
                                        </td>
                                        <td>
                                            <?php echo $row['district']; ?>
                                        </td>
                                        <td>
                                            <?php echo $row['tehsil']; ?>
                                        </td>
                                        <td>
                                            <?php echo $row['ucs']; ?>
                                        </td>
                                        <td class="right">
                                            <?php echo number_format($row['facility_total_pouplation']); ?>
                                        </td>
                                        <?php
                                        foreach ($this->items as $items) {

                                            $nod = $items['no_of_doses'];
                                            $max_i;
                                            $col_span = 0;
                                            for ($i = $items['start_no']; $i <= $items['no_of_doses']; $i++) {
                                                if ($i == 0) {
                                                    $nod += 1;
                                                }
                                                $col_span += 5;
                                                ?>
                                                <?php ($i == 1 && $i == $nod) ? '' : $i; ?>
                                                <!--0-11 months-->
                                                <?php $row0 = $this->reports()->ucWiseReport3($row['pk_id'], $items['pk_id'], '145', $this->year_sel, $this->month_sel, $i); ?>
                                                <td class="right">
                                                    <?php echo (!empty($row0['inside_uc_male'])) ? $row0['inside_uc_male'] : '0'; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo (!empty($row0['inside_uc_male'])) ? $row0['outside_uc_female'] : '0'; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo (!empty($row0['outside_uc_male'])) ? $row0['outside_uc_male'] : '0'; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo (!empty($row0['outside_uc_male'])) ? $row0['outside_uc_male'] : '0'; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo (!empty($row0['total'])) ? $row0['total'] : '0'; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo (!empty($row0['total'])) ? $row0['total'] : '0'; ?>
                                                </td>

                                                <!--end-->                                      
                                            <?php } ?>
                                            <!--opening balance-->
                                            <?php $row2 = $this->reports()->ucWiseReport11($row['pk_id'], $items['pk_id'], $this->year_sel, $this->month_sel); ?>
                                            <td class="right">
                                                <?php echo (!empty($row2['opening_balance'])) ? $row2['opening_balance'] : '0'; ?>
                                            </td>
                                            <td class="right">
                                                <?php echo (!empty($row2['received_balance'])) ? $row2['received_balance'] : '0'; ?>
                                            </td>

                                            <td class="right">
                                                <?php echo (!empty($row2['closing_balance'])) ? $row2['closing_balance'] : '0'; ?>
                                            </td>
                                            <td class="right">
                                                <?php echo (!empty($row2['closing_balance'])) ? $row2['closing_balance'] : '0'; ?>
                                            </td>
                                            <td class="right">
                                                <?php echo (!empty($row2['closing_balance'])) ? $row2['closing_balance'] : '0'; ?>
                                            </td>

                                            <!--end-->  

                                        <?php } ?>
                                    </tr>
                                    <?php
                                    $j++;
                                }
                                ?>
                            </tbody>
                        </table>
                        </td>
                        </tr>
                        </table>
                    </div>
                </div>


                <?php
            } else {
                echo "No record found";
            }
            ?>
        </div>
    </div>
</div>



