<?php

/**
 * Model_CcmStatusList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Cold Chain
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_CcmStatusList extends Model_Base {

    private $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('CcmStatusList');
    }

    public function getStatusLists() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("csl.pkId,csl.ccmStatusListName")
                ->from('CcmStatusList', 'csl')
                ->where('csl.type = 1');
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }

    public function getAllReasons() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("csl.pkId,csl.ccmStatusListName")
                ->from('CcmStatusList', 'csl')
                ->where('csl.type = 2');
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }
    
     public function getAllUtilizations() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("csl.pkId,csl.ccmStatusListName")
                ->from('CcmStatusList', 'csl')
                ->where('csl.type = 3');
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }
    
    
     public function getAllStatusLists($order = null, $sort = null) {
      
       
        $str_sql = $this->_em->createQueryBuilder()
                ->select("sl.pkId,sl.ccmStatusListName,sl.type,sl.status,u.userName")
                ->from('CcmStatusList', 'sl')
                ->join('sl.createdBy', 'u');
        if (!empty($this->form_values['ccmStatusListName'])) {
            $str_sql->where("sl.ccmStatusListName = '".$this->form_values['ccmStatusListName']."'  ");
        }
        
        if ( $this->form_values['status'] =='1') {
            $str_sql->where("sl.status = '1'  ");
        }
        if ( $this->form_values['status'] =='2') {
            $str_sql->where("sl.status = '0'  ");
        }
     //  echo $str_sql->getQuery()->getSql();exit;
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }
//
//    public function getAllMakesByAssetType() {
//        $str_sql = $this->_em->createQueryBuilder()
//                ->select("mm.pkId,mm.ccmMakeName")
//                ->from('CcmModels', 'm')
//                ->join("m.ccmMake", 'mm')
//                ->where('m.ccmAssetType='.$this->form_values['type_id']);
//       
////echo $str_sql->getQuery()->getSql();
//        $row = $str_sql->getQuery()->getResult();
//
//        if (!empty($row) && count($row) > 0) {
//            return $row;
//        } else {
//            return false;
//        }
//    }
//
//    public function addStatusList() {
//        $ccm_status_list= new CcmStatusList();
//        $ccm_status_list->setTransactionReference($this->form_values['transaction_reference']);
//        $ccm_status_list->setTransactionNumber($trans_no);
//
//        $this->_em->persist($ccm_status_list);
//        $this->_em->flush();
//        return $stock_master->getPkId();
//    }
//    
//    public function getAllMakesForAddForm() {
//        $str_sql = $this->_em->createQueryBuilder()
//                ->select("m.pkId, m.ccmMakeName")
//                ->from('CcmMakes', 'm');
//        $row = $str_sql->getQuery()->getResult();
//        if (!empty($row) && count($row) > 0) {
//            return $row;
//        } else {
//            return false;
//        }
//    }
//
//    public function getMakeByMakeId() {
//        $str_sql = $this->_em->createQueryBuilder()
//                ->select('c.pkId', 'c.ccmMakeName')
//                ->from("CcmMakes", "c")
//                ->where("c.pkId = " . $this->form_values['make_id']);
//        $result = $str_sql->getQuery()->getResult();
//        return $result;
//    }

}
