<?php

/**
 * Model_CcmMakes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Cold Chain
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_GatepassVehicles extends Model_Base {

    private $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('GatepassVehicles');
    }
    
    public function getVehicleNumberByType() {

        $str_sql = $this->_em->createQueryBuilder()
                ->select('gpv.pkId', 'gpv.number')
                ->from("GatepassVehicles", "gpv")
                ->where("gpv.vehicleType = " . $this->form_values['vehicle_type_id']);
        //echo $str_sql->getQuery()->getSql();exit;
        $result = $str_sql->getQuery()->getResult();

        return $result;
    }

}
