<?php

/**
 * Model_VvmTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_LocationTypes extends Model_Base {

    protected $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('LocationTypes');
    }

//    public function getAll() {
//        $str_sql = $this->_em->createQueryBuilder()
//                ->select('vt.pkId as pk_id, vt.vvmTypeName as vvm_type_name')
//                ->from("VvmTypes", "vt")
//                ->orderBy("vt.pkId", "DESC");
//        $result = $str_sql->getQuery()->getResult();
//        return $result;
//    }
  
    public function getAllLocationTypes($order = null, $sort = null) {
      
       
        $str_sql = $this->_em->createQueryBuilder()
                ->select("lt.pkId,lt.locationTypeName,lt.status,u.userName,gl.geoLevelName")
                ->from('LocationTypes', 'lt')
                ->join('lt.createdBy', 'u')
                ->join('lt.geoLevel', 'gl');
        if (!empty($this->form_values['locationTypeName'])) {
            $str_sql->where("lt.locationTypeName = '".$this->form_values['locationTypeName']."'  ");
        }
        
        if ( $this->form_values['status'] =='1') {
            $str_sql->ANDwhere("lt.status = '1'  ");
        }
        if ( $this->form_values['status'] =='2') {
            $str_sql->ANDwhere("lt.status = '0'  ");
        }
       //echo $str_sql->getQuery()->getSql();exit;
       return $row = $str_sql->getQuery()->getResult();
      
    }

}
