<?php

/**
 * Model_Placements
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_Period extends Model_Base {

    private $_table;
    const QUARTER = 3;
    const HALFYEAR = 6;
    const ANNUAL = 12;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Period');
    }

    public function getPeriodById() {
        return $this->_table->find($this->form_values['id']);
    }
    
    public function getTimeIntervals() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("p.periodName,p.pkId,p.monthCount")
                ->from("Period", "p")
                ->where("p.monthCount > 1");

        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }

}
