<?php

/**
 * Model_ItemPackSizes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_PhysicalStockTaking extends Model_Base {

   
    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('PhysicalStockTaking');
    }

    public function getAllDescripiton() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("ips")
                ->from("PhysicalStockTaking", "ips")
                ->orderBy("ips.pkId", "ASC");
        //   echo $str_sql->getQuery()->getSql();
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }

   

}
