<?php

/**
 * Model_PlacementQuantity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_PlacementQuantity extends Model_Base {

    private $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('CcmEquipmentTypes');
    }

    public function find_by_asset_batch($cc_id = 0, $batch_id = 0) {

        $str_sql = $this->_em->createQueryBuilder()
                ->select("pq.*")
                ->from("Model_PlacementQuantity pq")
                ->where("pq.ccm_id =2")
                ->andWhere("pq.stock_batch_id=92");

        $result = $str_sql->fetchArray();

        return $result;
    }

    public function add($data) {
        $placement_qty = new Model_PlacementQuantity();
        $placement_qty->ccm_id = $data['coldchain'];
        $placement_qty->quantity = $data['quantity'];
        $placement_qty->stock_batch_id = $data['batchID'];
        $placement_qty->save();
        return $placement_qty->getLast();
    }

    public function update($data) {
        $quantity = $data['quantity'];
        $pk_id = $data['pk_id'];

        $str_sql = $this->_em->createQueryBuilder()
                ->update('Model_PlacementQuantity')
                ->set('quantity', '?', $quantity)
                ->where('pk_id = ?', $pk_id);

        $str_sql->execute();
        return ( $str_sql->getCountSqlQuery() == 1) ? true : false;
    }

}
