<?php

/**
 * Model_Roles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_Roles extends Model_Base {

    protected $_table;

    const CAMPAIGN = 7;
    const INVENTORY = 29;
    const COLDCHAIN = 30;
    const SUPPLIER = 21;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Roles');
    }

    public function getRoleByCat($cat_id) {
        return $this->_table->findBy(array("category" => $cat_id));
    }

    public function getRoles($order = null, $sort = null) {
        if (!empty($this->form_values)) {
            return $this->_table->findBy($this->form_values);
        } else {
            $qry = $this->_em->createQueryBuilder()
                    ->select("r")
                    ->from("Roles", "r")
                    ->join("r.category", "c");

            if ($order == 'role_name') {
                $qry->orderBy("r.roleName", $sort);
            }
            if ($order == 'description') {
                $qry->orderBy("r.description", $sort);
            }
            if ($order == 'created_date') {
                $qry->orderBy("r.createdDate", $sort);
            }
            if ($order == 'category') {
                $qry->orderBy("c.pkId", $sort);
            }

            return $qry->getQuery()->getResult();
        }
    }

    public function getAllRoles() {

        $qry = $this->_em->createQueryBuilder()
                ->select("r.pkId,r.roleName")
                ->from("Roles", "r");


        return $qry->getQuery()->getResult();
    }

    public function getAllRolesResources() {


        $qry = $this->_em->createQueryBuilder()
                ->select("r.pkId,r.roleName")
                ->from("Roles", "r");
        if (!empty($this->form_values['role'])) {
            $qry->where("r.pkId =" . $this->form_values['role']);
        }

        return $qry->getQuery()->getResult();
    }

}
