<?php

/**
 * Model_Shipment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author    Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_Shipments extends Model_Base {

    private $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Shipments');
    }

    public function getMinDate($date) {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("MIN(sh.shipmentDate) sh_date")
                ->from("Shipments", "sh")
                ->where("sh.shipmentDate > '" . $date . "'");

        $result = $str_sql->getQuery()->getResult();
        if (count($result) > 0) {
            return $result[0]['sh_date'];
        } else {
            return '';
        }
    }

    public function getMaxDate($date) {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("MAX(sh.shipmentDate) sh_date")
                ->from("Shipments", "sh")
                ->where("sh.shipmentDate > '" . $date . "'");

        $result = $str_sql->getQuery()->getResult();
        if (count($result) > 0) {
            return $result[0]['sh_date'];
        } else {
            return '';
        }
    }

    public function addProcurements() {

        $data = $this->form_values;
        //  App_Controller_Functions::pr($data);
        $shipments = new Shipments();
        $shipmentHistory = new ShipmentHistory();




        $shipments->setReferenceNumber($data['transaction_reference']);

        $item_id = $this->_em->getRepository('ItemPackSizes')->find($data['item_id']);
        $shipments->setItemPackSize($item_id);
        $shipments->setShipmentDate(new \DateTime(App_Controller_Functions::dateToDbFormat($data['shipment_date'])));
        $shipments->setShipmentQuantity($data['quantity']);
        $funding_source_id = $this->_em->getRepository('Warehouses')->find($data['from_warehouse_id']);
        $shipments->setFundingSource($funding_source_id);
        $activity_id = $this->_em->getRepository('StakeholderActivities')->find($data['activity_id']);
        $shipments->setStakeholderActivity($activity_id);
        $warhouse_id = $this->_em->getRepository('Warehouses')->find($this->_identity->getWarehouseId());
        $shipments->setWarehouse($warhouse_id);
        $shipments->setCreatedDate(new \DateTime(date("Y-m-d")));
        $created_by = $this->_em->getRepository('Users')->find($this->_user_id);
        $shipments->setCreatedBy($created_by);

        $this->_em->persist($shipments);
        $this->_em->flush();

        $id = $shipments->getPkId();

        $shipment_id = $this->_em->getRepository('Shipments')->find($id);
        $shipmentHistory->setShipment($shipment_id);
        $shipmentHistory->setStatus($data['status']);
        $shipmentHistory->setReferenceNumber($data['transaction_reference']);
        $shipmentHistory->setCreatedDate(new \DateTime(date("Y-m-d")));
        $created_by = $this->_em->getRepository('Users')->find($this->_user_id);
        $shipmentHistory->setCreatedBy($created_by);

        $this->_em->persist($shipmentHistory);
        $this->_em->flush();

        $shipment_history_id = $shipmentHistory->getPkId();
        return $shipment_history_id;
    }

    public function getProcurements() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("DISTINCT s.referenceNumber, s.pkId, warehouse.warehouseName, "
                        . "s.shipmentDate,s.shipmentQuantity as quantity,sh.status,ips.itemName,sa.activity")
                ->from("ShipmentHistory", "sh")
                ->join("sh.shipment", "s")
                ->join("s.itemPackSize", "ips")
                ->join("s.stakeholderActivity","sa")
                ->join("s.fundingSource", 'warehouse')
                ->join("s.warehouse",'w')
                ->andWhere("w.pkId = " . $this->_identity->getWarehouseId());

        if (!empty($this->form_values['from_date']) && !empty($this->form_values['to_date'])) {
            $str_sql->andWhere("DATE_FORMAT(s.shipmentDate,'%Y-%m-%d') BETWEEN '" . App_Controller_Functions::dateToDbFormat($this->form_values['from_date']) . "' AND '" . App_Controller_Functions::dateToDbFormat($this->form_values['to_date']) . "'");
        } else {
            $date_from = date('Y-m' . '-01');
            $date_to = date('Y-m-d');
            $str_sql->andWhere("DATE_FORMAT(s.shipmentDate,'%Y-%m-%d') BETWEEN '" . $date_from . "' AND '" . $date_to . "'");
        }
        if (!empty($this->form_values['item_pack_size_id'])) {
            $str_sql->andWhere("ips.pkId = '" . $this->form_values['item_pack_size_id'] . "'");
        }
        if (!empty($this->form_values['from_warehouse_id'])) {
            $str_sql->andWhere("warehouse.pkId = '" . $this->form_values['from_warehouse_id'] . "'");
        }
        if (!empty($this->form_values['status'])) {
            $str_sql->andWhere("sh.status = '" . $this->form_values['status'] . "'");
        } //else {
//            $str_sql->andWhere("sh.status = 'Received' ");
//        }

        $str_sql->orderBy("s.pkId", "DESC");
        $row = $str_sql->getQuery()->getResult();
        return $row;
    }

}
