<?php

/**
 * Model_VvmTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_VvmTypes extends Model_Base {

    protected $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('CcmEquipmentTypes');
    }

    public function getAll() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select('vt.pkId as pk_id, vt.vvmTypeName as vvm_type_name')
                ->from("VvmTypes", "vt")
                ->orderBy("vt.pkId", "DESC");
        $result = $str_sql->getQuery()->getResult();
        return $result;
    }

    public function getAllVvmTypes($order = null, $sort = null) {

        $str_sql = $this->_em->createQueryBuilder()
                ->select("vt.pkId,vt.vvmTypeName,vt.status,u.userName,ip.itemName")
                ->from('VvmTypes', 'vt')
                ->join('vt.createdBy', 'u')
                ->join('vt.itemPackSize', 'ip');
        if (!empty($this->form_values['vvmTypeName'])) {
            $str_sql->where("vt.vvmTypeName = '" . $this->form_values['vvmTypeName'] . "'  ");
        }

        if ($this->form_values['status'] == '1') {
            $str_sql->where("vt.status = '1'  ");
        }
        if ($this->form_values['status'] == '2') {
            $str_sql->where("vt.status = '0'  ");
        }
        //echo $str_sql->getQuery()->getSql();exit;
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }

    public function checkVvmTypes() {
        $form_values = $this->form_values;
        $str_sql = $this->_em->createQueryBuilder()
                ->select('vt.vvmTypeName')
                ->from("VvmTypes", "vt")
                ->where("vt.vvmTypeName= '" . $form_values['vvm_type_name'] . "' ");

        $result = $str_sql->getQuery()->getResult();
        return $result;
    }

}
