<div class="row">
    <div class="col-md-3">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("Role"); ?></label>
            <?php echo $this->form->role; ?>
        </div>
    </div>

</div>

<?php echo $this->form->user_id; ?>
<?php echo $this->form->office_id_edit; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->tehsil_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->warehouse_users_id_edit; ?>
<?php echo $this->form->default_warehouse_update_hidden; ?>

