<div class="banner-wrapper">
    <div class="banner">
        <ul>
            <li>
                <div class="banner-text">
                    <img src="images/slide-logo-1.png" alt="" class="left" />
                    <div style="float: left;">
                        <h1>Pakistan Logistics</h1>
                        <h2>Management Information System</h2>
                        <p>The LMIS is a web-based health commodity information system catering the logistics management of health products for both population and health sectors.</p>
                    </div>
                </div> <!--banner-text END-->
                <img src="images/slide-image-1.jpg" alt="" class="right" />
            </li>
            <li>
                <div class="banner-text">
                    <div style="float: left;">
                        <h1>Contraceptives</h1>
                        <h2>Information System for Contraceptives</h2>
                        <p>The LMIS is a web-based reproductive health commodity information system catering to the logistics management of contraceptive commodities.</p>
                    </div>
                </div> <!--banner-text END-->
                <img src="images/slide-image-cont.jpg" alt="" class="right" />
            </li>
            <li>
                <div class="banner-text">
                    <div style="float: left;">
                        <h1>Tuberculosis Drug</h1>
                        <h2>Management Information System</h2>
                        <p>With TB-DMIS implementation, the liklyhood of stock outs and overstocks that can lead to product expiration will reduce and programs can avoid wasting valuable tuberculosis medicine resources through prolonged and frequent stock outs, overstocks and losses.</p>
                    </div>
                </div> <!--banner-text END-->
                <img src="images/slide-image-TB.jpg" alt="" class="right" />
            </li>
            <li>
                <div class="banner-text">
                    <div style="float: left;">
                        <h1>Vaccines Logistics</h1>
                        <h2>Management Information System</h2>
                        <p>Manages the national immunization programmes by providing a well-designed logistics management information system for vaccines. Supports Data Collection, Reporting and Stock Inventory Control to ensure proper management of all vaccine product supplies.</p>
                    </div>
                </div> <!--banner-text END-->
                <img src="images/slide-image-vaccine.jpg" alt="" class="right" />
            </li>
        </ul>
    </div> <!--banner-inner END-->
</div> <!--banner-wrapper END-->