<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9"> <![endif]-->
<!--[if gt IE 8]> <html class="ie gt-ie8"> <![endif]-->
<!--[if !IE]><!--><html><!-- <![endif]-->
    <head>
        <meta charset="UTF-8" />
        <?php echo $this->headTitle('Pakistan Logistics Management Information System'); ?>

        <!-- Meta -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="title" content="<?php echo Zend_Registry::get('pageTitle'); ?>">
        <meta name="description" content="<?php echo Zend_Registry::get('metaDescription'); ?>">

        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/css/fonts/custom.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/css/components.css" rel="stylesheet" type="text/css"/>

        <!-- Glyphicons Font Icons -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/glyphicons.css" rel="stylesheet" />
        <!--[if !IE]>
        <!-- Column Filter Widgets Css -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/ColumnFilterWidgets.css" rel="stylesheet" />
        <!-- PrettyPhoto -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/gallery/prettyphoto/css/prettyPhoto.css" rel="stylesheet" />
        <!-- DateTimePicker Plugin -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/bootstrap-datetimepicker/css/datetimepicker.css" rel="stylesheet" />
        <!-- JQueryUI -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery-ui/css/smoothness/jquery-ui-1.9.2.custom.min.css" rel="stylesheet" />
        <!--[endif]>
        <!-- Main Theme Stylesheet :: CSS -->
        <!-- Notyfy Notifications Plugin -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/notifications/notyfy/jquery.notyfy.css" rel="stylesheet" />
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/notifications/notyfy/themes/default.css" rel="stylesheet" />

        <!-- BEGIN PAGE LEVEL STYLES -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/select2/select2.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/select2/select2-metronic.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css"/>
        <!-- END PAGE LEVEL STYLES -->

        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/style-light.css?1369414385" rel="stylesheet" />
        <!--        <link href="--><?php ////echo $this->baseUrl();                        ?><!--<!--/common/theme/css/style-green.css" rel="stylesheet" />-->
        <!-- LESS.js Library
        <script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/less.min.js"></script>-->
        <!--[if !IE]>
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/google-fonts.css" rel="stylesheet" />

        <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
        <!--        <link href="--><?php //echo $this->baseUrl();                       ?><!--/common/assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>-->
        <!--[endif]>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css"/>
        <!--        <link href="--><?php //echo $this->baseUrl();                       ?><!--/common/assets/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>-->
        <!--        <link href="--><?php //echo $this->baseUrl();                       ?><!--/common/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css"/>-->
        <!-- END PAGE LEVEL PLUGIN STYLES -->

        <!-- BEGIN THEME STYLES -->
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/pages/tasks.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/print.css" rel="stylesheet" type="text/css" media="print"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>

        <!-- BEGIN PAGE LEVEL STYLES -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/jquery-notific8/jquery.notific8.min.css"/>
        <!-- END PAGE LEVEL STYLES -->
        <style>
            .page-content{
                margin-left: 0;
                margin-top: 0;
            }
        </style>
        <!--[if lt IE 9]>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/respond.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/excanvas.min.js"></script>
        <!--<link href="<?php echo $this->baseUrl(); ?>/common/assets/global/css/ie8.css" rel="stylesheet" type="text/css" />-->
        <!--[endif]-->

        <!-- Fusion Charts -->
        <!-- JQuery-->
        <script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery.min.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/fusioncharts.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.fint.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.carbon.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.ocean.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.zune.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Code/assets/ui/js/lib.js"></script>

        <link href="<?php echo $this->baseUrl(); ?>/js/OpenLayers-2.13/theme/default/style.css" rel="stylesheet" />
        <!--<script src="<?php echo $this->baseUrl(); ?>/js/OpenLayers-2.13/OpenLayers.js"></script>-->

        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php $uri = $_SERVER['REQUEST_URI']; ?>
    <body class="page-header-fixed <?php if ($uri == '/dashboard/index') { ?>page-sidebar-closed <?php } ?>" <?php if (isset($child) && $child == 1) { ?> onunload="window.opener.location.reload();" <?php } ?> onLoad="<?php if (isset($xgrid) && $xgrid == 1) : ?> doInitGrid(); <?php endif; ?> <?php if (isset($stkholder) && $stkholder == 1) : ?>showstkHolders(); <?php endif; ?><?php if (isset($_POST['go'])): ?> showProvinces(); showDistricts(); <?php endif; ?><?php if (isset($func) && $func == 1) : ?> func(); <?php endif; ?>">
        <!-- Main Container Fluid -->
        
        <div class="page-container">
            <!-- Sidebar menu & content wrapper -->
