<?php
/**
*  phtml for Locations Combos For Distt
*/
?>
<?php if ($this->result != false) { ?>
    <option value=""><?php echo $this->translate("Select"); ?></option>
    <?php foreach ($this->result as $row) {
        ?>
        <option value="<?php echo $row['key']; ?>" <?php if (!empty($this->district_id) && $row['key'] == $this->district) echo 'selected'; ?>>
            <?php echo $row['value']; ?></option>
    <?php }
} ?>
