<div class="page-content-wrapper">
    <div class="page-content">
         <h3 class="page-title">Cold Chain Capacity</h3>
         <div class="row">
             <div class="col-md-12">
                 <div class="widget widget-tabs">  
                     <div class="widget-head dashboard-widget">
                            <ul>
                                <li class="">
                                     <a href="<?php echo $this->baseUrl(); ?>/default/maps/cold-chain-capacity/?id=4">
                                        <div class="dashboard-stat_custom">
                                            <div class="visual" style="width: auto;">
                                                <i class="fa fa-routine-immunization"></i>
                                            </div>
                                            <div class="details" style="float: left;">
                                                <div class="dashboard-title-1"> District </div>
                                                <div class="dashboard-title-2">Map</div>
                                            </div>   
                                        </div>
                                    </a>
                                </li>
                                 <li class="active">
                                     <a href="<?php echo $this->baseUrl(); ?>/default/maps/cold-chain-capacity/?id=5">
                                        <div class="dashboard-stat_custom">
                                            <div class="visual" style="width: auto;">
                                                <i class="fa fa-routine-immunization"></i>
                                            </div>
                                            <div class="details" style="float: left;">
                                                <div class="dashboard-title-1"> Tehsil </div>
                                                <div class="dashboard-title-2">Map</div>
                                            </div>   
                                        </div>
                                    </a>
                                </li>
                              
                            </ul>
                     </div>
                     
                     
                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active">
                                <div class="row">
                                    <div class="col-md-12"> 




            <div class="col-md-12">
                   
                    <div class="col-md-12">
                        <div class="portlet box green">
                            <div class="portlet-title">
                                <div class="caption">
                                    User Filter
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <div class="col-md-12">

                                             <div class="col-md-10">
                                                  <div class="col-md-1"></div>
                                                    <div class="col-md-2">
                                                        <div class="form-group ">
                                                            <label class="control-label" > <?php echo $this->translate("Province/Region"); ?>:</label>
                                                            <?php echo $this->form->prov; ?>
                                                        </div>
                                                    </div>
                                                   <div class="col-md-2">
                                                        <div class="form-group ">
                                                            <label class="control-label" > <?php echo $this->translate("District"); ?>:</label>
                                                            <?php echo $this->form->dist; ?>
                                                        </div>
                                                    </div>
                                                   <div class="col-md-2">
                                                        <div class="form-group ">
                                                            <label class="control-label" >  <?php echo $this->translate("Type"); ?>:</label>
                                                            <?php echo $this->form->cc_type; ?>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-1">
                                                        <div class="form-group  form-btn-margin-top">
                                                            <button class="btn btn-primary" id="submit" type="submit" name="search"><?php echo $this->translate("Filter") ?></button>
                                                        </div>
                                                    </div>
                                                </div> 
                                            <br/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                
                
            </div>

       
            <div class="col-md-12">
                <div class="map-buttons-download">
                    <img id="image"  src="<?php echo $this->baseUrl(); ?>/images/image.png"  align="right" title="Download Map" />
                    <img id="excel"  src="<?php echo $this->baseUrl(); ?>/images/excel-32.png"  align="right" title="Download Excel" />
                </div>
            </div>
       

            
            <div class="col-md-8">
                
                <div id="capture" style="width:auto;height:auto">
                            <table width="100%" cellpadding="0" cellspacing="0">
                                                <tr>
                                                    <td width="100%">
                                                        <div id="map">
                                                            <div id="customZoom">
                                                              <a href="#customZoomIn" id="customZoomIn">in</a>
                                                                <a href="#customZoomOut" id="customZoomOut">out</a>
                                                            </div>
                                                            <div id="legendDiv">
                                                                <div>
                                                                    <table id='legend'></table>
                                                                </div>
                                                            </div>
                                                            <img id="loader" src="<?php echo $this->baseUrl(); ?>/images/ajax-loader.gif" />
                                                            <div id="mapTitle"></div>
                                                            <div id="printedDate"></div>
                                                        </div>
                                                    </td>
                                                </tr>
                            </table>
                </div>
                              
            </div>
            
            <div class="col-md-4">
                
               
                           <div class="widget" data-toggle="collapse-widget">
                                <div class="widget-head">
                                    <h3 class="heading">Tehsil Information</h3>
                                </div>
                                <div class="widget-body">
                                    <div>
                                          <table border='1' class='infoTable'>
                                        <tr>
                                            <td class='bold'>Province</td>
                                            <td id='province'></td>
                                        </tr>
                                        <tr>
                                            <td class='bold'>District</td>
                                            <td id='district'></td>
                                        </tr>
                                        <tr>
                                            <td class='bold'>Tehsil</td>
                                            <td id='tehsil'></td>
                                        </tr>
                                        <tr>
                                            <td class='bold'>Capacity(litre)</td>
                                            <td id='capacity'></td>
                                        </tr>
                                    </table>
                                    </div>
                                </div>
                            </div>
                
                           <hr/>
                           <div class="widget" data-toggle="collapse-widget">
                                <div class="widget-head">
                                    <h3 class="heading">Cold Chain Asset Types Details</h3>
                                </div>
                                <div class="widget-body">
                                    <div id="_list"></div>
                                </div>
                            </div><hr/>

            </div>
            
                <div class="col-md-12">
                        <div class="col-md-6">
                            <div class="widget" data-toggle="collapse-widget">
                                <div class="widget-head">
                                    <h3 class="heading">Cold Chain Capacity Status</h3>
                                </div>
                                <div class="widget-body">
                                    <div id='tehsilPie'></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="widget" data-toggle="collapse-widget">
                                <div class="widget-head">
                                    <h3 class="heading">Tehsil wise Cold Chain Capacity Status</h3>
                                </div>
                                <div class="widget-body">
                                    <div id='attributeGrid'></div>
                                </div>
                            </div>
                        </div>
                    </div>  

   

          
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                 
                 </div>  
                 
                 
             </div>
         </div>
    </div>
</div>

