<div class="row">
<div class="col-md-5">
    <div class="form-group ">
        <label class="control-label" ><?php echo $this->translate("Transaction Type Name"); ?> <span class="red">*</span></label>
        <?php echo $this->form->transaction_type_name; ?>
    </div> 
</div>
    
    <div class="col-md-1 margin-top-33">
    <div class="form-group ">
        <?php echo $this->form->is_adjustment; ?>
    </div></div>
     <div class="col-md-5">
    <div class="form-group ">
        <label class="control-label" ><?php echo $this->translate("Stock recieve from warehouse"); ?></label>
        
    </div>
</div>
</div>
<?php echo $this->form->transaction_type_id; ?>