<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Transaction Types") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Transaction Type Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php if (isset($_GET['success']) && $_GET['success'] == 1) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been saved successfully!
                                    </div>
                                <?php }

                                if (isset($_GET['success']) && $_GET['success'] == 2) {
                                    ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been updated successfully!
                                    </div>
                                <?php }
                                ?>
                                <form method="POST" name="transaction_type_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Transaction Type"); ?></label>
                                                    <?php echo $this->form->transaction_type_name; ?>
                                                </div>
                                            </div>

                                            <div class="col-md-4 margin-top-25">
                                                <div class="form-group" id="div_status">
                                                    <label class="control-label" ><?php echo $this->translate("Nature"); ?></label>
                                                    <?php echo $this->form->nature; ?>
                                                </div>
                                            </div>
                                            <div class="col-md-3 margin-top-25">
                                                <div class="form-group">
                                                    <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                    <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Transaction Type List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#add-transaction-type"><?php echo $this->translate("Add Transaction Type") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'transaction_type_name' => 'Transaction Type Name',
                                            'created_by' => 'Created By',
                                            'nature' => 'Nature'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row['transactionTypeName']; ?></td>
                                                        <td><?php echo $row['userName']; ?></td>
                                                        <td>

                                                            <?php if ($row['nature'] == '+') { ?>
                                                                <a id="nature_<?php echo $row['pkId']; ?>" class="positive btn-link btn-danger input-sm"><?php echo $this->translate("Positive"); ?></a>
                                                            <?php } else { ?>
                                                                <a id="nature_<?php echo $row['pkId']; ?>" class="negative btn-link btn-danger input-sm"><?php echo $this->translate("Negative"); ?></a>
                                                            <?php } ?>

                                                        </td>
                                                        <td>
                                                            <a itemid="<?php echo $row['pkId']; ?>" class="btn update-transaction-type btn-link btn-success btn-mini" data-toggle="modal" href="#modal-update-transaction-type"><?php echo $this->translate("Edit") ?></a>
                                                            <?php if ($row['status'] == 1) { ?>
                                                                <a id="<?php echo $row['pkId']; ?>" class="active btn-link btn-danger input-sm"><?php echo $this->translate("Active"); ?></a>
                                                            <?php } else { ?>
                                                                <a id="<?php echo $row['pkId']; ?>" class="deactivate btn-link btn-danger input-sm"><?php echo $this->translate("Deactive"); ?></a>
                                                            <?php } ?>
                                                        </td>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                            $i++;
                                                        endforeach;
                                                    endif;
                                                    ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/add-transaction-type" id="add-transaction-types">
            <div class="modal fade" id="add-transaction-type" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add Transaction Type</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Transaction Type Name"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->transaction_type_name; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" ><?php echo $this->translate("Nature"); ?></label>
                                        <?php echo $this->form_add->nature; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-1 margin-top-33">
                                    <?php echo $this->form_add->is_adjustment; ?></div>
                                <div class="col-md-5">
<label class="control-label" ><?php echo $this->translate("Stock recieve from warehouse"); ?></label>
                                </div>
                                <div class="col-md-6 ">
                                    <div class="form-group" id="div_status">
                                        <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
                                        <?php echo $this->form_add->status; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/update-transaction-type" id="update-transaction-types">
            <div class="modal fade" id="modal-update-transaction-type" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit Transaction Type</h4>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>

            </div>
        </form>

    </div>
</div>
<!-- // Content END -->
