<div class="row">
    <div class="col-md-12 right">
        <img src="<?php echo $this->baseUrl(); ?>/images/print-16.png" onClick="printContents()" alt="Print" style="cursor:pointer;" />
        <img src="<?php echo $this->baseUrl(); ?>/images/excel-16.png" onClick="tableToExcel('export', 'sheet 1', '<?php echo $this->file_name;?>')" alt="Excel" style="cursor:pointer;" />
    </div>
</div>
</br>
<div class="row" id="export">

    <style>
        table#myTable{margin-top:0px !important; color: #000; font-family: 'Arial';}
        table#myTable{margin-top:20px;border-collapse: collapse;border-spacing: 0; width:100%; border:1px solid #999;}
        table#myTable tr td{font-size:11px;padding:3px; text-align:left; border:1px solid #999; color: #000; font-family: 'Arial';}
        table#myTable tr th{font-size:11px;padding:3px; text-align:center; border:1px solid #999; color: #000; font-family: 'Arial';}
        table#myTable tr td.TAR{text-align:right; padding:5px;width:50px !important;}
        .sb1NormalFont {color: #444444; font-size: 11px; font-weight: bold; text-decoration: none;}
        p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000; font-family: 'Arial';}
        table#headerTable tr td{ font-size:11px; color: #000; font-family: 'Arial';}
        h4{margin:0; color: #000; font-size:14px; font-family: 'Arial';}
        h5{margin:15px 0 5px 0; color: #000; font-family: 'Arial';}
        .right{text-align:right !important;}
        .center{text-align:center !important;}


        /* Print styles */
        @media only print
        {
            table#myTable{margin-top:0px !important;}

            table#myTable tr th{font-size:8px;padding:3px !important; text-align:center; border:1px solid #999; color: #000; font-family: 'Arial';}
            table#myTable tr td{font-size:8px;padding:3px !important; text-align:left; border:1px solid #999; color: #000; font-family: 'Arial';}
            #doNotPrint{display: none !important;}
            h4{margin:0; color: #000; font-family: 'Arial';}
            h5{margin:15px 0 5px 0; color: #000; font-family: 'Arial';}
            p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000; font-family: 'Arial';}    

        }
    </style>
    <script src="<?php echo $this->baseUrl(); ?>/js/reports/inventory-management/tableToExcel.js"></script>
    <script>
            function printContents() {
                var w = 900;
                var h = screen.height;
                var left = Number((screen.width / 2) - (w / 2));
                var top = Number((screen.height / 2) - (h / 2));
                var dispSetting = "toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes,left=" + left + ",top=" + top + ",width=" + w + ",height=" + h;
                var printingContents = document.getElementById("export").innerHTML;
                var docprint = window.open("", "", dispSetting);
                docprint.document.open();
                docprint.document.write('<html><head>');
                docprint.document.write('</head><body onLoad="self.print();self.close();"><center>');
                docprint.document.write(printingContents);
                docprint.document.write('</center></body></html>');
                docprint.document.close();
                docprint.focus();
            }
    </script>