<?php
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .="<rows>";

$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type_1 = $this->in_type_1;
$in_type = $this->in_type;
$sel_item = $this->sel_item;
$counter = 1;

foreach ($this->loc as $loc) {
    $xml_store .="<row id=\"$counter\">";
    $query_vals = $this->reports()->reportData($in_col, $in_rg, $in_type_1, $sel_month, $sel_year, $sel_item, 1, $loc['pk_id'], 0);
    foreach ($query_vals as $row_vals) {
        $item_id = $loc['pk_id'];
        $item_name = $loc['location_name'];
        $sel_stk = 0;
        $sel_lvl = 3;
        $month_num = "\"$sel_month\"";
        $year_num = "\"$sel_year\"";
        $temp_var = "";
        $temp_var .= "\"$sel_month\",";
        $temp_var .= "\"$sel_year\",";
        $temp_var .= "\"$sel_stk\",";
        $temp_var .= "\"$sel_lvl\",";
        $temp_var .= "\"$item_name\"";
        $tmp = explode('*', $row_vals['Value']);

        //<!-- begin data rending -->
        $sel_item = $loc['pk_id'];

        $xml_store .="<cell><![CDATA[<a href=javascript:functionCall($temp_var)>$item_name</a>]]>^_self</cell>";

        // $this->render('reports/ind_data_render.phtml');
        include ('ind_data_render.phtml');
    }

    $counter++;
}

$xml_store .="</rows>";
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>
            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:363px;">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<input type="hidden" name="sel_year" id="sel_year"  value="<?= $sel_year ?>">
<input type="hidden" name="sel_month" id="sel_month" value="<?= date('F', mktime(0, 0, 0, $sel_month)) ?>">
<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'>Divisional Report For Province/Region = " + $('#location_name').val() + " And Product = " + $('#item_name').val() + "(" + $('#sel_month').val() + " " + $('#sel_year').val() + ")</div>,#cspan,#cspan,#cspan,#cspan,#cspan");
        mygrid.attachHeader("<span title='Division'>Division</span>,<span title='Product Consumption'>Consumption (Doses)</span>,<span title='Average Monthly Consumption'>AMC (Doses)</span>,<span title='Product On Hand'>On Hand (Doses)</span>,<span title='Months of Stock'>MOS</span>,#cspan");
        mygrid.setInitWidths("*,160,160,160,40,40");
        mygrid.setColAlign("left,right,right,right,center,center");
        //mygrid.setColSorting("str,int");
        mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro");
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver');   // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store);?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }
</script>
