<?php
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .="<rows>";

$sel_month = $this->month_sel;
$sel_prov = $this->province;
$sel_dist = $this->district1;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$period = $this->period;
$whlist = "";
$counter = 1;
$i = 1;
if ($wh_type == 2) {
    $province = "Province/Region";
    $district = "District";
} else {
    $province = "Province/Region";
    $district = "District";
    $tehsil = "Tehsil";
}

foreach ($period as $date) {
    $str_date = $date->format("Y-m");
}

$query_0 = $this->reports()->getTotalByUc($wh_type, $str_date, $sel_prov, $sel_dist, $sel_tehsil);
$total = $query_0;
//echo $total[0];


$query_1 = $this->reports()->getNonReportedTotalByUc($wh_type, $str_date, $sel_prov, $sel_dist, $sel_tehsil);
$reported = $query_1;

$nonreported = $total[0]['abc'] - $reported[0]['abc'];
if ($total[0] == 0) {
    $ReportRate = (($total[0]['abc'] - $nonreported) / 1) * 100;
} else {
    $ReportRate = @(($total[0]['abc'] - $nonreported) / $total[0]['abc']) * 100;
}

$query_vals = $this->reports()->getNonReportedDistrictsByUc($wh_type, $str_date, $sel_prov, $sel_dist, $sel_tehsil);
foreach ($query_vals as $row) {
    $whlist .= "'" . $row['UCID'] . "',";
    //$whlist .= $row['UCID'];
    // $whlist;
}
if ($whlist) {
    $whlist = substr($whlist, 0, strlen($whlist) - 1);
    $qwhlist = " AND UC.pk_id NOT IN(" . $whlist . ")";
} else {
    $qwhlist = "";
}

$query1 = $this->reports()->getNonReportedDistrictsByUc1($wh_type, $str_date, $sel_prov, $sel_dist, $sel_tehsil, $qwhlist);

$counter = 1;
foreach ($query1 as $rowr2) {

    $xml_store .="<row id=\"$counter\">";
    $xml_store .="<cell style=\"text-align:center;\">" . $counter . "</cell>";
    $xml_store .="<cell><![CDATA[$rowr2[Province]]]></cell>";
    $xml_store .="<cell><![CDATA[$rowr2[District]]]></cell>";
    $xml_store .="<cell><![CDATA[$rowr2[tehName]]]></cell>";
    $xml_store .="<cell><![CDATA[$rowr2[UCName]]]></cell>";
    $xml_store .="<cell><![CDATA[$rowr2[User]]]></cell>";
    $xml_store .="<cell><![CDATA[$rowr2[Phone]]]></cell>";
    $xml_store .="</row>";
    $counter++;
}
$xml_store .="</rows>";
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">Non-Reported EPI Centers Report</h3>
        <div class="innerLR">
        </div>
        <div class="wrraper" style="height:auto; padding-left:5px">
            <div class="content" align="" style="min-height:679px;">
                <?php //showBreadCrumb();  ?>
                <table width="99%">
                    <tr>
                        <td colspan="6">
                            <?php
                            echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                            <input type="hidden" name="dist_id_hidden" id="dist_id_hidden" value="<?php echo $this->dist_id_hidden; ?>">
                        </td>
                    </tr>

                    <tr>
                        <td width="120" height="29" align="center" valign="middle"><strong class="sb1FormLabel">Total EPI Centers</strong></td>
                        <td width="22" align="left" valign="middle">&nbsp;<span class="sb1Exception"><?php echo $total[0]['abc']; ?></span></td>
                        <td width="240" align="center" valign="middle" class="sb1FormLabel">Total Non Reported EPI Centers</td>
                        <td width="60" align="left" valign="middle" class="sb1FormLabel"><span class="sb1Exception"><?php echo $nonreported; ?></span></td>
                        <td width="147" align="center" valign="middle" class="sb1FormLabel">Reporting Rate</td>
                        <td width="31" align="left" valign="middle" class="sb1Exception"><?php echo number_format($ReportRate, 2) ?>%&nbsp;</td>
                    </tr>  	
                    <tr>
                        <td align="right" colspan="6" style="padding-bottom: 10px;">
                            <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                            <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                        </td>
                    </tr>
                </table>
                <table width="99%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <div id="mygrid_container" style="width:100%; height:610px; background-color:white;overflow:hidden"></div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "Non-reported EPI Centers Report For $province $this->location_name (" . date('F', mktime(0, 0, 0, $this->month_sel)) . ' ' . $this->year_sel . ")"; ?></div>,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan");
        mygrid.attachHeader("<span title='Serial Number'>Sr No.</span>,<span title='Province/Region Name'>Province/Region</span>,<span title='District'>District</span>,<span title='Tehsil'>Tehsil</span>,<span title='Union Council'>Union Council</span>,<span title='vLMIS Operator'>Operator</span>,<span title='TelePhone Number'>TelePhone No</span>");
        //	mygrid.attachHeader(",#select_filter,#select_filter,#select_filter,#select_filter");
        mygrid.setInitWidths("60,170,170,170,170,*,160");
        mygrid.setColAlign("left,left,left,left,left,left,left");
        //mygrid.setColSorting("int,str,str,str,str");
        mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro");
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver');   // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }

    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;
</script>

