<?php
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .="<rows>";

$sel_month = $this->month_sel;
$sel_prov = $this->province;
$sel_dist = $this->district1;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$period = $this->period;
foreach ($period as $date) {
    $str_date = $date->format("Y-m");
}
$query_0 = $this->reports()->getTotalByFacility($wh_type,$str_date, $sel_prov, $sel_dist,$sel_tehsil);
$total = $query_0;

$query_1 = $this->reports()->getNonReportedTotalByFacility($wh_type,$str_date, $sel_prov, $sel_dist,$sel_tehsil);
$reported = $query_1;

$nonreported = $total[0]['abc'] - $reported[0]['abc'];
if ($total[0] == 0) {
    $ReportRate = (($total[0]['abc'] - $nonreported) / 1) * 100;
} else {
    $ReportRate = @(($total[0]['abc'] - $nonreported) / $total[0]['abc']) * 100;
}

$counter = 1;
$i = 1;

foreach ($period as $date) {
    $str_date = $date->format("Y-m");
}
$query_vals = $this->reports()->getNonReportedDistrictsByFacility($str_date, $sel_prov, $sel_dist);

foreach ($query_vals as $row) {
    $whlist .= "'" . $row['warehouse_id'] . "',";
    //$whlist .= $row['UCID'];
    // $whlist;
}
if ($whlist) {
    $whlist = substr($whlist, 0, strlen($whlist) - 1);
    $qwhlist = " AND warehouses.pk_id NOT IN(" . $whlist . ")";
} else {
    $qwhlist = "";
}

$query_vals1 = $this->reports()->getNonReportedDistrictsByFacility1($wh_type,$str_date, $sel_prov, $sel_dist, $qwhlist,$sel_tehsil);

foreach ($query_vals1 as $row_vals) {
    $query = $this->reports()->getNonReportedDistrictsByFacility2($row_vals['pk_id']);
    //if (count($query) > 0):
    $xml_store .="<row id=\"$counter\">";
    $xml_store .="<cell style=\"text-align:center;\">" . $i . "</cell>";
    foreach ($query as $row) {
        $wh_name = htmlentities($row['warehouse_name']);
        $prov_tittle = htmlentities($row[prov_tittle]);
        $d_name = htmlentities($row['d_name']);
         $teh_name = htmlentities($row['teh_name']);
        $UC = htmlentities($row['UC']);

        //$prov_tittle = (empty($row[prov_tittle]))? "-" : $row[prov_tittle];
        //$d_name = (empty($d_name))? "-" : $d_name;
        //$UC = (empty($UC))? "-" : $UC;
        //$wh_name = (empty($wh_name))? "-" : $wh_name;
        //$xml_store .="<cell><![CDATA[$row[prov_tittle]]]></cell>";
        //$xml_store .="<cell><![CDATA[$row[d_name]]]></cell>";
        //$xml_store .="<cell><![CDATA[$row[UC]]]></cell>";

        $xml_store .="<cell><![CDATA[$prov_tittle]]></cell>";
        $xml_store .="<cell><![CDATA[$d_name]]></cell>";
         $xml_store .="<cell><![CDATA[$teh_name]]></cell>";
        $xml_store .="<cell><![CDATA[$UC]]></cell>";

        $xml_store .="<cell><![CDATA[$wh_name]]></cell>";
//        $xml_store .="<cell><![CDATA[$row[FullName]]]></cell>";
//        $xml_store .="<cell><![CDATA[$row[Phone]]]></cell>";
        $xml_store .="</row>";
    }
    $counter++;
    $i++;
    //endif;
}

$xml_store .="</rows>";
?>
<?php
//XML write function
App_Controller_Functions::writeXML('non_report_facility.xml', $xml_store);
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">Non-Reported EPI Centers Report</h3>
        <div class="innerLR">
            <div class="wrraper" style="height:auto; padding-left:5px">
                <div class="content" align="" style="min-height:679px;">
                    <?php //showBreadCrumb();   ?>
                    <table width="99%">
                        <tr>
                            <td colspan="6">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="6">
                                <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                                <input type="hidden" name="dist_id_hidden" id="dist_id_hidden" value="<?php echo $this->dist_id_hidden; ?>">
                            </td>
                        </tr>

                        <tr>
                            <td width="120" height="29" align="center" valign="middle"><strong class="sb1FormLabel">Total EPI Centers</strong></td>
                            <td width="22" align="left" valign="middle">&nbsp;<span class="sb1Exception"><?php echo $total[0]['abc']; ?></span></td>
                            <td width="240" align="center" valign="middle" class="sb1FormLabel">Total Non Reported EPI Centers</td>
                            <td width="60" align="left" valign="middle" class="sb1FormLabel"><span class="sb1Exception"><?php echo $nonreported; ?></span></td>
                            <td width="147" align="center" valign="middle" class="sb1FormLabel">Reporting Rate</td>
                            <td width="31" align="left" valign="middle" class="sb1Exception"><?php echo number_format($ReportRate, 2) ?>%&nbsp;</td>
                        </tr>  	
                        <tr>
                            <td align="right" colspan="6" style="padding-bottom: 10px;">
                                <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                                <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                            </td>
                        </tr>
                    </table>
                    <table width="99%" cellpadding="0" cellspacing="0">
                        <tr>
                            <td>
                                <div id="mygrid_container" style="width:100%; height:610px; background-color:white;overflow:hidden"></div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "Non-reported EPI Centers Report For Province/Region $this->location_name (" . date('F', mktime(0, 0, 0, $this->month_sel)) . ' ' . $this->year_sel . ") "; ?></div>,#cspan,#cspan,#cspan,#cspan,#cspan");
        mygrid.attachHeader("<span title='Serial Number'>Sr No.</span>,<span title='Province/Region Name'>Province/Region</span>,<span title='District'>District</span>,<span title='tehsil'>Tehsil</span>,<span title='Union Council'>Union Council</span>,<span title='EPI Center'>EPI Center</span>");
        //	mygrid.attachHeader(",#select_filter,#select_filter,#select_filter,#select_filter");
        mygrid.setInitWidths("60,160,160,160,180,*");
        mygrid.setColAlign("left,left,left,left,left,left");
        mygrid.setColSorting("int,str,str,str,str,str");
        mygrid.setColTypes("ro,ro,ro,ro,ro,ro");
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver'); // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }
    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;
</script>
