<?php
$param = $this->param;

$wh_type = $param[0];
$districtId = $param[1];
$month = $param[2];
$year = $param[3];
$query = $this->reports()->getReportedUc($districtId, $wh_type);

$ucInfo = array();
foreach ($query as $row) {
    array_push($ucInfo, $row);
    $districtName = $row['District'];
}
$query_1 = $this->reports()->getReportedUc1($districtId, $month, $year, $wh_type);

$reportedUcArr = array();

foreach ($query_1 as $row) {
    array_push($reportedUcArr, $row['PkLocID']);
    $reportedUcDate[$row['PkLocID']] = $row['reported_date'];
}

$title = "Consumption Data Reporting Status For $districtName ($month/$year)";
?>

<style>
    table#myTable{margin-top:20px;border-collapse: collapse;border-spacing: 0;}
    table#myTable tr th{font-family:Arial,Helvetica,sans-serif; font-size:11px;padding-left:5px; border:1px solid #999;}
    table#myTable tr td{font-family:Arial,Helvetica,sans-serif; font-size:11px;padding-left:5px; border:1px solid #999;}
    table#myTable tr td.TAR{text-align:right; padding:5px;font-family:Arial,Helvetica,sans-serif; width:50px !important;}
    .sb1NormalFont {
        color: #444444;
        font-family: Verdana,Arial,Helvetica,sans-serif;
        font-size: 12px;
        font-weight: bold;
        text-decoration: none;
    }
</style>

<!-- Content -->
<div id="content" style="margin-left:0; min-height:560px !important;">
    <div class="innerLR">
        <table width="100%">
            <tr>
                <td style="text-align:right; padding-bottom:10px;">
                    <img style="cursor:pointer;" src="../../images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="Export to PDF"/>&nbsp;&nbsp;
                    <img style="cursor:pointer; margin-left:-5px" src="../../images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="Export to Excel" />
                </td>
            </tr>
        </table>
        <?php
        $xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
        $xml_store .="<rows>";
        for ($i = 0; $i < sizeof($ucInfo); $i++) {
            $r_date = $reportedUcDate[$ucInfo[$i]['PkLocID']];//"01/".$month."/".$year;
            $color = (in_array($ucInfo[$i]['PkLocID'], $reportedUcArr)) ? 'color:#008000;' : 'color:#FF0000;';
            $reported = (in_array($ucInfo[$i]['PkLocID'], $reportedUcArr)) ? '--' : 'NR';
            $reported_date = (in_array($ucInfo[$i]['PkLocID'], $reportedUcArr)) ? $r_date : 'NR';
            $ucId = $ucInfo[$i]['PkLocID'];
            $param1 = base64_encode("$ucId|$month|$year");

            $xml_store .="<row>";
            $xml_store .="<cell style=\"text-align:center;$color\">" . ($i + 1) . "</cell>";
            if (in_array($ucInfo[$i]['PkLocID'], $reportedUcArr)) {
                $xml_store .= "<cell style=\"text-align:left;$color\"><![CDATA[<a style=\"text-decoration: underline;\" href=javascript:showPopup('$param1')>" . $ucInfo[$i]['UCName'] . "</a>]]>^_self</cell>";
            } else {
                $xml_store .="<cell style=\"$color\"><![CDATA[" . $ucInfo[$i]['UCName'] . "]]></cell>";
            }
            $xml_store .="<cell style=\"$color\"><![CDATA[" . $ucInfo[$i]['WHName'] . "]]></cell>";
            $xml_store .="<cell style=\"$color\"><![CDATA[" . $ucInfo[$i]['FullName'] . "]]></cell>";
            $xml_store .="<cell style=\"$color\"><![CDATA[" . App_Controller_Functions::clearString($ucInfo[$i]['Address']) . "]]></cell>";
            $xml_store .="<cell style=\"$color\"><![CDATA[" . $ucInfo[$i]['Phone'] . "]]></cell>";
            $xml_store .="<cell style=\"$color\">$reported</cell>";
            $xml_store .="<cell style=\"$color\">$reported_date</cell>";
            $xml_store .="</row>";
        }
        $xml_store .="</rows>";
        ?>
    </div>
    <div id="mygrid_container" style="width:auto;height:500px;"></div>
</div>

<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        //mygrid.setHeader("Province,Consumption,AMC,On Hand,MOS,#cspan");
        mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo $title; ?> </div>,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan");
        mygrid.attachHeader("S.No.,UC Name,Health Facility,Operator,Address,Phone,Status,Reported Date");
        mygrid.setInitWidths("50,160,160,130,130,150,50,*");
        //mygrid.setColAlign("left,right,right,right,right,right,right,right,right,right,right,right,right");
        //mygrid.setColSorting("str,int");
        mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro,ro");
        mygrid.setColumnHidden(0, true);
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver'); // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }
    window.onload = function() {
        doInitGrid();
    }
    function showPopup(param) {
        var width = 1002;
        var height = 595;
        var x = (screen.width / 2) - (width / 2);
        var y = (screen.height / 2) - (height / 2);
        window.open('popup-data-entry?param=' + param + '&byUC=1', '_blank', 'scrollbars=1,width=' + width + ',height=' + height + ',left=' + x + ',top=' + y);
    }
  
</script>

