<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            Stock Balance Report <?php if(!empty($this->warehousename)) { ?>(<?php echo $this->warehousename; ?>)<?php } ?>
        </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Search Filters"); ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse"></a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form method="POST" name="ledger" action="" id="product_plac">
                            <?php if($this->role_id != 24) { ?>
                            <div class="row">
                                <?php $this->allLevelCombo(); ?>
                            </div>
                            <?php } ?>
                            <div class="row">
                                <div class="col-md-12">                                
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="month"><?php echo $this->translate("Month") ?></label>
                                                <select class="form-control" name="month">
                                                    <?php
                                                    for ($m = 1; $m <= 12; $m++) {
                                                        $dateObj = DateTime::createFromFormat('!m', $m);
                                                        $monthName = $dateObj->format('F');
                                                        ?>
                                                        <option value="<?php echo $m; ?>" <?php if ($m == $this->month) { ?>selected="selected" <?php } ?>><?php echo $monthName; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="year"><?php echo $this->translate("Year") ?></label>
                                                <select class="form-control" name="year">
                                                    <?php for ($y = date("Y"); $y >= date("Y") - 1; $y--) { ?>
                                                        <option value="<?php echo $y; ?>" <?php if ($y == $this->year) { ?>selected="selected" <?php } ?>><?php echo $y; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="button">&nbsp;</label><br/>
                                                <input type="submit" class="btn btn-success" name="submit" id="submit" value="Go" />
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php
                                    $dateObj = DateTime::createFromFormat('!m', $this->month);
                                    $monthName = $dateObj->format('F');

                                    if ($this->month == date("m")) {
                                        $monthName = date("d") . " " . $monthName;
                                    } else {
                                        $date = new DateTime($this->year . "-" . $this->month . "-01");
                                        $day = $date->modify('last day of this month');
                                        $monthName = $day->format('d') . " " . $monthName;
                                    }
                                    ?>
                                    Stock Balance Report as on <?php echo $monthName; ?>, <?php echo $this->year; ?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <?php if (count($this->result) > 0) { ?>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th class="center">
                                    #
                                </th>
                                <th>
                                    Product
                                </th>
                                <th class="right">
                                    Closing Balance (Vials)
                                </th>
                                <th class="center">
                                    Doses per vial
                                </th>
                                <th class="right">
                                    Closing Balance (Doses)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 1;
                            foreach ($this->result as $row) {
                                ?>
                                <tr>
                                    <td class="center">
                                        <?php echo $i; ?>
                                    </td>
                                    <td>
                                        <?php echo $row['item_name']; ?>
                                    </td>
                                    <td class="right">
                                        <?php echo number_format($row['cb_vials']); ?>
                                    </td>
                                    <td class="center">
                                        <?php echo $row['doses_per_vial']; ?>
                                    </td>
                                    <td class="right">
                                        <?php echo number_format($row['cb_doses']); ?>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12 right">
                    <a class="btn btn-success" onclick="window.open('print-stock-report?month=<?php echo $this->month; ?>&year=<?php echo $this->year; ?>&warehouse=<?php echo $this->warehouse; ?>', '_blank', 'scrollbars=1,width=840,height=595');" href="javascript:void(0);">Print</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h4>Last transactions date of <?php echo $this->warehousename; ?> is <?php echo $this->lastdate; ?></h4>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<input id="cmbo1" type="hidden" value="<?php echo (!empty($this->params['office']) ? $this->params['office'] : 1); ?>" />
<input id="cmbo2" type="hidden" value="<?php echo $this->params['combo1']; ?>" />
<input id="cmbo3" type="hidden" value="<?php echo (!empty($this->params['warehouse']) ? $this->params['warehouse'] : 159); ?>" />