<?php
$total = 0;
$cwhtotal = 0;
$ppiutotal = 0;
$disttotal = 0;
$old1 = '';
//print_r($this->rs_items['national']);

$num_item_cwh = ($this->rs_items['national']) ? count($this->rs_items['national']) : 0;
$xml_national = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_national .="<rows>";
$counter = 1;

$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$sel_item = $this->sel_item;
$sel_stk = $this->sel_stk;
$sel_prov = $this->sel_prov;

if ($num_item_cwh > 0) {
    foreach ($this->rs_items['national'] as $row_item) {
        $xml_national .="<row id=\"$counter\">";
        $cwhamc = 0;
        $cwhtotal = 0;
        $cwhmos = 0;

        $cwhamc = $this->reports()->getConsumptionAVG('N', $sel_month, $sel_year, $sel_item, $row_item['stakeholder_id'], 0, 0);

        $cwhtotal = $this->reports()->getCB('NW', $sel_month, $sel_year, $sel_item, $row_item['stakeholder_id'], 0, 0);

        $cwhtotal = $this->reports()->getMOS('NW', $sel_month, $sel_year, $sel_item, $row_item['stakeholder_id'], 0, 0);


        if ($old1 != $row_item['warehouse_name']) {
            $cwh_name = $row_item['warehouse_name'];
        }

        $stk_name = $row_item['stakeholder_name'];
        $xml_national .="<cell>" . $cwh_name . "</cell>";
        $xml_national .="<cell><![CDATA[$stk_name]]></cell>";
        $xml_national .="<cell>" . number_format($cwhamc[0]['Rate'] / 1) . "</cell>";
        $xml_national .="<cell>" . number_format($cwhtotal[0]['Rate'] / 1) . "</cell>";
        if (!empty($cwhmos)) {
            $xml_national .="<cell>" . number_format($cwhmos[0]['Rate'], 1) . "</cell>";
        }
        $xml_national .="</row>";

        $old1 = $row_item['warehouse_name'];
        $total = $total + $ppiutotal;
        $counter++;
    }
}
$xml_national .="</rows>";

$old1 = '';
$xml_provincial = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_provincial .="<rows>";
$counter = 1;

$num_item = ($this->rs_items['provincial']) ? count($this->rs_items['provincial']) : 0;
if (!empty($num_item) && $num_item > 0) {
    foreach ($this->rs_items['provincial'] as $row_item) {

        $xml_provincial .="<row id=\"$counter\">";
        $ppiuamc = 0;
        $ppiutotal = 0;
        $ppiumos = 0;

        $ppiuamc = $this->reports()->getConsumptionAVG('P', $sel_month, $sel_year, $sel_item, $row_item['stakeholder_id'], $row_item['province_id'], 0);

        $ppiutotal = $this->reports()->getCB('PW', $sel_month, $sel_year, $sel_item, $row_item['stakeholder_id'], $row_item['province_id'], 0);

        $ppiumos = $this->reports()->getMOS('PW', $sel_month, $sel_year, $sel_item, $row_item['stakeholder_id'], $row_item['province_id'], 0);


        $stk_name = $row_item['stakeholder_name'];
        $xml_provincial .="<cell>" . $row_item['province'] . "</cell>";
        $xml_provincial .="<cell><![CDATA[$stk_name]]></cell>";
        $xml_provincial .="<cell>" . number_format(round($ppiuamc[0]['Rate']), 2) . "</cell>";
        $xml_provincial .="<cell>" . number_format(round($ppiutotal[0]['Rate']), 2) . "</cell>";
        $xml_provincial .="<cell>" . number_format(round($ppiumos[0]['Rate'], 2), 2) . "</cell>";
        $xml_provincial .="</row>";


        //$old1 = $row_item['warehouse_name'];
        $total = $total + $ppiutotal[0]['Rate'];
        $counter++;
    }
}
$xml_provincial .="</rows>";

//App_Controller_Functions::pr($xml_provincial);

$old1 = '';
$xml_district = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_district .="<rows>";
$counter = 1;
$num_item2 = ($this->rs_items['district']) ? count($this->rs_items['district']) : 0;
if (!empty($num_item2) && $num_item2 > 0) {
    foreach ($this->rs_items['district'] as $row_item2) {
        $xml_district .="<row id=\"$counter\">";

        $district_name = $row_item2['district'];
        // echo $district_name;
        $province_name = $row_item2['province'];
        $stk_name = $row_item2['stakeholder_name'];
        $ppiuamc = 0;
        $AMC = 0;
        $WHCB = 0;
        $store = 0;
        $MOS = 0;
        $FLDCB = 0;
        $field = 0;
        $MOS1 = 0;

        $ppiuamc = $this->reports()->getConsumptionAVG('D', $sel_month, $sel_year, $sel_item, $row_item2['stakeholder_id'], $row_item2['district_id'], 0);

        $AMC = number_format($ppiuamc[0]['Rate'] / 1);
        $AMC = $ppiuamc;

        $WHCB = $this->reports()->getCB('DW', $sel_month, $sel_year, $sel_item, $row_item2['stakeholder_id'], $row_item2['district_id'], 0);
        $store = $WHCB;

        if ($store > 0 && $AMC > 0)
            $MOS = $store[0]['Rate'] / $AMC[0]['Rate'];
        else
            $MOS = 0;

        $FLDCB = $this->reports()->getCB('UD', $sel_month, $sel_year, $sel_item, $row_item2['stakeholder_id'], $row_item2['district_id'], 0);
        $field = $FLDCB;

        if ($field > 0 && $AMC > 0)
            $MOS1 = $field[0]['Rate'] / $AMC[0]['Rate'];
        else
            $MOS1 = 0;

        $d_total = $WHCB[0]['Rate'] + $FLDCB[0]['Rate'];
        $total_amount = $d_total;
        $MOS2 = $MOS + $MOS1;

        $old2 = $row_item2['district_id'];
        $old3 = $row_item2['province_id'];
        $disttotal = $WHCB[0]['Rate'] + $FLDCB[0]['Rate'];
        $total = $total + $disttotal;

        $xml_district .="<cell>" . $district_name . "</cell>";
        $xml_district .="<cell>" . $province_name . "</cell>";
        $xml_district .="<cell><![CDATA[$stk_name]]></cell>";
        $xml_district .="<cell>" . number_format($AMC[0]['Rate']) . "</cell>";
        $xml_district .="<cell>" . number_format($store[0]['Rate']) . "</cell>";
        $xml_district .="<cell>" . number_format($MOS, 2) . "</cell>";
        $xml_district .="<cell>" . number_format($field[0]['Rate']) . "</cell>";
        $xml_district .="<cell>" . number_format($MOS1, 2) . "</cell>";
        $xml_district .="<cell>" . number_format($total_amount) . "</cell>";
        $xml_district .="<cell>" . number_format($MOS2, 2) . "</cell>";
        $xml_district .="</row>";

        $counter++;
    }
}
$xml_district .="</rows>";

$str_stock_report_national = "Stock Present at Federal EPI Store Islamabad For Product = $this->product_name (" . date('F', mktime(0, 0, 0, $this->month_sel)) . ' ' . $this->year_sel . ")";
$str_stock_report_province = "Provincial Report For Province/Region = $this->location_name  And Product = $this->product_name (" . date('F', mktime(0, 0, 0, $this->month_sel)) . ' ' . $this->year_sel . ")";
$str_stock_report_district = "Districts Report For Province/Region = $this->location_name And Product = $this->product_name (" . date('F', mktime(0, 0, 0, $this->month_sel)) . ' ' . $this->year_sel . ")";
?>
<input type="hidden" name="total" id="total" value="<?php echo number_format($total / PLMIS_CBL_UNIT); ?>" />
<input type="hidden" name="hdn_stock_report_national" id="hdn_stock_report_national" value="<?php echo $str_stock_report_national; ?>">
<input type="hidden" name="hdn_stock_report_province" id="hdn_stock_report_province" value="<?php echo $str_stock_report_province; ?>">
<input type="hidden" name="hdn_stock_report_district" id="hdn_stock_report_district" value="<?php echo $str_stock_report_district; ?>">

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">Stock Availability Report (Doses)</h3>
        <div class="innerLR">
            <script>
                function frmvalidate() {
                    if (document.getElementById('prod_sel').value == '') {
                        alert('Please Select Product');
                        document.getElementById('prod_sel').focus();
                        return false;
                    }

                    if (document.getElementById('month_sel').value == '') {
                        alert('Please Select Month');
                        document.getElementById('month_sel').focus();
                        return false;
                    }

                    if (document.getElementById('year_sel').value == '') {
                        alert('Please Select Year');
                        document.getElementById('year_sel').focus();
                        return false;
                    }
                }

                var mygrid;
                function doInitGrid() {
                    mygrid = new dhtmlXGridObject('mygrid_container_provincial');
                    mygrid.selMultiRows = true;
                    mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'>'" + $('#hdn_stock_report_province').val() + "'</div>,#cspan,#cspan,#cspan,#cspan");
                    mygrid.attachHeader("<span title='Provincial Office'>Provincial Store</span>,<span title='Stakeholder Name'>Stakeholder</span>,<span title='Average Monthly Consumption'>AMC</span>,<span title='Total'>Total</span>,<span title='Months of Stock'>MOS</span>");
                    mygrid.setInitWidths("*,250,100,100,100");
                    mygrid.setColAlign("left,left,right,right,right");
                    mygrid.setColSorting("str,str");
                    mygrid.setColTypes("ro,ro,ro,ro,ro");
                    //mygrid.enableLightMouseNavigation(true);
                    mygrid.enableRowsHover(true, 'onMouseOver');   // `onMouseOver` is the css class name.
                    mygrid.setSkin("light");
                    mygrid.init();
                    mygrid.clearAll();
                    mygrid.loadXMLString('<?php echo $xml_provincial ?>');
                    $('body').append('<textarea id="xml_provincial" style="display:none;"><?php echo addslashes($xml_provincial); ?></textarea>');
                    mygrid.loadXMLString(document.getElementById('xml_provincial').value);

                    mygrid1 = new dhtmlXGridObject('mygrid_container_district');
                    mygrid1.selMultiRows = true;
                    mygrid1.setImagePath("../operations/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    mygrid1.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'>'" + $('#hdn_stock_report_district').val() + "'</div>,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan");
                    mygrid1.attachHeader("<span title='District Name'>Districts</span>,<span title='Province/Region Name'>Province/Region</span>,<span title='Stakeholder Name'>Stakeholder</span>,<span title='Average Monthly Consumption'>AMC</span>,<span title='Store'>Store</span>,<span title='Months of Stock'>MOS</span>,<span title='Field'>Field</span>,<span title='Months of Stock'>MOS</span>,<span title='Total'>Total</span>,<span title='Months of Stock'>MOS</span>");
                    mygrid1.setInitWidths("*,150,100,80,80,80,80,80,80,80");
                    mygrid1.setColAlign("left,left,left,right,right,right,right,right,right,right");
                    mygrid1.setColSorting("str,str,str");
                    mygrid1.setColTypes("ro,ro,ro,ro,ro,ro,ro,ro,ro,ro");
                    //mygrid1.enableLightMouseNavigation(true);
                    mygrid1.enableRowsHover(true, 'onMouseOver');   // `onMouseOver` is the css class name.
                    mygrid1.setSkin("light");
                    mygrid1.init();
                    mygrid1.clearAll();
                    mygrid1.loadXMLString('<?php echo $xml_district ?>');
                    $('body').append('<textarea id="xml_district" style="display:none;"><?php echo addslashes($xml_district); ?></textarea>');
                    mygrid1.loadXMLString(document.getElementById('xml_district').value);

                    mygrid2 = new dhtmlXGridObject('mygrid_container_national');
                    mygrid2.selMultiRows = true;
                    mygrid2.setImagePath("../operations/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    mygrid2.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'>'" + $('#hdn_stock_report_national').val() + "'</div>,#cspan,#cspan,#cspan,#cspan");
                    mygrid2.attachHeader("<span title='Central Warehouse Name'>Federal EPI Store</span>,<span title='Stakeholder Name'>Stakeholder</span>,<span title='Average Monthly Consumption'>AMC</span>,<span title='Total'>Total</span>,<span title='Months of Stock'>MOS</span>");
                    mygrid2.setInitWidths("*,250,100,100,100");
                    mygrid2.setColAlign("left,left,right,right,right");
                    mygrid2.setColSorting("str,str");
                    mygrid2.setColTypes("ro,ro,ro,ro,ro");
                    //mygrid2.enableLightMouseNavigation(true);
                    mygrid2.enableRowsHover(true, 'onMouseOver');   // `onMouseOver` is the css class name.
                    mygrid2.setSkin("light");
                    mygrid2.init();
                    mygrid2.clearAll();
                    mygrid2.loadXMLString('<?php echo $xml_national ?>');
                    $('body').append('<textarea id="xml_national" style="display:none;"><?php echo addslashes($xml_national); ?></textarea>');
                    mygrid2.loadXMLString(document.getElementById('xml_national').value);
                }
            </script>

            <div class="wrraper" style="height:auto; padding-left:5px">
                <div class="content" align="">
                    <table width="99%">
                        <tr>
                            <td colspan="2">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                            </td>
                        </tr>
                        
                    </table>

                    <?php if ($num_item_cwh > 0) { ?>
                        <table width="99%">
                            <tr>
                                <td class="sb1NormalFont">&nbsp;</td>
                                <td align="right" style="padding:10px;">
                                    <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid2.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="Export to PDF"/>&nbsp;&nbsp;
                                    <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid2.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="Export to Excel" />
                                </td>
                            </tr>
                        </table>
                        <table width="99%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <div id="mygrid_container_national" style="width:100%; height:100px; background-color:white; overflow:hidden;"></div>
                                </td>
                            </tr>
                        </table><br>
                    <?php } else { ?>
                        <table width="99%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <div id="mygrid_container_national" style="width:100%; height:0px; background-color:white; overflow:hidden;"></div>
                                </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <strong>No record found.</strong>
                                </td>
                            </tr>
                        </table><br>
                    <?php } if ($num_item > 0) { ?>
                        <table width="99%">
                            <tr>
                                <td class="sb1NormalFont">&nbsp;
                                </td>
                                <td align="right" style="padding-right:0px">
                                    <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="Export to PDF"/>&nbsp;&nbsp;
                                    <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="Export to Excel" />
                                </td>
                            </tr>
                        </table>


                        <table width="99%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <div id="mygrid_container_provincial" style="width:100%; height:100px; background-color:white; overflow:hidden;"></div>
                                </td>
                            </tr>
                        </table><br>

                    <?php } else { ?>
                        <table width="99%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <div id="mygrid_container_provincial" style="width:100%; height:0px; background-color:white; overflow:hidden;"></div>
                                </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <strong>No record found.</strong>
                                </td>
                            </tr>
                        </table>
                    <?php } ?><br />

                    <?php if ($num_item2 > 0) { ?>
                        <table width="99%">
                            <tr>
                                <td class="sb1NormalFont">&nbsp;</td>
                                <td align="right">
                                    <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid1.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="Export to PDF"/>&nbsp;&nbsp;
                                    <img style="cursor:pointer; margin-left:-5px;" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid1.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="Export to Excel" />
                                </td>
                            </tr>
                        </table>
                        <table width="99%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <div id="mygrid_container_district" style="width:100%; height:250px; background-color:white; overflow:hidden;"></div>
                                </td>
                            </tr>
                        </table>
                    <?php } else { ?>
                        <table width="99%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <div id="mygrid_container_district" style="width:100%; height:0px; background-color:white; overflow:hidden;"></div>
                                </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <strong>No record found.</strong>
                                </td>
                            </tr>
                        </table>
                    <?php } ?>

                </div>
            </div>
        </div>
    </div>
</div>

