<?php
$header = 'District, Product, Opening Balance, Stock Receive, Stock Issue, Closing Balance, Consumption, Wastages Rate';
//$header1 = '#rspan';
$cspan = ',#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan';
$width = '200,200,*,*,*,*,*,*';
$ro = 'ro,ro,ro,ro,ro,ro,ro,ro';

$monthName = '';
$year = $this->form->year->getValue();
$month = $this->form->month->getValue();
if (!empty($month)) {
    $dateObj = DateTime::createFromFormat('!m', $month);
    $monthName = $dateObj->format('F');
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->report_title; ?></h3>
        <form name="stock_analysis" method="post" action="">
            <div class="row">
                <div class="col-md-2">
                    <!-- Group Receive No-->
                    <div class="control-group">
                        <label class="control-label" for="month">
                            <?php echo $this->translate("Month"); ?>
                        </label>
                        <div class="controls">
                            <?php echo $this->form->month; ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <!-- Group Receive No-->
                    <div class="control-group">
                        <label class="control-label" for="year">
                            <?php echo $this->translate("Year"); ?>
                        </label>
                        <div class="controls">
                            <?php echo $this->form->year; ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <!-- Group Receive No-->
                    <div class="control-group">
                        <label class="control-label" for="submit">
                            &nbsp;
                        </label>
                        <div class="controls">
                            <input type="submit" name="submit" class="btn btn-success" value="Go"/>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-md-12">
                <script>
                    var mygrid;
                    function doInitGrid() {
                        mygrid = new dhtmlXGridObject('mygrid_container');
                        mygrid.selMultiRows = true;

                        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                        mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "Monthly Stock Analysis of all districts (" . $monthName . ' ' . $year . ") " ?><?php echo $cspan; ?>");
                        mygrid.attachHeader("<?php echo $header; ?>");
                        //mygrid.attachHeader("<?php //echo $header1;                  ?>");
                        mygrid.setInitWidths("<?php echo $width; ?>");
                        //mygrid.setColAlign("left,right,right,right,right,right,right,right,right,right,right,right,right");
                        //mygrid.setColSorting("str,int");
                        mygrid.setColTypes("<?php echo $ro; ?>");
                        mygrid.setSkin("light");
                        // mygrid.enablePaging(true, 50, 3, "infoArea");
                        //  mygrid.setPagingSkin("toolbar", "dhx_skyblue");
                        mygrid.init();
                        mygrid.clearAll();
                        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($this->xml_store); ?></textarea>');
                        mygrid.loadXMLString(document.getElementById('xml_string').value);
                    }
                </script>
                <table width="99%">
                    <tr>
                        <td colspan="2">
                            <?php
                            echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?php //echo $this->render('inventory-management/reports-header.phtml')  ?>
                        </td>
                    </tr>

                    <tr>
                        <td colspan="2" style="text-align:right; padding-bottom:10px;">
                            <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                            <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                        </td>
                    </tr>
                </table>

                <table width="99%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <div id="mygrid_container" style="width:100%; height:760px;">
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

