<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            Stock Sufficiency Report (Federal EPI Store)
        </h3>
        <?php if ($this->role_id == 2 || $this->role_id == 22) { ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Search Filters"); ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse"></a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <form method="POST" name="sufficient" action="" id="sufficient">
                                <?php
                                $this->allLevelCombo('', null, 1, 10);
                                ?>
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="control-label" for="button">&nbsp;</label><br/>
                                            <input type="submit" class="btn btn-success" name="submit" id="submit" value="Submit" />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if (count($this->result) > 0) { ?>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-bordered table-condensed" id="stkledger">
                        <thead>
                            <tr>
                                <th>S.No</th>
                                <th class="col-md-2">Product</th>
                                <th class="col-md-2">Stock On Hand</th>
                                <th class="col-md-2" style="background-color: #CDFFA5;">EPI AMC</th>
                                <th class="center col-md-2" style="background-color: #CDFFA5;">MOS (EPI AMC)</th>
                                <th class="col-md-2" style="background-color: #C0DDF9;">Shipment Quantity</th>
                                <th class="col-md-2" style="background-color: #C0DDF9;">Projected SOH</th>
                                <th class="col-md-2" style="background-color: #C0DDF9;">Projected MOS</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $count = 1;
                            foreach ($this->result as $row) {
                                $month6 = ROUND($row['soh'] / $row['amc'], 1);
                                //if ($month6 < 12) {
                                ?>
                                <tr>
                                    <td><?php echo $count; ?></td>
                                    <td><?php echo $row['item_name']; ?></td>
                                    <td class="right"><?php echo number_format($row['soh']); ?></td>
                                    <td style="background-color: #CDFFA5;" class="right"><?php echo number_format($row['amc']); ?></td>
                                    <td class="center" style="background-color: #CDFFA5;"><?php echo ROUND($row['soh'] / $row['amc'], 2) . " months"; ?></td>
                                    <td class="right" style="background-color: #C0DDF9;"><?php echo number_format($row['quantity']); ?></td>
                                    <td class="right" style="background-color: #C0DDF9;"><?php echo number_format($row['soh']+$row['quantity']); ?></td> 
                                    <td class="center" style="background-color: #C0DDF9;"><?php echo ROUND(($row['soh']+$row['quantity'])/$row['amc'], 2) . " months"; ?></td>                                      
                                </tr>
                                <?php
                                $count++;
                                //}
                            }
                            ?>

                        </tbody>
                    </table>
                </div>
            </div>
        <?php } else { ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>Transactions not found</h4>
                </div>
            </div>
        <?php } ?>
        <div class="row">
            <div class="col-md-12"><span style="color: blue;">Stock Sufficiency report from <?php echo $this->from_date; ?> to <?php echo $this->to_date; ?></span></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                require_once 'FusionCharts/Code/PHP/Includes/FusionCharts.php';
                FC_SetRenderer('javascript');
                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Column2D.swf", "", $this->xml_store, 'chartContainer', '100%', 395, false, false);
                ?>
            </div>
        </div>
    </div>
</div>