<?php
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .="<rows>";

$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type1 = $this->in_type_1;

$in_type = $this->in_type;

$sel_item = $this->sel_item;
$sel_dist = $this->dist_sel;
//echo $sel_dist;

$sel_prov = $this->prov_sel;
$counter = 1;

foreach ($this->loc as $loc) {
    $xml_store .="<row id=\"$counter\">";
    $query_vals = $this->reports()->reportData($in_col, $in_rg, $in_type1, $sel_month, $sel_year, $sel_item, 1, $loc['pk_id'], 0);

    foreach ($query_vals as $row_vals) {
        $item_id = $loc['pk_id'];
        $item_name = $loc['location_name'];
        $sel_stk = 0;
        $sel_lvl = 5;
        $month_num = "\"$sel_month\"";
        $year_num = "\"$sel_year\"";
        $temp_var = "";
        $temp_var .= "\"$sel_month\",";
        $temp_var .= "\"$sel_year\",";
        $temp_var .= "\"$sel_item\",";
        $temp_var .= "\"$sel_prov\",";
        $temp_var .= "\"$sel_dist\",";
        $temp_var .= "\"$item_id\"";
        $tmp = explode('*', $row_vals['Value']);

        //<!-- begin data rending -->


        $xml_store .="<cell><![CDATA[<a href=javascript:functionCall($temp_var)>$item_name</a>]]>^_self</cell>";

        include ('ind_data_render.phtml');
    }

    $counter++;
}

$xml_store .="</rows>";
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<input type="hidden" name="sel_year" id="sel_year"  value="<?= $sel_year ?>">
<input type="hidden" name="sel_month" id="sel_month" value="<?= date('F', mktime(0, 0, 0, $sel_month)) ?>">
<input type="hidden" name="item_name" id="item_name"  value="<?= $this->item_name; ?>">
<input type="hidden" name="location_name" id="location_name"  value="<?= $this->location_name; ?>">
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <script>
                var mygrid;
                function doInitGrid() {
                    mygrid = new dhtmlXGridObject('mygrid_container');
                    mygrid.selMultiRows = true;
                    mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'>Tehsil Report For Province = " + $('#location_name').val() + " And Product = " + $('#item_name').val() + "(" + $('#sel_month').val() + " " + $('#sel_year').val() + ")</div>,#cspan,#cspan,#cspan,#cspan,#cspan");
                    mygrid.attachHeader("<span title='Tehsil Name'>Tehsil</span>,<span title='Product Consumption'>Consumption (Doses)</span>,<span title='Average Monthly Consumption'>AMC (Doses)</span>,<span title='Product On Hand'>Product On Hand (Doses)</span>,<span title='Months of Scale'>Months of Scale (MOS)</span>,#cspan");
                    mygrid.setInitWidths("150,*,*,*,40,100");
                    mygrid.setColAlign("left,right,right,right,center,center");
                    //mygrid.setColSorting("str,int");
                    mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro");
                    //mygrid.enableLightMouseNavigation(true);
                    mygrid.enableRowsHover(true, 'onMouseOver');   // `onMouseOver` is the css class name.
                    mygrid.setSkin("light");
                    mygrid.init();
                    mygrid.clearAll();
                    $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
                    mygrid.loadXMLString(document.getElementById('xml_string').value);
                }
                function functionCall(month, year, prod, province, district, tehsil) {
                    window.location = "uc-report?month_sel=" + month
                            + "&year_sel=" + year
                            + "&prov_sel=" + province
                            + "&stkid=1&prod_sel=" + prod
                            + "&dist_id=" + district
                            + "&teh_id=" + tehsil;
                }
                $(function() {
                    $('#wh_type').change(function() {
                        //alert("test");
                        $('#loader').show();
                        $.ajax({
                            type: "POST",
                            url: "provWH.php",
                            data: {SkOfcLvl: $(this).val(), combo: '2'},
                            dataType: 'html',
                            success: function(data) {
                                $('#loader').hide();
                                $('#warehouse_id').html(data);
                            }
                        });
                    });

                    $('#prov_sel').change(function() {
                        $('#loader').show();
                        $.ajax({
                            type: "POST",
                            url: appName + "/reports/inventory-management/prov-2dist",
                            data: {prov_sel: $(this).val(), combo: '2'},
                            dataType: 'html',
                            success: function(data) {
                                $('#loader').hide();
                                $('#dist_id').html(data);
                                $('#teh_id').empty();
                                $('#uc_id').empty();
                            }
                        });
                    });

                    $('#dist_id').change(function() {
                        var dist_id = $(this).val();
                        $('#loader').show();
                        $.ajax({
                            type: "POST",
                            url: appName + "/reports/inventory-management/prov-2dist",
                            data: {dist_sel: dist_id, combo: '4'},
                            dataType: 'html',
                            success: function(data) {
                                /*$('#hidden_dist').val(dist_id);
                                 $('#hidden_teh').val($('#teh_id').val());*/
                                $('#loader').hide();
                                $('#teh_id').html(data);
                            }
                        });
                        $.ajax({
                            type: "POST",
                            url: appName + "/reports/inventory-management/prov-2dist",
                            data: {dist_sel: dist_id, combo: '5'},
                            dataType: 'html',
                            success: function(data)
                            {
                                $('#loader').hide();
                                $('#uc_id').html(data);
                            }
                        });
                    });

                    $('#teh_id').change(function() {
                        var teh_id = $(this).val();
                        $('#loader').show();
                        $.ajax({
                            type: "POST",
                            url: appName + "/reports/inventory-management/prov-2dist",
                            data: {teh_sel: teh_id, combo: '5'},
                            dataType: 'html',
                            success: function(data) {
                                /*$('#hidden_dist').val(dist_id);
                                 $('#hidden_teh').val($('#teh_id').val());*/
                                $('#loader').hide();
                                $('#uc_id').html(data);
                            }
                        });
                    });

                });
            </script>
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header.phtml') ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div style="float:right; padding-bottom: 5px; padding-right: 10px;">
                            <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                            <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("IExport to Excel"); ?>" />
                        </div>
                    </td>
                </tr>
            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:600px;">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>




