<?php
$sel_month = $this->month_sel;
$sel_year = $this->year_sel;

$from_sel_month = $this->from_month_sel;
$from_sel_year = $this->from_year_sel;
$counter = 1;

$sel_stk = $this->in_stk;
$sel_prov = $this->province;
$sel_dist = $this->district1;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$sel_indicator = $this->sel_indicator;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type = $this->in_type;
$stk_sel = $this->stk_sel;
$start_date = $this->start_date;
$end_date = $this->end_date;
$period = $this->period;
$str_indicator = $this->str_indicator;
$year = $this->year_sel;
$month = $this->month_sel;
$item = $this->sel_item;


$data_arr = array();

$header = 'Tehsil,UC Name,'
        . 'Total Coverage  Penta I'
        . ',Total Coverage  Penta III'
        . ',Penta Dropout Rate'
        . ',Total Coverage BCG'
        . ',Total Coverage Measles I'
        . ',Dropout Rate BCG to Measles';

$cspan = '';
$width = '160,160,*,*,*,*,*,*';
$ro = 'ro,ro,ro,ro,ro,ro,ro,ro';



$query = $this->reports()->vaccineDropoutRate($wh_type, $sel_dist, $sel_tehsil, $year, $month, $item,$from_sel_month,$from_sel_year);

$district = 'District:';

foreach ($query as $row) {
    $item_id = $row['pk_id'];

    $data_arr[$item_id][] = $row['teh'];
    $data_arr[$item_id][] = $row['uc'];
    $data_arr[$item_id][] = $row['pen_1'];
    $data_arr[$item_id][] = $row['pen_2'];
    $data_arr[$item_id][] = $row['penta_dropout_rate'];
    $data_arr[$item_id][] = $row['bcg'];
    $data_arr[$item_id][] = $row['measles'];
    $data_arr[$item_id][] = $row['bcg_measles_dropout_rate'];
}


//App_Controller_Functions::pr($data_arr);
$s_date = $this->start_date;
$e_date = $this->end_date;
$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .= "<rows>";

$sum_arr = array();

foreach ($data_arr as $dis_id => $sub_arr) {

    $xml_store .= "<row>";

    $xml_store .= "<cell>$sub_arr[0]</cell>";


    foreach ($sub_arr as $key => $value) {
        if ($value < 0) {
            $style = "style=\"text-align:right; color:red;\"";
        } else {
            $style = "";
        }
        if ($key > 0) {

            $xml_store .= "<cell $style>$value </cell>";
        }
    }
    $xml_store .="</row>";
}


$xml_store .="</rows>";
?>

<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <h5 style="color: red">
            Note: This report is under user testing.
        </h5>
        <div class="innerLR">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                     <?php echo $this->render('inventory-management/reports-header_coverage.phtml') ?>
                    </td>
                </tr>

                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.setColumnHidden(0, false);
                                mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');
                                mygrid.setColumnHidden(0, true);" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>
            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:510px;">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Dropout Rate = ((Penta I - Penta III)/Penta I)*100 
                    </td>
                   </tr>
                 
            </table>
        </div>
    </div>
</div>
<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath(
                "<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        //mygrid.setHeader("Province,Consumption,AMC,On Hand,MOS,#cspan");
        mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "'$report_title at  $this->loc_name'   for (" . date('F', mktime(0, 0, 0, $this->from_month_sel)) . '-' . $this->from_year_sel .') to ('. date('F', mktime(0, 0, 0, $this->month_sel)) . '-' . $this->from_year_sel; ?>)  (Doses)<?php echo $cspan; ?>,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan");
        mygrid.attachHeader("<?php echo $header; ?>");
        //   mygrid.attachHeader("<?php //echo $header1;                       ?>");
        mygrid.setInitWidths("<?php echo $width; ?>");
        mygrid.setColAlign("left,left,right,right,right,right,right,right");
        //mygrid.setColSorting("str,int");
        mygrid.setColTypes("<?php echo $ro; ?>");
        //mygrid.setColumnHidden(0, true);
        //mygrid.setColumnHidden(0, true);
        //mygrid.enableLightMouseNavigation(true);
        mygrid.enableRowsHover(true, 'onMouseOver'); // `onMouseOver` is the css class name.
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }

    function functionCall(param) {
        var width = 1002;
        var height = 595;
        var x = (screen.width / 2) - (width / 2);
        var y = (screen.height / 2) - (height / 2);
        window.open('reported-warehouse-list?param=' + param, '_blank', 'scrollbars=1,width=' + width + ',height=' + height + ',left=' + x + ',top=' + y);
    }

    function showGraph(param) {
        window.open('<?php echo $this->baseUrl(); ?>/reports/graphs/reported-districts?param=' + param, '_blank', 'scrollbars=1,width=950,height=600');
    }
    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;
</script>

