<div class="row">
    <div class="col-md-6">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Page Name"); ?></label>
            <div class="controls">
                <?php echo $this->form_add->page_name; ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
            <div class="controls">
                <?php echo $this->form_add->status; ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Description"); ?></label>
            <div class="controls">
                <?php echo $this->form_add->description; ?>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form_add->id; ?>