<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Help Messages"); ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Search Narratives/Messages") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form method="POST" name="messages_search" action="" >
                            <!-- Row -->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Message Description"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->search_text; ?>
                                            </div>
                                        </div>
                                    </div>                                    
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Resource Name"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->page_name; ?>
                                            </div>
                                        </div>
                                    </div>                                    
                                    <div class="col-md-5" style="margin-top: 25px;">
                                        <?php echo $this->form->deleted; ?>                                        
                                        <label class="control-label" for="deleted" ><?php echo $this->translate("Search Deleted Records"); ?>&nbsp;&nbsp;</label>
                                        <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Messages List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="dataTables_wrapper form-inline">
                            <div class="row">
                                <div class="col-md-3">
                                    <?php $this->recordsPerPage($this->counter); ?>
                                </div>
                                <div class="col-md-9">
                                    <div class="dataTables_filter">
                                        <label>
                                            <a class="btn btn-primary" data-toggle="modal" href="#modal-add-narrative"><?php echo $this->translate("Add Narrative"); ?></a>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                <!-- Table heading -->
                                <?php
                                $fields = array(
                                    'sr_no' => 'Sr. No.',
                                    'title' => 'Page Name/Link',
                                    'description' => 'Description',
                                    'status' => 'Status'
                                );
                                $this->tableHeading($this->order, $this->sort, $fields);
                                ?>
                                <!-- // Table heading END -->
                                <!-- Table body -->

                                <!-- // Table body END -->
                                <tbody>
                                    <?php
                                    $m_res = array();
                                    $i = 1;
                                    if ($this->paginator && count($this->paginator) > 0) :
                                        foreach ($this->paginator as $row):
                                            ?>
                                            <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                <td><?php echo $row['pkId']; ?></td>
                                                <td><?php echo $row['resourceName']; ?></td>
                                                <td style="width:60%;"><?php echo $row['description']; ?></td>
                                                <td><?php if ($row['status'] == Model_HelpMessages::ACTIVE) echo "Active"; elseif ($row['status'] == Model_HelpMessages::DEACTIVE) echo "Deactive"; elseif ($row['status'] == Model_HelpMessages::DELETED) echo "Deleted"; ?></td>
                                                <td>
                                                    <a pkid="<?php echo $row['pkId']; ?>" class="btn update-narrative btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-message"><?php echo $this->translate("Edit") ?></a>
                                                    <?php if ($row['status'] != Model_HelpMessages::DELETED) { ?>
                                                        <a data-bind="<?php echo $row['pkId']; ?>" data-toggle="notyfy" data-type="confirm" data-layout="top" class="btn btn-danger btn-link input-sm"><?php echo $this->translate("Delete") ?></a>
                                                    <?php } ?>
                                                </td>                                        
                                            </tr>
                                            <!-- // Table row END --><?php
                                            $i++;
                                        endforeach;
                                    endif;
                                    ?>
                                </tbody>
                            </table>
                            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-help-messages/add" id="add-narrative">
            <div class="modal fade" id="modal-add-narrative" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Add Narrative</h3>
                        </div>
                        <div class="modal-body">
                            <div class="row margin-bottom-10">
                                <div class="col-md-6">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Page Resource Name"); ?></label>
                                        <div class="controls">
<?php echo $this->form_add->page_name; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
                                        <div class="controls">
<?php echo $this->form_add->status; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Description"); ?></label>
                                        <div class="controls">
<?php echo $this->form_add->description; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Save"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-help-messages/update" id="update-narrative">
            <div class="modal fade" id="modal-update-message" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Narrative</h3>
                        </div>
                        <div class="modal-body" id="modal-body-contents"></div>
                        <div class="modal-footer" id="update-button">
                            <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Update"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->