<div class="row">
    <div class="col-md-5">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Campaign Type"); ?><span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->campaign_type_name; ?>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form->campaign_type_id; ?>
