  
<div class="row" >
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">Campaign</label>
            <?php echo $this->form->campaign_add_id; ?>
            <?php echo $this->form->campaign_add_id_hidden; ?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">UC</label>
            <?php echo $this->form->uc_add_id; ?>
            <?php echo $this->form->warehouse_add_id_hidden; ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">Targeted</label>
            <div class="controls">
                <?php echo $this->form->target; ?>

            </div>
        </div>
    </div>


</div>

<div class="row">
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">Inaccessible Children</label>
            <div class="controls">
                <?php echo $this->form->inaccessible_children; ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">No. of mobile teams</label>
            <div class="controls">
                <?php echo $this->form->no_of_mobile_teams; ?>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">Inaccessible Area</label>
            <div class="controls">
                <?php echo $this->form->inaccessible_area; ?>
            </div>

        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group">

            <label class="control-label">No. of fixed teams</label>
            <div class="controls">

                <?php echo $this->form->no_of_fixed_teams; ?>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">Area In-charge</label>
            <div class="controls">
                <?php echo $this->form->area_in_charge; ?>
            </div>

        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group">

            <label class="control-label">No. of Transist Points</label>
            <div class="controls">

                <?php echo $this->form->no_of_transist_points; ?>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">AICs Trained</label>
            <div class="controls">
                <?php echo $this->form->aics_trained; ?>
            </div>

        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group">

            <label class="control-label">No. of Teams Trained</label>
            <div class="controls">

                <?php echo $this->form->no_of_teams_trained; ?>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="control-group">
            <label class="control-label">Areas with mobile population</label>
            <div class="controls">
                <?php echo $this->form->area_mobile_population; ?>
            </div>

        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group">

            <label class="control-label">Date of UPEC Meeting</label>
            <div class="controls">

                <?php echo $this->form->date_upec_meeting; ?>

            </div>
        </div>
    </div>
</div>
<script>
 

</script>