<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Stock Placements"); ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Stock Placements") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <tr>
                                        <th>S.No</th>
                                        <th>Product</th>
                                        <th>Warehouse</th>                                        
                                        <th>Stock Qty (A)</th>
                                        <th>Placed Qty (B)</th>
                                        <th>Difference (A-B)</th>
                                        <th>Action</th>
                                    </tr>
                                    <?php
                                    $count = 1;
                                    foreach($this->result as $row){
                                        $diff = $row['BatchQty'] - $row['PlacedQty'];
                                        $action = ($diff > 0 ? "0" : "1");
                                    ?>
                                    <tr>
                                        <td><?php echo $count; ?></td>
                                        <td><?php echo $row['ItemName']; ?></td>
                                        <td><?php echo $row['warehouse_name']; ?></td>
                                        <td><?php echo $row['BatchQty']; ?></td>
                                        <td><?php echo $row['PlacedQty']; ?></td>
                                        <td><?php echo ($diff > 0 ? "Place: " : "Pick: ").$diff; ?></td>
                                        <td><a onclick="window.open('fix-stock-placement-qty?action=<?php echo $action; ?>&wh_id=<?php echo $row['warehouse_id']; ?>&item_id=<?php echo $row['item_id']; ?>', '_blank', 'scrollbars=1,width=860,height=595')">Fix</a></td>                                        
                                    </tr>
                                        <?php
                                        $count++;
                                    }
                                    ?>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- // Content END -->