<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Negative Stock Batches"); ?> </h3>
        <?php
        /**
         *  phtml for Ajax Merge Batch
         */
        ?>
        <?php if (!empty($this->result) && count($this->result) > 0) { ?>
            <div class="row">
                <div class="col-md-12">
                    <form name="merge-batches" id="merge-batches" method="post" action="">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr>
                                <th class="center" style="width: 3%;">S.No</th>
                                <th class="col-md-2">Product</th>
                                <th class="col-md-1">Batch</th>
                                <th class="col-md-1">Quantity</th>
                                <th class="col-md-1">Batch ID</th>
                                <th class="col-md-1">Product ID</th>
                                <th class="col-md-1">Action</th>
                            </tr>              
                            <?php
                            $count = 1;
                            $number = '';
                            foreach ($this->result as $row) {
                                ?>
                                <tr>
                                    <td><?php echo $count; ?></td>
                                    <td><?php echo $row['item_name']; ?></td>
                                    <td><?php echo $row['number']; ?></td>
                                    <td><?php echo $row['qty']; ?></td>
                                    <td><?php echo $row['batch_id']; ?></td>
                                    <td><?php echo $row['item_id']; ?></td>
                                    <td><a href="<?php echo $this->baseUrl(); ?>/iadmin/admin-tools/stock-batch-with-negative-qty/batch/<?php echo $row['batch_id']; ?>/date/<?php echo $row['transaction_date']; ?>/qty/<?php echo ABS($row['qty']); ?>">Add Adjustment</a></td>
                                </tr>
                                <?php
                                $count++;
                            }
                            ?>                            
                        </table>
                    </form>
                </div>
            </div>
        <?php } else { ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>No Record found!</h4>
                </div>
            </div>
        <?php } ?>
    </div>
</div>