<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("CCEM Graphs") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate($this->main_heading) ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="search" action="" >
                                    <div class="row">
                                        <?php $this->allLevelAreaCombo(array("level" => $this->form_values['office'], "province" => $this->form_values['combo1'], "district" => $this->form_values['combo2'], "facility_type" => '')); ?>
                                        <div class="col-md-3">
                                            <label>&nbsp;</label>
                                            <div class="controls">
                                                <button type="button" id="search" class="btn btn-success"><?php echo $this->translate("Search"); ?></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row margin-top-10">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="gen-chart-render form-btn-margin-top" id="gen-chart-render"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- // Content END -->
