BarcodeScanners:
  type: entity
  table: barcode_scanners
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    scannerName:
      type: string
      length: 200
      fixed: false
      nullable: true
      column: scanner_name
    licenceNumber:
      type: string
      length: 30
      fixed: false
      nullable: true
      column: licence_number
  lifecycleCallbacks: {  }
