CampaignItemGroups:
  type: entity
  table: campaign_item_groups
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    ageGroup1Min:
      type: integer
      unsigned: false
      nullable: true
      column: age_group1_min
    ageGroup1Max:
      type: integer
      unsigned: false
      nullable: true
      column: age_group1_max
    ageGroup2Min:
      type: integer
      unsigned: false
      nullable: true
      column: age_group2_min
    ageGroup2Max:
      type: integer
      unsigned: false
      nullable: true
      column: age_group2_max 
  oneToOne:
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
   
  lifecycleCallbacks: {  }
