CcmHumanResources:
  type: entity
  table: ccm_human_resources
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 50
      fixed: false
      nullable: true
    designation:
      type: string
      length: 50
      fixed: false
      nullable: true
    mobileNumber:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: mobile_number
    email:
      type: string
      length: 50
      fixed: false
      nullable: true
    logDate:
      type: datetime
      nullable: true
      column: log_date
  oneToOne:
    ccmPersonType:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_person_type:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
