CcmStatusHistory:
  type: entity
  table: ccm_status_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    temperatureAlarm:
      type: integer
      unsigned: false
      nullable: true
      column: temperature_alarm
    workingQuantity:
      type: integer
      unsigned: false
      nullable: true
      column: working_quantity
    comments:
      type: text
      nullable: true
    statusDate:
      type: datetime
      nullable: true
      column: status_date
  oneToOne:
    utilization:
      targetEntity: CcmStatusList
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        utilization_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    ccmAssetType:
      targetEntity: CcmAssetTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_asset_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    ccm:
      targetEntity: ColdChain
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    ccmStatusList:
      targetEntity: CcmStatusList
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_status_list_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    reason:
      targetEntity: CcmStatusList
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        reason_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
