CcmWarehousesSolarEnergy:
  type: entity
  table: ccm_warehouses_solar_energy
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
  oneToOne:
    ccmWarehouse:
      targetEntity: CcmWarehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    solarEnergy:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        solar_energy_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
