GatepassVehicles:
  type: entity
  table: gatepass_vehicles
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    number:
      type: string
      length: 255
      fixed: false
      nullable: true
  oneToOne:
    vehicleType:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vehicle_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
