GeoColor:
  type: entity
  table: geo_color
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    colorCode:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: color_code
  lifecycleCallbacks: {  }
