GeoIndicators:
  type: entity
  table: geo_indicators
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    geoIndicatorName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: geo_indicator_name
  lifecycleCallbacks: {  }
