GeoLocations:
  type: entity
  table: geo_locations
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    gisId:
      type: integer
      unsigned: false
      nullable: true
      column: gis_id
  oneToOne:
    location:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    geoLevel:
      targetEntity: GeoLevels
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        geo_level_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    geoMap:
      targetEntity: GeoMaps
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        geo_map_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholder:
      targetEntity: Stakeholders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
