HelpMessages:
  type: entity
  table: help_messages
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    description:
      type: text
      nullable: true
    status:
      type: integer
      nullable: true
  oneToOne:
    resource:
      targetEntity: Resources
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        resource_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
