HfDataDetailDraft:
  type: entity
  table: hf_data_detail_draft
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    fixedInsideUcMale:
      type: decimal
      nullable: true
      column: fixed_inside_uc_male
    fixedInsideUcFemale:
      type: decimal
      nullable: true
      column: fixed_inside_uc_female
    fixedOutsideUcMale:
      type: decimal
      nullable: true
      column: fixed_outside_uc_male
    fixedOutsideUcFemale:
      type: decimal
      nullable: true
      column: fixed_outside_uc_female
    referalMale:
      type: decimal
      nullable: true
      column: referal_male
    referalFemale:
      type: decimal
      nullable: true
      column: referal_female
    pregnantWomen:
      type: integer
      unsigned: false
      nullable: true
      column: pregnant_women 
    nonPregnantWomen:
      type: integer
      unsigned: false
      nullable: true
      column: non_pregnant_women     
    outreachMale:
      type: decimal
      nullable: true
      column: outreach_male
    outreachFemale:
      type: decimal
      nullable: true
      column: outreach_female
    vaccineScheduleId:
      type: integer
      unsigned: false
      nullable: true
      column: vaccine_schedule_id
  oneToOne:
    hfDataMaster:
      targetEntity: HfDataMasterDraft
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        hf_data_master_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    ageGroup:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        age_group_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
