ItemSchedule:
  type: entity
  table: item_schedule
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    numberOfDoses:
      type: integer
      unsigned: false
      nullable: true
      column: number_of_doses
    startingNo:
      type: integer
      unsigned: false
      nullable: true
      column: starting_no
  oneToOne:
    stakeholderActivity:
      targetEntity: StakeholderActivities
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_activity_id:
          referencedColumnName: pk_id
      orphanRemoval: false   
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
      
  lifecycleCallbacks: {  }
