LocationPopulations:
  type: entity
  table: location_populations
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    population:
      type: integer
      unsigned: false
      nullable: true
    estimationDate:
      type: datetime
      nullable: true
      column: estimation_date
  oneToOne:
    location:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
