LogBookItemDoses:
  type: entity
  table: log_book_item_doses
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    doses:
      type: integer
      unsigned: false
      nullable: true
  oneToOne:
    logBook:
      targetEntity: LogBook
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        log_book_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
