MapDistrictMapping:
  type: entity
  table: map_district_mapping
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    mappingId:
      type: integer
      unsigned: false
      nullable: true
      column: mapping_id
    districtName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: district_name
    provinceName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: province_name
    defaultDistrict:
      type: integer
      unsigned: false
      nullable: true
      column: default_district
    pilotDistrictStatus:
      type: boolean
      nullable: true
      column: pilot_district_status
  oneToOne:
    district:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        district_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    province:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        province_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
