NonCcmLocations:
  type: entity
  table: non_ccm_locations
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    locationName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: location_name
  oneToOne:
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    area:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        area:
          referencedColumnName: pk_id
      orphanRemoval: false
    level:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        level:
          referencedColumnName: pk_id
      orphanRemoval: false
    pallet:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        pallet:
          referencedColumnName: pk_id
      orphanRemoval: false
    rackInformation:
      targetEntity: RackInformation
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        rack_information_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    rack:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        rack:
          referencedColumnName: pk_id
      orphanRemoval: false
    row:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        row:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
