Period:
  type: entity
  table: period
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    periodName:
      type: text
      nullable: true
      column: period_name
    periodCode:
      type: integer
      unsigned: false
      nullable: false
      column: period_code
    isMonth:
      type: text
      nullable: true
      column: is_month
    beginMonth:
      type: integer
      unsigned: false
      nullable: true
      column: begin_month
    endMonth:
      type: integer
      unsigned: false
      nullable: true
      column: end_month
    monthCount:
      type: integer
      unsigned: false
      nullable: true
      column: month_count
  lifecycleCallbacks: {  }
