PhysicalStockTakingDetail:
  type: entity
  table: physical_stock_taking_detail
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    batchNumber:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: batch_number
    stakeholderItemPackSize:
      type: integer
      unsigned: false
      nullable: true
      column: stakeholder_item_pack_size_id
    quantity:
      type: decimal
      nullable: true
    currentQuantity:
      type: decimal
      nullable: true
      column: current_quantity
    productionDate:
      type: datetime
      nullable: true
      column: production_date
    expiryDate:
      type: datetime
      nullable: true
      column: expiry_date
    createdDate:
      type: datetime
      nullable: true
      column: created_date
  oneToOne:
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage:
          referencedColumnName: pk_id
      orphanRemoval: false
    physicalStockTaking:
      targetEntity: PhysicalStockTaking
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        physical_stock_taking_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockBatch:
      targetEntity: StockBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockMaster:
      targetEntity: StockMaster
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_master_id:
          referencedColumnName: pk_id
      orphanRemoval: false 
    placementLocation:
      targetEntity: PlacementLocations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        placement_location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false  
  lifecycleCallbacks: {  }
