PlacementLocations:
  type: entity
  table: placement_locations
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    locationBarcode:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: location_barcode
    locationId:
      type: integer
      unsigned: false
      nullable: true
      column: location_id
    capacityPercentage:
      type: decimal
      nullable: true
      column: capacity_percentage
  oneToOne:
    locationType:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_type:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
