Roles:
  type: entity
  table: roles
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    roleName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: role_name
    description:
      type: text
      nullable: true
    status:
      type: boolean
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    category:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        category_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
