ShipmentHistory:
  type: entity
  table: shipment_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    status:
      type: string
      length: null
      fixed: false
      nullable: true
    referenceNumber:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: reference_number
    createdDate:
      type: datetime
      nullable: true
      column: created_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    shipment:
      targetEntity: Shipments
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipment_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
