ShipmentDetail:
  type: entity
  table: shipment_detail
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    receivedDate:
      type: date
      nullable: true
      column: received_date
    receivedQuantity:
      type: decimal
      nullable: true
      column: received_quantity
    createdDate:
      type: date
      nullable: true
      column: created_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    shipment:
      targetEntity: Shipments
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipment_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
