Shipments:
  type: entity
  table: shipments
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    referenceNumber:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: reference_number
    shipmentDate:
      type: date
      nullable: true
      column: shipment_date
    shipmentQuantity:
      type: decimal
      nullable: true
      column: shipment_quantity
    createdDate:
      type: date
      nullable: true
      column: created_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    fundingSource:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        funding_source_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholderActivity:
      targetEntity: StakeholderActivities
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_activity_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
