StakeholderActivities:
  type: entity
  table: stakeholder_activities
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    activity:
      type: string
      length: 255
      fixed: false
      nullable: true
    createdBy:
      type: integer
      unsigned: false
      nullable: true
      column: created_by
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedBy:
      type: integer
      unsigned: false
      nullable: true
      column: modified_by
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  lifecycleCallbacks: {  }
