Stakeholders:
  type: entity
  table: stakeholders
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    stakeholderName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: stakeholder_name
    listRank:
      type: integer
      unsigned: false
      nullable: true
      column: list_rank
  oneToOne:
    stakeholderActivity:
      targetEntity: StakeholderActivities
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_activity_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    geoLevel:
      targetEntity: GeoLevels
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        geo_level_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    parent:
      targetEntity: Stakeholders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        parent_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    mainStakeholder:
      targetEntity: Stakeholders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        main_stakeholder:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholderSector:
      targetEntity: StakeholderSectors
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_sector_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholderType:
      targetEntity: StakeholderTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
