StockDetailHistory:
  type: entity
  table: stock_detail_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    detailId:
      type: integer
      unsigned: false
      nullable: true
      column: detail_id
    quantity:
      type: bigint
      nullable: true
    temporary:
      type: boolean
      nullable: true
    isReceived:
      type: integer
      unsigned: false
      nullable: true
      column: is_received
    adjustmentType:
      type: boolean
      nullable: true
      column: adjustment_type
    actionType:
      type: integer
      unsigned: false
      nullable: true
      column: action_type
  oneToOne:
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemUnit:
      targetEntity: ItemUnits
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_unit_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockBatch:
      targetEntity: StockBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockMasterHistory:
      targetEntity: StockMasterHistory
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_master_id:
          referencedColumnName: master_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
