StockMaster:
  type: entity
  table: stock_master
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    transactionDate:
      type: datetime
      nullable: true
      column: transaction_date
    transactionNumber:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: transaction_number
    transactionCounter:
      type: integer
      unsigned: false
      nullable: true
      column: transaction_counter
    transactionReference:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: transaction_reference
    dispatchBy:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: dispatch_by
    draft:
      type: boolean
      nullable: true
    comments:
      type: text
      nullable: true
    parentId:
      type: integer
      unsigned: false
      nullable: false
      column: parent_id
    campaignId:
      type: integer
      unsigned: false
      nullable: true
      column: campaign_id
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    issueFrom:
      type: date
      nullable: true
      column: issue_from
    issueTo:
      type: date
      nullable: true
      column: issue_to
  oneToOne:
    stakeholderActivity:
      targetEntity: StakeholderActivities
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_activity_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    fromWarehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        from_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    toWarehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        to_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    transactionType:
      targetEntity: TransactionTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        transaction_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
