System:
  type: entity
  table: system
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    startDate:
      type: datetime
      nullable: true
      column: start_date
    tagLine:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: tag_line
  lifecycleCallbacks: {  }
