VvmGroups:
  type: entity
  table: vvm_groups
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    vvmGroup:
      type: integer
      unsigned: false
      nullable: false
      column: vvm_group_id
  oneToOne:
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage_id:
          referencedColumnName: pk_id
      orphanRemoval: false    
  lifecycleCallbacks: {  }