VvmStages:
  type: entity
  table: vvm_stages
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    vvmStageValue:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: vvm_stage_value
  lifecycleCallbacks: {  }
