VvmTransferHistory:
  type: entity
  table: vvm_transfer_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: integer
      unsigned: false
      nullable: true
    createdDate:
      type: date
      nullable: true
      column: created_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    batch:
      targetEntity: StockBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    fromVvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        from_vvm_stage_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    toVvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        to_vvm_stage_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
