WarehouseInactive:
  type: entity
  table: warehouse_inactive
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    inactiveDate:
      type: date
      nullable: false
      column: inactive_date
  oneToOne:
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
