WarehouseTypeCategories:
  type: entity
  table: warehouse_type_categories
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    categoryName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: category_name
  lifecycleCallbacks: {  }
