<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            <?php echo $this->translate("Assign Resources to Role"); ?>
        </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Role Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form method="POST" name="role_search" action="" >
                            <!-- Row -->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-3">
                                        <div class="control-group ">

                                            <label class="control-label" ><?php echo $this->translate("Role name"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->role; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Resource name"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->resource_name; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Resource type"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->resource_type; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-3" style="margin-top: 25px;">
                                        <label class="control-label" >&nbsp;</label>
                                        <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Resource List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="dataTables_wrapper form-inline">

                            <table class="table table-striped table-bordered table-hover dt-responsive dataTable no-footer dtr-inline collapsed"  role="grid" id="sample_2">
                                <thead>
                                    <tr role="row">
                                        <th>Resource Name</th>
                                        <?php foreach ($this->roles as $roles) { ?>

                                            <th><?php echo $roles['roleName']; ?></th>
                                        <?php } ?>

                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $m_res = array();
                                    $i = 1;
                                    if ($this->paginator && count($this->paginator) > 0) :
                                        foreach ($this->paginator as $row):
                                            ?>
                                            <tr role="row">

                                                <td ><?php echo $row->getResourceName(); ?></td>
                                                <?php foreach ($this->roles as $roles) { ?>
                                                    <?php
                                                    if (count($this->roleResources($row->getPkId(), $roles['pkId'])) > 0) {
                                                        $check = "checked='checked'";
                                                    } else {
                                                        $check = "";
                                                    }
                                                    ?> 
                                                    <td><input type="checkbox" value="<?php echo $row->getPkId(); ?>-<?php echo $roles['pkId']; ?>" id="<?php echo $row->getPkId(); ?>-<?php echo $roles['pkId']; ?>-role_resource" name="role_resource[<?php echo $row->getPkId(); ?>-<?php echo $roles['pkId']; ?>]" <?php echo $check; ?> ></td>
                                                    <?php } ?>

                                            </tr>
                                            <!-- // Table row END --><?php
                                            $i++;
                                        endforeach;
                                    endif;
                                    ?>
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
<!-- // Content END -->