<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <div class="row">
            <h3 class="col-md-6">
                Dashboard <small>dashboard & statistics</small>
            </h3>
            <div class="col-md-6">
                    <?php $this->allLevelAreaCombo(array("level" => $this->level, "province" => $this->province, "district" => '')); ?>
            </div>                
        </div>
        <div class="row">&nbsp;</div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                            <?php
                            $count = 1;
                            foreach ($this->dashboards as $dashboard) {
                                $str = $dashboard->getResource()->getDescription();
                                $split = explode(" ", $str);
                                $last_word = $split[count($split) - 1];
                                $first_word = str_replace($last_word, "", $str);
                                ?>
                                <li class="<?php echo (($this->r == 'ri' && $dashboard->getResource()->getPkId() == $this->ri) || ($this->i == 'im' && $dashboard->getResource()->getPkId() == $this->im) || ($this->c == 'camp' && $dashboard->getResource()->getPkId() == $this->campaign) || ($this->r != 'ri' && $this->c != 'camp' && $this->i != 'im' && $count == 1)) ? "active" : ""; ?>">
                                    <a href="#tab-<?php echo $count; ?>" data-toggle="tab">
                                        <div class="dashboard-stat_custom">
                                            <div class="visual" style="width: auto;">
                                                <i class="fa <?php echo $dashboard->getResource()->getIconClass(); ?>"></i>
                                            </div>
                                            <div class="details" style="float: left;">
                                                <div class="dashboard-title-1"><?php echo $first_word; ?></div>
                                                <div class="dashboard-title-2"><?php echo $last_word; ?></div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <?php
                                $count++;
                            }
                            ?>
                        </ul>
                    </div>
                    <div class="widget-body">
                        <div class="tab-content">
                            <?php
                            $count = 1;
                            foreach ($this->dashboards as $dashboard) {
                                ?>
                                <div class="tab-pane <?php echo (($this->r == 'ri' && $dashboard->getResource()->getPkId() == $this->ri) || ($this->i == 'im' && $dashboard->getResource()->getPkId() == $this->im) || ($this->c == 'camp' && $dashboard->getResource()->getPkId() == $this->campaign) || ($this->r != 'ri' && $this->c != 'camp' && $this->i != 'im' && $count == 1)) ? "active" : ""; ?>" id="tab-<?php echo $count; ?>">
                                    <?php if ($dashboard->getResource()->getPkId() == $this->ri || $dashboard->getResource()->getPkId() == $this->im) {
                                        if($dashboard->getResource()->getPkId() == $this->ri){
                                            $button = "ri_btn";
                                            $button_val = "ri";
                                        }
                                        if($dashboard->getResource()->getPkId() == $this->im){
                                            $button = "im_btn";
                                            $button_val = "im";
                                        }
                                        ?>
                                        <div class = "row">
                                            <form method="post" name="<?php echo $button_val; ?>" id="<?php echo $button_val; ?>" action="">
                                                <div class = "col-md-12 col-sm-12">
                                                    <div id = "sample_2_filter" class = "dataTables_filter">                                                        
                                                        <label><button class="btn btn-success" type="button" id="<?php echo $button; ?>" name="<?php echo $button; ?>" value="<?php echo $button_val; ?>">GO</button></label>
                                                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                        <label>Vaccines:
                                                            <select id = "items<?php echo $button_val; ?>" name="items" class = "form-control input-inline">
                                                                <?php foreach ($this->items as $item) {
                                                                    ?>
                                                                    <option value="<?php echo $item['pkId']; ?>" <?php if ($item['pkId'] == $this->item) { ?>selected="selected"<?php } ?>><?php echo $item['itemName']; ?></option>   
                                                                <?php } ?>                    
                                                            </select>
                                                        </label>
                                                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                        <?php if($this->level == 1){ ?>
                                                        <label>Period:
                                                            <select name="period" id="period<?php echo $button_val; ?>" class="form-control input-inline">
                                                                <optgroup label="Quarter">
                                                                    <?php
                                                                    foreach ($this->time_intervals as $key => $value) {
                                                                        if ($value['monthCount'] == $this->quarter) {
                                                                            ?>           
                                                                            <option value="<?php echo $value['pkId']; ?>" <?php if ($this->period == $value['pkId']) { ?>selected="selected"<?php } ?>><?php echo $value['periodName']; ?></option>
                                                                        <?php } ?>
                                                                    <?php } ?>
                                                                </optgroup>
                                                                <optgroup label="Half"> 
                                                                    <?php
                                                                    foreach ($this->time_intervals as $key => $value) {
                                                                        if ($value['monthCount'] == $this->halfyear) {
                                                                            ?>           
                                                                            <option value="<?php echo $value['pkId']; ?>" <?php if ($this->period == $value['pkId']) { ?>selected="selected"<?php } ?>><?php echo $value['periodName']; ?></option>
                                                                        <?php } ?>
                                                                    <?php } ?>
                                                                </optgroup>
                                                                <optgroup label="Annual"> 
                                                                    <?php
                                                                    foreach ($this->time_intervals as $key => $value) {
                                                                        if ($value['monthCount'] == $this->annual) {
                                                                            ?>           
                                                                            <option value="<?php echo $value['pkId']; ?>" <?php if ($this->period == $value['pkId']) { ?>selected="selected"<?php } ?>><?php echo $value['periodName']; ?></option>
                                                                        <?php } ?>
                                                                    <?php } ?>
                                                                </optgroup>
                                                                <?php //}     ?>
                                                            </select>
                                                        </label>
                                                        <?php } ?>
                                                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                        <?php if($this->level == 1){ ?>
                                                        <label>Year:
                                                            <select id="date<?php echo $button_val; ?>" name="date" class="form-control input-inline">
                                                                <?php for ($i = 2013; $i <= date("Y"); $i++) { ?>
                                                                    <option value="<?php echo $i; ?>" <?php if ($i == $this->date) { ?>selected="selected"<?php } ?>><?php echo $i; ?></option>   
                                                                <?php } ?>                    
                                                            </select>
                                                        </label> 
                                                        <?php } else { ?>
                                                        <label>Reporting Month:
                                                            <select id="date<?php echo $button_val; ?>" name="date" class="form-control input-inline">
                                                                <?php
                                                                for ($i = 2013; $i <= date("Y"); $i++) {
                                                                    for ($j = 1; $j <= 12; $j++) {
                                                                        if ($i == date("Y") && $j > date("m")) {
                                                                            continue;
                                                                        }
                                                                        $date = $i . "-" . str_pad($j, 2, '0', STR_PAD_LEFT);
                                                                        ?>
                                                                        <option value="<?php echo $date; ?>" <?php if ($date == $this->date) { ?>selected="selected"<?php } ?>><?php echo str_pad($j, 2, '0', STR_PAD_LEFT) . " - " . $i; ?></option>   
                                                                        <?php
                                                                    }
                                                                }
                                                                ?>                    
                                                            </select>
                                                        </label>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <?php
                                    }
                                    if ($dashboard->getResource()->getPkId() == $this->campaign) {
                                        ?>
                                        <div class="row">
                                            <form method="post" name="ri" id="ri" action="">
                                                <div class="col-md-12 col-sm-12">
                                                    <div id="sample_2_filter" class="dataTables_filter">
                                                        <label><button class="btn btn-success" type="button" id="camp_btn" name="camp_btn" value="camp">GO</button></label>
                                                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                        <label>Campaign: 
                                                            <select id="camp" name="camp" class="form-control input-inline input-small">
                                                                <?php foreach ($this->campaigns as $camp) { ?>
                                                                    <option value="<?php echo $camp['pkId']; ?>" <?php if ($camp['pkId'] == $this->camp) { ?>selected="selected"<?php } ?>><?php echo $camp['campaignName']; ?></option>   
                                                                <?php } ?>                    
                                                            </select>
                                                        </label>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    <?php } ?>
                                    <div class="row">
                                        <?php echo $this->dashlets($dashboard->getResource()->getPkId()); ?>
                                    </div>
                                </div>
                                <?php
                                $count++;
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <!-- // Tabs END -->                
            </div>
        </div>
    </div>
</div>