<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Users") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Users Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="batch_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="control-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Username"); ?></label>
                                                    <div class="controls">
                                                        <?php echo $this->form->login_id; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="control-group ">
                                                    <label class="control-label" ><?php echo $this->translate("User Role"); ?></label>
                                                    <div class="controls">
                                                        <?php echo $this->form->role; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3 margin-top-25">
                                                <label class="control-label" >&nbsp;</label>
                                                <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Users List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#modal-add-user"><?php echo $this->translate("Add User") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-condensed dataTable">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'login_id' => 'Username',
                                            'role' => 'User Role',
                                            'created_by' => 'Created By',
                                            'logged_at' => 'Last Login'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    $last_login = $row->getLoggedAt()->format('Y-m-d H:i:s');
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row->getLoginId(); ?></td>
                                                        <td><?php echo $row->getRole()->getRoleName(); ?></td>
                                                        <td><?php echo $row->getCreatedBy()->getUsername(); ?></td>
                                                        <td><?php
                                                            if ($last_login != '-0001-11-30 00:00:00') {
                                                                echo $last_login;
                                                            } else {
                                                                echo 'Not Loggedin';
                                                            }
                                                            ?></td>
                                                        <td><a itemid="<?php echo $row->getPkId(); ?>" class="btn update-user btn-link btn-success btn-mini" data-toggle="modal" href="#modal-update-user"><?php echo $this->translate("Edit") ?></a> <a data-bind="<?php echo $row->getPkId(); ?>" data-toggle="notyfy" data-type="confirm" data-layout="top" class="btn btn-danger btn-link btn-mini"><?php echo $this->translate("Delete") ?></a>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/cadmin/manage-users/add" id="add-user">
            <div class="modal fade" id="modal-add-user" tabindex="-1" role="basic" aria-hidden="true" >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add User</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Username"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->login_id; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("User Role"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->role; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Email"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->email; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Phone"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->phone; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Password"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->password; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Confirm Password"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->confirm_password; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <?php $this->allLevelCombo(); ?>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Save"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/cadmin/manage-users/update" id="update-user" enctype="multipart/form-data">
            <div class="modal fade" id="modal-update-user" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit User</h4>
                        </div>
                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer" id="update-button">
                            <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Update"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->