<?php
/**
 *  phtml for Ajax requisitions details
 */
?>
<?php
if ($this->arr_data && count($this->arr_data) > 0) {
    $status = $this->arr_data[0]['draft'];
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <?php echo $this->translate("Requisition Details - Req #") . $this->arr_data[0]['requisitionNumber'] . "- Received From " . $this->arr_data[0]['fromWH'] ?>
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse"></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form name="pipeline-form" id="pipeline-form" method="post" action="<?php echo $this->baseUrl(); ?>/stock-demand/update-requisition">
                                <table class="table table-striped table-bordered table-condensed">
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th>
                                                <?php echo $this->translate("S.No"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Product"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("From Store"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Demand Qty"); ?>
                                            </th>
                                            <?php if ($status == 1) { ?>
                                                <th>
                                                    <?php echo $this->translate("Remaining Qty"); ?>
                                                </th>
                                            <?php } ?>
                                            <th>
                                                <?php echo $this->translate("Approved Qty"); ?>
                                            </th>                                              
                                        </tr>
                                    </thead>
                                    <!-- // Table heading END -->

                                    <!-- Table body -->
                                    <tbody>
                                        <!-- Table row -->
                                        <?php
                                        $i = 1;
                                        foreach ($this->arr_data as $row) {
                                            $status = $row['draft'];
                                            ?>
                                            <tr class="gradeX">
                                                <td class="center" style="width: 2%">
                                                    <?php echo $i; ?>
                                                </td>
                                                <td nowrap>
                                                    <?php echo $row['itemName']; ?>
                                                </td>
                                                <td>
                                                    <?php echo $row['fromWH']; ?>
                                                </td>
                                                <td align="right" style="width: 20%">
                                                    <?php echo number_format($row['quantity']); ?>
                                                </td>
                                                <?php if ($status == 1) { ?>
                                                    <td align="right">
                                                        <input type="text" enabled="false" class="form-control" id="remainingQty" name="remainingQty[]">
                                                    </td>
                                                <?php } ?>
                                                <td align="right" style="width: 20%">
                                                    <?php if ($status == 0) { ?>
                                                        <input type="hidden"  class="form-control" id="<?php echo $row['pkId'] ?>" name="masterId[]" value="<?php echo $row['pkId'] ?>">
                                                        <input type="hidden"  class="form-control" id="<?php echo $row['detailId'] ?>" name="detailId[]" value="<?php echo $row['detailId'] ?>">                                                        
                                                        <input class="qty form-control input-sm" type="text" name="approvedQty[<?php echo $row['detailId'] . "]" ?>"  value="0">
                                                    <?php } else { ?>
                                                        <?php
                                                        if ($status == 4) {
                                                            echo '0';
                                                        } else {
                                                            echo number_format($row['approvedQuantity']);
                                                        }
                                                    }
                                                    ?>

                                                </td>

                                            </tr>
                                            <?php
                                            $i++;
                                        }
                                        ?>
                                        <!-- // Table row END -->
                                    </tbody>
                                    <!-- // Table body END -->

                                    <tfoot>

                                    </tfoot>

                                </table>
                                <input type="hidden" id="type" name="type" value="1"/>

                                <br>
                                <table> 
                                    <tbody>                                       
                                        <tr>
                                            <td><b>Suggested Date: </b></td>
                                            <td style="width: 20px"></td>
                                            <td> <?php echo $this->form->suggested_date; ?></td>
                                            <?php if ($status == 0) { ?>
                                                <td> <b> &nbsp;New Suggested Date: </b></td>
                                                <td style="width: 20px"></td>
                                                <td><?php echo $this->form->new_suggested_date; ?></td>
                                            <?php } ?>
                                            <td><b> &nbsp;Attachments:</b></td>
                                            <td style="width: 20px"></td>
                                            <td> 
                                                <?php if (!empty($this->attachments)) { ?> <a href="<?php echo str_replace("stock-demand", "", $this->baseUrl()) . '/' . $this->attachments[0]['file_path']; ?>" target="_blank">View</a><i class="fa fa-paperclip"></i><?php } else {
                                                    ?>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <span>No attachments found.</span>
                                                        </div>
                                                    </div>
                                                <?php }
                                                ?>
                                            </td>
                                        </tr>                                          
                                    </tbody>
                                </table>
                                <table width="100%">
                                    <?php if ($status == 0) { ?>
                                        <tr>
                                            <td colspan="11" class="right">
                                                <div class="row">
                                                    <div class="col-md-12 right">
                                                        <?php if ($status == 0) { ?>
                                                            <button class="btn btn-primary" name="approve" onclick="return confirm('Are you sure you want to approve the requsition?');" type="submit">Approve</button>
                                                            <button class="btn btn-primary" name="unapprove" onclick="return confirm('Are you sure you want unapprove the requsition?');" type="submit">UnApprove</button>                                                           
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                </table>
                            </form>

                        </div>
                    </div>  
                </div>
            </div>
        </div>
    </div>

    <?php
}
?>
