<?php
/**
 *  phtml for Ajax requisitions details
 */
?>
<?php
if ($this->arr_data && count($this->arr_data) > 0) {
    $status = $this->arr_data[0]['draft'];
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <?php echo $this->translate("Requisition Details - Req #") . $this->arr_data[0]['requisitionNumber'] . "- Requisition To " . $this->arr_data[0]['warehouseName'] ?>
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse"></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form name="pipeline-form" id="pipeline-form" method="post" action="<?php echo $this->baseUrl(); ?>/stock-demand/update-requisition">
                                <table class="table table-striped table-bordered table-condensed">
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th>
                                                <?php echo $this->translate("S.No"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Product"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("To Store"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Demand Qty"); ?>
                                            </th>
                                            <?php if ($status == 2 || $status == 3) { ?>
                                                <th>
                                                    <?php echo $this->translate("Approved Qty"); ?>
                                                </th>    
                                            <?php } ?>
                                        </tr>
                                    </thead>
                                    <!-- // Table heading END -->

                                    <!-- Table body -->
                                    <tbody>
                                        <!-- Table row -->
                                        <?php
                                        $i = 1;
                                        foreach ($this->arr_data as $row) {
                                            $status = $row['draft'];
                                            ?>
                                            <tr class="gradeX">
                                                <td class="center" style="width: 2%">
                                                    <?php echo $i; ?>
                                                </td>
                                                <td nowrap>
                                                    <?php echo $row['itemName']; ?>
                                                </td>
                                                <td>
                                                    <?php echo $row['warehouseName']; ?>
                                                </td>
                                                <td align="right" style="width: 20%">
                                                    <?php echo number_format($row['quantity']); ?>
                                                </td>
                                                <?php if ($status == 2 || $status == 3) { ?>
                                                    <td align="right" style="width: 20%">
                                                        <?php
                                                        echo number_format($row['approvedQuantity']);
                                                        ?>
                                                    </td>
                                                <?php } ?>
                                            </tr>
                                            <?php
                                            $i++;
                                        }
                                        ?>
                                        <!-- // Table row END -->
                                    </tbody>
                                    <!-- // Table body END -->

                                    <tfoot>

                                    </tfoot>

                                </table>
                                <input type="hidden" id="type" name="type" value="1"/>
                                <br>
                                <table> 
                                    <tbody>                                        
                                        <tr>
                                            <td><b>Attachments:</b></td>
                                            <td style="width: 20px"></td>
                                            <td> 

                                                <?php if (!empty($this->attachments)) { ?> <a href="<?php echo str_replace("stock-demand", "", $this->baseUrl()) . '/' . $this->attachments[0]['file_path']; ?>" target="_blank">View</a><i class="fa fa-paperclip"></i><?php } else {
                                                    ?>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <span>No attachments found.</span>
                                                        </div>
                                                    </div>
                                                <?php }
                                                ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                        </div>
                    </div>  
                    </form>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
