<?php
/**
 *  phtml for Issue
 */
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            <?php echo $this->translate("Stock Requisition Form"); ?>
        </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php
                            $type = $this->type;
                            if ($this->issueedit) {
                                $label = "Update Issue";
                                $d_id = $this->detail_id;
                                $btn_hidden = "<input type=hidden name=issueedit value=Yes />";
                                $btn_hidden .= "<input type=hidden name=detailid value=$d_id />";
                                $btn_hidden .= "<input type=hidden name=type value=$type />";
                            } else {
                                $label = "Add to List";
                                $btn_hidden = '';
                            }
                            ?>
                            <?php echo $this->translate('Fill Form') ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse"></a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row margin-top-10 margin-bottom-10">
                            <?php if (!empty($this->msg)) { ?>
                                <div class="col-md-12">
                                    <div class="alert alert-info">
                                        <button data-dismiss="alert" class="close" type="button">
                                            ×
                                        </button>
                                        <?php echo $this->msg; ?>                                        
                                        <a id="issue-print" onclick="window.open('print-issue?id=<?php echo $this->master_id; ?>', '_blank', 'scrollbars=1,width=840,height=595');" href="javascript:void(0);"><strong><?php echo $this->voucher; ?></strong></a>
                                    </div>                                
                                </div>
                            <?php } ?>
                            <div class="col-md-12">
                                <?php
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?php if (!empty($this->arr_data['success']) && $this->arr_data['success'] == 1) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> ×</button>
                                        <strong><?php echo $this->translate("Data"); ?></strong> <?php echo $this->translate("has been saved successfully"); ?>!
                                    </div>
                                <?php } ?>
                                <form method="POST" name="requisition_form" id="new_issue_form" action="">
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="requisition_number">
                                                    <?php echo $this->translate("Requisition No"); ?> 
                                                </label>
                                                <?php echo $this->form->requisition_number; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="period">
                                                    <?php echo $this->translate("Period"); ?> 
                                                    <span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->period; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="requisition_reference"> 
                                                    <?php echo $this->translate("Requisition Reference"); ?> 
                                                </label>
                                                <?php echo $this->form->requisition_reference; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="warehouse_name"> 
                                                    <?php echo $this->translate("To Store"); ?> <span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->warehouse_name; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="control-group">
                                                <label class="control-label" for="activity_id">
                                                    <?php echo $this->translate("Purpose"); ?> <span class="red">*</span>
                                                </label>
                                                <div class="controls">
                                                    <?php echo $this->form->activity_id; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="suggested_date">
                                                    <?php echo $this->translate("Suggested Pickup/Delivery Date"); ?> 
                                                    <span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->suggested_date; ?>                                            
                                            </div>
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="item_id">
                                                    <?php echo $this->translate("Product"); ?> <span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->item_id; ?>

                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="usage">
                                                    <?php echo $this->translate("Used for"); ?> 
                                                </label>
                                                <select id="usage" class="form-control" name="usage">
                                                    <option value="">Select</option>

                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="transaction_reference"> 
                                                    <?php echo $this->translate("Quantity Required"); ?> (Vials) <span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->quantity; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row" id="remaining_balance_div" style="display:none">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="allowcated_qty">
                                                    <?php echo $this->translate("Allocated Qty for the Period"); ?> 
                                                </label>
                                                <?php echo $this->form->allocated_qty; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group"> 
                                                <label class="control-label" for="remaining_balance">
                                                    <?php echo $this->translate("Remaining Balance for the Period"); ?> 
                                                </label>
                                                <?php echo $this->form->remaining_balance; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">                                        
                                        <div class="col-md-12 right">
                                            <div class="form-group form-btn-margin-top pull-right">
                                                <label class="control-label" for="hdn_stock_id">
                                                    &nbsp;
                                                </label>
                                                <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit">
                                                    <?php echo $this->translate($label); ?>
                                                </button>
                                                <?php
                                                if ($this->issueedit) {
                                                    if ($type == 's') {
                                                        $url = "stock/issue-search";
                                                    } else {
                                                        $url = "stock/issue";
                                                    }
                                                    ?>
                                                    <a href="<?php echo $this->baseUrl(); ?>/<?php echo $url; ?>"><button type="button" class="btn btn-danger" id="cancel_issue">
                                                            <?php echo $this->translate("Cancel"); ?>
                                                        </button></a>
                                                <?php } ?>
                                                <?php echo $btn_hidden; ?>
                                                <?php echo $this->form->hdn_stock_id; ?>
                                                <?php echo $this->form->hdn_to_warehouse_id; ?>
                                            </div>

                                        </div></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        if (!empty($this->arr_data) && count($this->arr_data) > 0) {
            ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Requisition Detail"); ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">                                   
                                    <table class="table table-striped table-bordered table-condensed">
                                        <!-- Table heading -->
                                        <thead>
                                            <tr>
                                                <th>
                                                    <?php echo $this->translate("S. No."); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Date"); ?>
                                                </th>                                               
                                                <th>
                                                    <?php echo $this->translate("Product"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Unit"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("To Store"); ?>
                                                </th>
                                                <th class="col-md-2 center">
                                                    <?php echo $this->translate("Demand Qty"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Pickup/Delivery Date"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Action"); ?>
                                                </th>
                                            </tr>
                                        </thead>
                                        <!-- // Table heading END -->

                                        <!-- Table body -->
                                        <tbody>

                                            <?php
                                            $i = 1;
                                            foreach ($this->arr_data as $row) {
                                                ?>
                                                <tr class="gradeX">
                                                    <td><?php echo $i; ?></td>

                                                    <td align="center"><?php echo App_Controller_Functions::dateToUserFormat($row['created_date']); ?></td>                                                    
                                                    <td>
                                                        <?php echo $row['item_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row['item_unit_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row['to_warehouse_name']; ?>
                                                    </td>
                                                    <td class="right"><?php echo number_format(abs($row['demand_quantity'])); ?></td>

                                                    <td align="center"><?php echo App_Controller_Functions::dateToUserFormat($row['suggested_date']); ?></td>
                                                    <td align="center">
                                                        <span data-toggle="notyfy" id="<?php echo $row['demand_detail_id']; ?>" data-type="confirm"
                                                              data-layout="top" class="fa fa-times cursor-hand"></span>
                                                    </td>
                                                </tr>
                                                <?php
                                                $i++;
                                            }
                                            ?>
                                            <!-- // Table row END -->
                                        </tbody>
                                        <!-- // Table body END -->

                                    </table>
                                </div>
                            </div>
                            <br>
                            <form name="issue_stock" id="issue_stock" action="" method="POST" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label" for="comments">
                                            <?php echo $this->translate("Comments Max 300 Char"); ?>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->comments; ?>
                                        </div>
                                        <br>                                            
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3">

                                    </div>
                                    <div id="issue_period_date" style="display:none;">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="issue_from">
                                                    <?php echo $this->translate("From"); ?>
                                                </label>

                                                <?php echo $this->form->issue_from; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="issue_to">
                                                    <?php echo $this->translate("To"); ?>
                                                </label>
                                                <?php echo $this->form->issue_to; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>  
                                <div class="row">                                       
                                    <div class="col-md-6">
                                        <label class="control-label col-md-3"><strong>Attachment:</strong></label>
                                        <div data-provides="fileinput" class="fileinput fileinput-new"><input type="hidden">
                                            <div class="input-group input-large">
                                                <div data-trigger="fileinput" class="form-control uneditable-input span3">
                                                    <i class="fa fa-file fileinput-exists"></i>&nbsp; <span class="fileinput-filename">
                                                    </span>
                                                </div>
                                                <span class="input-group-addon btn default btn-file">
                                                    <span class="fileinput-new">
                                                        Browse.. </span>
                                                    <span class="fileinput-exists">
                                                        Change </span>
                                                    <input type="file" name="attachment">
                                                </span>
                                                <a data-dismiss="fileinput" class="input-group-addon btn red fileinput-exists" href="#">
                                                    Remove </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 right">

                                        <button type="submit" class="btn btn-primary"
                                                onclick="return confirm('Are you sure you want to save the list?');">
                                                    <?php echo $this->translate("Save"); ?>
                                        </button>

                                        <button id="print_requisition" type="button" class="btn btn-primary">
                                            <?php echo $this->translate("Print"); ?>
                                        </button>
                                        <button type="submit" class="btn btn-primary"
                                                onclick="return confirm('Are you sure you want to cancel the list?');">
                                                    <?php echo $this->translate("Cancel"); ?>
                                        </button>
                                        <?php echo $this->form->hdn_master_id; ?>
                                    </div>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
</div>
<!-- // Content END -->
<input type="hidden" id="curr_wh" value="<?php echo $this->wh_id; ?>"/>
<div style="display: none;">
    <div id="cprov"><?php echo $this->params['province']; ?></div>
    <div id="cdist"><?php echo $this->params['district']; ?></div>
</div>