CampaignDistricts:
  type: entity
  table: campaign_districts
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    campaign:
      targetEntity: Campaigns
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        campaign_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    district:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        district_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
