Campaigns:
  type: entity
  table: campaigns
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    campaignName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: campaign_name
    dateFrom:
      type: datetime
      nullable: true
      column: date_from
    dateTo:
      type: datetime
      nullable: true
      column: date_to
    catchUpDays:
      type: integer
      unsigned: false
      nullable: true
      column: catch_up_days
    isClosed:
      type: boolean
      nullable: false
      column: is_closed
    createdDate:
      type: datetime
      nullable: false
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    campaignType:
      targetEntity: CampaignTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        campaign_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
