HfSessions:
  type: entity
  table: hf_sessions
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    fixedPlannedSessions:
      type: integer
      unsigned: false
      nullable: true
      column: fixed_planned_sessions
    fixedActuallyHeldSessions:
      type: integer
      unsigned: false
      nullable: true
      column: fixed_actually_held_sessions
    outreachPlannedSessions:
      type: integer
      unsigned: false
      nullable: true
      column: outreach_planned_sessions
    outreachActuallyHeldSessions:
      type: integer
      unsigned: false
      nullable: true
      column: outreach_actually_held_sessions
    reportingStartDate:
      type: datetime
      nullable: true
      column: reporting_start_date
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouseStatus:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_status:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
