PlacementLocations:
  type: entity
  table: placement_locations
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    locationBarcode:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: location_barcode
    locationId:
      type: integer
      unsigned: false
      nullable: true
      column: location_id
    capacityPercentage:
      type: decimal
      nullable: true
      column: capacity_percentage
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    locationType:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_type:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
