<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"> <?php echo $this->translate("Cold Chain") ?></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Vaccine Carrier Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row margin-top-10 margin-bottom-10">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="batch_search" action="" id="batch_search">
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="control-group">
                                                <label class="control-label" for="firstname"> <?php echo $this->translate("Catalogue ID") ?></label>
                                                <div class="controls">
                                                    <?php echo $this->form->catalogue_id; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="control-group">
                                                <label class="control-label" for="firstname"> <?php echo $this->translate("Make") ?></label>
                                                <div class="controls">
                                                    <?php echo $this->form->ccm_make_id; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="control-group">
                                                <label class="control-label" for="number"><?php echo $this->translate("Model") ?></label>
                                                <div class="controls">
                                                    <?php echo $this->form->ccm_model_id; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="control-group" id="placed_at_radio">
                                                <label class="control-label" for="placedat">
                                                    <?php echo $this->translate('Placed at'); ?>
                                                </label>
                                                <div class="widget-body uniformjs">
                                                    <?php echo $this->form->placed_at; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <?php $this->allLevelCombo(); ?>
                                        </div>
                                    </div>
                                    <label class="control-label" for="">   </label>
                                    <div class="widget">
                                        <div class="widget-body right">
                                            <button class="btn btn-primary" type="submit" id="search" name="search"><?php echo $this->translate('Search'); ?></button>
                                            <button id="reset" class="btn btn-info" type="reset"><?php echo $this->translate('Reset'); ?></button>
                                            <?php echo $this->form->office_id; ?>
                                            <?php echo $this->form->combo1_id; ?>
                                            <?php echo $this->form->warehouse_id; ?>
                                            <?php echo $this->form->model_id; ?>
                                        </div>
                                    </div>
                                    <?php echo $this->form->office_id; ?>
                                    <?php echo $this->form->combo1_id; ?>
                                    <?php echo $this->form->warehouse_id; ?>
                                    <?php echo $this->form->model_id; ?>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Vaccine Carrier Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-6" >
                                <div class="control-group" id="report_type_radio">
                                    <label class="control-label" for="report_type">
                                        <?php echo $this->translate('Report Tpe'); ?>
                                    </label>
                                    <div class="widget-body uniformjs" id="report_type_radio">
                                        <?php echo $this->form->report_type; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" id="details_div">
                            <div class="col-md-12">
                                <!-- Table -->
                                <table class="receiveSearch table table-striped table-bordered table-hover dataTable no-footer"  >
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th rowspan="2"><?php echo $this->translate("District") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Facility") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Make") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Model") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Date") ?></th>
                                            <th rowspan="2">Action</th>
                                        </tr>
                                    </thead>
                                    <!-- // Table heading END -->

                                    <!-- Table body -->
                                    <tbody>
                                        <!-- Table row -->
                                        <?php
                                        $i = 1;
                                        if ($this->vaccine_carrier_search && count($this->vaccine_carrier_search) > 0) :
                                            foreach ($this->vaccine_carrier_search as $row):
                                                ?>
                                                <tr class="gradeX">
                                                    <td><?php echo (($row['locationName'] == "") ? '-' : $row['locationName']); ?></td>
                                                    <td><?php echo (($row['warehouseName'] == "") ? '-' : $row['warehouseName']); ?></td>
                                                    <td><?php echo $row['ccmMakeName']; ?></td>
                                                    <td><?php echo $row['ccmModelName']; ?></td>
                                                    <td><?php echo (($row['createdDate'] == "0000-00-00 00:00:00") ? '-' : App_Controller_Functions::dateToUserFormat($row['createdDate'])); ?></td>
                                                    <td class="center">
                                                        <!--<a class="fa fa-files-o" onclick="javascript:void(0);" data-toggle="modal" href="#modal-new-catalogue_<?= $row['pkId'] ?>" title="<?php echo $this->translate("View more details"); ?>"></a>
                                                        |-->
                                                        <a class="fa fa-files-o cursor-hand" onclick="javascript:void(0);" id="<?= $row['pkId'] ?>print_button" title="<?php echo $this->translate("View more details"); ?>" target="_blank"></a>
                                                        <?php
                                                        /*
                                                          $detail_data = $this->coldChain()->getVaccineCarrierDetailById($row['pkId']);
                                                          if ($detail_data != false) :
                                                          $detail_row = $detail_data[0];
                                                          ?>
                                                          <!-- // Asset Add Popup  -->
                                                          <div id="modal-new-catalogue_<?php echo $row['pkId'] ?>" class="modal fade"  tabindex="-1" role="basic" aria-hidden="true">
                                                          <div class="modal-dialog">
                                                          <div class="modal-content">
                                                          <!-- Modal heading -->
                                                          <div class="modal-header">
                                                          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                                                          <h3><?php echo $this->translate("Vaccine Carrier Details"); ?></h3>
                                                          </div>
                                                          <!-- // Modal heading END -->

                                                          <!-- Modal body -->
                                                          <div class="modal-body">
                                                          <!-- BODY HERE -->
                                                          <div class="row">
                                                          <div class="col-md-6" id="detail">
                                                          <label class="control-label" for="" ><strong><?php echo $this->translate("Catalogue ID"); ?>:</strong></label>
                                                          <div class="controls text-left" id="detail_div" >
                                                          <?php echo $detail_row['catalogueId']; ?>
                                                          </div>
                                                          </div>
                                                          <div class="col-md-6" id="detail">
                                                          <label class="control-label" for="" ><strong><?php echo $this->translate("Internal Dimensions"); ?>:</strong> </label>
                                                          <div class="controls text-left" id="detail_div">
                                                          <?php echo $detail_row['assetDimensionLength'] . "x" . $detail_row['assetDimensionWidth'] . "x" . $detail_row['assetDimensionHeight']; ?>
                                                          </div>
                                                          </div>
                                                          </div>
                                                          <div class="row">
                                                          <div class="col-md-6" id="detail">
                                                          <label class="control-label" for="" ><strong><?php echo $this->translate("Make"); ?>:</strong> </label>
                                                          <div class="controls text-left" id="detail_div">
                                                          <?php echo $detail_row['ccmMakeName']; ?>
                                                          </div>
                                                          </div>
                                                          <div class="col-md-5" id="detail">
                                                          <label class="control-label" for="" ><strong><?php echo $this->translate("Model"); ?>:</strong> </label>
                                                          <div class="controls text-left" id="detail_div">
                                                          <?php echo $detail_row['ccmModelName']; ?>
                                                          </div>
                                                          </div>
                                                          </div>
                                                          <div class="row">
                                                          <div class="col-md-6" id="detail">
                                                          <label class="control-label" for="" ><strong><?php echo $this->translate("Quantity"); ?>:</strong> </label>
                                                          <div class="controls text-left" id="detail_div">
                                                          <?php echo $detail_row['quantity']; ?>
                                                          </div>
                                                          </div>
                                                          </div>
                                                          <div class="row">
                                                          <div class="col-md-6" id="detail">
                                                          <label class="control-label" ><strong><?php echo $this->translate("Placed At"); ?>:</strong></label>
                                                          <div class="controls text-left">
                                                          <?php echo $this->translate("District Province"); ?>: <?php echo $detail_row['district']; ?>&nbsp;
                                                          <?php echo $this->translate("Facility Store"); ?>: <?php echo $detail_row['facility']; ?>&nbsp;
                                                          </div>
                                                          </div>
                                                          </div>
                                                          </div>
                                                          <!-- // Modal body END -->

                                                          <!-- Modal footer -->
                                                          <div class="modal-footer">
                                                          <a data-dismiss="modal" class="btn btn-default" href="#"><?php echo $this->translate("Close"); ?></a>
                                                          </div>
                                                          </div>
                                                          </div>
                                                          <!-- // Modal footer END -->
                                                          </div>
                                                          <!-- // Asset Add Popup END  -->
                                                          <?php
                                                          endif;
                                                         */
                                                        ?>
                                                    </td>
                                                </tr>
                                                <?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                        <!-- // Table row END -->
                                    </tbody>
                                    <!-- // Table body END -->
                                </table>
                                <!-- // Table END -->
                            </div>
                        </div>
                        <div class="row hidden" id="summary_div">
                            <div class="col-md-12">
                                <!-- Table -->
                                <table class="receiveSearch table table-striped table-bordered table-hover dataTable no-footer"  >
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th rowspan="2"><?php echo $this->translate("Store") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Cold Chain Type") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Working Status") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Quantity"); ?></th>
                                        </tr>
                                    </thead>
                                    <!-- // Table heading END -->

                                    <!-- Table body -->
                                    <tbody>
                                        <!-- Table row -->
                                        <?php
                                        $i = 1;
                                        if ($this->vaccine_carrier_search && count($this->vaccine_carrier_search) > 0) :
                                            foreach ($this->vaccine_carrier_search as $row):
                                                ?>
                                                <tr class="gradeX">
                                                    <td><?= $row['warehouseName'] ?></td>
                                                    <td><?= $row['assetTypeName'] ?></td>
                                                    <td><?= $row['ccmStatusListName'] ?></td>
                                                    <td><?= $row['quantity'] ?></td>
                                                </tr>
                                                <?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                        <!-- // Table row END -->
                                    </tbody>
                                    <!-- // Table body END -->
                                </table>
                                <!-- // Table END -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- // Content END -->
