<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Location Types") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Location Type Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                 <?php if (isset($_GET['success']) && $_GET['success'] == 1) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been saved successfully!
                                    </div>
                                <?php } 
                                
                                if (isset($_GET['success']) && $_GET['success'] == 2) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been updated successfully!
                                    </div>
                                <?php }
                                
                                
                                ?>
                                <form method="POST" name="location_type_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Location Type"); ?></label>
                                                    <?php echo $this->form->location_type_name; ?>
                                                </div>
                                            </div>
                 
                                            <div class="col-md-4 margin-top-25">
                                                <div class="form-group" id="div_status">
                                                    <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
                                                    <?php echo $this->form->status; ?>
                                                </div>
                                            </div>
                                            <div class="col-md-3 margin-top-25">
                                                <div class="form-group">
                                                    <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                    <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Loation Type List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#add-location-type"><?php echo $this->translate("Add Location Type") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'location_type_name' => 'Location Type Name',
                                            'geo_level_id' => 'Geo Level',
                                            'created_by' => 'Created By'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row['locationTypeName']; ?></td>
                                                        <td><?php echo $row['geoLevelName']; ?></td>
                                                        <td><?php echo $row['userName']; ?></td>
                                                        <td>
                                                            <a itemid="<?php echo $row['pkId']; ?>" class="btn update-location-type btn-link btn-success btn-mini" data-toggle="modal" href="#modal-update-location-type"><?php echo $this->translate("Edit") ?></a>
                                                       <?php if ($row['status'] == 1) { ?>
                                                                <a id="<?php echo $row['pkId']; ?>" class="active btn-link btn-danger input-sm"><?php echo $this->translate("Active"); ?></a>
                                                            <?php } else { ?>
                                                                <a id="<?php echo $row['pkId']; ?>" class="deactivate btn-link btn-danger input-sm"><?php echo $this->translate("Deactive"); ?></a>
                                                            <?php } ?>
                                                        </td>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-locations/add-location-type" id="add-location-types">
            <div class="modal fade" id="add-location-type" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add Location Type</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Location Type Name"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->location_type_name; ?>
                                    </div>
                                </div>
                                   <div class="col-md-5">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Geo Level"); ?> <span class="red">*</span></label>
                                        <?php echo $this->form_add->geo_level_id; ?>
                                    </div>
                                </div>
                            </div>
                             <div class="row">
                                <div class="col-md-6 margin-top-25">
                                    <div class="form-group" id="div_status">
                                        <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
                                        <?php echo $this->form_add->status; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-locations/update-location-type" id="update-location-types">
            <div class="modal fade" id="modal-update-location-type" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit Location Type</h4>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>

            </div>
        </form>

    </div>
</div>
<!-- // Content END -->
