<div class="row">
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Username"); ?></label>
                <div class="controls">
                    <?php echo $this->form->user_name_update; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Email"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->email_update; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Phone"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->phone_update; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Old Password"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->old_password; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("New Password"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->new_password; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <?php echo $this->usersEditCombo($this->combos_1); ?>
    </div>
</div>

<?php echo $this->form->user_id; ?>
<?php echo $this->form->office_id_edit; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->tehsil_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->warehouse_users_id_edit; ?>

