<style>
    td {word-wrap: break-word}
</style>


<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Edit Profile") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("User Name will display here") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form method="POST" name="search" action="" >
                            <img src="<?php echo $this->baseUrl(); ?>/images/user.png" alt="User Picture" class="left" width="100" style="border: 1px solid #E0E0E0   "/>
                            <p><a href="" class="btn-sm ">Upload Picture</a></p>
                            <!-- Row -->
                            
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("User Name"); ?></label>
                                        <div class="controls">
                                            <input id="name" class="form-control" type="text" value="" name="name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Designation"); ?></label>
                                        <div class="controls">
                                            <input id="designation" class="form-control" type="text" value="" name="designation">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Department"); ?></label>
                                        <div class="controls">
                                            <input id="department" class="form-control" type="text" value="" name="department">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Email"); ?></label>
                                        <div class="controls">
                                            <input id="email" class="form-control" type="text" value="" name="email">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Mobile Number"); ?></label>
                                        <div class="controls">
                                            <input id="mobile" class="form-control" type="text" value="" name="mobile">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Phone Number"); ?></label>
                                        <div class="controls">
                                            <input id="phone" class="form-control" type="text" value="" name="phone">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Address"); ?></label>
                                        <div class="controls">
                                            <input id="address" class="form-control" type="text" value="" name="address">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                
                                <div class="col-md-12 right">
                                    <label class="control-label">&nbsp;</label>  
                                    <div class="controls">
                                        <button class="btn btn-primary" type="submit" name="save">
                                            <?php echo $this->translate("Save"); ?>
                                        </button>
                                        <button  class="btn btn-info" id="reset" type="reset">
                                            <?php echo $this->translate("Reset"); ?>
                                        </button>
                                    </div>
                                </div>
                                
                               
                            </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
<!-- // Content END -->
