<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Inventory Users ") ?> </h3>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Users Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <?php echo $this->usersCombo($this->combos, $this->combos_1); ?>
                                            <?php echo $this->form->province_id; ?>
                                            <?php echo $this->form->district_id; ?>
                                            <?php echo $this->form->tehsil_id; ?>
                                            <?php echo $this->form->parent_id; ?>

                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group" style="margin-top: 10px;">
                                                    <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                    <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Users List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#add-store"><?php echo $this->translate("Add User") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'user_name' => 'UserName',
                                            'Uc' => 'UC',
                                            'district' => 'District',
                                            'province' => 'Province'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row['loginId']; ?></td>
                                                        <td><?php echo $row['Parent']; ?></td>
                                                        <td><?php echo $row['districtName']; ?></td>
                                                        <td><?php echo $row['ProvinceName']; ?></td>
                                                        <td><a itemid="<?php echo $row['pkId']; ?>" class="btn update-stores btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-stores"><?php echo $this->translate("Edit") ?></a>
                                                            <?php if($row['role']==6 || $row['role']==21) { ?>
                                                            <a itemid="<?php echo $row['pkId']; ?>" class="btn update-role btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-role"><?php echo $this->translate("Role") ?></a>
                                                            <?php  } ?>
                                                        </td> 
                                                        <?php //if ($this->userDelete($row['pkId'])) { ?>
                                                        <?php //} else { ?>
                                                         <!-- <a data-toggle="notyfy" data-bind="<?php echo $row['pkId']; ?>" data-type="confirm" data-layout="top" class="btn-link btn-danger btn-mini"><?php echo $this->translate("Delete"); ?>
                                                             </a> -!>
                                                        <?php // } ?>                                                     
                                                        <!-- // Table row END --><?php
                                                        $i++;
                                                    endforeach;
                                                endif;
                                                ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml'); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-users/add-inventory" id="add-stores">
            <div class="modal fade" id="add-store" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Add User</h3>
                        </div>
                        <div class="modal-body">

                            <div class="row">
                                <div class="col-md-12">

                                    <div class="col-md-6">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("UserName"); ?></label><span class="red">*</span>
                                            <div class="controls">
                                                <?php echo $this->form->user_name_add; ?>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Email"); ?></label><span class="red">*</span>
                                            <div class="controls">
                                                <?php echo $this->form->email; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Phone"); ?></label><span class="red">*</span>
                                            <div class="controls">
                                                <?php echo $this->form->phone; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Password"); ?></label><span class="red">*</span>
                                            <div class="controls">
                                                <?php echo $this->form->password; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Confirm Password"); ?></label><span class="red">*</span>
                                            <div class="controls">
                                                <?php echo $this->form->confirm_password; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo $this->usersAddCombo($this->combos_1); ?>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group ">
                                            <label class="control-label" ><?php echo $this->translate("Default Store"); ?></label>
                                            <?php echo $this->form->default_warehouse; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--                        <div class="modal-body">
                                                    <div class="row">
                                                        <div class="col-md-12">
                        <?php echo $this->usersAddCombo($this->combos_1); ?>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="col-md-3">
                                                                <div class="form-group ">
                                                                    <label class="control-label" ><?php echo $this->translate("Default Store"); ?></label>
                        <?php echo $this->form->default_warehouse; ?>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group ">
                                                                    <label class="control-label" ><?php echo $this->translate("UserName"); ?></label>
                        <?php //echo $this->form->user_name_add; ?>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group ">
                                                                    <label class="control-label" ><?php echo $this->translate("Password"); ?></label>
                        <?php //echo $this->form->password; ?>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="form-group ">
                                                                    <label class="control-label" ><?php echo $this->translate("Confirm Password"); ?></label>
                        <?php //echo $this->form->confirm_password; ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                        
                                                </div>-->
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>

            </div>
        </form>



        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-users/add-inventory" id="add-stores">
            <div class="modal fade" id="add-store" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Add User</h3>
                        </div>

                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo $this->usersAddCombo($this->combos_1); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label" ><?php echo $this->translate("Default Store"); ?></label>
                                            <?php echo $this->form->default_warehouse; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label" ><?php echo $this->translate("UserName"); ?></label>
                                            <?php echo $this->form->user_name_add; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label" ><?php echo $this->translate("Password"); ?></label>
                                            <?php echo $this->form->password; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label" ><?php echo $this->translate("Confirm Password"); ?></label>
                                            <?php echo $this->form->confirm_password; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>

            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-users/update-inventory" id="update-stores">
            <div class="modal fade" id="modal-update-stores">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Users</h3>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-users/update-inventory-role" id="update-stores">
            <div class="modal fade" id="modal-update-role">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Role</h3>
                        </div>

                        <div class="modal-body" id="modal-body-contents1">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>   

    </div>
</div>
<!-- // Content END -->
