<style>
    .custom_width{
        overflow: hidden;
        width: 100px;
    }
</style>

<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("User Login Log") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("User Login Log") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php if ($this->result && count($this->result) > 0) { ?>

                                    <table class="table table-striped table-bordered table-condensed" id="sample_2">
                                        <!-- Table heading -->
                                        <thead>
                                            <tr>
                                                <th>
                                                    <?php echo $this->translate("S.No"); ?>
                                                </th>

                                                <th>
                                                    <?php echo $this->translate("Last Loggin Date"); ?>
                                                </th>

                                                <th>
                                                    <?php echo $this->translate("User Name"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Login Id"); ?>
                                                </th>
                                                                                               <th>
                                                    <?php echo $this->m . $this->translate("IP Address"); ?>
                                                </th>
                                            </tr>


                                        </thead>
                                        <!-- // Table heading END -->

                                        <!-- Table body -->
                                        <tbody>

                                            <!-- Table row -->
                                            <?php
                                            $j = 1;
                                            foreach ($this->result as $row) {
                                                ?>
                                                <tr class="dynamic-rows">
                                                    <td class="serial" style="font-size:12px" align="center">
                                                        <?php echo $j; ?>
                                                    </td>
                                                    <td style="font-size:12px;" align="center" nowrap>
                                                        <?php echo date("d/m/Y", strtotime($row['last_loggedin_at'])); ?>
                                                    </td>
                                                    <td style="font-size:12px" nowrap>
                                                        <?php echo $row['user_name'] ?>
                                                    </td>
                                                    <td style="font-size:12px" nowrap align="left">
                                                        <?php echo $row['login_id'] ?>
                                                    </td>
                                                    <td style="font-size:12px"  align="left">
                                                        <?php echo $row['ip_address'] ?>
                                                    </td>

                                                </tr>
                                                <?php
                                                $j ++;
                                            }
                                            ?>
                                            <!-- // Table row END -->
                                        </tbody>
                                        <!-- // Table body END -->                                      

                                    </table>


                                <?php } ?>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- // Content END -->

