<style>
    .form-group{
        padding-top:  18px;
    }
    textarea {
        resize: none;
    }
</style>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">


        <div class="col-md-4 col-md-offset-4 ">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i>Change Password
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php
                    if (isset($_GET['e']) && $_GET['e'] == 1) {
                        echo "<p style=\"color:green\">" . $this->translate("Password successfully changed") . "</p>";
                    }
                    ?>
                    <form id="form1" name="form1" method="post" action="">


                        <div class="form-group">
                            <label for="old_pass" class="col-md-3 control-label">
                                <?php echo $this->translate("Old Password"); ?><span class="red">*</span>
                            </label>
                            <div class="col-md-9">
                                <input type="password" name="old_pass" id="old_pass" class="form-control input-sm input-medium" />
                            </div>
                        </div>
                        <br>

                        <div class="form-group">
                            <label for="new_pass" class="col-md-3 control-label">
                                <?php echo $this->translate("New Password"); ?><span class="red">*</span>
                            </label>
                            <div class="col-md-9">
                                <input type="password" name="new_pass" id="new_pass" class="form-control input-sm input-medium" />
                            </div>
                        </div>
                        <br>

                        <div class="form-group">
                            <label for="confirm_pas" class="col-md-3 control-label">
                                <?php echo $this->translate("Confirm Password"); ?><span class="red">*</span>
                            </label>
                            <div class="col-md-9">
                                <input type="password" name="confirm_pas" id="confirm_pas" class="form-control input-sm input-medium" />
                            </div>
                        </div>
                        <br>


                        <div class="form-group">
                            <div class="input-group pull-right margin-right-10">
                                <input type="submit" name="Submit" id="Submit" value="<?php echo $this->translate("Change Password"); ?>" class="btn input-sm green" />
                            </div>
                        </div>
                        <br>



                    </form>
                </div>
            </div>
            <p class="center">
                <a href="<?php echo $this->baseUrl(); ?>/docs/project-doc">Back to Documentation</a>
            </p>
        </div>

    </div>
</div>


