<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN CONTENT -->
    <div class=" page-content-wrapper">
        <div class="page-content landing-content">
            <br/>
            <div class="col-md-12 "> 
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-folder"></i>Release Notes
                        </div>
                    </div>
                    <div class="portlet-body">
                        
                       
                          
                                <div class="row">
                                    <div class="col-md-10 " style="height: 300px;">
                                        <table class="" >
                                            <tbody>
                                                
                                                    <tr>
                                                       
                                                        <td ><h4>vLMIS Release Notes 2.5</h4></td>
                                                        <td style="padding-left: 100px;"><a class="btn btn-primary input-sm green" target="_blank"
                                                                                href="http://lmis.gov.pk/release_notes/vLMIS_Release_Notes_v2.5.pdf">Download</a></td>
                                                    </tr>
                                                  
                                            </tbody>
                                        </table>
                                    </div>
                                </div> 
                         
                        <div class="clearfix margin-bottom-20">
                        </div>                       

                    </div>
                </div>
            </div>
            <!-- BEGIN  PATNERS -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="tab-content stake-holder">stakeholders</div>
                    <div style="float:right; padding-top: 35px; padding-right: 20px;"><img src="<?php echo $this->baseUrl(); ?>/images/usa-delivered-logo.png" alt=""/></div>
                    <ul class="nav nav-tabs stake-holder-list">
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/govt-of-pak-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/unicef-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/us-aid-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/who-logo.png" alt=""/></li>
                    </ul>                    
                </div>
            </div>
            <!-- END PATNERS -->
        </div></div>