<?php
/**
*  phtml for Training Manuals
*/
?>
<!-- Tabs -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-10 ">
                <table class="table table-hover" >
                    <tbody>
                        <tr>
                            <td><h4>1</h4></td>
                            <td class="doc-title"><h4>Vaccines Logistics Manual Cold chain - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Download</a></td>
                        </tr>
                        <tr>
                            <td><h4>2</h4></td>
                            <td class="doc-title"><h4>vLMIS Administrators Manual - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_-_administrators_manual_updated.pdf">Download</a></td>
                        </tr>
                        <tr>
                            <td><h4>3</h4></td>
                            <td class="doc-title"><h4>vLMIS Facilitators Manual - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">Download</a></td>
                        </tr>
                        <tr>
                            <td><h4>4</h4></td>
                            <td class="doc-title"><h4>vLMIS Participants Guide - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">Download</a></td>
                        </tr>
                        <tr>
                            <td><h4>5</h4></td>
                            <td class="doc-title"><h4>vLMIS TOT Manual - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">Download</a></td>
                        </tr>
                        <tr>
                            <td><h4>6</h4></td>
                            <td class="doc-title"><h4>vLMIS User Manual - Cold Chain - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_updated.pdf">Download</a></td>
                        </tr>
                        <tr>
                            <td><h4>7</h4></td>
                            <td class="doc-title"><h4>vLMIS User Manual - Updated</h4></td>
                            <td class="doc-link"><a class="btn btn-primary input-sm btn-download" target="_blank"
                                                    href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_updated.pdf">Download</a></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>