</div>
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

<!-- // Footer END -->
</div>
<!--<div id="footer" class="hidden-print">
    <div class="row-fluid">

        <div class="col-md-8">
            <div class="row-fluid row-menu">
                <div class="col-md-3">
                    <ul class="unstyled">
                        <li>
                            <h4>Get Help</h4>
                            <ul class="unstyled">
                                <li><a href="#">Documentation</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <ul class="unstyled">
                        <li>
                            <h4>My account</h4>
                            <ul class="unstyled">
                                <li><a href="#">Edit account</a></li>
                                <li><a href="<?php echo $this->baseUrl(); ?>/index/change-password">Change password</a></li>
                                <li><a href="<?php echo $this->baseUrl(); ?>/index/logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </div>
        </div>

        <div class="col-md-4">
            <div class="right innerAll">
                <p>If you have any problems using <strong>vLMIS</strong> or you have any suggestions or requests, please contact us. We appreciate all your feedback.</p>
                <a class="btn btn-primary btn-icon glyphicons envelope" href="#"><i></i> Contact Support</a>
            </div>
        </div>
    </div>

    <div class="separator bottom"></div>

    <div class="copy">&copy; 2014 - <?php //echo date("Y"); ?> - <a href="#">Vaccine Logistics Management System</a> - All Rights Reserved.</div>-->


    <!--  End Copyright Line
</div>-->
<!-- BEGIN FOOTER -->
<div class="row m-l-r-zero">
    <div class="col-md-12 footer-stackholders">
        <span class="stackholders">Stakeholders</span>
    </div>
    <div class="col-md-12 bg-white" >
        <ul class="nav navbar-nav partners">
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/govt-of-pak-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/unicef-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/us-aid-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/who-logo.png" alt=""/></li>
        </ul>
        <div style="float:right; padding-top: 35px; padding-right: 20px;"><img src="<?php echo $this->baseUrl(); ?>/images/usa-delivered-logo.png" alt=""/></div>
    </div>
</div>

<div class="alert alert-error ">
    <div class="footer-inner">
         The presented analysis and reports are based on online reported storage and consumption data entered by > 500 trained vLMIS operators (vaccinators and store keepers) of EPI program at the national, provinical, district and EPI center levels.
    </div>
</div>

<div class="footer">
    <div class="footer-inner">
        For any comments and suggestions please write to <a href="mailto:support@lmis.gov.pk">support@lmis.gov.pk</a>        
   <a  href="http://lmis.gov.pk" style="color:white; padding-left: 700px;">
                 http://lmis.gov.pk
                </a>
                    
    </div>
    <div class="footer-tools">
		<span class="go-top">
			<i class="fa fa-angle-up"></i>
		</span>
    </div>
</div>
<!-- END FOOTER -->

<!-- // Main Container Fluid END -->
<!-- JQuery-->
<!--<![if !IE]>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery.min.js"></script>
<![endif]-->
<!-- JQueryUI-->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/jquery-validation/dist/jquery.validate.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/modernizr.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/notifications/notyfy/jquery.notyfy.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.price_format.1.8.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.inlineEdit.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.mask.min.js"></script>
<!-- jQuery 1.10.2
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>-->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip-->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/data-tables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/jquery-notific8/jquery.notific8.min.js"></script>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/core/app.js" type="text/javascript"></script>
<!-- -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/custom/date-uk.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/custom/table-advanced.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/admin/pages/scripts/ui-notific8.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.floatThead.min.js"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        Metronic.init();        
        TableAdvanced.init();
        UINotific8.init();
    });
</script>
<!-- END JAVASCRIPTS -->

<?php echo $this->inlineScript(); ?>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-48587374-1', 'auto');
  ga('send', 'pageview');
</script>

</body>
</html>