</div>
<br>
<div style="margin-left: 200px; text-align: justify; text-justify: inter-word;">
    <ul>
        <li>
            <b> Average Monthly Consumption(AMC):</b> Average Monthly Consumption is calculated as average of aggregated consumption of the last three non-zero consumption months of vaccines and related products.
        </li>
        <li>
            <b> Months of Stock(MOS):</b> Months of Stock is the estimate of number of months the stock will last. This obtains by dividing Stock of Hand by average monthly consumption.
        </li>
        <li>
            <b>Stock on Hand(SOH):</b> Stock on Hand is the amount of product on hand in order to monitor stock positions and anticipate stock outs in advance.
        </li>

        For more acronyms <a href="<?php echo $this->baseUrl() ?>/index/acronyms">Click Here</a>

    </ul>
</div>
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

<!-- // Footer END -->
</div>
<div class="row">
    <div class="col-md-12 footer-stackholders">
        <span class="stackholders">Stakeholders</span>
    </div>
    <div class="col-md-12 bg-white" >
        <ul class="nav navbar-nav partners">
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/govt-of-pak-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/unicef-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/us-aid-logo.png" alt=""/></li>
            <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/who-logo.png" alt=""/></li>
        </ul>
    </div>
</div>

<div class="alert alert-error ">
    <div class="footer-inner">
        The presented analysis and reports are based on online reported storage and consumption data entered by > 500 trained vLMIS operators (vaccinators and store keepers) of EPI program at the national, provinical, district and EPI center levels.
    </div>
</div>

<div class="footer">
    <div class="footer-inner">
<!--        &copy; 2014 - <?php //echo date("Y");    ?> - <a href="#">Vaccine Logistics Management System</a> - All Rights Reserved.-->
        For any comments and suggestions please write to support@lmis.gov.pk
        <a  href="http://lmis.gov.pk" style="color:white; padding-left: 700px;">
            http://lmis.gov.pk
        </a>

    </div>
    <div class="footer-tools">
        <span class="go-top">
            <i class="fa fa-angle-up"></i>
        </span>
    </div>
</div>

<!-- // Main Container Fluid END -->
<!-- JQuery
<script src="<?php // echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery.min.js"></script>-->
<!--
<script src="<?php //echo $this->baseUrl(); ?>/common/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>-->
<!-- JQueryUI -->
<!--<script src="<?php //echo $this->baseUrl();  ?>/common/theme/scripts/plugins/system/jquery-ui/js/jquery-ui-1.9.2.custom.min.js"></script>
 JQueryUI Touch Punch 
<script src="<?php //echo $this->baseUrl();  ?>/common/theme/scripts/plugins/forms/jquery-validation/dist/jquery.validate.js"></script>
 small hack that enables the use of touch events on sites using the jQuery UI user interface library 
<script src="<?php //echo $this->baseUrl();  ?>/common/theme/scripts/plugins/system/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>-->
<!-- Modernizr -->
<!--<script src="<?php // echo $this->baseUrl();  ?>/common/theme/scripts/plugins/system/modernizr.js"></script>-->
<!-- Bootstrap
<script src="<?php //echo $this->baseUrl();  ?>/common/bootstrap/js/bootstrap.min.js"></script>-->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<!-- SlimScroll Plugin -->
<!--<script  src="<?php //echo $this->baseUrl();  ?>/common/theme/scripts/plugins/other/jquery-slimScroll/jquery.slimscroll.min.js"></script>-->
<!--<script src="<?php //echo  $this->baseUrl();  ?>/common/theme/scripts/plugins/forms/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>-->
<!-- Tables Demo Script 
<script src="<?php // echo $this->baseUrl();   ?>/common/theme/scripts/demo/tables.js"></script>-->
<!-- Common Demo Script -->
<!--<script src="<?php //echo $this->baseUrl();  ?>/common/theme/scripts/demo/common.js?1369414385"></script>-->
<!-- Uniform Forms Plugin -->
<!--<script src="<?php // echo $this->baseUrl();  ?>/common/theme/scripts/plugins/forms/pixelmatrix-uniform/jquery.uniform.min.js"></script>-->
<!-- PrettyPhoto -->
<!--<script  src="<?php // echo $this->baseUrl();   ?>/common/theme/scripts/plugins/gallery/prettyphoto/js/jquery.prettyPhoto.js"></script>-->
<!-- DataTables Tables Plugin -->
<!--<script src="<?php //echo $this->baseUrl();   ?>/common/theme/scripts/plugins/tables/DataTables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php //echo $this->baseUrl();   ?>/common/theme/scripts/plugins/tables/DataTables/media/js/DT_bootstrap.js"></script>-->
<!-- <script src="<?php // echo $this->baseUrl();   ?>/plmis_js/jquery.price_format.1.8.min.js"></script> -->

<!--<script src="<?php // echo $this->baseUrl();   ?>/common/theme/scripts/plugins/notifications/notyfy/jquery.notyfy.js"></script>
<script src="<?php // echo $this->baseUrl();   ?>/js/jquery.price_format.1.8.min.js"></script>
<script src="<?php // echo $this->baseUrl();   ?>/js/jquery.inlineEdit.js"></script>
<script src="<?php // echo $this->baseUrl();   ?>/js/jquery.mask.min.js"></script>-->


<!-- Column Filter Widget
<script src="<?php // echo $this->baseUrl();   ?>/common/theme/scripts/demo/ColumnFilterWidgets.js"></script>
 Column Table Tools
<script src="<?php //echo $this->baseUrl();   ?>/common/theme/scripts/plugins/tables/DataTables/extras/TableTools/media/js/TableTools.js"></script>
 Column Table Tools min
<script src="<?php //echo $this->baseUrl();   ?>/common/theme/scripts/plugins/tables/DataTables/extras/TableTools/media/js/TableTools.min.js"></script>
 Column Table Tools zero Clipboard
<script src="<?php //echo $this->baseUrl();   ?>/common/theme/scripts/plugins/tables/DataTables/extras/TableTools/media/js/ZeroClipboard.js"></script>
 jQuery cookie plugin
<script src="<?php //echo $this->baseUrl();   ?>/common/theme/scripts/plugins/system/jquery.cookie.js"></script>-->

<!--
 *******************
 *******************
 Testing
 ******************
 ******************
-->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/core/app.js"></script>
<script>
    jQuery(document).ready(function() {
        App.init();
    });
</script>
<!-- END JAVASCRIPTS -->

<?php echo $this->inlineScript(); ?>

<script>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-48587374-1', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>

