<div class="header-wrapper">
    <div class="header-inner">
        <img src="images/lmis-logo.png" alt="LMIS" class="left" />
        <ul class="nav dropdown">
            <li><a href="index.php">Home</a></li>
            <li>|</li>
            <li class="sub_menu_list">
                <a href="inner.html">Resources <span class="down-arrow"></span></a>
                <ul class="sub_menu">
                    <li><a href="#">Publications</a></li>
                    <li><a href="#">Tools</a></li>
                    <li><a href="#">Links</a></li>
                    <li><a href="#">Acronyms</a></li>
                </ul>
            </li>
            <li>|</li>
            <li><a href="contactus.php">Contact Us</a></li>
            <li>|</li>
            <li><a href="faqs.php">FAQs</a></li>
        </ul>
    </div>
</div>