<!DOCTYPE html>

<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.1.1
Version: 2.0.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8"/>
        <title>Vaccine| LMIS</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <!-- BEGIN GLOBAL MANDATORY STYLES DONE-->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/fonts/custom.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        
        <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>

        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/custom.css" rel="stylesheet" type="text/css"/>
        <!-- END THEME STYLES -->

    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <body class="page-header-fixed">
        <!-- BEGIN HEADER -->
        <div class="header navbar navbar-fixed-top bgImg">
            <!-- BEGIN TOP NAVIGATION BAR -->
            <div class="header-inner ">
                <!-- BEGIN LOGO -->
                <a class="navbar-brand" href="#" style="margin-top: 5px;">
                    <img src="<?php echo $this->baseUrl(); ?>/images/epi_logo_header.png" height="55" width="323" alt="EPI MIS" />
                </a>
                <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/landing-images/vaccine-logo.png" height="63" width="327" alt="vaccine LMIS" />
                </a>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/menu-toggler.png" alt=""/>
                </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
            </div>
            <!-- END TOP NAVIGATION BAR -->
        </div>
        <!-- START SUB HEADER -->
        <div class="header-menu">
            <!-- BEGIN TOP NAVIGATION BAR -->
            <div class="header-inner headergreen">
                <a href="<?php echo $this->baseUrl(); ?>/index/faqs"><button type="button" class="btn btn-lg btn-primary pull-right btn-head-grey">FAQs</button></a>
                <a href="<?php echo $this->baseUrl(); ?>/index/contact-us"><button type="button" class="btn btn-lg btn-primary pull-right btn-head-blue">Contact Us</button></a>
                <a href="<?php echo $this->baseUrl(); ?>/"><span class="btn btn-lg btn-primary pull-right btn-head-green disabled">Vaccine</span></a>
            </div>
            <!-- END TOP NAVIGATION BAR -->
        </div>
        <!-- END HEADER -->
        <div class="clearfix">
        </div>
        <?php echo $this->layout()->content; ?>
        <!-- BEGIN FOOTER -->    
        <div class="footer">
            <div class="footer-inner">
                For any comments and suggestions please write to <a href="mailto:support@lmis.gov.pk" style="color:white;">support@lmis.gov.pk</a>
                
                <a  href="http://lmis.gov.pk" style="color:white; padding-left: 700px;">
                 http://lmis.gov.pk
                </a>
                    
            </div>
            <div class="footer-tools">
                <span class="go-top">
                    <i class="fa fa-angle-up"></i>
                </span>
            </div>
        </div>
        <!-- END FOOTER -->
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <!--[if lt IE 9]>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/respond.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/excanvas.min.js"></script> 
        <![endif]-->
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <!-- END JAVASCRIPTS -->
        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-48587374-1', 'auto');
  ga('send', 'pageview');
</script>
    </body>
    <!-- END BODY -->
</html>