<!-- BEGIN SIDEBAR -->

    <div class="page-sidebar navbar-collapse collapse">
    <!-- add "navbar-no-scroll" class to disable the scrolling of the sidebar menu -->
        <!-- BEGIN SIDEBAR MENU -->
        <?php //$page = $this->navigation()->findOneByLabel('Stock Receive (Supplier)'); ?>
        <?php //$this->navigation()->removePage($page); ?>
        <?php echo $this->navigation()->menu(); ?>
        <!-- END SIDEBAR MENU -->
    </div>
</div>
<!-- END SIDEBAR -->
<!-- Sidebar Menu
<div id="menu" class="hidden-phone hidden-print">
    <div class="slim-scroll" data-scroll-height="800px">
        <span class="profile">
            <a class="img" href="<?php //echo $this->baseUrl(); ?>/dashboard/">
                <img src="<?php //echo $this->baseUrl(); ?>/images/gop.png" alt="gop logo" />
            </a>
            <span>
                <strong>
                    <?php //echo $this->translate("Welcome"); ?>
                </strong>
                <a href="#" class="glyphicons right_arrow">
                    <?php //echo $this->layout()->user_name; ?>
                    <i></i>
                </a>
            </span>
        </span>
        <?php //$page = $this->navigation()->findOneByLabel('Stock Receive (Supplier)'); ?>
        <?php //$this->navigation()->removePage($page); ?>
        <?php //echo $this->navigation()->menu(); ?>
        
        <div class="clearfix"></div>
        <div class="separator bottom"></div>
    </div>
</div>-->
<!-- // Sidebar Menu END -->
