<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("CCEM Graphs") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate($this->main_heading) ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row margin-top-10 margin-bottom-10">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="gen-chart-render form-btn-margin-top">
                                    <?php
                                    FC_SetRenderer('javascript');
                                    echo renderChart($this->baseUrl() . "/FusionCharts/Charts/" . $this->chart_type . ".swf", "", $this->xmlstore, 'chartContainer', $this->width, $this->height, false, false);
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- // Content END -->
