CcmStatusHistory:
  type: entity
  table: ccm_status_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    temperatureAlarm:
      type: integer
      unsigned: false
      nullable: true
      column: temperature_alarm
    workingQuantity:
      type: integer
      unsigned: false
      nullable: true
      column: working_quantity
    comments:
      type: text
      nullable: true
    statusDate:
      type: datetime
      nullable: true
      column: status_date
    ccmStatusListId:
      type: integer
      unsigned: false
      nullable: true
      column: ccm_status_list_id
    ccmAssetTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: ccm_asset_type_id
    reasonId:
      type: integer
      unsigned: false
      nullable: true
      column: reason_id
    utilizationId:
      type: integer
      unsigned: false
      nullable: true
      column: utilization_id
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    ccm:
      targetEntity: ColdChain
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
