CcmVehicles:
  type: entity
  table: ccm_vehicles
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    registrationNo:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: registration_no
    usedForEpi:
      type: integer
      unsigned: false
      nullable: true
      column: used_for_epi
    comments:
      type: text
      nullable: true
    ccmId:
      type: integer
      unsigned: false
      nullable: true
      column: ccm_id
    ccmAssetSubTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: ccm_asset_sub_type_id
    fuelTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: fuel_type_id
    createdBy:
      type: integer
      unsigned: false
      nullable: false
      column: created_by
    createdDate:
      type: datetime
      nullable: false
      column: created_date
    modifiedBy:
      type: integer
      unsigned: false
      nullable: true
      column: modified_by
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  lifecycleCallbacks: {  }
