ContactUs:
  type: entity
  table: contact_us
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 100
      fixed: false
      nullable: false
    email:
      type: string
      length: 100
      fixed: false
      nullable: false
    phone:
      type: string
      length: 50
      fixed: false
      nullable: false
    department:
      type: string
      length: 50
      fixed: false
      nullable: true
    message:
      type: text
      nullable: false
  lifecycleCallbacks: {  }
