Documents:
  type: entity
  table: documents
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    docTitle:
      type: string
      length: 200
      fixed: false
      nullable: true
      column: doc_title
    docPath:
      type: string
      length: 1000
      fixed: false
      nullable: true
      column: doc_path
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    docCategory:
      targetEntity: DocumentCategories
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        doc_category_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
