PhysicalStockTaking:
  type: entity
  table: physical_stock_taking
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    fromDate:
      type: datetime
      nullable: true
      column: from_date
    toDate:
      type: datetime
      nullable: true
      column: to_date
    description:
      type: text
      nullable: true
    remarks:
      type: string
      length: 255
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
