PipelineConsignmentsCopy:
  type: entity
  table: pipeline_consignments_copy
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    voucherNumber:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: voucher_number
    transactionCounter:
      type: integer
      unsigned: false
      nullable: true
      column: transaction_counter
    expectedArrivalDate:
      type: datetime
      nullable: true
      column: expected_arrival_date
    referenceNumber:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: reference_number
    stakeholderActivityId:
      type: integer
      unsigned: false
      nullable: true
      column: stakeholder_activity_id
    description:
      type: text
      nullable: true
    itemPackSizeId:
      type: integer
      unsigned: false
      nullable: true
      column: item_pack_size_id
    batchNumber:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: batch_number
    productionDate:
      type: datetime
      nullable: true
      column: production_date
    expiryDate:
      type: datetime
      nullable: true
      column: expiry_date
    manufacturerId:
      type: integer
      unsigned: false
      nullable: true
      column: manufacturer_id
    vvmTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: vvm_type_id
    unitPrice:
      type: float
      nullable: true
      column: unit_price
    quantity:
      type: integer
      unsigned: false
      nullable: false
    receivedQuantity:
      type: integer
      unsigned: false
      nullable: true
      column: received_quantity
    fromWarehouseId:
      type: integer
      unsigned: false
      nullable: false
      column: from_warehouse_id
    toWarehouseId:
      type: integer
      unsigned: false
      nullable: false
      column: to_warehouse_id
    createdBy:
      type: integer
      unsigned: false
      nullable: false
      column: created_by
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    masterId:
      type: integer
      unsigned: false
      nullable: true
      column: master_id
    status:
      type: string
      length: null
      fixed: false
      nullable: true
    batchId:
      type: integer
      unsigned: false
      nullable: true
      column: batch_id
    transactionType:
      type: integer
      unsigned: false
      nullable: true
      column: transaction_type
  lifecycleCallbacks: {  }
