StockMasterHistory:
  type: entity
  table: stock_master_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    masterId:
      type: integer
      unsigned: false
      nullable: false
      column: master_id
    transactionDate:
      type: datetime
      nullable: true
      column: transaction_date
    transactionNumber:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: transaction_number
    transactionCounter:
      type: integer
      unsigned: false
      nullable: true
      column: transaction_counter
    transactionReference:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: transaction_reference
    draft:
      type: boolean
      nullable: true
    comments:
      type: text
      nullable: true
    transactionTypeId:
      type: integer
      unsigned: false
      nullable: false
      column: transaction_type_id
    fromWarehouseId:
      type: integer
      unsigned: false
      nullable: false
      column: from_warehouse_id
    toWarehouseId:
      type: integer
      unsigned: false
      nullable: false
      column: to_warehouse_id
    parentId:
      type: integer
      unsigned: false
      nullable: false
      column: parent_id
    campaignId:
      type: integer
      unsigned: false
      nullable: true
      column: campaign_id
    stakeholderActivityId:
      type: integer
      unsigned: false
      nullable: true
      column: stakeholder_activity_id
    createdBy:
      type: integer
      unsigned: false
      nullable: false
      column: created_by
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    actionType:
      type: boolean
      nullable: false
      column: action_type
    modifiedBy:
      type: integer
      unsigned: false
      nullable: false
      column: modified_by
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  lifecycleCallbacks: {  }
