TransactionTypes:
  type: entity
  table: transaction_types
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    transactionTypeName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: transaction_type_name
    nature:
      type: string
      length: 1
      fixed: false
      nullable: true
    isAdjustment:
      type: boolean
      nullable: true
      column: is_adjustment
    status:
      type: boolean
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
