WarehousePopulation:
  type: entity
  table: warehouse_population
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    facilityTotalPouplation:
      type: integer
      unsigned: false
      nullable: true
      column: facility_total_pouplation
    liveBirthsPerYear:
      type: integer
      unsigned: false
      nullable: true
      column: live_births_per_year
    pregnantWomenPerYear:
      type: integer
      unsigned: false
      nullable: true
      column: pregnant_women_per_year
    womenOfChildBearingAge:
      type: integer
      unsigned: false
      nullable: true
      column: women_of_child_bearing_age
    survivingChildren011:
      type: integer
      unsigned: false
      nullable: true
      column: surviving_children_0_11
    childrenAged1223:
      type: integer
      unsigned: false
      nullable: true
      column: children_aged_12_23
    above2Year:
      type: integer
      unsigned: false
      nullable: true
      column: above_2_year
    estimationYear:
      type: datetime
      nullable: true
      column: estimation_year
    requirments4degree:
      type: float
      nullable: true
      column: requirments_4degree
    requirments20degree:
      type: float
      nullable: true
      column: requirments_20degree
    capacity4degree:
      type: float
      nullable: true
      column: capacity_4degree
    capacity20degree:
      type: float
      nullable: true
      column: capacity_20degree
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
