<?php

/**
 * Model_CcmStatusList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Cold Chain
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_CcmStatusList extends Model_Base {

    private $_table;
    
   const WORKINGWELL = 1;
   const NEEDSMAINTENANCE = 2;
   const NOTWORKING = 3; 
   
   public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('CcmStatusList');
    }

    public function getStatusLists() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("csl.pkId,csl.ccmStatusListName")
                ->from('CcmStatusList', 'csl')
                ->where("csl.type =".Model_CcmStatusList::WORKINGWELL."");
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }

    public function getAllReasons() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("csl.pkId,csl.ccmStatusListName")
                ->from('CcmStatusList', 'csl')
                ->where("csl.type = ".Model_CcmStatusList::NEEDSMAINTENANCE."");
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }
    
     public function getAllUtilizations() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("csl.pkId,csl.ccmStatusListName")
                ->from('CcmStatusList', 'csl')
                ->where("csl.type = ".Model_CcmStatusList::NOTWORKING."");
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }
    
    
     public function getAllStatusLists($order = null, $sort = null) {
      
       
        $str_sql = $this->_em->createQueryBuilder()
                ->select("sl.pkId,sl.ccmStatusListName,sl.type,sl.status,u.userName")
                ->from('CcmStatusList', 'sl')
                ->join('sl.createdBy', 'u');
        if (!empty($this->form_values['ccmStatusListName'])) {
            $str_sql->where("sl.ccmStatusListName = '".$this->form_values['ccmStatusListName']."'  ");
        }
        
        if ( $this->form_values['status'] =='1') {
            $str_sql->where("sl.status = '1'  ");
        }
        if ( $this->form_values['status'] =='2') {
            $str_sql->where("sl.status = '0'  ");
        }
   
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return $row;
        } else {
            return false;
        }
    }


}
