<?php

/**
 * Model_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author    Hannan mehmood <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_Item extends Model_Base {

    public $item_pack_size_id;
    private $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Items');
    }

  

    public function getProductList() {
          $str_sql = $this->_em->createQueryBuilder()
                ->select("ips.pkId,  ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->ORDERBY("ips.listRank");
          return $row = $str_sql->getQuery()->getResult();
    }
    
    public function getProductByCategory() {
            $str_sql = $this->_em->createQueryBuilder()
                ->select("ips.pkId,  ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->where("ips.itemCategory IN (1,2)");
          return $row = $str_sql->getQuery()->getResult();
    }

    public function getAllItems() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("i.pkId, i.description")
                ->from("Items", "i");
        $row = $str_sql->getQuery()->getResult();

        return $row;
    }

}
