<?php

/**
 * Model_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author    Hannan mehmood <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_Item extends Model_Base {

    public $item_pack_size_id;
    private $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Items');
    }

    public function getUnitByItemId() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("iu.pkId, iu.itemUnitName, ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->join("ips.itemUnit", "iu")
                ->where("ips.pkId = " . $this->form_values['item_pack_size_id']);
        $row = $str_sql->getQuery()->getResult();
        if (!empty($row) && count($row) > 0) {
            return array(
                'id' => $row[0]['pkId'],
                'type' => $row[0]['itemUnitName']
            );
        } else {
            return FALSE;
        }
    }

    public function getProductList() {
          $str_sql = $this->_em->createQueryBuilder()
                ->select("ips.pkId,  ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->ORDERBY("ips.listRank");
          return $row = $str_sql->getQuery()->getResult();
    }
    
    public function getProductByCategory() {
            $str_sql = $this->_em->createQueryBuilder()
                ->select("ips.pkId,  ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->where("ips.itemCategory IN (1,2)");
          return $row = $str_sql->getQuery()->getResult();
    }

    public function getAllItems() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("i.pkId, i.description")
                ->from("Items", "i");
        $row = $str_sql->getQuery()->getResult();

        return $row;
    }

}
