<?php
/**
 *  phtml for Ajax Item Edit
 */
?>

<div class="row">
    <div class="col-md-5">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Geo Level Name"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->geo_level_name; ?>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Geo Level Description"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->geo_level_description; ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 margin-top-25">
        <div class="form-group" id="div_status">
            <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
            <?php echo $this->form->status; ?>
        </div>
    </div>
</div>
<?php
echo $this->form->geo_level_id;
echo $this->form->geo_level_name_hidden;
?>
