<?php
/**
 *  phtml for Geo Levels
 */
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Geo Levels") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Geo Level Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="form-body">
                            <form method="POST" name="country_search" action="" >
                                <!-- Row -->
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label" ><?php echo $this->translate("Geo Level Name"); ?></label>
                                            <?php echo $this->form->geo_level_name; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group" style="margin-top: 25px;">
                                            <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                            <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Geo Levels List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="dataTables_wrapper form-inline">
                            <div class="row">
                                <div class="col-md-3">

                                </div>
                                <div class="col-md-9">
                                    <div class="dataTables_filter">
                                        <label>
                                            <a class="btn btn-primary" data-toggle="modal" href="#add-geo-level"><?php echo $this->translate("Add Geo Level") ?></a>
                                        </label>
                                    </div>
                                </div>
                            </div>                            

                            <?php if ($this->result && count($this->result) > 0) { ?>
                                <table class="table table-striped table-bordered table-condensed" id="sample_2">
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th>
                                                <?php echo $this->translate("S.No"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Geo Level Name"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Geo Level Description"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Action"); ?>
                                            </th>
                                        </tr>
                                    </thead>
                                    <!-- // Table heading END -->

                                    <!-- Table body -->
                                    <tbody>
                                        <!-- Table row -->
                                        <?php
                                        $j = 1;
                                        foreach ($this->result as $row) {
                                            ?>
                                            <tr >
                                                <td >
                                                    <?php echo $j; ?>
                                                </td>
                                                <td >
                                                    <?php echo $row['geo_level_name']; ?>
                                                </td>
                                                <td >
                                                    <?php echo $row['description'] ?>
                                                </td>
                                                <td >
                                                    <a levelid="<?php echo $row['pk_id']; ?>" class="btn btn-update-geo-level btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-geo-level"><?php echo $this->translate("Edit") ?></a>
                                                    <?php if ($row['status'] == 1) { ?>
                                                        <a id="<?php echo $row['pk_id']; ?>" class="active btn-link btn-danger input-sm"><?php echo $this->translate("Active"); ?></a>
                                                    <?php } else { ?>
                                                        <a id="<?php echo $row['pk_id']; ?>" class="deactive btn-link btn-danger input-sm"><?php echo $this->translate("Deactive"); ?></a>
                                                    <?php } ?>
                                                </td>
                                            </tr>
                                            <?php
                                            $j ++;
                                        }
                                        ?>
                                        <!-- // Table row END -->
                                    </tbody>
                                    <!-- // Table body END -->                                      
                                </table>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-geo-levels/add-geo-level" id="form-add-geo-level">
            <div class="modal fade" id="add-geo-level" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Add Geo Level</h3>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Geo Level Name"); ?> <span class="red">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->form->geo_level_name; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Geo Level Description"); ?> <span class="red">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->form->geo_level_description; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 margin-top-25">
                                    <div class="form-group" id="div_status">
                                        <label class="control-label" ><?php echo $this->translate("Status"); ?></label>
                                        <?php echo $this->form->status; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary input-sm" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-geo-levels/update-geo-level" id="form-update-geo-level">
            <div class="modal fade" id="modal-update-geo-level" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Geo Level</h3>
                        </div>
                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer" id="update-button">
                            <input class="btn btn-primary input-sm" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->