<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Lists") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("List Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="batch_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="control-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Select List"); ?></label>
                                                    <div class="controls">
                                                        <?php echo $this->form->list_master; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="control-group ">
                                                    <label class="control-label" ><?php echo $this->translate("List Value"); ?></label>
                                                    <div class="controls">
                                                        <?php echo $this->form->list_value; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3 margin-top-25">
                                                <label class="control-label" >&nbsp;</label>
                                                <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Manage List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- Table -->
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#modal-add-user"><?php echo $this->translate("Add List Value") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'list_value' => 'List Value',
                                            'list_master' => 'List',
                                            'created_by' => 'Created By',
                                            'created_date' => 'Created Date'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    $created_date = $row->getCreatedDate()->format('Y-m-d H:i:s');
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row->getListValue(); ?></td>
                                                        <td><?php echo $row->getListMaster()->getListMasterName(); ?></td>
                                                        <td><?php echo $row->getCreatedBy()->getUsername(); ?></td>
                                                        <td><?php
                                                            if ($created_date != '-0001-11-30 00:00:00') {
                                                                echo $created_date;
                                                            } else {
                                                                echo '';
                                                            }
                                                            ?></td>
                                                        <td>
                                                            <a itemid="<?php echo $row->getPkId(); ?>" class="btn update-list btn-link btn-success btn-mini" data-toggle="modal" href="#modal-update-list"><?php echo $this->translate("Edit") ?></a>
                                                            <a data-bind="<?php echo $row->getPkId(); ?>" data-toggle="notyfy" data-type="confirm" data-layout="top" class="btn btn-danger btn-link btn-mini"><?php echo $this->translate("Delete") ?></a>
                                                        </td>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                                <!-- // Table END -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/cadmin/manage-lists/add" id="add-list">
            <div class="modal  fade" id="modal-add-user" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add List Value</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("Select List"); ?><span class="red">*</span></label>
                                        <?php echo $this->form_add->list_master; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("List Value"); ?><span class="red">*</span></label>
                                        <?php echo $this->form_add->list_value; ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" ><?php echo $this->translate("Description"); ?></label>
                                        <?php echo $this->form_add->description; ?>
                                    </div>
                                </div>

                            </div>

                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/cadmin/manage-lists/update" id="update-list">

            <div class="modal fade" id="modal-update-list" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit List Value</h4>
                        </div>
                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer" id="update-button">
                            <input class="btn btn-primary"  type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>
            </div>

        </form>

    </div>
</div>
<!-- // Content END -->
