
<?php
/**
 *  phtml for Reverse Logistics Report
 */
?>
<?php
$from_sel_month = $this->from_month_sel;
$from_sel_year = $this->from_year_sel;
$year = $this->year_sel;
$month = $this->month_sel;
$sel_prov = $this->prov_sel;
$sel_dist = $this->district_id;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$wh_type_1 = $this->wh_type_1;

// Headers of the Grid
$header = 'Sr.No., Received From,Product,Received Qty(Vials),Received Date';

$cspan = '#cspan,#cspan,#cspan,#cspan,#cspan';
$width = '50,*,150,150,150';
$ro = 'ro,ro,ro,ro,ro';


$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .= "<rows>";

$sum_arr = array();

$query = $this->reports()->reverseLogisticsReport($wh_type_1);
$j = 1;


foreach ($query as $row) {

    $location_id = $row['pk_id'];
    $data_arr[$location_id][] = $j;
    $data_arr[$location_id][] = $row['fwh'];
    $data_arr[$location_id][] = $row['item_name'];
    $data_arr[$location_id][] = $row['qty'];
    $data_arr[$location_id][] = $row['trans_date'];


    $j++;
}

$total_received_qty = 0;
foreach ($data_arr as $dis_id => $sub_arr) {

    $xml_store .= "<row>";
    $xml_store .= "<cell style=\"text-align:center;\">$sub_arr[0]</cell>";
    $xml_store .= "<cell style=\"text-align:left;\">$sub_arr[1]</cell>";
    $xml_store .= "<cell style=\"text-align:left;\">$sub_arr[2]</cell>";
    $xml_store .= "<cell style=\"text-align:right;\">" . number_format($sub_arr[3]) . "</cell>";
    $xml_store .= "<cell style=\"text-align:right;\">$sub_arr[4]</cell>";
    $total_received_qty += $sub_arr[3];

    $xml_store .="</row>";
}
// To show Total
array_shift($sum_arr);

$xml_store .= "<row>";
$xml_store .= "<cell></cell>";
$xml_store .= "<cell></cell>";

$xml_store .= "<cell style=\"font-weight:bold\">Total</cell>";
$xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($total_received_qty) . "</cell>";
$xml_store .= "<cell></cell>";
$xml_store .="</row>";

$xml_store .="</rows>";
?>

<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title; ?></h3>

        <div class="innerLR">
            <script>
                var mygrid;
                function doInitGrid() {
                    mygrid = new dhtmlXGridObject('mygrid_container');
                    mygrid.selMultiRows = true;
                    mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    //mygrid.setHeader("Province,Consumption,AMC,On Hand,MOS,#cspan");
                    mygrid.setHeader("<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "'$report_title at  $this->loc_name'"; ?>)</div>,#cspan,#cspan,#cspan,#cspan");
                    mygrid.attachHeader("<?php echo $header; ?>");
                    //   mygrid.attachHeader("<?php // echo $header1;       ?>");
                    mygrid.setInitWidths("<?php echo $width; ?>");
                    mygrid.setColAlign("center,left,left,right,right");
                    mygrid.setColTypes("<?php echo $ro; ?>");                    
                    mygrid.enableRowsHover(true, 'onMouseOver');
                    mygrid.setSkin("light");
                    mygrid.init();
                    mygrid.clearAll();
                    $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
                    mygrid.loadXMLString(document.getElementById('xml_string').value);
                }
            </script>
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header-reverse-logistics.phtml') ?>
                    </td>
                </tr>

                <tr>
                    <td style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>

            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:700px;"></div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>




<script>

    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;

</script>


