<div class="row">
    <div class="col-md-5">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Item Group Title"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->item_description ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form->item_group_id; ?>
