<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Products") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Products Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form method="POST" name="search" action="" >
                            <!-- Row -->
                            <div class="row">
                                <div class="col-md-12 margin-bottom">
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Product"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->item_name; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Item Category"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->item_category; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Item Unit"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->item_unit; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Group"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->item; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 ">
                                    <div class="col-md-3">
                                        <label class="control-label" >&nbsp;</label>
                                        <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                        <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Products List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="dataTables_wrapper form-inline">
                            <div class="row">
                                <div class="col-md-3">
                                    <?php $this->recordsPerPage($this->counter); ?>
                                </div>
                                <div class="col-md-9">
                                    <div class="dataTables_filter">
                                        <label>
                                            <a class="btn btn-primary" data-toggle="modal" href="#add-stakeholders"><?php echo $this->translate("Add Product") ?></a>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                <!-- Table heading -->
                                <?php
                                $fields = array(
                                    'product' => 'Product',
                                    'item_category' => 'Item Category',
                                    'item_unit' => 'Item Unit',
                                    'group' => 'Group'
                                );
                                $this->tableHeading($this->order, $this->sort, $fields);
                                ?>
                                <!-- // Table heading END -->
                                <!-- Table body -->

                                <!-- // Table body END -->
                                <tbody>
                                    <?php
                                    $m_res = array();
                                    $i = 1;
                                    if ($this->paginator && count($this->paginator) > 0) :
                                        foreach ($this->paginator as $row):
                                            ?>
                                            <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                <td><?php echo $row['itemName']; ?></td>
                                                <td><?php echo $row['itemCategoryName']; ?></td>
                                                <td><?php echo $row['itemUnitName']; ?></td>
                                                <td><?php echo $row['description']; ?></td>
                                                <td><a id="<?php echo $row['pkId']; ?>" class="btn update-asset-sub-type btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-asset-sub-type"><?php echo $this->translate("Edit") ?></a>

                                                </td>
                                                <!-- // Table row END --><?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                </tbody>
                            </table>
                            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/add-product" id="add-stakeholder">
            <div class="modal fade" id="add-stakeholders" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add Product</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12 margin-bottom">
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Product"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->item_name; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Category"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->item_category; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Description"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->description; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 margin-bottom">
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Product Unit"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->item_unit; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Group"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->item; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("List Rank"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->list_rank; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" id="lbl_no_of_doses" ><?php echo $this->translate("Number of Doses"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->number_of_doses; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-8">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Percent Population Covered"); ?> <span class="red">*</span></label>
                                            <div class="controls">
                                                <?php echo $this->form->percent_population_covered; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/update-product" id="update-asset-sub-types">
            <div class="modal fade" id="modal-update-asset-sub-type" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Product</h3>
                        </div>
                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer" id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->
