<div class="row">
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Stakeholder"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->stakeholder; ?>  
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Level"); ?></label>
            <div class="controls">
                <?php echo $this->form->geo_level; ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Office"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->office; ?>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form->stakeholder_id; ?>
