<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
    <h3 class="heading-mosaic">Makes index</h3>
    <div class="innerLR">
        <div class="widget">
            <!-- Widget Heading -->
            <div class="widget-head">
                <h3 class="heading">Index</h3>
            </div>
            <!-- // Widget Heading END -->
            <div class="widget-body">
                Welcome to Index

            </div>
        </div>
    </div>
    </div>
</div>
    <!-- // Content END -->