<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Locations(Geographical)") ?>  </h3>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Locations Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="locations" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12 margin-bottom">
                                            <?php echo $this->locationsCombo($this->combos); ?>
                                            <?php echo $this->form->province_id; ?>
                                            <?php echo $this->form->district_id; ?>
                                            <?php echo $this->form->parent_id; ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="control-label" ><?php echo $this->translate("Not Used in Warehouses"); ?></label>
                                                    <?php //echo $this->form->not_used; ?>
                                                    <input type="checkbox" name="not_used" id="not_used" <?php if ($this->delete_location == "on") echo 'checked'; ?> >
                                                </div>
                                            </div>

                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label class="control-label" >&nbsp;</label>
                                            <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                            <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Locations List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php  // $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary input-sm" data-toggle="modal" href="#add-asset-sub-type"><?php echo $this->translate("Add Locations") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'location' => 'Location',
                                            'Situated_in' => 'Situated In',
                                            'administrative_level' => 'Administrative Level',
                                            'ccm_code' => 'Ccm Code',
                                            'locatoion_type' => 'Type'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                        <?php
                                        $m_res = array();
                                        $i = 1;
                                        if ($this->paginator && count($this->paginator) > 0) :
                                            foreach ($this->paginator as $row):
                                                ?>
                                        <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                            <td><?php echo $row['locationName']; ?></td>
                                                <td><?php echo $row['parent']; ?></td>
                                                <td><?php echo $row['geoLevelName']; ?></td>
                                                <td><?php echo $row['ccmLocationId']; ?></td>
                                                <td><?php echo $row['locationTypeName']; ?></td>
                                                <td>
                                                    <a itemid="<?php echo $row['pkId']; ?>" class="btn update-locations btn-link btn-success input-sm" data-toggle="modal" href="#modal-update-locations"><?php echo $this->translate("Edit") ?>
                                                    </a>
                                                    <?php if ($this->locationsDelete($row['pkId'])) { ?>
                                                    <?php } else { ?>
                                                    <a data-toggle="notyfy" data-bind="<?php echo $row['pkId']; ?>" data-type="confirm" data-layout="top" class="btn btn-link btn-danger input-sm"><?php echo $this->translate("Delete"); ?>
                                                    </a>
                                                    <?php } ?>
                                                </td>
                                                <!-- // Table row END --><?php
                                                $i++;

                                            endforeach;

                                        endif;
                                        ?>
                                        </tbody>
                                    </table>
                                    <?php // echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-locations/add" id="locations-add">
            <div class="modal fade" id="add-asset-sub-type" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add Locations</h4>
                        </div>

                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12">
                                     <div class="col-md margin-bottom">
                                        <?php echo $this->locationsAddCombo(); ?>
                                    </div>
                                    </div>
                                <div class="col-md-12">
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Type"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->location_type_id; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("Location Name"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->location_name_add; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="control-group ">
                                            <label class="control-label" ><?php echo $this->translate("CCM Code"); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->ccm_location_id; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-locations/update" id="update-locations">
            <div class="modal fade" id="modal-update-locations"tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit Locations</h3>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>
<!-- // Content END -->
