{
"pkId": "<?php echo $this->arr_data[0]['pkId'] ?>",
"ccmMakeName": "<?php echo $this->arr_data[0]['ccmMakeName'] ?>",
"ccmModelName": "<?php echo $this->arr_data[0]['ccmModelName'] ?>",
"cfcFree": "<?php echo $this->arr_data[0]['cfcFree'] ?>",
"netCapacity4": "<?php echo $this->arr_data[0]['netCapacity4'] ?>",
"netCapacity20": "<?php echo $this->arr_data[0]['netCapacity20'] ?>",
"grossCapacity4": "<?php echo $this->arr_data[0]['grossCapacity4'] ?>",
"grossCapacity20": "<?php echo $this->arr_data[0]['grossCapacity20'] ?>",
"assetDimensionHeight": "<?php echo $this->arr_data[0]['assetDimensionHeight'] ?>",
"assetDimensionWidth": "<?php echo $this->arr_data[0]['assetDimensionWidth'] ?>",
"assetDimensionLength": "<?php echo $this->arr_data[0]['assetDimensionLength'] ?>",
"ccm_asset_type": "<?php echo $this->arr_data[0]['ccm_asset_type'] ?>",
"ccm_model": "<?php echo $this->arr_data[0]['ccm_model'] ?>",
"ccm_make": "<?php echo $this->arr_data[0]['ccm_make'] ?>"
}
