<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
    <h3 class="page-title">Stock Index</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        Index
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                <div class="row">
                    <div class="col-md-12">
                        <p>Welcome to Index</p>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

    <!-- // Content END -->