CcmHumanResources:
  type: entity
  table: ccm_human_resources
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 50
      fixed: false
      nullable: true
    designation:
      type: string
      length: 50
      fixed: false
      nullable: true
    mobileNumber:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: mobile_number
    email:
      type: string
      length: 50
      fixed: false
      nullable: true
    logDate:
      type: datetime
      nullable: true
      column: log_date    
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    ccmPersonType:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_person_type:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
