DemandDetail:
  type: entity
  table: demand_detail
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    demandQuantity:
      type: bigint
      nullable: false
      column: demand_quantity
    approvedQuantity:
      type: bigint
      nullable: true
      column: approved_quantity
    pairProductId:
      type: integer
      unsigned: false
      nullable: true
      column: pair_product_id
    draft:
      type: boolean
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
  oneToOne:
    demandMaster:
      targetEntity: DemandMaster
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        demand_master_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    product:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        product_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
