DemandWarehousesLogic:
  type: entity
  table: demand_warehouses_logic
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    createdBy:
      type: integer
      unsigned: false
      nullable: false
      column: created_by
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedBy:
      type: integer
      unsigned: false
      nullable: false
      column: modified_by
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    fromWarehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        from_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    toWarehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        to_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
