GatepassDetail:
  type: entity
  table: gatepass_detail
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: string
      length: 255
      fixed: false
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockDetail:
      targetEntity: StockDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_detail_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    gatepassMaster:
      targetEntity: GatepassMaster
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        gatepass_master_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
