ItemPairsLogic:
  type: entity
  table: item_pairs_logic
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: integer
      unsigned: false
      nullable: true
    groupId:
      type: integer
      unsigned: false
      nullable: true
      column: group_id
    rank:
      type: integer
      unsigned: false
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    unitOfQuantity:
      targetEntity: ItemUnits
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        unit_of_quantity:
          referencedColumnName: pk_id
      orphanRemoval: false
    item:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemPair:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pair_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
