ListDetail:
  type: entity
  table: list_detail
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    listValue:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: list_value
    description:
      type: text
      nullable: true
    rank:
      type: integer
      unsigned: false
      nullable: true
    referenceId:
      type: integer
      unsigned: false
      nullable: true
      column: reference_id
    parentId:
      type: integer
      unsigned: false
      nullable: true
      column: parent_id
    createdDate:
      type: datetime
      nullable: false
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    listMaster:
      targetEntity: ListMaster
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        list_master_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
