RackInformation:
  type: entity
  table: rack_information
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    rackType:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: rack_type
    noOfBins:
      type: smallint
      nullable: true
      column: no_of_bins
    binNetCapacity:
      type: float
      nullable: true
      column: bin_net_capacity
    grossCapacity:
      type: float
      nullable: true
      column: gross_capacity
    capacityUnit:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: capacity_unit
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
