StockUsedFor:
  type: entity
  table: stock_used_for
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: decimal
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    itemPairLogic:
      targetEntity: ItemPairsLogic
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pair_logic_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockDetail:
      targetEntity: StockDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_detail_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    transactionType:
      targetEntity: TransactionTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        transaction_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
