WarehouseTypes:
  type: entity
  table: warehouse_types
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    warehouseTypeName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: warehouse_type_name
    resupplyInterval:
      type: integer
      unsigned: false
      nullable: true
      column: resupply_interval
    reservedStock:
      type: integer
      unsigned: false
      nullable: true
      column: reserved_stock
    usagePercentage:
      type: decimal
      nullable: true
      column: usage_percentage
    geoLevelId:
      type: integer
      unsigned: false
      nullable: true
      column: geo_level_id
    listRank:
      type: integer
      unsigned: false
      nullable: true
      column: list_rank
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouseTypeCategory:
      targetEntity: WarehouseTypeCategories
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_type_category_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
