<div class="col-md-3">
    <div class="form-group ">
        <label class="control-label" ><?php echo $this->translate("Asset Type"); ?></label>
        <?php echo $this->form->asset_type; ?>
    </div>
</div>
<div class="col-md-3">
    <div class="form-group ">
        <label class="control-label" ><?php echo $this->translate("Asset Sub Type"); ?></label>
        <?php echo $this->form->asset_sub_type; ?>
    </div>
</div>
<?php echo $this->form->asset_id; ?>
