<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Campaign Readiness ") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Campaign Readiness Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="batch_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">

                                            <div class="col-md-3">
                                                <div class="control-group">
                                                    <label class="control-label">Campaign</label>
                                                    <div class="controls">
                                                        <?php echo $this->form->campaign_id; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="control-group">
                                                    <label class="control-label">UC</label>
                                                    <div class="controls">
                                                        <?php echo $this->form->uc_id; ?>
                                                        <?php echo $this->form->uc_id_hidden; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <label class="control-label" >&nbsp;</label>
                                                <div class="controls">
                                                    <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                    <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Campaign Readiness List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <!--                                        <div class="col-md-3">
                                        <?php //$this->recordsPerPage($this->counter); ?>
                                                                                </div>-->
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-condensed dataTable" id="sample_2">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'uc' => 'UC',
//                                            'targeted' => 'Targeted',
                                            'inacc' => 'Inacc',
                                            'mobile pop.' => 'Mobile <br /> Pop.',
                                            'inacc areas' => 'Inacc <br /> Areas',
                                            'areas ics' => 'Areas <br /> ICs',
                                            'mobile teams' => 'Mobile <br /> Teams',
                                            'fixed teams' => 'Fixed <br /> Teams',
                                            'transit pt.' => 'Transit <br /> pt.',
                                            'aics trained' => 'AICs <br /> Trained',
                                            'teams trained' => 'Teams <br /> Trained',
                                            'upec meeting' => "UPEC <br /> meeting"
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                // App_Controller_Functions::pr($this->paginator);
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row['ucName']; ?></td>
        <!--                                                        <td><?php //echo $row['inaccessibleChildren'];        ?></td>-->
                                                        <td><?php echo $row['inaccessibleChildren']; ?></td>
                                                        <td><?php echo $row['mobilePopulationAreas']; ?></td>
                                                        <td><?php echo $row['inaccessibleArea']; ?></td>
                                                        <td><?php echo $row['numberMobileTeams']; ?></td>
                                                        <td><?php echo $row['numberMobileTeams']; ?></td>
                                                        <td><?php echo $row['numberFixedTeams']; ?></td>
                                                        <td><?php echo $row['numberTransitPoints']; ?></td>
                                                        <td><?php echo $row['aicTrained']; ?></td>
                                                        <td><?php echo $row['numberTeamsTrained']; ?></td>
                                                        <td><?php
                                                            if (!empty($row['upecMeetingDate'])) {
                                                                echo date("m/d/Y", strtotime($row['upecMeetingDate']));
                                                            } else {
                                                                echo "";
                                                            }
                                                            ?></td>
                                                        <td>
                                                            <?php if ($this->IsCampaignDataEntered($row['campaign_id'], $row['warehouse_id'])) { ?>
                                                                <?php if ($this->IsEdit($row['campaign_id'], $row['warehouse_id'])) { ?>
                                                                    <a itemid="<?php echo $row['pkId']; ?>" class="update-user btn btn-xs green cursor-hand" data-toggle="modal" href="#modal-update-user">Edit
                                                                        <i class="fa fa-edit"></i>
                                                                    </a>
                                                                    <?php
                                                                } else {
                                                                    ?>  <a itemid="<?php echo $row['campaign_id'] . "," . $row['warehouse_id']; ?>" class="add-user btn btn-xs blue" data-toggle="modal" href="#modal-add-user"><?php echo $this->translate("Add") ?> <i class="fa fa-plus"></i></a>
                                                                <?php } ?>
                                                            <?php
                                                            } else {
                                                                
                                                            }
                                                            ?>

                                                        </td>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
<?php // echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params));  ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <form method="post" action="<?php echo $this->baseUrl(); ?>/campaign/manage-campaigns/add-campaign-readiness-uc" id="add-user">
        <div class="modal fade" id="modal-add-user"  tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3>Campaign Readiness at UC</h3>
                    </div>

                    <div class="modal-body" id="modal-body-add">
                        <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>

                    </div>
                    <div class="modal-footer">
                        <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Save"); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <form method="post" action="<?php echo $this->baseUrl(); ?>/campaign/manage-campaigns/update-campaign-readiness-uc" id="update-user" enctype="multipart/form-data">
        <div class="modal fade" id="modal-update-user" tabindex="-1" role="basic" aria-hidden="true" >
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3>Edit Campaign Readiness</h3>
                    </div>

                    <div class="modal-body" id="modal-body-contents">
                        <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                    </div>
                    <div class="modal-footer" id="update-button">
                        <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Update"); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>
</div>
<!-- // Content END -->