<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Campaign Readiness") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Campaign Readiness Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="batch_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="control-label">Campaign</label>
                                                    <?php echo $this->form->campaign_id; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                    <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Campaign Readiness List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#modal-add-user"><?php echo $this->translate("Add Campaign Readiness") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            'district' => 'District',
                                            'campaign' => 'Campaign',
                                            'no of telly sheets received' => 'No. of telly sheets received',
                                            'no of finger markers received' => 'No. of finger markers received',
                                            'arrival date of social mobilization material' => 'Arrival Date of social mobilization material'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $row['districtName']; ?></td>
                                                        <td><?php echo $row['campaignName']; ?></td>
                                                        <td><?php echo $row['numTallySheets']; ?></td>
                                                        <td><?php echo $row['numFingerMarkers']; ?></td>
                                                        <td><?php echo date("m/d/Y", strtotime($row['arrivalDateMobilizationMaterial'])); ?></td>
                                                        <td><a itemid="<?php echo $row['pkId']; ?>" class="update-user btn btn-xs green cursor-hand" data-toggle="modal" href="#modal-update-user">
                                                                Edit <i class="fa fa-edit"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Widget -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/campaign/manage-campaigns/add-campaign-readiness" id="add-user">
            <div class="modal fade" id="modal-add-user" tabindex="-1" role="basic" aria-hidden="true">

                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add Campaign Readiness</h4>
                        </div>

                        <div class="modal-body">
                            <div class="row" >
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Campaign</label>
                                        <?php echo $this->form->campaign_add_id; ?>
                                    </div>
                                </div>

                            </div>



                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Vaccine</label>
                                        <input type="text" class="form-control" name="item_id" id="item_id" readonly="readonly" />
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Vials Required</label>
                                        <input type="text" class="form-control" name="vials_required" id="vials_required" readonly="readonly" />
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Vials Available</label>
                                        <input type="text" class="form-control" name="vials_available" id="vials_available" readonly="readonly" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">No. of tally sheets received</label>
                                        <?php echo $this->form->num_tally_sheets; ?>
                                        <label class="control-label">Arrival date of social mobilization material</label>
                                        <?php echo $this->form->arrival_date_mobiliztion_material; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">No. of finger markers received</label>
                                        <?php echo $this->form->num_finger_markers; ?>
                                        <label class="control-label">Date of DPEC Meeting</label>
                                        <?php echo $this->form->dpec_meeting_date; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="group-control">
                                            <input type="checkbox" name="dco_attended_meeting" id="dco_attended_meeting">

                                            <label class="control-label">DCO Attended Meeting
                                            </label>
                                        </div>
                                        <div class="group-control">
                                            <input type="checkbox" name="edo_attended_meeting" id="edo_attended_meeting">
                                            <label class="control-label">EDO Attended Meeting
                                            </label>
                                        </div>
                                        <div class="group-control">
                                            <input type="checkbox" name="all_members_attended_meeting" id="all_members_attended_meeting" >
                                            <label class="control-label">All Members Attended Meeting
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <label class="form-label">Remarks</label>
                                        <?php echo $this->form->remarks; ?>  </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Save"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/campaign/manage-campaigns/update-campaign-readiness" id="update-user" enctype="multipart/form-data">
            <div class="modal fade" id="modal-update-user"  tabindex="-1" role="basic" aria-hidden="true" >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit Campaign Readiness</h4>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer" id="update-button">
                            <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Update"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->