<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Reported Districts") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Reported Districts Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                            <div class="col-md-12">
                                <form method="POST" name="batch_search" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $this->translate("Campaign"); ?></label>
                                                    <?php echo $this->form->campaign_search_id; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <button class="btn btn-primary" type="submit" name="search"><?php echo $this->translate("Search") ?></button>
                                                <button type="reset" class="btn btn-info" id="reset">Reset</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Reported Districts List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>

                                    </div>
                                    <table class="table table-striped table-bordered table-condensed dataTable">
                                        <!-- Table heading -->
                                        <thead>
                                            <tr>
                                                <th rowspan="2"><?php echo $this->translate("Sr.No.") ?></th>
                                                <th rowspan="2"><?php echo $this->translate("District") ?></th>
                                                <th rowspan="2"><?php echo $this->translate("Total Ucs") ?></th>
                                                <th rowspan="2"><?php echo $this->translate("Reported Ucs") ?></th>

                                            </tr>

                                        </thead>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td><?php echo $i; ?></td>
                                                        <td><?php echo $row['DistrictName']; ?></td>
                                                        <td><?php echo $row['TotalUC']; ?></td>
                                                        <td><?php echo $row['ReportedUC']; ?></td>


                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/campaign/manage-campaigns/add-campaign-lqas" id="add-user">
            <div class="modal hide fade" id="modal-add-user">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modalt-title">LQAS Data Entry</h4>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Campaign"); ?></label>
                                    <?php echo $this->form->campaign_id; ?>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Province"); ?></label>
                                    <?php echo $this->form->province_id; ?>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("District"); ?></label>
                                    <?php echo $this->form->district_id; ?>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Uc"); ?></label>
                                    <?php echo $this->form->uc_id; ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Surveyor"); ?></label>
                                    <?php echo $this->form->surveyor; ?>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Checked"); ?></label>
                                    <?php echo $this->form->checked; ?>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Unvaccinated"); ?></label>
                                    <?php echo $this->form->unvaccinted; ?>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $this->translate("Remarks"); ?></label>
                                    <?php echo $this->form->remarks; ?>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Save"); ?></button>
                </div>
            </div>
        </form>
        <form method="post" action="<?php echo $this->baseUrl(); ?>/campaign/manage-campaigns/update-campaign-lqas" id="update-user" enctype="multipart/form-data">
            <div class="modal hide fade" id="modal-update-user">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Edit LQAS Data Entry</h4>
                </div>

                <div class="modal-body" id="modal-body-contents">
                    <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                </div>
                <div class="modal-footer hide" id="update-button">
                    <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit"><?php echo $this->translate("Update"); ?></button>
                </div>
            </div>
        </form>


    </div>
</div>
<!-- // Content END -->