<div class="row">
    <?php echo $this->usersEditCombo($this->combos_1); ?>  
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("Default Store"); ?></label>
            <?php echo $this->form->default_warehouse_update; ?>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("UserName"); ?></label>
            <?php echo $this->form->user_name_update; ?>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("Email"); ?></label>
            <?php echo $this->form->user_name_update; ?>
        </div>
    </div>


    <div class="col-md-6">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("Phone"); ?></label>
            <?php echo $this->form->user_name_update; ?>
        </div>
    </div>

</div>

<?php echo $this->form->user_id; ?>
<?php echo $this->form->office_id_edit; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->tehsil_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->warehouse_users_id_edit; ?>
<?php echo $this->form->default_warehouse_update_hidden; ?>

