
<div class="modal1"></div>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"> Change Warehouse Cluster Leads </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">

                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form name="frm" id="frm" action="" method="post" onsubmit="return frmValidate()">
                                    <div class="widget-body">
                                        <!-- Row -->
                                        <div class="row">
                                            <div class="col-md-12"> </div>
                                            <div class="col-md-12">
                                                <div class="col-md-12">
                                                    <div class="col-md-12">
                                                        <?php
                                                        if (isset($_GET['e'])) {
                                                            echo "<p style=\"color: green\">Leads have been successfully changed.</p>";
                                                        }
                                                        ?>
                                                        <div class="col-md-3">
                                                            <div class="control-group ">
                                                                <label class="control-label" ><?php echo $this->translate("Province"); ?></label>
                                                                <div class="controls">
                                                                    <?php echo $this->form->province; ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <div class="control-group ">
                                                                <label class="control-label" ><?php echo $this->translate("District"); ?></label>
                                                                <div class="controls">
                                                                    <?php echo $this->form->district; ?>

                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <div class="control-group ">
                                                                <label class="control-label" ><?php echo $this->translate("User"); ?></label>
                                                                <div class="controls">
                                                                    <?php echo $this->form->user; ?>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div style="clear:both;"></div>
                                                        <div class="control-group span7" id="wh"></div>

                                                        <div class="control-group span7">
                                                            <label class="control-label" >&nbsp;</label>
                                                            <button class="btn btn-primary pull-right" type="submit" id="submit" name="search" style="display:none;"><?php echo $this->translate("Submit") ?></button>
                                                        </div>

                                                    </div>
                                                    <div class="col-md-12"> <span id="showMonths"> </span> </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

