<?php
if ($this->all_running_batches != false) {
    ?>
    <option value=""><?php echo $this->translate("Select"); ?></option>
    <?php
    foreach ($this->all_running_batches as $row) {
        ?>
    <option value="<?php echo $row['pkId']; ?>"><?php echo $row['number']; ?> | <?php echo number_format($row['quantity']); if(isset($row['priority'])) { ?> | <?php echo $row['priority']; } ?></option>
        <?php
    }
}

if ($this->batch_expiry != false) {
    ?>
    <div class="col-md-3">
        <label class="control-label" for="firstname"><?php echo $this->translate("Available"); ?></label>
        <div class="controls">
            <input type="text" class="form-control" name="available_quantity" id="available_quantity" readonly="" value="<?php echo number_format($this->batch_expiry['qty']); ?>" />
            <input type="hidden" class="form-control" name="hdn_available_quantity" id="hdn_available_quantity" value="<?php $this->batch_expiry['qty'] ?>"/>
        </div>
    </div>
    <div class="col-md-3" id="expiry_div" <?php if ($this->batch_expiry['cat'] == '2') { ?> style="display: none;" <?php } ?> >
        <label class="control-label" for="expiry_date"><?php echo $this->translate("Expiry Date"); ?></label>
        <div class="controls">
            <input type="text" class="form-control" name="expiry_date" id="expiry_date" readonly="" value="<?php echo date("d M, Y", strtotime($this->batch_expiry['date'])) ?>" />
        </div>
    </div>
    <?php
}

if ($this->available_quantity != false) {
    ?>
    <input class="form-control" id="available" name="available" type="text" value="<?php echo number_format($this->available_quantity['qty']) ?>" required="" disabled="" />
    <?php
}
?>