<div class="scroller" style="min-height:200px" data-always-visible="1" data-rail-visible1="1">
    <strong>Product : </strong><?php echo $this->array_data['1']; ?>,&nbsp;&nbsp;&nbsp;<strong>Batch No : </strong> <?php echo $this->array_data['2']; ?>,&nbsp;&nbsp;&nbsp;<strong>Expiry : </strong><?php echo date("d/m/Y", strtotime($this->array_data['3'])); ?>
    <br>
    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
        <!-- Table heading -->
        <thead>
            <tr>
                <th><?php echo $this->translate("Sr No"); ?></th>
                <th><?php echo $this->translate("Location"); ?></th>
                <th><?php echo $this->translate("VVM Stage"); ?> </th>
                <th><?php echo $this->translate("Available Quantity (Vials)"); ?></th>
            </tr>
        </thead>
        <!-- // Table heading END -->

        <!-- Table body -->
        <tbody>
            <?php
            if (!empty($this->data) && count($this->data) > 0) {
                $i = 1;
                $total = 0;
                foreach ($this->data as $row) {
                    ?>
                    <!-- Table row -->
                    <tr class="gradeX">
                        <td class="center"><?php echo $i; ?></td>
                        <td><?php echo $row['asset_id']; ?></td>
                        <td class="center"><?php echo $row['vvm_stage']; ?></td>
                        <td class="right"><?php echo number_format($row['quantity']); ?></td>
                    </tr>
                    <?php
                    $total += $row['quantity'];
                    $i++;
                }
                ?>
                <!-- // Table row END -->
            </tbody>
            <!-- // Table body END -->
            <tfoot>
                <tr>
                    <th class="right" colspan="3"><?php echo $this->translate("Total:"); ?></th>
                    <th class="right"><?php echo number_format($total); ?></th>
                </tr>
            </tfoot>
            <?php
        } else {
            ?>
            <tfoot>
                <tr class="gradeX center">
                    <th colspan="4" class="center">No Record Found</th>
                </tr>
            </tfoot>
            <?php
        }
        ?>



    </table>
    <div style="clear: both;"></div>
    <!--<br>
    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
         Table heading 
        <thead>
            <tr>
    
                <th ><?php echo $this->translate("VVM Stage 1"); ?></th>
                <th ><?php echo $this->translate("VVM Stage 2"); ?> </th>
                <th ><?php echo $this->translate("VVM Stage 3"); ?></th>
                <th ><?php echo $this->translate("VVM Stage 4"); ?></th>
            </tr>
        </thead>
         // Table heading END 
    
         Table body 
        <tbody>
    <?php
    if (!empty($this->data1) && count($this->data1) > 0) {
        $i = 1;
        foreach ($this->data1 as $row1) {
            ?>
                                     Table row 
                                    <tr class="gradeX">
            
                                        <td class="right"><?php echo $row1['vvm_stage'] == 1 ? $row1['quantity'] : 0; ?></td>
                                        <td class="right"><?php echo $row1['vvm_stage'] == 2 ? $row1['quantity'] : 0; ?></td>
                                        <td class="right"><?php echo $row1['vvm_stage'] == 3 ? $row1['quantity'] : 0; ?></td>
                                        <td class="right"><?php echo $row1['vvm_stage'] == 4 ? $row1['quantity'] : 0; ?></td>
                                    </tr>
            <?php
            $i++;
        }
    } else {
        ?>
                        <tr class="gradeX center">
                            <td colspan="4">No Record Found</td>
                        </tr>
        <?php
    }
    ?>
             // Table row END 
        </tbody>
         // Table body END 
    
    </table>
      <div style="clear: both;"></div>-->

</div>