<table class="table table-striped table-bordered table-hover dataTable no-footer"  >
    <!-- Table heading -->
    <thead>
        <tr>
            <th class="col-md-3"><?php echo $this->translate("Placement Label"); ?></th>
            <th class="col-md-3"><?php echo $this->translate("Carton Quantity"); ?></th>
            <th class="col-md-3"><?php echo $this->translate("Quantity"); ?></th>				 
        </tr>
    </thead>
    <!-- // Table heading END -->

    <!-- Table body -->
    <tbody>				
        <!-- Table row -->
        <?php
        if ($this->result && count($this->result) > 0) {
            foreach ($this->result as $row):
                $carton_qty = $row['quantity'] / $row['quantity_per_pack'];
                ?>
                <tr class="gradeX">
                    <td class="left"><?php echo $row['location_name']; ?></td>
                    <td class="right"><?php echo $carton_qty; ?></td>
                    <td class="right"><?php echo $row['quantity']; ?></td>
                </tr>
                <?php
            endforeach;
        }
        else {
            echo "No record Found";
        }
        ?>
        <!-- // Table row END -->
    </tbody> 
    <!-- // Table body END -->
</table>
<!-- // Table END -->		