<?php
/**
 *  phtml for Ajax Product Placement Detail
 */
?>



<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <?php
                    echo $this->product_name;
                    echo $this->translate(" Placement ");
                    ?>
                    <?php if ($this->detail_summary == 1) { ?> Summary <?php } else { ?> Detail <?php } ?>
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-12">
                        <?php if ($this->detail_summary == 1) { ?>
                            <table class="table table-striped table-bordered table-condensed" id="sample_2">
                                <thead>
                                    <tr>
                                        <th class="center">
                                            #
                                        </th>
                                        <th>
                                            Cold Room
                                        </th>
                                        <th>Product</th>
                                        <th class="right">
                                            VVM Stage
                                        </th>
                                        <th class="right">
                                            Quantity (Vials)
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $i = 1;
                                    $total = 0;
                                    if ($this->result != false) {
                                        foreach ($this->result as $row) {
                                            $total += $row['quantity'];
                                            ?>
                                            <tr>
                                                <td class="center">
                                                    <?php echo $i; ?>
                                                </td>
                                                <td>
                                                    <a href="<?php echo $this->baseUrl(); ?>/stock/stock-in-bin-vaccines?id=<?php echo $row['pk_id']; ?>&asset=<?php echo $row['asset_id']; ?>" target="_blank"><?php echo $row['asset_id']; ?></a>
                                                </td>
                                                <td>
                                                    <?php echo $this->product_name; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo $row['vvm_stage']; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo number_format($row['quantity']); ?>
                                                </td>
                                            </tr>
                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="4" class="right">
                                            Total:
                                        </th>
                                        <th class="right">
                                            <?php echo number_format($total); ?>
                                        </th>
                                    </tr>
                                </tfoot>
                            </table>
                        <?php } else { ?>
                            <table class="table table-striped table-bordered table-condensed" id="sample_2">
                                <thead>
                                    <tr>
                                        <th class="center">
                                            #
                                        </th>
                                        <th>
                                            Cold Room
                                        </th>
                                        <th>Product</th>
                                        <th>
                                            Batch Number
                                        </th>
                                        <th class="right">
                                            VVM Stage
                                        </th>
                                        <th class="right">
                                            Quantity (Vials)
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $i = 1;
                                    $total = 0;
                                    if ($this->result != false) {
                                        foreach ($this->result as $row) {
                                            $total += $row['quantity'];
                                            ?>
                                            <tr>
                                                <td class="center">
                                                    <?php echo $i; ?>
                                                </td>
                                                <td>
                                                    <a href="<?php echo $this->baseUrl(); ?>/stock/stock-in-bin-vaccines?id=<?php echo $row['pk_id']; ?>&asset=<?php echo $row['asset_id']; ?>" target="_blank"><?php echo $row['asset_id']; ?></a>
                                                </td>
                                                <td>
                                                    <?php echo $this->product_name; ?>
                                                </td>
                                                <td>
                                                    <?php echo $row['batch_number']; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo $row['vvm_stage']; ?>
                                                </td>
                                                <td class="right">
                                                    <?php echo number_format($row['quantity']); ?>
                                                </td>
                                            </tr>
                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="5" class="right">
                                            Total:
                                        </th>
                                        <th class="right">
                                            <?php echo number_format($total); ?>
                                        </th>
                                    </tr>
                                </tfoot>
                            </table>
                        <?php } ?>
                        <br>
                        <div class="row">
                            <div class="col-md-12 right">
                                <a class="btn btn-success" href="javascript:void(0);" 
                                   onclick="window.open('product-placement-detail-print?param=<?php echo $this->detail_summary; ?>&product=<?php echo $this->product; ?>', '_blank', 'scrollbars=1,width=840,height=595');">
                                       <?php echo $this->translate("Print"); ?>
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>








