<?php if (count($this->result) > 0) { ?>
    <div class="row">
        <div class="col-md-12">
            <form name="ajax-product" id="ajax-prdouct" method="post">
                <table class="table table-striped table-bordered table-condensed" id="stkledger">
                    <thead>
                        <tr>
                            <th style="width:1%;"><input type="checkbox" id="checkall" value="" /></th>
                            <th style="width:1%;">S.No</th>
                            <th>Product</th>
                            <th>Batch No.</th>
                            <th class="center">Expiry</th>
                            <th class="right">Current Quantity</th>
                            <th class="right">Physical Quantity</th>
                            <th class="right">Difference</th>
                            <th class="center">VVM Stage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $count = 1;
                        $pq = 0;
                        $cpq = 0;
                        foreach ($this->result as $row) {
                            $current_qty = ($row->getStockBatch() != null) ? $row->getStockBatch()->getQuantity() : 0;
                            if ($row->getStockBatch() != null) {
                                $physical_quantity = $this->getPhysicalBatchQuantity($row->getStockBatch()->getPkId());                                
                            } else {
                                $physical_quantity = $row->getQuantity();
                            }
                            $pq += $physical_quantity;
                            $cpq += $current_qty;
                            ?>
                            <tr>
                                <td><input type="checkbox" class="check" name="adjust[]" value="<?php echo $row->getPkId(); ?>" /></td>
                                <td><?php echo $count; ?></td>
                                <td align="left"><?php echo $row->getItemPackSize()->getItemName(); ?></td>
                                <td align="left"><?php echo $row->getBatchNumber(); ?></td>
                                <td align="center"><?php echo $row->getExpiryDate() != "" ? $row->getExpiryDate()->format("d/m/Y") : $row->getStockBatch()->getExpiryDate()->format("d/m/Y"); ?></td>
                                <td align="right"><?php echo $current_qty; ?></td>
                                <td align="right"><?php echo $physical_quantity; ?> | <?php echo $pq ?></td>  
                                <td align="right"><?php echo $physical_quantity - $current_qty; ?></td>
                                <td align="left"><?php echo $row->getVvmStage()->getVvmStageValue(); ?></td>                                
                            </tr>
                            <?php
                            $count++;
                        }
                        ?>
                    </tbody>
                </table>
                <br>
                <div class="left"><input type="button" class="btn btn-success" name="adjust" id="adjust" value="Adjust Selected" /></div>
            </form>
        </div>
    </div>
<?php } else { ?>
    <div class="row">
        <div class="col-md-12">
            <h4>Transactions not found</h4>
        </div>
    </div>
<?php } ?>