<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Unused Stock Transactions/Adjustments") ?> found between <?php echo $this->date_from; ?> and <?php echo $this->date_to; ?></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Filters") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse"></a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row margin-top-10 margin-bottom-10">
                            <div class="col-md-12">
                                <?php echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource')); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="expired_stock" id="expired_stock" action="">
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-3">
                                                <div class="form-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Date From") ?></label>
                                                    <?php echo $this->form->date_from; ?>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Date To") ?></label>
                                                    <?php echo $this->form->date_to; ?>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group ">
                                                    <label class="control-label" ><?php echo $this->translate("Reason"); ?></label>
                                                    <?php echo $this->form->adjustment_type; ?>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group form-btn-margin-top">
                                                    <button class="btn btn-success" type="submit" name="search" value="Search"><?php echo $this->translate("Go") ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Search Result") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- Table -->
                                <table class="dynamicTable table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th rowspan="2"><?php echo $this->translate("Product") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Batch Number") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Reason") ?></th>
                                            <th colspan="2" class="center"><?php echo $this->translate("Quantity") ?></th>
                                            <th rowspan="2"><?php echo $this->translate("Expiry Date") ?></th>
                                        </tr>
                                        <tr>
                                            <th class="right">Vials</th>
                                            <th class="right">Doses</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        
                                    </tfoot>
                                    <tbody>
                                        <?php
                                        if ($this->expired && count($this->expired) > 0) :
                                            $m_res = array();
                                            $i = 1;
                                            foreach ($this->expired as $row):
                                                ?>
                                                <tr class="gradeX">
                                                    <td><?php echo $row['item_name']; ?></td>
                                                    <td><?php echo $row['number']; ?></td>
                                                    <td><?php echo $row['reason']; ?></td>
                                                    <td class="right"><?php echo number_format($row['vails']); ?></td>
                                                    <td class="right"><?php echo number_format($row['doses']); ?></td>
                                                    <td><?php echo $row['expiry_date']; ?></td>
                                                </tr>
                                                <!-- // Table row END --><?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                        <?php
                                        if ($this->ccbreak && count($this->ccbreak) > 0) :
                                            $m_res = array();
                                            $i = 1;
                                            foreach ($this->ccbreak as $row):
                                                ?>
                                                <tr class="gradeX">
                                                    <td><?php echo $row['item_name']; ?></td>
                                                    <td><?php echo $row['number']; ?></td>
                                                    <td><?php echo $row['reason']; ?></td>
                                                    <td class="right"><?php echo number_format($row['vails']); ?></td>
                                                    <td class="right"><?php echo number_format($row['doses']); ?></td>
                                                    <td><?php echo $row['expiry_date']; ?></td>
                                                </tr>
                                                <!-- // Table row END --><?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                        <!-- // Table body END -->
                                    </tbody>
                                </table>
                                <!-- // Table END --><br>
                                <div class="right">
                                    <button id="print_stock" class="btn btn-warning input-sm" type="button"><?php echo $this->translate("Print") ?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- // Content END -->