<!-- Content -->

<div class="page-content-wrapper">
    <div class="page-content">
        <?php if (isset($this->do) && !empty($this->do)) { ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-7">
                        <h3> <?php echo $this->warehouse_name; ?> </h3>
                    </div>

                    <div class="col-md-5">
                        <div class="well">
                            <div class="control-group">
                                <label class="control-label" for="firstname">
                                    <?php echo $this->translate("View Monthly Consumption Report for") ?>
                                </label>
                                <div class="controls">
                                    <?php echo $this->form->monthly_report; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row margin-top-10 margin-bottom-10">
                <div class="col-md-12">
                    <?php
                    //echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Referral from Outside UC's Detail") ?>  (<?php echo $this->month . "-" . $this->year; ?>)
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php if ($this->is_new_report == 2) { ?>
                                        <!--                                        <div style="width:100%;text-align:right; margin-bottom:10px;"><a id="print-monthly-conumption" href="#" ><button type="button" class="btn btn-primary">Print</button></a></div>-->
                                        <div class="right">
                                            <button type="button" id="print-monthly-consumption" class="btn btn-warning input-sm"><?php echo $this->translate("Print") ?></button>
                                        </div>
                                        <div style="clear:both;"></div>
                                    <?php } ?>
                                    <form name="frmF7" id="dataEntryfrm" action="" method="POST" enctype="multipart/form-data">
                                        <div style="overflow: auto">
                                            
                                        <!-- Table -->
                                        <table class="table table-striped table-bordered table-condensed">
                                            <thead  style="background-color: lightgray;">
                                                <tr>
                                                    <th rowspan="2">S.No</th>
                                                    <th colspan="8" style="background-color: #1fc70c; text-align: center">Vaccinated Child Information</th>
                                                    <th rowspan="2">Date</th>
                                                    <th colspan="5" style="background-color: #e1f20d; text-align: center">Dose No.</th>
                                                    <th rowspan="2">Refer to</th>
                                                    <th rowspan="2">Remarks if any</th>   
                                                </tr>
                                                <tr>
                                                    <th style="background-color: #1fc70c;">Name</th>
                                                    <th style="background-color: #1fc70c;">Father Name</th>
                                                    <th style="background-color: #1fc70c;">Gender</th>
                                                    <th style="background-color: #1fc70c;">Age</th>
                                                    <th style="background-color: #1fc70c;">Contact No.</th>
                                                    <th style="background-color: #1fc70c;">Address</th>
                                                    <th style="background-color: #1fc70c;">District</th>
                                                    <th style="background-color: #1fc70c;">U.C</th>
                                                    <th style="background-color: #e1f20d;">BCG</th>
                                                    <th style="background-color: #e1f20d;">OPV-0</th>
                                                    <th style="background-color: #e1f20d;">OPV/Penta</th>
                                                    <th style="background-color: #e1f20d;">PCV-10</th>
                                                    <th style="background-color: #e1f20d;">Measles</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                for ($i = 0; $i < 10; $i++) {
                                                    ?>
                                                    <tr>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 120px"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 120px"></td>
                                                        <td><select name="" id="" class="form-control col-md-1 input-sm" style="width: 80px"><option>Select</option><option>Male</option><option>Female</option></select></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 40px"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 100px"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 120px"></td>
                                                        <td><select name="" id="" class="form-control col-md-1 input-sm" style="width: 80px"><option>Select</option></select></td>
                                                        <td><select name="" id="" class="form-control col-md-1 input-sm" style="width: 80px"><option>Select</option></select></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 80px"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 100px"></td>
                                                        <td><input type="text" name="" id="" class="form-control col-md-1 input-sm" style="width: 120px"></td>
                                                        
                                                        
                                                    </tr>
                                                    <?php
                                                }
                                                ?>

                                            </tbody>
                                        </table>
                                        <!-- // Table END -->
                                        </div>
                                       <button id="print-monthly-consumption" class="btn btn-success pull-right" type="button">Save</button>
                                        <input type="hidden" name="rpt_date" value="<?php echo $this->rpt_date; ?>">
                                        <input type="hidden" name="wh_id" id="wh_id" value="<?php echo $this->wh_id; ?>">
                                        <input type="hidden" name="loc_id" value="<?php echo $this->locid; ?>">
                                        <input type="hidden" name="do" id="do" value="<?php echo $this->do; ?>">
                                        <input type="hidden" name="yearmonth" id="yearmonth" value="<?php echo $this->year . "-" . $this->mm; ?>">
                                        <input type="hidden" name="is_new_report" id="isNewRpt" value="<?php echo $this->is_new_report; ?>" />
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } else { ?>
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN SAMPLE TABLE PORTLET-->
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-arrow-down"></i>Consumption Data Entry
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th style="vertical-align: top;">#</th>
                                            <th style="vertical-align: top;">Union Council</th>                                        
                                            <th style="vertical-align: top;">EPI Center / Health Facility</th>                                        
                                            <th style="vertical-align: top;">Reporting Months<br/><h5>Click month to add/view reported data</h5></th>
                                    <th style="vertical-align: top;">Last Update</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $count = 1;
                                        foreach ($this->warehouses as $row) {
                                            ?>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td><?php echo $row['locationName']; ?></td>
                                                <td><?php echo $row['warehouseName']; ?></td>
                                                <td><?php echo $this->loadLast3Months()->loadReportedMonths($row['pkId'], 1); ?></td>
                                                <td><?php echo $this->loadLast3Months()->loadLastReportedDate($row['pkId']); ?></td>                                        
                                            </tr>
                                            <?php
                                            $count++;
                                        }
                                        ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END SAMPLE TABLE PORTLET-->
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<a id="notific8_show" href="javascript:;" class="hide"></a>
<div id="notific8_heading" class="hide">Your Data</div>
<div id="notific8_life" class="hide">5000</div>
<div id="notific8_text" class="hide">has been saved as draft.</div>
