<!-- Content -->
<div class="page-content-wrapper" xmlns="http://www.w3.org/1999/html">
    <div class="page-content">
        <h3 class="page-title"> <?php echo $this->translate("Manage Pick Stock"); ?></h3>
        <?php if (isset($_GET['success']) && $_GET['success'] == 1) { ?>
            <div class="alert alert-success">
                <button data-dismiss="alert" class="close" type="button"> ×</button>
                <strong>Stock</strong> has been picked successfully!
            </div>
        <?php } ?>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Pick From Issue Voucher List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <form method="POST" name="pickstock" action="" id="pickstock">
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="control-label" for="issueno"><?php echo $this->translate("Issue No") ?></label>
                                    <div class="controls">
                                        <?php echo $this->form->stock_master_id; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div id="ajax_tbl_data"></div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
<!-- // Content END -->
