<?php
ob_start();
?>
<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table.mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table.mytable tr td {
        border: 1px solid #444;
    }
    table.mytable tr th {
        border: 1px solid #444;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>
<?php
foreach ($this->result as $row) {
    $transaction_number = $row['transactionNumber'];
    $transaction_date = $row['transactionDate'];
    $warehouse_name = $row['warehouseName'];
    $detail_id = $row['detailId'];
    $master_id = $row['masterId'];
    $comments = $row['comments'];
    $purpose = $row['activity'];
}

//App_Controller_Functions::pr($this->result,FALSE);
?>

<div class="row">
    <div class="col-md-12">
        <table style="width:100%;">
            <tr>
                <td class="center" colspan="4"><b style="font-size: 16px;"><?php echo $this->print_title; ?></b></td>
            </tr>
            <tr>
                <td class="right" colspan="4"><b style="font-size: 16px;">Receive Voucher # <span style="font-family: Verdana; "><?php echo $transaction_number; ?></span> </b></td>
            </tr>
            <tr>
                <td><b>Received Date:</b> <?php echo date("d/m/Y", strtotime($transaction_date)); ?></td>
                <?php if (!empty($purpose)) { ?>
                    <td><b>Purpose:</b> <?php echo $purpose; ?></td>
                <?php } ?>
                <td><?php echo $this->reports()->getIssueNumberByReceiveNumber($detail_id); ?></td>
            </tr>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="mytable" cellpadding='2'>
            <tr >
                <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
                <th rowspan="2" align="left"><?php echo $this->translate("Product"); ?></th>
                <th rowspan="2" align="left"><?php echo $this->translate("Batch No"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Expiry Date"); ?></th>
                <th colspan="3" align="center"><?php echo $this->translate("Quantity"); ?></th>
                <th rowspan="2"><?php echo $this->translate("VVM Stage"); ?></th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th><?php echo $this->translate("Doses Per Vial"); ?></th>
                <th><?php echo $this->translate("Total Doses"); ?></th>
            </tr>
            <tbody>
                <?php
                $i = 0;
                if (!empty($this->result)) {
                    foreach ($this->result as $val) {
                        $batch[] = $val['number'];
                        $i++;
                        ?>
                        <tr>
                            <td align="center"><?php echo $i; ?></td>
                            <td align="left" nowrap><?php echo $val['itemName']; ?></td>	    
                            <td align="left"><?php echo $val['number']; ?></td>
                            <td align="center"><?php echo date("d/m/Y", strtotime($val['expiryDate'])); ?></td>
                            <td align="right"><?php echo number_format($val['quantity']); ?></td>
                            <td align="center"><?php echo $val['description']; ?></td>
                            <td align="right"><?php echo number_format($val['quantity'] * $val['description']); ?></td>
                            <td align="center"><?php echo (!empty($val['vvmStage']) ? $val['vvmStage'] : 'NA'); ?></td>
                        </tr>
                        <?php
                    }
                }
                ?>
            </tbody>

        </table>
    </div>
</div><br/>
<?php
$query = $this->reports()->getAdjustmentReceiveList($master_id, $this->wh_id);
if (count($query) > 0) {
    ?>
    <div class="row">
        <div class="col-md-12">
            <h4>Adjustments</h4>
            <table class="mytable" cellpadding='2'>

                <!-- Table heading -->
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th width="8%">Date</th>
                        <th align="left">Adjustment No.</th>
                        <th align="left">Product</th>
                        <th align="left">Batch No.</th>
                        <th align="right">Quantity</th>
                        <th align="left">Adjustment Type</th>
                    </tr>
                </thead>
                <!-- // Table heading END -->

                <!-- Table body -->
                <tbody>
                    <!-- Table row -->
                    <?php
                    $a = 1;
                    foreach ($query as $row) {
                        ?>
                        <tr class="gradeX">
                            <td align="center"><?php echo $a; ?></td>
                            <td align="center"><?php echo date("d/m/y", strtotime($row['transaction_date'])); ?></td>
                            <td align="left"><?php echo $row['transaction_number']; ?></td>
                            <td align="left"><?php echo $row['item_name']; ?></td>
                            <td align="left"><?php echo $row['number']; ?></td>
                            <td align="right"><?php echo number_format(abs($row['quantity'])); ?></td>
                            <td align="left"><?php echo $row['transaction_type_name']; ?></td>
                        </tr>
                        <?php
                        $a++;
                    }
                    ?>
                    <!-- // Table row END -->
                </tbody>
                <!-- // Table body END -->

            </table> 
        </div>
    </div> <br/>
<?php } ?>
<?php $query2 = $this->reports()->getSummaryList($master_id); ?>
<div class="row">
    <div class="col-md-12">
        <h5>Summary</h5>
        <table class="mytable" cellpadding='2' style="width:60%;">
            <!-- Table heading -->
            <thead>
                <tr>
                    <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
                    <th rowspan="2" align="left"><?php echo $this->translate("Product"); ?></th>
                    <th colspan="2" align="center"><?php echo $this->translate("Net Received Quantity"); ?></th>
                </tr>
                <tr>
                    <th align="right"><?php echo $this->translate("Vials/Pcs"); ?></th>
                    <th align="right"><?php echo $this->translate("Total Doses"); ?></th>
                </tr>
            </thead>
            <!-- // Table heading END -->

            <!-- Table body -->
            <tbody>
                <!-- Table row -->
                <?php
                $i = 1;
                foreach ($query2 as $row) {
                    ?>  
                    <tr>
                        <td align="center"><?php echo $i; ?></td>
                        <td align="left"><?php echo $row['item_name']; ?></td>
                        <td align="right"><?php echo number_format($row['net_received']); ?></td>
                        <td align="right"><?php echo number_format($row['total_doses']); ?></td>
                    </tr>
                    <?php
                    $i++;
                }
                ?>
                <!-- // Table row END -->
            </tbody>
            <!-- // Table body END -->

        </table> 
    </div>
</div> <br/>
<?php if (!empty($comments)) { ?>
    <div class="row">
        <div class="col-md-12">
            <b>Notes:</b><?php echo $comments; ?>
        </div>
    </div>

<?php } ?>
<div class="row"> 
    <div class="col-md-12">
        <div style="width:100%; clear:both; margin-top:20px;">
            <table width="48%" cellpadding="5" style="float:left; border:0px solid #E5E5E5 !important; border-collapse:collapse;">
                <tr>
                    <td><b>Issued by: </b></td>
                    <td>.........................................................</td>
                </tr>
                <tr>
                    <td>Name:</td>
                    <td>.........................................................</td>
                </tr>
                <tr>
                    <td>Designation:</td>
                    <td>.........................................................</td>
                </tr>
                <tr>
                    <td>Date:</td>
                    <td>.........................................................</td>
                </tr>
            </table>
            <table width="48%" cellpadding="5" style="float:right; border:0px solid #E5E5E5 !important; border-collapse:collapse;">
                <tr>
                    <td><b>Received by: </b></td>
                    <td>.........................................................</td>
                </tr>
                <tr>
                    <td>Name:</td>
                    <td>.........................................................</td>
                </tr>
                <tr>
                    <td>Designation:</td>
                    <td>.........................................................</td>
                </tr>
                <tr>
                    <td>Date:</td>
                    <td>.........................................................</td>
                </tr>
            </table>
        </div> 

    </div></div><br/>
<div class="row" style="clear: both; padding-top: 50px;">
</div>
<div class="row" style="clear: both;">
    <table width="100%">
        <tr>
            <td width="33%"><b>Prepared By:</b> <?php echo $this->getPreparedBy($this->result[0]['masterId']); ?></td>
            <td width="33%"><b>Printed By:</b> <?php echo $this->username; ?></td>            
            <td width="33%"><b>Print Serial Number:</b> <?php echo $this->print_serial; ?></td>
        </tr>
    </table>
    <div class="col-md-12 left">
        <b>Print Date:</b> <?php echo date("d/m/Y"); ?>
    </div>
</div>
<?php
file_put_contents(PUBLIC_DIR . "\prints\print-receive\\" . $this->print_serial . ".html", ob_get_contents());
?>
<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div>