<style>
    #content_print {
        margin-left: 55px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
    .watermark {
        position: absolute;
        color: #ff4c4c;
        opacity: 0.25;
        font-size: 8em;
        width: 100%;
        z-index: 1000;
        -webkit-transform: rotate(-45deg);
        -moz-transform: rotate(-45deg);
        -o-transform: rotate(-45deg);
        -ms-transform: rotate(-45deg);
        transform: rotate(-45deg);
    }
</style>

<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>
<?php
$row = $this->result[0];
$transaction_number = $row['transactionNumber'];
$transaction_date = $row['transactionDate'];
$warehouse_name = $row['warehouseName'];
$comments = $row['comments'];
$reference = $row['transactionReference'];
//$dispatch_by = $row['dispatchBy'];
$master_id = $row['pkId'];

$purpose = $row['activity'];
?>
<div class="row">
    <div class="col-md-12">
        <table style="width:100%;">
            <tr>
                <td colspan="4" class="right"><b style="font-size: 16px;">Canceled Voucher # <span style="font-family: Verdana; "><?php echo $transaction_number; ?></span> </b></td>
            </tr>
            <tr>
                <td colspan="4"><b>Date of Cancellation:</b> <?php echo date("d/m/Y", strtotime($transaction_date)); ?></td>
            </tr>
            <tr>
                <?php if (!empty($purpose)) { ?>
                    <td><b>Purpose:</b> <?php echo $purpose; ?></td>
                <?php } ?>
                <td><b>Ref. Number:</b> <?php echo (!empty($reference)) ? $reference : 'N/A'; ?></td>
                <td><b>Recipient:</b> <?php echo $warehouse_name; ?></td>
                <td class="right"><b>Transport Mode:</b> <?php echo (!empty($dispatch_by)) ? $dispatch_by : 'N/A'; ?></td>
            </tr>
        </table>
        <div class="watermark">Canceled</div>
    </div>
</div>
<div class="row">
    <div class="col-md-10">
        <table id="mytable" cellpadding="2">
            <tr >
                <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Item"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Batch Number"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Manufacturer"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Expiry Date"); ?></th>
                <th colspan="3" align="center"><?php echo $this->translate("Quantity"); ?></th>
                <th rowspan="2"><?php echo $this->translate("VVM Stage"); ?></th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th><?php echo $this->translate("Doses Per Vials"); ?></th>
                <th><?php echo $this->translate("Total Doses"); ?></th>
            </tr>
            <tbody>
                <?php
                $i = 0;
                if (!empty($this->result)) {
                    foreach ($this->result as $val) {
                        $i++;
                        ?>
                        <tr>
                            <td align="center"><?php echo $i; ?></td>
                            <td align="left" nowrap><?php echo $val['itemName']; ?></td>	    
                            <td align="left"><?php echo $val['number']; ?></td>
                            <td align="center" nowrap><?php echo $val['stakeholderName']; ?></td>
                            <td align="center"> <?php echo date("d/m/y", strtotime($val['expiryDate'])); ?></td>
                            <td align="right"><?php echo number_format($val['quantity']); ?></td>
                            <td align="center"><?php echo $val['numberOfDoses']; ?></td>
                            <td align="right"><?php echo number_format($val['quantity'] * $val['numberOfDoses']); ?></td>
                            <td align="center"><?php echo (!empty($val['vvmStage'])) ? $val['vvmStage'] : 'NA'; ?></td>
                        </tr>

                        <?php
                    }
                }
                ?>
            </tbody>
        </table>
        <br />
    </div>
</div>
<?php $query2 = $this->reports()->getCancelSummaryList($master_id); ?>
<div class="row">
    <div class="col-md-6">

        <h5>Summary</h5>
        <table id="mytable" style="width:60%;" cellpadding="2">
            <!-- Table heading -->
            <thead>
                <tr>
                    <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
                    <th rowspan="2" align="left"><?php echo $this->translate("Item"); ?></th>
                    <th colspan="2" align="center"><?php echo $this->translate("Quantity"); ?></th>
                </tr>
                <tr>
                    <th align="right"><?php echo $this->translate("Vials/Pcs"); ?></th>
                    <th align="right"><?php echo $this->translate("Doses/Pcs"); ?></th>
                </tr>
            </thead>
            <!-- // Table heading END -->
            <!-- Table body -->
            <tbody>
                <!-- Table row -->
                <?php
                $total = 0;
                $i = 1;
                foreach ($query2 as $row) {
                    $total = $total + $row['total_cost'];
                    ?>  
                    <tr>
                        <td align="center"><?php echo $i; ?></td>
                        <td align="left"><?php echo $row['item_name']; ?></td>
                        <td align="right"><?php echo number_format($row['net_received']); ?></td>
                        <td align="right"><?php echo number_format($row['total_doses']); ?></td>
                    </tr>
                    <?php
                    $i++;
                }
                ?>
                <!-- // Table row END -->
            </tbody>
            <!-- // Table body END -->
            <!-- <tfoot>
                <tr>
                    <td colspan="4" class="right"><b>Total Price: </b> <b><?php //echo round(number_format($total),2);       ?> (Rs.)</b></td>
                </tr>
            </tfoot> -->
        </table> 
    </div>
</div><br>
<?php if (!empty($this->result[0]['issue_from'])) { ?>
    <div class="row">
        <div class="col-md-6">
            <b>Issuance for the period of: </b>From <?php echo $this->result[0]['issue_from']; ?> To <?php echo $this->result[0]['issue_to']; ?>
        </div>
    </div> <?php } ?>
<?php if (!empty($comments)) { ?>
    <div class="row">
        <div class="col-md-12">
            <b>Notes:</b> <?php echo $comments; ?>
        </div>
    </div>
<?php } ?>
<div class="row"> 
    <div style="width:100%; clear:both; margin-top:30px;">
        <table width="48%" cellpadding="5" style="float:left; border:0px solid #E5E5E5 !important; border-collapse:collapse;">
            <tr>
                <td><b>Issued by: </b></td>
                <td>.........................................................</td>
            </tr>
            <tr>
                <td>Name:</td>
                <td>.........................................................</td>
            </tr>
            <tr>
                <td>Designation:</td>
                <td>.........................................................</td>
            </tr>
            <tr>
                <td>Date:</td>
                <td>.........................................................</td>
            </tr>
        </table>
        <table width="48%" cellpadding="5" style="float:right; border:0px solid #E5E5E5 !important; border-collapse:collapse;">
            <tr>
                <td><b>Received by: </b></td>
                <td>.........................................................</td>
            </tr>
            <tr>
                <td>Name:</td>
                <td>.........................................................</td>
            </tr>
            <tr>
                <td>Designation:</td>
                <td>.........................................................</td>
            </tr>
            <tr>
                <td>Date:</td>
                <td>.........................................................</td>
            </tr>
        </table>
    </div>
</div>

<div class="row" style="clear: both; padding-top: 20px;">
    <div class="col-md-12 center"><br><br>
        ...............................................<br>
        <b>IN-CHARGE STORE</b><br>
        <b><?php echo $this->department; ?></b>
    </div>
</div><br>
<div class="row" style="clear: both;">
    <table width="100%">
        <tr>
            <td width="33%"><b>Prepared By:</b> <?php echo $this->getPreparedBy($this->result[0]['pkId']); ?></td>
            <td width="33%"><b>Print By:</b> <?php echo $this->username; ?></td>            
            <td width="33%"><b>Print Serial Number:</b> <?php echo $this->print_serial; ?></td>
        </tr>
    </table>
</div>
<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div>