<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            Priority Vaccines Distribution
        </h3>  
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3 right">
                <div data-toggle="buttons" class="btn-group btn-group-justified">
                    <label class="btn blue">
                        <input type="radio" class="toggle" value="1"> Summary</label>
                    <label class="btn blue active">
                        <input type="radio" class="toggle" value="2"> Detail </label>
                </div>
                <!-- <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                <?php //echo $this->translate("Search Filters"); ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse"></a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form method="POST" name="ledger" action="" id="product_plac">
                            <div class="row">
                                <div class="col-md-12">                                
                <!-- Row -->
                <!-- <div class="row">
                    <div class="col-md-3">
                        <div class="form-group" style="margin-top: 31px">
                            <label class="control-label" for="type"><?php //echo $this->translate(" ")   ?></label>

                <?php //echo $this->form->detail_summary; ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label" for="button">&nbsp;</label><br/>
                            <input type="submit" class="btn btn-success" name="submit" id="submit" value="Submit" />
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>
</div> -->
            </div>
        </div>
        <div  id="priority-vaccine">

        </div>        
    </div>
</div>