<style>
#content_print {
    margin-left: 50px;
    width: 624px;
}
table#mytable {
    border: 1px solid #e5e5e5;
    font-size: 9pt;
    width: 100%;
}
table#mytable tr td {
    border: 1px solid #e5e5e5;
}
table#mytable tr th {
    border: 1px solid #e5e5e5;
}
</style>
<!-- Content -->

 <style type="text/css" media="print">
        .page
        {
            -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
            filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
        }
        @media print
        {    
            #printButt
            {
                display: none !important;
            }
        }
    </style>

    <table id="mytable" >
        <thead>
            <tr>
                <th rowspan="2" width="5%"><?php echo $this->translate("S. No."); ?></th>
                <th rowspan="2" width="10%"><?php echo $this->translate("Date"); ?></th>
                <th rowspan="2" width="10%" ><?php echo $this->translate("Product"); ?></th>
                <th rowspan="2"  width="10%" ><?php echo $this->translate("Received From"); ?></th>
                <th rowspan="2"  width="20%" ><?php echo $this->translate("Ref.No."); ?></th>
                <th rowspan="2"  width="10%"><?php echo $this->translate("Batch No."); ?></th>
                <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
                <th rowspan="2" width="10%"><?php echo $this->translate("Expiry Date"); ?></th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th width="10%"><?php echo $this->translate("Doses Per Vial"); ?></th>
                <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 0;
            if (!empty($this->result)) {
                foreach ($this->result as $row) {
                    $i++;
                    ?>
                    <tr>
                        <td align="right"><?php echo $i; ?></td>
                        <td align="center"><?php echo date("m/d/y", strtotime($row['transactionDate'])); ?></td>	    
                        <td align="left"><?php echo $row['itemName']; ?></td>
                        <td align="left"><?php echo $row['warehouseName']; ?></td>
                        <td align="left"><?php echo '&nbsp;' . $row['transactionReference']; ?></td>
                        <td align="right"><?php echo $row['number']; ?></td>
                        <td align="right"><?php echo number_format($row['quantity']); ?></td>
                        <td align="right"><?php echo number_format($row['description']) ?></td>
                        <td align="right"><?php echo number_format($row['quantity'] * $row['description']) ?></td>
                        <td align="center"><?php echo date("m/d/y", strtotime($row['expiryDate'])); ?></td>
                    </tr>
                    <?php
                }
            }
            ?>
        </tbody>

    </table>
   
    <br />
   
       <div style="float:left;">
   
        <b>Print Date:</b> <?php echo date('d/m/y').' <b>by</b> '.$this->username;?>
    </div>  
       
  
    <div class="col-md-12" class="widget">
        <div class="widget-body right">
            <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
        </div>
    </div> 	  

<!-- // Content END -->
