<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page
    {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>
<div style="text-align:center;">
    <b style="float:left;">Issue Date: <?php echo date("m/d/Y", strtotime($this->arr_data[0]['transactionDate'])); ?></b>
    <b style="float:right;"></b><br />
</div>
<div style="text-align:center;">
    <b style="float:left;">Entered By: <?php echo $this->username; ?></b>
    <b style="float:right;">Request Number: ____________ <?php //echo $_REQUEST['refrenceno']; ?></b><br />
</div>
<div style="clear:both;">
    <b style="float:left;">Recipient: <?php echo $this->arr_data[0]['warehouseName']; ?></b>
    <b style="float:right;">Dispatch Voucher No: ____________ </b>
</div>
<div style="clear:both;">
    <b style="float:left;">Through: ____________</b>
    <b style="float:right;">Designation: ____________ </b>
</div>
<div style="clear:both;">
    <b style="float:left;">Name of Driver: ____________</b>
    <b style="float:right;">Vehicle No.: ____________ </b>
</div>
<div style="clear:both;">
    <b style="float:left;">Issued to DOH/EDO: ____________</b>
   
</div>

<table id="mytable">
    <tr >
        <th rowspan="2" width="5%"><?php echo $this->translate("Sr No"); ?></th>
        <th rowspan="2" width="10%"><?php echo $this->translate("Product"); ?></th>
        <th rowspan="2" width="10%"><?php echo $this->translate("Batch No"); ?></th>
        <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
      
        
        <th rowspan="2" width="9%"><?php echo $this->translate("VVM Stage"); ?></th>
      
        <th rowspan="2" width="10%"><?php echo $this->translate("Expiry Date"); ?></th>
    </tr>
    <tr style="background-color: #F8F8F8;">
        <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
        <th width="10%"><?php echo $this->translate("Doses Per Vial"); ?></th>
        <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
    </tr>
    <tbody>
        <?php
        $i = 0;
        if (!empty($this->arr_data)) {
            
            foreach ($this->arr_data as $val) {
                $i++;
                ?>
        
                <tr>
                    <td align="right"><?php echo $i; ?></td>
                    <td align="left"><?php echo $val['itemName']; ?></td>	    
                    <td align="right"><?php echo $val['number']; ?></td>
                    <td align="right"><?php echo $val['quantity']; ?></td>
                    <td align="right"><?php echo $val['description']; ?></td>
                    <td align="right"><?php echo $val['quantity'] * $val['description']; ?></td>
                    
                 
                    <td align="right"><?php echo '&nbsp;' . $val['vvmStage']; ?></td>
                   
                    <td align="center"> <?php echo date("m/d/y", strtotime($val['expiryDate'])); ?></td>
                </tr>
                <?php
            }
        }
        ?>
                 <?php
                                    $i = 0;
                                    $summary_arr = array();
                                    $product = '0';
                                    foreach ($this->arr_data as $val) {
                                        
                                        $i++;
                                        if ($product != $val['itemName']) {
                                            $summary_arr[$val['itemName']]['quantity'][] = abs($val['quantity']);
                                            $summary_arr[$val['itemName']]['doses'][] = ($val['description'] * abs($val['quantity']));
                                            $product = $val['itemName'];
                                        } else {
                                            $summary_arr[$val['itemName']]['quantity'][] = abs($val['quantity']);
                                            $summary_arr[$val['itemName']]['doses'][] = ($val['description'] * abs($val['quantity']));
                                        }
                                    }
                                        ?>
    </tbody>

</table>
<br />

   <h5 style="margin-top:30px;" class="heading">Summary</h5>
    <table id="mytable" style="width:70%;">
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity/Dose</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach( $summary_arr as $product=>$qty)
        {
        ?>
            <tr>
                <td><?php echo $product;?></td>
                <td><?php echo number_format(array_sum($summary_arr[$product]['quantity'])) . ' / ' .number_format(array_sum($summary_arr[$product]['doses']));?></td>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
<div style="width:100%; clear:both; margin-top:30px;">
    <table width="48%" cellpadding="5" style="float:left; border:2px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Issued by</b> - Name: ____________________________</td>
        </tr>
        <tr>
            <td>Designation: __________________________________</td>
        </tr>
        <tr>
            <td>Signature: ____________________________________</td>
        </tr>
    </table>
    <table width="48%" cellpadding="5" style="float:right; border:2px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Received by</b> - Name: _________________________</td>
        </tr>
        <tr>
            <td>Designation: __________________________________</td>
        </tr>
        <tr>
            <td>Signature: ____________________________________</td>
        </tr>
    </table>
</div>
<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div> 	  



