<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #e5e5e5;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #e5e5e5;
    }
    table#mytable tr th {
        border: 1px solid #e5e5e5;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page
    {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>
<?php
if ($this->result && count($this->result) > 0) :
    foreach ($this->result as $val) {
        $productArr[$val['itemName']][] = $val;
        $locationArr[$val['warehouseName']][] = $val;
    }
endif;
?>
<table style="width:100%;">
    <tr>
        <td class="center" colspan="3"><b style="font-size: 16px;"><?php echo $this->print_title?> from <?php echo $_GET['date_from']; ?> to <?php echo $_GET['date_to']; ?> </b></td>
    </tr>
</table>
<?php
if ($this->result && count($this->result) > 0 && $this->val == 'prod') {
    //echo "<pre>";
    foreach ($productArr as $key => $data) {
        ?>
        <b><?php echo $key; ?></b>
        <table id="mytable">
            <tr>
                <th rowspan="2" width="10%"><?php echo $this->translate("S No") ?></th>
                <th rowspan="2" width="17%"><?php echo $this->translate("Issue") ?><br><?php echo $this->translate("Date") ?></th>
                <th rowspan="2"><?php echo $this->translate("Issued To") ?></th>  
                <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>

            </tr>
            <tr style="background-color: #F8F8F8;">
                <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th width="10%"><?php echo $this->translate("Doses Per Vials"); ?></th>
                <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
            </tr>
            <tbody>
                <?php
                $i = 0;
                $totalVials = 0;
                $totalDoses = 0;
                foreach ($data as $val) {
                    $i++;

                    $totalVials += abs($val['quantity']);
                    $totalDoses += ($val['description'] * abs($val['quantity']));
                    ?>

                    <tr>
                        <td style="text-align:right;"><?php echo $i; ?></td>
                        <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($val['transactionDate'])); ?></td>
                        <td style="text-align:left;"><?php echo $val['warehouseName']; ?> </td>

                        <td style="text-align:right;"><?php echo number_format($val['quantity']); ?></td>
                        <td style="text-align:right;"><?php echo $val['description'] ?></td>
                        <td style="text-align:right;"><?php echo number_format(($val['description'] * abs($val['quantity']))); ?></td>

                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td colspan="3" style="text-align: right;"><b>Total</b></td>
                    <td style="text-align: right;"><b><?php echo number_format($totalVials); ?></b></td>
                    <td>&nbsp;</td>
                    <td style="text-align: right;"><b><?php echo number_format($totalDoses); ?></b></td>
                </tr>
            </tbody>
        </table>
        <?php
    }
}
if ($this->result && count($this->result) > 0 && $this->val == 'loc') {
    //echo "<pre>";
    foreach ($locationArr as $key => $data) {
        ?>
        <b><?php echo $key; ?></b>
        <table id="mytable">
            <tr>
                <th rowspan="2" width="10%"><?php echo $this->translate("S No") ?></th>
                <th rowspan="2" width="17%"><?php echo $this->translate("Issue") ?><br><?php echo $this->translate("Date") ?></th>
                <th rowspan="2"><?php echo $this->translate("Product") ?></th>
                <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th width="8%"><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th width="10%"><?php echo $this->translate("Doses Per Vials"); ?></th>
                <th width="10%"><?php echo $this->translate("Total Doses"); ?></th>
            </tr>
            <tbody>
                <?php
                $i = 0;
                $totalVials = 0;
                $totalDoses = 0;
                foreach ($data as $val) {
                    $i++;
                    $totalVials += abs($val['quantity']);
                    $totalDoses += ($val['description'] * abs($val['quantity']));
                    ?>
                    <tr>
                        <td style="text-align:right;"><?php echo $i; ?></td>
                        <td style="text-align:center;"><?php echo date("d/m/Y", strtotime($val['transactionDate'])); ?></td>
                        <td><?php echo $val['itemName']; ?></td>
                        <td style="text-align:right;"><?php echo number_format($val['quantity']); ?></td>
                        <td style="text-align:right;"><?php echo $val['description'] ?></td>
                        <td style="text-align:right;"><?php echo number_format(($val['description'] * abs($val['quantity']))); ?></td>
                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td colspan="3"  style="text-align: right;"><b>Total</b></td>
                    <td style="text-align: right;"><b><?php echo number_format($totalVials); ?></b></td>
                    <td>&nbsp;</td>
                    <td style="text-align: right;"><b><?php echo number_format($totalDoses); ?></b></td>
                </tr>
            </tbody>
        </table>
        <?php
    }
}
?>
<div style="float:left;">

    <b>Print Date:</b> <?php echo date('d/m/Y') . ' <b>by</b> ' . $this->username; ?>
</div>  
<div class="col-md-12" class="widget">

    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary"><?php echo $this->translate("Print") ?></button>
    </div>
</div> 	  



