<?php
/**
 *  phtml for Search Log Book
 */
?>
<!-- Content -->

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            <?php echo $this->translate("Approval"); ?>
        </h3>

        <?php //if ($this->arr_data && count($this->arr_data) > 0) { ?>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php
                            echo $this->translate("Requisitions");
                            ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-striped table-bordered table-condensed" >
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th>
                                                <?php echo $this->translate("S.No"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Date"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Requisition #"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("From Warehouse"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Suggested Delivery Date"); ?>
                                            </th>
                                            <th>
                                                <?php echo $this->translate("Status"); ?>
                                            </th>

                                        </tr>

                                    </thead>
                                    <!-- // Table heading END -->

                                    <!-- Table body -->
                                    <tbody>

                                        <!-- Table row -->
                                        <?php
                                        $j = 1;
                                        //foreach ($this->arr_data as $row) {
                                        ?>
                                        <tr>
                                            <td align="center">
                                                1
                                            </td>
                                            <td align="left">
                                                28-01-2016
                                            </td>
                                            <td >
                                                R123456
                                            </td>
                                            <td >
                                                Punjab EPI Store
                                            </td>
                                            <td >
                                                02-14-2016
                                            </td>
                                            <td align="left">
                                                Pending
                                            </td>


                                        </tr>
                                        <?php
                                        $j ++;
                                        // }
                                        ?>
                                        <!-- // Table row END -->
                                    </tbody>
                                    <!-- // Table body END -->                                      

                                </table>

                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <?php
        // } else {
        ?>
        <!--            <div class="row">
                        <div class="col-md-12">
                            <h4>No data found</h4>
                        </div>
                    </div>-->
        <?php // }  ?>

        <form action="" name="approval-form" id="approval-form">

            <?php if ($this->products && count($this->products) > 0) { ?>
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box green">
                            <div class="portlet-title">
                                <div class="caption">
                                    <?php
                                    echo $this->translate("Requisition Detail");
                                    ?>
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <table class="table table-striped table-bordered table-condensed" >
                                            <!-- Table heading -->
                                            <thead>
                                                <tr>
                                                    <th>
                                                        <?php echo $this->translate("S.No"); ?>
                                                    </th>
                                                    <th>
                                                        <?php echo $this->translate("Product"); ?>
                                                    </th>
                                                    <th>
                                                        <?php echo $this->translate("Remaining Quantity"); ?>
                                                    </th>
                                                    <th>
                                                        <?php echo $this->translate("Demanded Quantity"); ?>
                                                    </th>
                                                    <th>
                                                        <?php echo $this->translate("Approved Quantity"); ?>
                                                    </th>

                                                </tr>

                                            </thead>
                                            <!-- // Table heading END -->

                                            <!-- Table body -->
                                            <tbody>

                                                <!-- Table row -->
                                                <?php
                                                $j = 1;
                                                foreach ($this->products as $row) {
                                                    ?>
                                                    <tr>
                                                        <td >
                                                            <?php echo $j ?>
                                                        </td>
                                                        <td align="left">
                                                            <?php echo $row['itemName'] ?>
                                                        </td>
                                                         <td align="center">
                                                            1000
                                                        </td>
                                                        <td align="center">
                                                            2000
                                                        </td>
                                                        <td >

                                                            <div class="control-group">
                                                                <div class="controls">
                                                                    <input type="text" class="form-control" id="<?php echo $row['pkId'] ?>" name="<?php echo $row['pkId'] ?>">
                                                                </div>
                                                            </div>
                                                        </td>

                                                    </tr>
                                                    <?php
                                                    $j ++;
                                                }
                                                ?>
                                                <!-- // Table row END -->
                                            </tbody>
                                            <!-- // Table body END -->                                      

                                        </table>

                                    </div>
                                </div>
                                <div class="col-md-6 col-md-offset-3">
                                    <br><br>
                                    <label class="control-label" for="">
                                        <?php echo $this->translate("Requisition Period: 3rd Qtr 2016"); ?>
                                    </label>
                                    <br>
                                     <label class="control-label" for="district">
                                        <?php echo $this->translate("Requisition Date: 28-01-2016"); ?>
                                    </label>
                                    <div class="pull-right">
                                        <a href="">View Attachment</a><i class="fa fa-paperclip"></i>

                                    </div>
                                    <br><br>
                                    Delivery Date
                                    <table class="table table-striped table-bordered table-condensed"  >
                                        
                                        <thead>
                                            <tr>
                                                <th>Suggested Date</th>
                                                <td>02-04-2016</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th>New Suggested Date</th>
                                                <td><?php echo $this->form->new_suggested_date; ?></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <br><br><br><br><br><br>
                                <div class="row">
                                    <div class="col-md-12 right">
                                        <button class="btn btn-primary" onclick="return confirm('Are you sure you want to approve the requsition?');" type="submit"> Approve </button>
                                        <button class="btn btn-primary" onclick="return confirm('Are you sure you want not to approve the requsition?');" type="submit"> Not Approve </button>
                                        <button class="btn btn-primary" onclick="return confirm('Are you sure you want to Cancel the approval?');" type="submit"> Cancel </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            } else {
                ?>
                <!--            <div class="row">
                                <div class="col-md-12">
                                    <h4>No data found</h4>
                                </div>
                            </div>-->
            <?php } ?>

        </form>

    </div>
</div>

