CampaignLqasData:
  type: entity
  table: campaign_lqas_data
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    surveyor:
      type: string
      length: 255
      fixed: false
      nullable: true
    checked:
      type: string
      length: 255
      fixed: false
      nullable: true
    unvaccinated:
      type: string
      length: 255
      fixed: false
      nullable: true
    remarks:
      type: text
      nullable: true
    createdDate:
      type: datetime
      nullable: false
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    unionCouncil:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        union_council_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    campaign:
      targetEntity: Campaigns
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        campaign_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    district:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        district_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
