DemandFiles:
  type: entity
  table: demand_files
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    fileName:
      type: text
      nullable: true
      column: file_name
    createdBy:
      type: integer
      unsigned: false
      nullable: false
      column: created_by
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedBy:
      type: integer
      unsigned: false
      nullable: false
      column: modified_by
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    demandMaster:
      targetEntity: DemandMaster
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        demand_master_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
