PipelineConsignmentsPlacements:
  type: entity
  table: pipeline_consignments_placements
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    batchNumber:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: batch_number
    quantity:
      type: decimal
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    pipelineConsignment:
      targetEntity: PipelineConsignments
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        pipeline_consignment_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    placementLocation:
      targetEntity: PlacementLocations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        placement_location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
