ReportOptions:
  type: entity
  table: report_options
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    reportId:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: report_id
    reportTitleSql:
      type: string
      length: 1000
      fixed: false
      nullable: true
      column: report_title_sql
    reportDataSql:
      type: string
      length: 1000
      fixed: false
      nullable: true
      column: report_data_sql
    reportStakeholder:
      type: integer
      unsigned: false
      nullable: false
      column: report_stakeholder
    reportComparision:
      type: integer
      unsigned: false
      nullable: true
      column: report_comparision
    reportDataPosition:
      type: integer
      unsigned: false
      nullable: true
      column: report_data_position
    reportComparisionFlag:
      type: integer
      unsigned: false
      nullable: true
      column: report_comparision_flag
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
