WarehousePopulationArchieve:
  type: entity
  table: warehouse_population_archieve
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    facilityTotalPouplation:
      type: integer
      unsigned: false
      nullable: true
      column: facility_total_pouplation
    liveBirthsPerYear:
      type: integer
      unsigned: false
      nullable: true
      column: live_births_per_year
    pregnantWomenPerYear:
      type: integer
      unsigned: false
      nullable: true
      column: pregnant_women_per_year
    womenOfChildBearingAge:
      type: integer
      unsigned: false
      nullable: true
      column: women_of_child_bearing_age
    estimationYear:
      type: datetime
      nullable: true
      column: estimation_year
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
