<div class="page-content-wrapper">
    <div class="page-content">
    <h3 class="page-title"></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">

                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="getting-started-wrapper">
                                    <p>Welcome, <span style="color: #128000;"><?php echo $this->layout()->user_name; ?>!</span></p>
                                    <h1>Getting Started <img src="<?php echo $this->baseUrl(); ?>/images/logo-pak.png" alt="" style="float: right; position: relative; right: 68px; top: -33px;" /></h1>
                                    <hr />
                                    <p>with Vaccine Logistics Managment Information System (vLMIS)</p>
                                    <div class="info-box" style="border-left: none;">
                                        <h4><img src="<?php echo $this->baseUrl(); ?>/images/icon-monthly.png" alt="" />Monthly Reports</h4>
                                        <p>View monthly reported data for all of the reporting levels.</p>
                                        <strong>To do's</strong>
                                        <ul class="landingul">
                                            <li>National Report</li>
                                            <li>Provincial Report</li>
                                            <li>Divisional Report</li>
                                            <li>District Report</li>
                                            <li>Tehsil Report</li>
                                            <li>UC Report</li>
                                        </ul>
                                    </div>

                                    <div class="info-box">
                                        <h4><img src="<?php echo $this->baseUrl(); ?>/images/icon-annual.png" alt="" />Annual Reports</h4>
                                        <p>View annual report for the central, provincial and district level.</p>
                                        <strong>To do's</strong>
                                        <ul class="landingul">
                                            <li>Central/Provincial</li>
                                            <li>WH Report</li>
                                            <li>District Annual Report</li>
                                            <li>Sub-District Annual Report</li>
                                        </ul>
                                    </div>

                                    <div class="info-box">
                                        <h4><img src="<?php echo $this->baseUrl(); ?>/images/icon-graph.png" alt="" /> Graph Reports</h4>
                                        <p>View simple graphs of indicators or compare them for data analysis.</p>
                                        <strong>To do's</strong>
                                        <ul class="landingul">
                                            <li>View simple graphs</li>
                                            <li>View comparison graphs</li>
                                        </ul>
                                    </div>

                                    <div class="info-box">
                                        <h4><img src="<?php echo $this->baseUrl(); ?>/images/icon-explorer.png" alt="" />vLMIS Explorer</h4>
                                        <p>View Individual store/warehouse monthly submitted reports</p>
                                        <strong>Shows</strong>
                                        <ul class="landingul">
                                            <li>Opening and Closing balances</li>
                                            <li>Issue & dispensed stocks</li>
                                            <li>Receive stocks during month</li>
                                        </ul>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>