<div id="dashletCCC" style="width:500px;height:400px;position:relative">
    <div style="width:50%;height:30px;position: absolute;top:0px;left:10%;z-index: 2000">
        <div class="col-md-8"> 
            <div class="control-group ">
                <div class="controls">
                    <b><?php echo $this->translate("Type"); ?>: <?php echo $this->form->coldchain_type; ?></b>
                </div>
            </div>
        </div>
    </div>
    <div id="legendDivCapacity" style="display:none;position:absolute;padding:6px;border-radius:5px;border:1px solid black;width:auto;height:auto;top:65%;font-size:10px;font-weight:bold;left:66%;z-index: 1000;">
        <table id='legendCapacity' style="width:100%"></table>
    </div>  
    <div id="ccInfoDiv" style="position:absolute;top:24%;left:2%;width:auto;height:auto;opacity : 0.85; border-radius:4px;background-color:green;color:white;text-align:center;padding: 3px;font-family: Arial;z-index:5000;"></div>
</div>     
