<style>
    #content_print {
        margin-left: 55px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
</style>
<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>
<div class="row">
    <div class="col-md-12">
        <h4>Cold Chain Capacity by Utilization</h4>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table id="mytable">
            <tr>
                <th>Cold Room</th>
                <th class="right">Gross (In Litres)</th>
                <th class="right">Net Usable (In Litres)</th>
                <th class="right" colspan="2">Being Used (In Litres/Percentage)</th>
            </tr>
            <?php foreach ($this->data as $row) { ?>
                <tr>
                    <td><?php echo $row['asset_id']; ?></td>
                    <td class="right"><?php echo number_format($row['gross']); ?></td>
                    <td class="right"><?php echo number_format($row['net_usable']); ?></td>
                    <td class="right"><?php echo number_format($row['being_used']); ?></td>
                    <td class="right"><?php echo ROUND($row['being_used'] * 100 / $row['net_usable']); ?>%</td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12 right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div>