<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
<!--        <h3 class="page-title">Demographic Map</h3>-->

        <div class="row">
            <div class="col-md-12">
                <div class="map-buttons-download">
                    <img id="image"  src="<?php echo $this->baseUrl(); ?>/images/image.png"  align="right" title="Download Map" />
                    <img id="excel"  src="<?php echo $this->baseUrl(); ?>/images/excel-32.png"  align="right" title="Download Excel" />
                </div>
            </div>
        </div>
        <div class="row">
            
            
            
             <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        Demographic Map
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div id="capture" style="width:auto;height:auto">
                                <table width="100%" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td width="100%">
                                            <div id="map">
                                                <div id="customZoom">
                                                  <a href="#customZoomIn" id="customZoomIn">in</a>
                                                    <a href="#customZoomOut" id="customZoomOut">out</a>
                                                </div>
                                                <img id="loader" src="<?php echo $this->baseUrl(); ?>/images/ajax-loader.gif" />
                                                <div id="info" class="CSSTableGenerator">
                                                    <table>
                                                    <tr>
                                                        <td colspan="2">District Information</td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Province</b></td>
                                                        <td style='width:100px;' id="prov"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>District</b></td>
                                                        <td style='width:100px;' id="dist"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Tehsils</b></td>
                                                        <td style='width:100px;' id="tehsils"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Ucs</b></td>
                                                        <td style='width:100px;' id="ucs"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Users</b></td>
                                                        <td style='width:100px;' id="users"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Facility</b></td>
                                                        <td style='width:100px;' id="facility"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Population</b></td>
                                                        <td style='width:100px;' id="pop"></td>
                                                    </tr>
                                                    </table>
                                                </div>
                                                <div id="mapTitle"></div>
                                                <div id="printedDate"></div>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            
            
            
            
<!--            <div class="col-md-12">
                
                <div id="capture" style="width:auto;height:auto">
                                <table width="100%" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td width="100%">
                                            <div id="map">
                                                <div id="customZoom">
                                                  <a href="#customZoomIn" id="customZoomIn">in</a>
                                                    <a href="#customZoomOut" id="customZoomOut">out</a>
                                                </div>
                                                <img id="loader" src="<?php echo $this->baseUrl(); ?>/images/ajax-loader.gif" />
                                                <div id="info" class="CSSTableGenerator">
                                                    <table>
                                                    <tr>
                                                        <td colspan="2">District Information</td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Province</b></td>
                                                        <td style='width:100px;' id="prov"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>District</b></td>
                                                        <td style='width:100px;' id="dist"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Tehsils</b></td>
                                                        <td style='width:100px;' id="tehsils"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Ucs</b></td>
                                                        <td style='width:100px;' id="ucs"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Users</b></td>
                                                        <td style='width:100px;' id="users"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Facility</b></td>
                                                        <td style='width:100px;' id="facility"></td>
                                                    </tr>
                                                    <tr>
                                                        <td><b>Population</b></td>
                                                        <td style='width:100px;' id="pop"></td>
                                                    </tr>
                                                    </table>
                                                </div>
                                                <div id="mapTitle"></div>
                                                <div id="printedDate"></div>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                </div>
                              
            </div>
            -->
            
                <div class="col-md-12">
                    
                      <div class="col-md-8">
                            <div class="widget" data-toggle="collapse-widget">
                                <div class="widget-head">
                                    <h3 class="heading">District wise Demographic Details</h3>
                                </div>
                                <div class="widget-body">
                                    <div id='attributeGrid' class="CSSTableGenerator"></div>
                                </div>
                            </div>
                        </div>
                    
                     <div class="col-md-4">
                            <div class="widget" data-toggle="collapse-widget">
                                <div class="widget-head">
                                    <h3 class="heading">Product wise Yearly Targets</h3>
                                </div>
                                <div class="widget-body">
<!--                                    <div id='attributeGrid' class="CSSTableGenerator"></div>-->
                                </div>
                            </div>
                        </div>
                    
                    
                </div>  
        </div>
    </div>
</div>
    <!-- // Content END -->