<div class="row">
    <div class="col-md-6">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Top Level"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->geo_level; ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Sector"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->sector; ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Activites Supported"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->activity; ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Stakeholder"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->stakeholder_name; ?>  
            </div>
        </div>
    </div>
</div>
<?php echo $this->form->stakeholder_id; ?>
