<div class="col-md-6">
    <?php
    FC_SetRenderer('javascript');
    echo renderChart("FusionCharts/Charts/Pie2D.swf", "", $this->xmlstore, 'vvmStageStatus', '100%', 395, false, false);
    ?>
</div>
<div class="col-md-6" id="data15">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-picture"></i>Vvm Stage Status
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>
                                S.No
                            </th>
                            <th>
                                Batch Name
                            </th>
                            <th>
                                Quantity
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $count = 1;
                        foreach ($this->data as $row) {
                            ?>
                            <tr>
                                <td><?php echo $count; ?></td>
                                <td><?php echo $row['number']; ?></td>
                                <td><?php echo number_format($row['Qty']); ?></td>
                            </tr>
                            <?php
                            $count++;
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>