<div class="row">
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Sector"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->sector; ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Manufacturer"); ?> <span class="red">*</span></label>
            <div class="controls">
                <?php echo $this->form->manufacturer; ?>  
            </div>
        </div>
    </div>

</div>
<?php echo $this->form->stakeholder_id; ?>
