<?php
/**
*  phtml for Ajax Item Units Edit
*/
?>
<div class="row">
<div class="col-md-4">
    <div class="control-group ">
        <label class="control-label" ><?php echo $this->translate("Item Unit"); ?></label>
        <div class="controls">
            <?php echo $this->form->item_unit_name; ?>
        </div>
    </div>
</div>
</div>
<?php 
echo $this->form->item_unit_id;
echo $this->form->item_unit_name_hidden;
?>
