<?php
/**
*  phtml for VVM Type
*/
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage VVM Groups") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                    
                    
                        
                            <div class="col-md-12">
                                <?php if (isset($_GET['success']) && $_GET['success'] == 1) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been saved successfully!
                                    </div>
                                <?php
                                }

                                if (isset($_GET['success']) && $_GET['success'] == 2) {
                                    ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been updated successfully!
                                    </div>
                                <?php }
                                ?>
                                
                                <?php
                                

                                if (isset($_GET['success']) && $_GET['success'] == 3) {
                                    ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> has been deleted successfully!
                                    </div>
                                <?php }
                                ?>
                                <?php
                                

                                if (isset($_GET['success']) && $_GET['success'] == 4) {
                                    ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> Ã—</button>
                                        <strong>Data</strong> couldn't be modified!
                                    </div>
                                <?php }
                                ?>
                                
                            </div>
                       
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
<?php echo $this->translate("VVM Groups List") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
<?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" data-toggle="modal" href="#add-vvm-group"><?php echo $this->translate("Add VVM Group") ?></a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            's_no' => 'S.No',
                                            'vvm_type_name' => 'VVM Group',                                            
                                            'created_by' => 'VVM Stages',
                                            
                                        );
                                        
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        
                                        <tbody>
                                            <?php
                                            $m_res = array();
                                            $i = $this->count;
                                            $data = $this->paginator;
                                            if ($data != false) :
                                                foreach ($data as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td class="center" width="25"><?php echo $i; ?></td>
                                                        <td><?php echo $row['vvmGroupId']; ?></td>
<!--                                                        <td><?php echo $row['vvmGroupId']; ?></td>-->
                                                        <td><?php echo $row['vvmstages']; ?></td>
                                                        <td>
                                                            <a itemid="<?php echo $row['vvmGroupId']; ?>" stages="<?php echo $row['vvmstages']; ?>" class="btn update-vvm-group btn-link btn-success btn-sm" data-toggle="modal" href="#modal-update-vvm-group"><?php echo $this->translate("Edit") ?></a>
                                                            <?php if(!isset($row['item_name'])){ ?>
                                                            <a id="<?php echo $row['vvmGroupId']; ?>" href="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/delete-vvm-group?id=<?php echo $row['vvmGroupId']; ?>" class="btn active btn-link btn-danger btn-sm"><?php echo $this->translate("Delete"); ?></a>
                                                            <?php } ?>
                                                        </td>
                                                    </tr>
                                                    <!-- // Table row END --><?php
                                                    $i++;
                                                endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                        <!-- // Table body END -->
                                    </table>
                                    <?php
                                    if ($data != false) :
                                        echo $this->paginationControl($data, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params));
                                    endif;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- // modal box for add -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/add-vvm-group" id="add-vvm-groups">
            <div class="modal fade" id="add-vvm-group" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Add VVM Group</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group ">
                                        <label class="control-label" ><?php echo $this->translate("VVM Group Id"); ?> <span class="red">*</span></label>
<?php echo $this->form->vvm_group_id; ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group" id="div_stages">
                                        <label class="control-label" ><?php echo $this->translate("VVM Stages"); ?> <span class="red">*</span></label>
                                        <div>
                                            <?php echo $this->form->stages; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input id="save" class="btn btn-primary" type="submit" value="<?php echo $this->translate("Save"); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="<?php echo $this->baseUrl(); ?>/iadmin/manage-products/update-vvm-group" id="update-vvm-groups">
            <div class="modal fade" id="modal-update-vvm-group" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Edit VVM Group</h4>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <input id='update' class="btn btn-primary" type="submit" value="<?php echo $this->translate("Update"); ?>">
                        </div>
                    </div>
                </div>

            </div>
        </form>

    </div>
</div>
<!-- // Content END -->

