<?php
/**
 *  phtml for Issue Search
 */
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <?php echo $this->translate("Change Store Filters"); ?>
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-10">
                        <?php $this->allLevelCombo(); ?>
                    </div>
                    <div class="col-md-2 right" style="padding-top: 29px;">
                        <a href="<?php echo $this->baseUrl(); ?>/reports/dashlet/cold-chain-capacity" class="btn btn-success">Change Store</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
