

<div class="row">
    <div class="col-md-12">


      <form name="consumption_comments" id="consumption_comments" onsubmit="return closeSelf(this);" action="" method="POST">
      <!-- Row -->
            <div class="row">
                <div class="col-md-3">
                    <label class="control-label" for="comments">
                        <?php echo $this->translate("Comments Max 300 Char"); ?>
                    </label>
                    <input id="wh_id" type="hidden" name="wh_id" value="<?php echo $this->wh_id; ?>" />
                    <input id="rpt_date" type="hidden" name="rpt_date" value="<?php echo $this->rpt_date; ?>" />
                    <div class="controls">
                        <textarea rows="4" cols="50" id="comments" name="comments"></textarea>
                    </div>
                </div>

            </div>



            <div class="row">                                        
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">
                        <?php echo $this->translate("Save"); ?>
                    </button>
                </div>
            </div>
        </form>

    </div>
</div>

