<?php
/**
 *  phtml for Print Monthly Consumption 2
 */
?>

<script>
    function printContents() {
        var dispSetting = "toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes, left=100, top=25";
        var printingContents = document.getElementById("dataEntryfrm").innerHTML;

        var docprint = window.open("", "", dataEntryfrm);
        docprint.document.open();
        docprint.document.write('<html><head><title>CLR6</title>');
        docprint.document.write('</head><body onLoad="self.print(); self.close()"><center>');
        docprint.document.write(printingContents);
        docprint.document.write('</center></body></html>');
        docprint.document.close();
        docprint.focus();
    }
</script>
<!-- Content -->
<div id="content_print">

    <style>
        .rotated-text {
            transform: rotate(45deg);

        }
        #content_print {
            margin-left: 30px;
            width: 940px;
        }
        table#mytable {
            border: 1px solid #e5e5e5;
            font-size: 10px;
            width: 100%;
        }
        table#mytable tr td {
            border: 1px solid #e5e5e5;
        }
        table#mytable tr th {
            border: 1px solid #e5e5e5;
        }
    </style>
    <!-- Content -->

    <style type="text/css" media="print">
        .page
        {
            -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
            filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
        }
        @media print
        {
            #printButt
            {
                display: none !important;
            }
        }
    </style>
    <style>
        *{
            font-family: sans-serif;
        }
        td{
            border: 1px solid gray;
        }
        th{
            border: 1px solid gray;
            background-color: #F1F1F1;
        }
        h2{
            text-align: center;
        }
        table{
            border-collapse: collapse;
        }
        input{
            width: 96%;
        }
        input:focus{
            border: 1px solid red;
            background-color: #FFE4E1;
        }
    </style>
    <div style="clear:both"></div>

    <div style="width: 80%; margin: auto;">
        <div style="width: 54%;  float: left; margin-top: 24px; padding-bottom: 10px;">
            <table style="width:100%; height: 80px;">
                <thead>
                    <tr>
                        <th class="center">Month</th>
                        <td><?php echo date('F', mktime(0, 0, 0, $this->mm, 1)); ?></td>
                        <th class="center">Year</th>
                        <td><?php echo $this->year ?></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th class="center">District</th>
                        <td colspan="1"><?php echo $this->district_name; ?></td>

                        <th class="center">Taluka</th>
                        <td colspan="1"><?php echo $this->tehsil_name; ?></td>
                    </tr>
                    <tr>
                        <th class="center">UC</th>
                        <td colspan="1"><?php echo $this->uc_name; ?></td>

                        <th class="center">EPI Center</th>
                        <td colspan="1"><?php echo $this->warehouse_name; ?></td>
                    </tr>
                    <?php
                    if ($this->province_id == 1) {
                        $col_size = "colspan='4'";
                        $col_size1 = "colspan='2'";
                        $height = "22px";
                        $style = "style='height: 27px'";
                    } else {
                        $col_size = "colspan='2'";
                        $col_size1 = "colspan='1'";
                        $height = "35px";
                        $style = "";
                    }
                    ?>
                    <tr>
                        <?php if ($this->province_id != 1) { ?>
                            <th <?php echo $col_size; ?> class="center" >Fixed Vaccinations Sessions</th>
                        <?php } ?>
                        <th <?php echo $col_size; ?> class="center" style="height: 21px">Outreach Vaccination Session</th>
                    </tr>
                    <tr style="height: 21px">
                        <?php if ($this->province_id != 1) { ?>
                            <th <?php echo $col_size1; ?> class="center" >Planned</th>

                            <th <?php echo $col_size1; ?>class="center">Actually Held</th>
                        <?php } ?>
                        <th <?php echo $col_size1; ?> class="center" >Planned</th>

                        <th <?php echo $col_size1; ?> class="center">Actually Held</th>
                    </tr>
                    <?php $row_hf = $this->monthlyConsumtion2()->monthlyConsumtion2HfSessions($this->wh_id, $this->rpt_date); ?>
                    <tr>
                        <?php if ($this->province_id != 1) { ?>
                            <td class="center" <?php echo $col_size1; ?>><?php echo (!empty($row_hf['fixed_planned_sessions'])) ? $row_hf['fixed_planned_sessions'] : '0'; ?></td>
                            <td class="center" <?php echo $col_size1; ?>><?php echo (!empty($row_hf['fixed_actually_held_sessions'])) ? $row_hf['fixed_actually_held_sessions'] : '0'; ?></td>
                        <?php } ?>
                        <td class="center" <?php echo $col_size1; ?>><?php echo (!empty($row_hf['outreach_planned_sessions'])) ? $row_hf['outreach_planned_sessions'] : '0'; ?></td>
                        <td class="center" <?php echo $col_size1; ?>><?php echo (!empty($row_hf['outreach_actually_held_sessions'])) ? $row_hf['outreach_actually_held_sessions'] : '0'; ?></td>

                    </tr>
                </tbody>
            </table>
        </div>
        <?php
        if ($this->province_id == 1) {
            $height = "138px";
        } else {
            $height = "80px";
        }
        ?>
        <div style="width: 44%; float: right; padding-bottom: 10px;">
            <table style="width:100%; height: <?php echo $height; ?>;">
                <caption><h4>MONTHLY TARGETS</h4></caption>

                <?php
                $row0 = $this->monthlyConsumtion2()->monthlyConsumtion2Targets($this->wh_id, $this->rpt_date);



                if ($this->is_new_report == 1 && count($row0) < 0) {
                    ?>
                    <thead>
                        <tr>
                            <td class="center">Children Live Birth</td>
                            <td><input type="text" name="children_live_birth" id="children_live_birth" class="form-control col-md-1"></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="center">Surviving Children (0-11 M)</td>
                            <td><input type="text" name="surviving_children_0_11_M" id="surviving_children_0_11_M" class="form-control col-md-1"></td>
                        </tr>
                        <tr>
                            <td class="center">Children Aged (12-23 M)</td>
                            <td><input type="text" name="children_aged_12_23_M" id="children_aged_12_23_M" class="form-control col-md-1"></td>
                        </tr>
                        <?php if ($this->province_id != 1) { ?>
                            <tr>
                                <td class="center">2 year and Above</td>
                                <td><input type="text" name="2_year_and_above" id="2_year_and_above" class="form-control col-md-1"></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td class="center">Pregnant Women</td>
                            <td><input type="text" name="pregnant_women1" id="pregnant_women1" class="form-control col-md-1"></td>
                        </tr>
                        <tr>
                            <td class="center">CBAs</td>
                            <td><input type="text" name="cba" id="cba" class="form-control col-md-1"></td>
                        </tr>
                    </tbody>
                <?php } else if ($this->is_new_report == 1 && count($row0) > 0) {
                    ?>
                    <thead>
                        <tr>
                            <td class="center">Children Live Birth</td>
                            <td><input type="text" name="children_live_birth" id="children_live_birth" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['children_live_birth'])) ? $row0['children_live_birth'] : '0'; ?>"></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="center">Surviving Children (0-11 M)</td>
                            <td><input type="text" name="surviving_children_0_11_M" id="surviving_children_0_11_M" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['surviving_children_0_11'])) ? $row0['surviving_children_0_11'] : '0'; ?>"></td>
                        </tr>

                        <tr>
                            <td class="center">Children Aged (12-23 M)</td>
                            <td><input type="text" name="children_aged_12_23_M" id="children_aged_12_23_M" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['children_aged_12_23'])) ? $row0['children_aged_12_23'] : '0'; ?>"></td>
                        </tr>

                        <tr>
                            <td class="center">Pregnant Women</td>
                            <td><input type="text" name="pregnant_women1" id="pregnant_women1" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['pregnant_women'])) ? $row0['pregnant_women'] : '0'; ?>"></td>
                        </tr>
                        <tr>
                            <td class="center">CBAs</td>
                            <td><input type="text" name="cba" id="cba" class="form-control col-md-1" readonly="readonly" value="<?php echo (!empty($row0['cbas'])) ? $row0['cbas'] : '0'; ?>"></td>
                        </tr>
                    </tbody>
                <?php } else if ($this->is_new_report == 2 && count($row0) > 0) {
                    ?>
                    <thead>
                        <tr>
                            <td class="center">Children Live Birth</td>
                            <td><?php echo (!empty($row0['children_live_birth'])) ? $row0['children_live_birth'] : '0'; ?></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="center">Surviving Children (0-11 M)</td>
                            <td><?php echo (!empty($row0['surviving_children_0_11'])) ? $row0['surviving_children_0_11'] : '0'; ?></td>
                        </tr>
                        <tr>
                            <td class="center">Children Aged (12-23 M)</td>
                            <td><?php echo (!empty($row0['children_aged_12_23'])) ? $row0['children_aged_12_23'] : '0'; ?></td>
                        </tr>
                        <?php if ($this->province_id != 1) { ?>
                            <tr>
                                <td class="center">2 year and Above</td>
                                <td><?php echo (!empty($row0['above_2_year'])) ? $row0['above_2_year'] : '0'; ?></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td class="center">Pregnant Women</td>
                            <td><?php echo (!empty($row0['pregnant_women'])) ? $row0['pregnant_women'] : '0'; ?></td>
                        </tr>
                        <tr>
                            <td class="center">CBAs</td>
                            <td><?php echo (!empty($row0['cbas'])) ? $row0['cbas'] : '0'; ?></td>
                        </tr>
                    </tbody>
                <?php } else { ?>
                    <thead>
                        <tr>
                            <td class="center">Children Live Birth</td>
                            <td><input type="text" name="children_live_birth" id="children_live_birth" class="form-control col-md-1"  value="<?php echo (!empty($row0['children_live_birth'])) ? $row0['children_live_birth'] : '0'; ?>"></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="center">Surviving Children (0-11 M)</td>
                            <td><input type="text" name="surviving_children_0_11_M" id="surviving_children_0_11_M" class="form-control col-md-1" value="<?php echo (!empty($row0['surviving_children_0_11'])) ? $row0['surviving_children_0_11'] : '0'; ?>"></td>
                        </tr>
                        <tr>
                            <td class="center">Children Aged (12-23 M)</td>
                            <td><input type="text" name="children_aged_12_23_M" id="children_aged_12_23_M" class="form-control col-md-1" value="<?php echo (!empty($row0['children_aged_12_23'])) ? $row0['children_aged_12_23'] : '0'; ?>"></td>
                        </tr>
                        <?php if ($this->province_id != 1) { ?>
                            <tr>
                                <td class="center">2 year and Above</td>
                                <td><input type="text" name="2_year_and_above" id="2_year_and_above" class="form-control col-md-1" value="<?php echo (!empty($row0['above_2_year'])) ? $row0['above_2_year'] : '0'; ?>"></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td class="center">Pregnant Women</td>
                            <td><input type="text" name="pregnant_women1" id="pregnant_women1" class="form-control col-md-1" value="<?php echo (!empty($row0['pregnant_women'])) ? $row0['pregnant_women'] : '0'; ?>"></td>
                        </tr>
                        <tr>
                            <td class="center">CBAs</td>
                            <td><input type="text" name="cba" id="cba" class="form-control col-md-1" value="<?php echo (!empty($row0['cbas'])) ? $row0['cbas'] : '0'; ?>"></td>
                        </tr>
                    </tbody>
                <?php } ?>
            </table>
        </div>
        <div style="clear:both;">  Filled By ________________________Date________________________ Sign.________________________     </div>
    </div>

    </br>
    <table width="100%" cellpadding="3" id="mytable">
        <thead>
            <tr>
                <th rowspan="4">Product</th>
                <th rowspan="4">Opening Balance (Doses)</th>
                <th rowspan="4">Received (Doses)</th>
                <th rowspan="4">#</th>
                <th colspan="10">Number of Children Vaccinated (0-11 Months)</th>
                <th colspan="10">Number of Children Vaccinated (12-23 Months)</th>
                <th colspan="10" >2 Years and Above</th>
                <th rowspan="4" class="center">Total Male</th>
                <th rowspan="4" class="center">Total Female</th>
                <th rowspan="4" class="center">Total</th>
                <th rowspan="4">Closing Balance (Doses)</th>
                <th rowspan="4">Unusable (Doses)</th>
            </tr>
            <tr>

                <th colspan="4">Fixed</th>
                <th colspan="2" rowspan="2" style="background-color: #FFCC99;" >Referral from Outside UCs*</th>
                <th colspan="4" >Out</br>reach</th>
                <th colspan="4">Fixed</th>
                <th colspan="2" rowspan="2" style="background-color: #FFCC99;"> Referral from Outside UCs*</th>
                <th colspan="4" >Out</br>reach</th>
                <th colspan="4" >Fixed</th>
                <th colspan="2" rowspan="2" style="background-color: #FFCC99;"> Referral from Outside UCs*</th>
                <th colspan="4"   >Out</br>reach</th>
            </tr>
            <tr>
                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>

                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>
                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>
                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>
                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>
                <th colspan="2">Inside UC</th>
                <th colspan="2">Outside UC</th>

            </tr>
            <tr>

                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
                <th style="background-color: #FFCC99;">M</th>
                <th style="background-color: #FFCC99;">F</th>
                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>

                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
                <th style="background-color: #FFCC99;">M</th>
                <th style="background-color: #FFCC99;">F</th>
                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>

                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
                <th style="background-color: #FFCC99;">M</th>
                <th style="background-color: #FFCC99;">F</th>
                <th>M</th>
                <th>F</th>
                <th>M</th>
                <th>F</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->items as $result):
                ?>

                <?php
                if ($this->is_new_report == 1) {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->prev_month_date, $result['pk_id'], Model_ListDetail::AGE_0_11);
                } else {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->rpt_date, $result['pk_id'], Model_ListDetail::AGE_0_11);
                    $row3 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->rpt_date, $result['pk_id'], Model_ListDetail::AGE_12_23);
                    $row_reff_male = $this->monthlyConsumtion2()->monthlyConsumtionRefferal($this->wh_id, $this->rpt_date, $result['pk_id'], 'Male');
                    $row_reff_female = $this->monthlyConsumtion2()->monthlyConsumtionRefferal($this->wh_id, $this->rpt_date, $result['pk_id'], 'Female');
                    $row4 = $this->monthlyConsumtion2()->monthlyConsumtion2Vaccines($this->wh_id, $this->rpt_date, $result['pk_id'], Model_ListDetail::AGE_24);
                }

                $counter = 1;
                $nod = $result['no_of_doses'];
                $max_i;
                ?>
                <?php if ($this->is_new_report == 2) {
                    ?>
                    <?php
                    $j = 0;
                    for ($i = $result['start_no']; $i <= $result['no_of_doses']; $i++) {
                        if ($i == 0) {
                            $nod += 1;
                        }
                        ?>
                        <tr>
                            <?php if ($counter == 1) { ?>
                                <td rowspan="<?php echo $nod ?>" class=""><?php echo $result['item_name'] ?></td>
                        <input type="hidden" name="flitm_id[]" value="<?php echo $result['pk_id']; ?>" />
                        <input type="hidden" name="doses_per_unit[]" id="<?php echo $result['pk_id']; ?>-doses" value="<?php echo $result['description']; ?>" />
                        <input type="hidden" name="start_no[]" id="<?php echo $result['pk_id']; ?>-start_no" value="<?php echo $result['start_no']; ?>" />
                        <input type="hidden" name="no_of_doses[]" id="<?php echo $result['pk_id']; ?>-no_of_doses" value="<?php echo $result['no_of_doses']; ?>" />

                        <td rowspan="<?php echo $nod ?>">
                            <?php echo (!empty($row2[0]['openingBalance'])) ? $row2[0]['openingBalance'] : '0'; ?>
                        </td>


                        <td rowspan="<?php echo $nod ?>">
                            <?php echo (!empty($row2[0]['receivedBalance'])) ? number_format($row2[0]['receivedBalance']) : '0'; ?>
                        </td>

                    <?php } ?>
                    <input type="hidden" name="vaccine_schedule_id[]" value="<?php echo ($i == 1 && $i == $nod) ? '' : $i; ?>" />
                    <td><?php echo ($i == 1 && $i == $nod) ? '' : $i; ?></td>
                    <td> <?php echo (!empty($row2[$j]['fixed_inside_uc_male']) ) ? $row2[$j]['fixed_inside_uc_male'] : '0'; ?></td>
                    <td> <?php echo (!empty($row2[$j]['fixed_inside_uc_female']) ) ? $row2[$j]['fixed_inside_uc_female'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row2[$j]['fixed_outside_uc_male']) ) ? $row2[$j]['fixed_outside_uc_male'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row2[$j]['fixed_outside_uc_female'])) ? $row2[$j]['fixed_outside_uc_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row_reff_male['total']) ) ? $row_reff_male['total'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row_reff_female['total'])) ? $row_reff_female['total'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row2[$j]['outreach_male']) ) ? $row2[$j]['outreach_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row2[$j]['outreach_female']) ) ? $row2[$j]['outreach_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row2[$j]['outreach_outside_male']) ) ? $row2[$j]['outreach_outside_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row2[$j]['outreach_outside_female']) ) ? $row2[$j]['outreach_outside_female'] : '0'; ?>  </td>

                    <td> <?php echo (!empty($row3[$j]['fixed_inside_uc_male'])) ? $row3[$j]['fixed_inside_uc_male'] : '0'; ?></td>
                    <td> <?php echo (!empty($row3[$j]['fixed_inside_uc_female']) ) ? $row3[$j]['fixed_inside_uc_female'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row3[$j]['fixed_outside_uc_male']) ) ? $row3[$j]['fixed_outside_uc_male'] : '0'; ?> </td>
                    <td> <?php echo (!empty($row3[$j]['fixed_outside_uc_female'])) ? $row3[$j]['fixed_outside_uc_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['referal_male']) ) ? $row3[$j]['referal_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['referal_female']) ) ? $row3[$j]['referal_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['outreach_male']) ) ? $row3[$j]['outreach_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['outreach_female'])) ? $row3[$j]['outreach_female'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['outreach_outside_male']) ) ? $row3[$j]['outreach_outside_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['outreach_outside_female'])) ? $row3[$j]['outreach_outside_female'] : '0'; ?>  </td>

                    <td > <?php echo (!empty($row4[$j]['fixed_inside_uc_male'])) ? number_format($row4[$j]['fixed_inside_uc_male']) : '0'; ?></td>
                    <td > <?php echo (!empty($row4[$j]['fixed_inside_uc_female']) ) ? number_format($row4[$j]['fixed_inside_uc_female']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row4[$j]['fixed_outside_uc_male']) ) ? number_format($row4[$j]['fixed_outside_uc_male']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row4[$j]['fixed_outside_uc_female'])) ? number_format($row4[$j]['fixed_outside_uc_female']) : '0'; ?>  </td>

                    <td> <?php echo (!empty($row3[$j]['referal_male']) ) ? $row3[$j]['referal_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[$j]['referal_female']) ) ? $row3[$j]['referal_female'] : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4[$j]['outreach_male']) ) ? number_format($row4[$j]['outreach_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4[$j]['outreach_female'])) ? number_format($row4[$j]['outreach_female']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4[$j]['outreach_outside_male']) ) ? number_format($row4[$j]['outreach_outside_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4[$j]['outreach_outside_female'])) ? number_format($row4[$j]['outreach_outside_female']) : '0'; ?>  </td>
                    <?php
                    $sum_male = $row_reff_male['total'] + $row3[$j]['referal_male'] + $row2[$j]['fixed_inside_uc_male'] + $row2[$j]['fixed_outside_uc_male'] + $row2[$j]['outreach_male'] + $row2[$j]['outreach_outside_male'] + $row3[$j]['fixed_inside_uc_male'] + $row3[$j]['fixed_outside_uc_male'] + $row3[$j]['outreach_male'] + $row3[$j]['outreach_outside_male'] + $row4[$j]['fixed_inside_uc_male'] + $row4[$j]['fixed_outside_uc_male'] + $row4[$j]['outreach_male'] + $row4[$j]['outreach_outside_male'];
                    $sum_female = $row_reff_female['total'] + $row3[$j]['referal_female'] + $row2[$j]['fixed_inside_uc_female'] + $row2[$j]['fixed_outside_uc_female'] + $row2[$j]['outreach_female'] + $row2[$j]['outreach_outside_female'] + $row3[$j]['fixed_inside_uc_female'] + $row3[$j]['fixed_outside_uc_female'] + $row3[$j]['outreach_female'] + $row3[$j]['outreach_outside_female'] + $row4[$j]['fixed_inside_uc_female'] + $row4[$j]['fixed_outside_uc_female'] + $row4[$j]['outreach_female'] + $row4[$j]['outreach_outside_female'];
                    $sum = $sum_female + $sum_male;
                    ?>
                    <td> 
                        <?php echo (!empty($sum_male)) ? $sum_male : '0'; ?>
                    </td> 
                    <td> 
                        <?php echo (!empty($sum_female)) ? $sum_female : '0'; ?>
                    </td> 
                    <td> 
                        <?php echo (!empty($sum)) ? $sum : '0'; ?>
                    </td> 

                    <?php if ($counter == 1) { ?>
                        <td>
                            <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?>
                        </td>
                        <td> <?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?> </td>
                    <?php } ?> </tr>

                    <?php
                    $counter++;
                    $j++;
                }
                ?>
            <?php } ?>
            <?php
            if ($result['pk_id'] != 6 && $result['pk_id'] != 40) {
                if ($this->is_new_report == 1) {
                    $row2_total = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTotal($this->wh_id, $this->prev_month_date, $result['pk_id']);
                } else {
                    $row2_total = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTotal($this->wh_id, $this->rpt_date, $result['pk_id'], Model_ListDetail::AGE_0_11);
                    $row3_total = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTotal($this->wh_id, $this->rpt_date, $result['pk_id'], Model_ListDetail::AGE_12_23);
                    $row4_total = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTotal($this->wh_id, $this->rpt_date, $result['pk_id'], Model_ListDetail::AGE_24);
                    $row_reff_male_total = $this->monthlyConsumtion2()->monthlyConsumtionRefferalTotal($this->wh_id, $this->rpt_date, $result['pk_id'], 'Male');
                    $row_reff_female_total = $this->monthlyConsumtion2()->monthlyConsumtionRefferalTotal($this->wh_id, $this->rpt_date, $result['pk_id'], 'Female');
                }
                ?>
                <tr>


                    <td colspan="4" class="right"><b>Total</b></td>
                    <td > <?php echo (!empty($row2_total[0]['fixed_inside_uc_male']) ) ? number_format($row2_total[0]['fixed_inside_uc_male']) : '0'; ?></td>
                    <td > <?php echo (!empty($row2_total[0]['fixed_inside_uc_female']) ) ? number_format($row2_total[0]['fixed_inside_uc_female']) : '0'; ?> </td>
                    <td> <?php echo (!empty($row2_total[0]['fixed_outside_uc_male']) ) ? number_format($row2_total[0]['fixed_outside_uc_male']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row2_total[0]['fixed_outside_uc_female'])) ? number_format($row2_total[0]['fixed_outside_uc_female']) : '0'; ?>  </td>
                    <td> <?php echo (!empty($row_reff_male_total['total']) ) ? $row_reff_male_total['total'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row_reff_female_total['total'])) ? $row_reff_female_total['total'] : '0'; ?>  </td>

                    <td > <?php echo (!empty($row2_total[0]['outreach_male']) ) ? number_format($row2_total[0]['outreach_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row2_total[0]['outreach_female']) ) ? number_format($row2_total[0]['outreach_female']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row2_total[0]['outreach_outside_male']) ) ? number_format($row2_total[0]['outreach_outside_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row2_total[0]['outreach_outside_female']) ) ? number_format($row2_total[0]['outreach_outside_female']) : '0'; ?>  </td>

                    <td > <?php echo (!empty($row3_total[0]['fixed_inside_uc_male'])) ? number_format($row3_total[0]['fixed_inside_uc_male']) : '0'; ?></td>
                    <td > <?php echo (!empty($row3_total[0]['fixed_inside_uc_female']) ) ? number_format($row3_total[0]['fixed_inside_uc_female']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row3_total[0]['fixed_outside_uc_male']) ) ? number_format($row3_total[0]['fixed_outside_uc_male']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row3_total[0]['fixed_outside_uc_female'])) ? number_format($row3_total[0]['fixed_outside_uc_female']) : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[0]['referal_male']) ) ? $row3[0]['referal_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[0]['referal_female']) ) ? $row3[0]['referal_female'] : '0'; ?>  </td>

                    <td > <?php echo (!empty($row3_total[0]['outreach_male']) ) ? number_format($row3_total[0]['outreach_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row3_total[0]['outreach_female'])) ? number_format($row3_total[0]['outreach_female']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row3_total[0]['outreach_outside_male']) ) ? number_format($row3_total[0]['outreach_outside_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row3_total[0]['outreach_outside_female'])) ? number_format($row3_total[0]['outreach_outside_female']) : '0'; ?>  </td>

                    <td > <?php echo (!empty($row4_total[0]['fixed_inside_uc_male'])) ? number_format($row4_total[0]['fixed_inside_uc_male']) : '0'; ?></td>
                    <td > <?php echo (!empty($row4_total[0]['fixed_inside_uc_female']) ) ? number_format($row4_total[0]['fixed_inside_uc_female']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row4_total[0]['fixed_outside_uc_male']) ) ? number_format($row4_total[0]['fixed_outside_uc_male']) : '0'; ?> </td>
                    <td > <?php echo (!empty($row4_total[0]['fixed_outside_uc_female'])) ? number_format($row4_total[0]['fixed_outside_uc_female']) : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[0]['referal_male']) ) ? $row3[0]['referal_male'] : '0'; ?>  </td>
                    <td> <?php echo (!empty($row3[0]['referal_female']) ) ? $row3[0]['referal_female'] : '0'; ?>  </td>

                    <td > <?php echo (!empty($row4_total[0]['outreach_male']) ) ? number_format($row4_total[0]['outreach_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4_total[0]['outreach_female'])) ? number_format($row4_total[0]['outreach_female']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4_total[0]['outreach_outside_male']) ) ? number_format($row4_total[0]['outreach_outside_male']) : '0'; ?>  </td>
                    <td > <?php echo (!empty($row4_total[0]['outreach_outside_female'])) ? number_format($row4_total[0]['outreach_outside_female']) : '0'; ?>  </td>
                    <?php
                    $sum_total_male = $row3[0]['referal_male'] + $row_reff_male_total['total'] + $row2_total[0]['fixed_inside_uc_male'] + $row2_total[0]['fixed_outside_uc_male'] + $row2_total[0]['outreach_male'] + $row2_total[0]['outreach_outside_male'] + $row3_total[0]['fixed_inside_uc_male'] + $row3_total[0]['fixed_outside_uc_male'] + $row3_total[0]['outreach_male'] + $row3_total[0]['outreach_outside_male'] + $row4_total[0]['fixed_inside_uc_male'] + $row4_total[0]['fixed_outside_uc_male'] + $row4_total[0]['outreach_male'] + $row4_total[0]['outreach_outside_male'];
                    $sum_total_female = $row3[0]['referal_female'] + $row_reff_female_total['total'] + $row2_total[0]['fixed_inside_uc_female'] + $row2_total[0]['fixed_outside_uc_female'] + $row2_total[0]['outreach_female'] + $row2_total[0]['outreach_outside_female'] + $row3_total[0]['fixed_inside_uc_female'] + $row3_total[0]['fixed_outside_uc_female'] + $row3_total[0]['outreach_female'] + $row3_total[0]['outreach_outside_female'] + $row4_total[0]['fixed_inside_uc_female'] + $row4_total[0]['fixed_outside_uc_female'] + $row4_total[0]['outreach_female'] + $row4_total[0]['outreach_outside_female'];
                    $sum = $sum_total_female + $sum_total_male;
                    ?>
                    <td> 
                        <?php echo (!empty($sum_total_male)) ? $sum_total_male : '0'; ?>

                    </td>  
                    <td> 
                        <?php echo (!empty($sum_total_female)) ? $sum_total_female : '0'; ?>

                    </td> 
                    <td> 
                        <?php echo (!empty($sum)) ? $sum : '0'; ?>

                    </td> 
                    <?php if ($counter == 1) { ?>

                        <td> 
                            <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?>
                        </td>
                        <td> <?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?> </td>
                    <?php } ?> </tr>
            <?php } ?>
        <?php endforeach; ?>


        </tbody>
    </table>

    <h6>TT- Coverage</h6>
    <table width="100%" cellpadding="3" id="mytable">
        <thead>
            <tr>
                <th class="center">Product</th>

                <th class="center">Opening Balance (Doses)</th>
                <th class="center">Received (Doses)</th>
                <th class="center">S. No</th>
                <th class="center">Pregnant Women</th>
                <th class="center">CBAs</th>
                <th class="center">Total</th>
                <th class="center">Closing Balance (Doses)</th>
                <th class="center">Unusable (Doses)</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->items_tt as $result) {
                if ($this->is_new_report == 1) {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTt($this->wh_id, $this->prev_month_date, $result['pk_id']);
                } else {

                    $row2 = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTt($this->wh_id, $this->rpt_date, $result['pk_id']);
                }
                ?>
                <?php
                if ($this->is_new_report == 2) {

                    $j = 0;
                    for ($i = 1; $i <= 6; $i++) {
                        ?>
                        <tr>
                            <?php
                            if ($i == 1) {
                                ?>   <td rowspan = "6" class="center"><?php echo $result['item_name'] ?></td>
                                <td rowspan = "6"> <?php echo (!empty($row2[0]['openingBalance'])) ? $row2[0]['openingBalance'] : '0'; ?></td>
                                <td rowspan = "6"> <?php echo (!empty($row2[0]['receivedBalance'])) ? number_format($row2[0]['receivedBalance']) : '0'; ?></td>     <?php
                            }
                            ?>
                            <?php
                            if ($i <= 5) {
                                ?>
                        <input type="hidden" name="vaccine_schedule_id[]" value="<?php echo $i; ?>" />
                        <td class="center"><?php echo $i ?></td>

                        <td >
                            <input type="hidden"  name="pregenant_women[]"  id="<?php echo $result['pk_id']; ?>-pregenant_women" class="pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['pregnant_women'])) ? number_format($row2[$j]['pregnant_women']) : '0'; ?>">


                            <?php echo (!empty($row2[$j]['pregnant_women'])) ? number_format($row2[$j]['pregnant_women']) : '0'; ?></td>

                        <?php
                    }
                    ?>
                    <?php
                    if ($i == 6) {
                        if ($this->is_new_report == 1) {
                            $row2_total = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTtTotal($this->wh_id, $this->prev_month_date, $result['pk_id']);
                        } else {

                            $row2_total = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTtTotal($this->wh_id, $this->rpt_date, $result['pk_id']);
                        }
                        ?>

                        <td class="center">Total</td>
                        <td > <?php echo (!empty($row2_total[0]['pregnant_women'])) ? number_format($row2_total[0]['pregnant_women']) : '0'; ?></td>


                        <?php
                    }
                    ?>

                    <?php
                    if ($i <= 5) {
                        ?>

                        <td class="non_pregnant_women">
                            <input type="hidden"  name="non_pregnant_women[]"  id="<?php echo $result['pk_id']; ?>-non_pregenant_women" class="non_pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?>">
                            <?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?></td>
                        <?php
                        $sum_tt = $row2[$j]['pregnant_women'] + $row2[$j]['non_pregnant_women'];
                        ?>
                        <td class="non_pregnant_women">
                            <input type="hidden"  name="non_pregnant_women[]"  id="<?php echo $result['pk_id']; ?>-non_pregenant_women" class="non_pregenant_women form-control col-md-1"  value="<?php echo (!empty($row2[$j]['non_pregnant_women'])) ? number_format($row2[$j]['non_pregnant_women']) : '0'; ?>">                             
                            <?php echo (!empty($sum_tt)) ? number_format($sum_tt) : '0'; ?></td>

                        <?php
                        $j++;
                    }
                    ?>
                    <?php
                    if ($i == 6) {
                        ?><?php
                        $sum_total_tt = $row2_total[0]['pregnant_women'] + $row2_total[0]['non_pregnant_women'];
                        if ($this->is_new_report == 1) {
                            $row2_total_non = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTtTotal($this->wh_id, $this->prev_month_date, $result['pk_id']);
                        } else {

                            $row2_total_non = $this->monthlyConsumtion2()->monthlyConsumtion2VaccinesTtTotal($this->wh_id, $this->rpt_date, $result['pk_id']);
                        }
                        ?> 

                        <td  > <?php echo (!empty($row2_total_non[0]['non_pregnant_women'])) ? number_format($row2_total_non[0]['non_pregnant_women']) : '0'; ?></td>
                        <td  ><?php echo (!empty($sum_total_tt)) ? number_format($sum_total_tt) : '0'; ?></td>

                        <?php
                    }
                    ?>


                    <?php
                    if ($i == 1) {
                        ?>
                        <td rowspan="6"> <?php echo (!empty($row2[0]['closingBalance'])) ? $row2[0]['closingBalance'] : '0'; ?></td>
                        <td rowspan="6"><?php echo (!empty($row2[0]['adjustments']) ? $row2[0]['adjustments'] : '0' ); ?></td><?php
                    }
                    ?>
                    </tr>
                    <?php
                }
            }
            ?>
        <?php } ?>
        </tbody>
    </table>

    <h6>Other Items</h6>
    <table width="100%" cellpadding="3" id="mytable">
        <thead>
            <tr>
                <th>Product</th>
                <th>Opening Balance (No)</th>
                <th>Received (No)</th>
                <th>Dispensed (No)</th>
                <th>Closing Balance (No)</th>
            </tr>
        </thead>
        <tbody>

            <?php
            foreach ($this->items_non_vaccinces as $result) {

                if ($this->is_new_report == 1) {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumptionNonVaccinces($this->wh_id, $this->prev_month_date, $result['pk_id']);
                } else {
                    $row2 = $this->monthlyConsumtion2()->monthlyConsumptionNonVaccinces($this->wh_id, $this->rpt_date, $result['pk_id']);
                }
                ?>

                <?php if ($this->is_new_report == 2) { ?>
                    <tr>
                        <td><?php echo $result['item_name'] ?></td>
                        <td><?php echo (!empty($row2['openingBalance'])) ? $row2['openingBalance'] : '0'; ?></td>
                        <td><?php echo (!empty($row2['receivedBalance'])) ? $row2['receivedBalance'] : '0'; ?></td>
                        <td><?php echo (!empty($row2['issueBalance'])) ? $row2['issueBalance'] : '0'; ?></td>
                        <td><?php echo (!empty($row2['closingBalance'])) ? $row2['closingBalance'] : '0'; ?></td>


                    </tr>
                <?php } ?>

                <?php
            }
            ?>
        </tbody>


    </table>
    <div style="clear:both;"></div>
    <div style="width:100%;text-align:right; margin-bottom:10px;"><button type="button" id="printButt" class="btn btn-primary" onclick="printCont()">Print</button></div>
    <div style="clear:both;"></div>
</div>