<?php
/**
 *  phtml for Search Log Book
 */
?>
<!-- Content -->

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            <?php echo $this->translate("UC wise Target List"); ?>
        </h3>
        <div class="row">

            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Filters"); ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse"></a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form name="search-logbook" id="search-logbook" method="post" action="">

                            <div class="row">
                                <div class="col-md-3">
                                    <!-- Group Receive No-->
                                    <div class="control-group">
                                        <label class="control-label" for="province">
                                            <?php echo $this->translate("Province"); ?><span class="red">*</span>

                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->province; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <!-- Group Receive No-->
                                    <div class="control-group">
                                        <label class="control-label" for="district">
                                            <?php echo $this->translate("District"); ?>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->district; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <!-- Group Receive No-->
                                    <div class="control-group">
                                        <label class="control-label" for="year">
                                            <?php echo $this->translate("Year"); ?><span class="red">*</span>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->year; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label">&nbsp;</label>  
                                    <div class="controls">
                                        <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit">
                                            <?php echo $this->translate("Go"); ?>
                                        </button>
                                    </div>
                                </div>

                            </div>
                            <div class="row">


                            </div>
                    </div>

                    </form>
                </div>
            </div>

        </div>
        <?php if ($this->arr_data && count($this->arr_data) > 0) { ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php
                                echo $this->translate("UC wise Targets for ");
                                echo $this->province;
                                echo $this->translate(" for year ");
                                echo $this->year;
                                ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-bordered table-condensed" id="sample_2">
                                        <!-- Table heading -->
                                        <thead>
                                            <tr>
                                                <th>
                                                    <?php echo $this->translate("S.No"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("District"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Tehsil"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("UC"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Population"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Target"); ?>
                                                </th>

                                            </tr>

                                        </thead>
                                        <!-- // Table heading END -->

                                        <!-- Table body -->
                                        <tbody>

                                            <!-- Table row -->
                                            <?php
                                            $j = 1;
                                            foreach ($this->arr_data as $row) {
                                                ?>
                                                <tr>
                                                    <td align="center">
                                                        <?php echo $j; ?>
                                                    </td>
                                                    <td >
                                                        <?php echo $row['district_name'] ?>
                                                    </td>
                                                    <td >
                                                        <?php echo $row['tehsil_name'] ?>
                                                    </td>
                                                    <td >
                                                        <?php echo $row['uc_name'] ?>
                                                    </td>
                                                    <td align="right">
                                                        <?php echo number_format($row['population']) ?>
                                                    </td>
                                                    <td align="right">
                                                        <?php echo number_format($row['target']) ?>
                                                    </td>

                                                </tr>
                                                <?php
                                                $j ++;
                                            }
                                            ?>
                                            <!-- // Table row END -->
                                        </tbody>
                                        <!-- // Table body END -->                                      

                                    </table>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 right">
                                    <a class="btn btn-success" href="javascript:void(0);" 
                                       onclick="window.open('uc-wise-target-print?p=<?php echo $this->province_id; ?>&d=<?php echo $this->district; ?>&y=<?php echo $this->year; ?>', '_blank', 'scrollbars=1,width=840,height=595');">
                                           <?php echo $this->translate("Print"); ?>
                                    </a>

                                </div>
                            </div>
                            Target =  ( Population / 100) * 3.5  
                        </div>
                    </div>
                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>No data found</h4>
                </div>
            </div>
        <?php } ?>
        <div id="future_arrival_details"></div>
    </div>
</div>


<input type="hidden" id="district_hdn" name="district_hdn" value="<?php echo $this->district_hdn ?>">
<input type="hidden" id="tehsil_hdn" name="tehsil_hdn" value="<?php echo $this->tehsil_hdn ?>">
<input type="hidden" id="uc_hdn" name="uc_hdn" value="<?php echo $this->uc_hdn ?>">