
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
    <h3 class="page-title row-br-b-wp">
       <?php echo $this->translate("Change Password"); ?>
    </h3>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i>Change Password
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php
                    if (isset($_GET['e']) && $_GET['e'] == 1) {
                        echo "<p style=\"color:green\">".$this->translate("Password successfully changed")."</p>";
                    }
                    ?>
                    <form id="form1" name="form1" method="post" action="">
                        <div class="form-body">
                            <div  class="form-group">
                                <label><?php echo $this->translate("Old Password"); ?></label>
                                <div class="input-group">
                                    <input type="password" name="old_pass" id="old_pass" class="form-control input-sm input-medium" />
                                </div>
                            </div>
                            <div  class="form-group">
                                <label><?php echo $this->translate("New Password"); ?></label>
                                <div class="input-group">
                                    <input type="password" name="new_pass" id="new_pass" class="form-control input-sm input-medium" />
                                </div>
                            </div>
                            <div  class="form-group">
                                <label><?php echo $this->translate("Confirm  Password"); ?></label>
                                <div class="input-group">
                                    <input type="password" name="confirm_pas" id="confirm_pas" class="form-control input-sm input-medium" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="submit" name="Submit" id="Submit" value="<?php echo $this->translate("Change Password"); ?>" class="btn input-sm green" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
    </div>
</div>


