<!-- BEGIN CONTAINER -->
<style>
    .form-group{
        padding-top:  5px;
    }
    textarea {
        resize: none;
    }
</style>
<div class="page-container">
    <!-- BEGIN CONTENT -->
    <div class=" page-content-wrapper">
        <div class="page-content landing-content">
            <br/>

            <div class="col-md-4 col-md-offset-4">
                <?php if ($this->saved == true) { ?>
                    <div class="alert alert-info" id="saved">
                        <button data-dismiss="alert" class="close" type="button">
                            ×
                        </button>
                        Your password has been sent to your Email. 
                        <a href="<?php echo $this->baseUrl(); ?>/index/login">Login here</a>
                    </div>  
                <?php } ?>
            </div>



            <div class="col-md-4 col-md-offset-4"> 

                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-user"></i>Forget Password
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form name="forget-password" id="forget-password" method="post" action="">

                            <div class="form-group">
                                <label for="e_mail" class="col-md-3 control-label">
                                    <?php echo $this->translate("Your Email"); ?><span class="red">*</span>
                                </label>
                                <div class="col-md-9">
                                    <input type="text" name="e_mail" id="e_mail" class="form-control input-sm input-medium" />
                                </div>
                            </div>
                            <br>

                          
                            <div class="form-group">
                                <div class="pull-right" style="padding-top: 5px">
                                    <div class="col-md-6">
                                        <button type="reset" id="reset" value="Reset" class="btn btn-info">
                                            <?php echo $this->translate("Reset"); ?>
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button name="send_contact" id="send_contact" type="submit" class="form-control btn btn-success green">Submit</button>
                                    </div>
                                </div>
                                <p class="col-md-12" style="text-align: center; margin-left: -90px; color: #c40040;"><?php echo $this->error; ?></p>
                            </div>

                            <br>
                                                       
                        </form>

                        <div class="clearfix margin-bottom-20">
                        </div>                       

                    </div>
                </div>
               
            </div>
           
        </div>
    </div>
