<style>
    h2 {
        font-family: "PT Sans Narrow",Helvetica,Arial,sans-serif;
        font-size: 22px;
        font-weight: normal;
        margin: 13px 0;
    }

    p {
        font-size: 13.5px;
        line-height: 150%;
        padding-bottom: 5px;
        text-align: left;
        margin: 0 0 10px;
    }

    a {
        font-size: 14.5px !important;
        color: black;
    }
    .thumbnail{
        width: 114px;
        height: 160px;
        border: solid #D3D3D3 1px;
    }


</style>

<!-- Tabs -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="innerLR">
            <div class="widget widget-tabs widget-tabs-double"  style=" border-bottom: 1px solid #77e588; border-right: 1px solid #77e588; border-top: 1px solid #77e588; margin-bottom: -2px;  ">

                <!-- Tabs Heading -->
                <div class="widget-head">
                    <ul>
                        <li class="active"><a class="glyphicons table"  href="#federal"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Federal</span></a></li>
                        <li><a class="glyphicons table"  href="#sindh"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Sindh</span></a></li>
                        <li><a class="glyphicons table"  href="#punjab"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Punjab</span></a></li>
                        <li><a class="glyphicons table"  href="#kpk"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">KPK</span></a></li>
                        <li><a class="glyphicons table"  href="#balochistan"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Balochistan</span></a></li>
                        <li><a class="glyphicons table"  href="#regions"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Regions</span></a></li>
                        <li><a class="glyphicons table"  href="#training"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Training Manuals</span></a></li>
                    </ul>
                </div>
                <!-- // Tabs Heading END -->

                <div class="widget-body">
                    <div class="tab-content">

                        <!-- Tab content -->
                        <div id="federal" class="tab-pane active widget-body-regular">

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>Federal</h2>
                                    <h4>1- CW&S Manuals   </h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/1_cw_&_s_manuals/warehouse_procedures_monitoring_checklist.pdf">Warehouse Procedures Monitoring Checklist</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/1_cw_&_s_manuals/warehouse_staff_job_descriptions.pdf">Warehouse Staff Job Descriptions</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/1_cw_&_s_manuals/warehouse_staff_safety_manual.pdf">Warehouse Staff Safety Manual</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/1_cw_&_s_manuals/warehouse_standard_operating_procedures.pdf">Warehouse Standard Operating Procedures</a>
                                        </li>
                                    </ol>

                                    <h4>2- CW&S Videos   </h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/2_cw_&_s_videos/1_cwh_six_minute_video/warehouse_usaid-6min.mp4.mp4">CWH six minute video</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/2_cw_&_s_videos/2_cwh_one_minute_video/cw&s_video-1_min.mp4">CWH one minute video</a>
                                        </li>
                                    </ol>

                                    <h4>3- SCM Certification Course of Health Commodities   </h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/3_scm_certification_course_of_health_commodities/lecturerss_guide_certification_course_of_health_commodities.pdf">Lecturer's Guide_Certification Course of Health Commodities</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/3_scm_certification_course_of_health_commodities/studentss_guide_certification_course_of_health_commodities.pdf">Student's Guide_Certification Course of Health Commodities</a>
                                        </li>
                                    </ol>

                                    <h4>4- SCM Three Credit Course of Health Commodities </h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/4_scm_three_credit_course_ of_health_commodities/lecturerss_guide_three_credit_course_of_health_commodities.pdf">Lecturer's Guide_Three Credit Course of Health Commodities</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/4_scm_three_credit_course_ of_health_commodities/studentss_guide_three_credit_course_of_health_commodities.pdf">Student's Guide_Three Credit Course of Health Commodities</a>
                                        </li>
                                    </ol>

<!--                                    <h2>5- Training Manuals</h2>
                                    <h4>cLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h4>vLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual-Cold chain-Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_-_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/1_federal/5_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>-->
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="sindh" class="tab-pane widget-body-regular">
                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>Sindh</h2>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/1_contraceptives_logistics_manual_english_sindh/contraceptives_logistics_manual_english_sindh.pdf">Contraceptives Logistics Manual English Sindh</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/2_contraceptives_logistics_manual_urdu_sindh/contraceptives_logistics_manual_urdu_sindh.pdf">Contraceptives Logistics Manual Urdu Sindh</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/3_contraceptives_logistics_manual_sindhi/contraceptives_logistics_manual_sindhi.pdf">Contraceptives Logistics Manual Sindhi</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/4_essential_medicines_list_sindh/essential_medicines_list_sindh.pdf">Essential Medicines List Sindh</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/5_contraceptives_procurement_manual_sindh/contraceptives_procurement_manual_sindh.pdf">Contraceptives Procurement Manual Sindh</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/6_medicines_&_supplies_procurement_manual_sindh/medicines_&_supplies_procurement_manual_sindh.pdf">Medicines & Supplies Procurement Manual Sindh</a>
                                        </li>

                                    </ol>
                                    
<!--                                    <h2>Training Manuals</h2>
                                    <h4>cLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h4>vLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual-Cold chain-Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/2_sindh/7_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>-->
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="punjab" class="tab-pane widget-body-regular">
                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>Punjab</h2>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/1_contraceptives_logistics_manual_english_punjab/contraceptives_logistics_manual_english_punjab.pdf">Contraceptives Logistics Manual English Punjab</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/2_contraceptives_logistics_manual_urdu_punjab/contraceptives_logistics_manual_urdu_punjab.pdf">Contraceptives Logistics Manual Urdu Punjab</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/3_essential_medicines_list_punjab/essential_medicines_list_punjab.pdf">Essential Medicines List Punjab</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/4_contraceptive_procurement_manual_punjab/contraceptive_procurement_manual_punjab.pdf">Contraceptive Procurement Manual Punjab</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/5_medicines_&_supplies_procurement_manual_punjab/medicines_&_supplies_procurement_manual_punjab.pdf">Medicines & Supplies Procurement Manual Punjab</a>
                                        </li>
                                        
                                    </ol>
                                    
<!--                                    <h2>Training Manuals</h2>
                                    <h4>cLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h4>vLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual-Cold chain-Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/3_punjab/6_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>-->
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="kpk" class="tab-pane widget-body-regular">
                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>KPK</h2>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/1_contraceptives_logistics_manual_english_kpk/contraceptives_logistics_manual_english_kpk.pdf">Contraceptives Logistics Manual English KPK</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/2-contraceptives_logistics_manual_urdu_kpk/contraceptives_logistics_manual_urdu_kpk.pdf">Contraceptives Logistics Manual Urdu KPK</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/3_essential_medicines_list_kpk/essential_medicines_list_kpk.pdf">Essential Medicines List KPK</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/4_contraceptives_procurement_manual_kpk/contraceptives_procurement_manual_kpk.pdf">Contraceptive Procurement Manual KPK</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/5_medicines_&_supplies_procurement_manual_kpk/medicines_&_supplies_procurement_manual_kpk.pdf">Medicines & Supplies Procurement Manual KPK</a>
                                        </li>
                                        
                                    </ol>
                                    
<!--                                    <h2>Training Manuals</h2>
                                    <h4>cLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h4>vLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/vlmis_user_& _training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual-Cold chain-Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/vlmis_user_& _training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/vlmis_user_& _training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/vlmis_user_& _training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/vlmis_user_& _training_manuals/vlmis_user_manual_cold_chain_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/4_kpk/6_training_manuals/vlmis_user_& _training_manuals/vlmis_user_manual_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>-->
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="balochistan" class="tab-pane widget-body-regular">
                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>Balochistan</h2>
                                     <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/1_contraceptives_logistics_manual_english_balochistan/contraceptives_logistics_manual_english_balochistan.pdf">Contraceptives Logistics Manual English Balochistan</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/2_contraceptives_logistics_manual_urdu_balochistan/contraceptives_logistics_manual_urdu_balochistan.pdf">Contraceptives Logistics Manual Urdu Balochistan</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/3_essential_medicines_list_balochistan/essential_medicines_list_balochistan.pdf">Essential Medicines List Balochistan</a>
                                        </li>
                                                                             
                                    </ol>
                                    
<!--                                    <h2>Training Manuals</h2>
                                    <h4>cLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h4>vLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual-Cold chain-Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/5_balochistan/4_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>-->
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="regions" class="tab-pane widget-body-regular">
                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>Regions</h2>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/1_contraceptives_logistics_manual_ajk/contraceptives_logistics_manual_ajk.pdf">Contraceptives Logistics Manual AJK</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/2_contraceptives_logistics_manual_gb/contraceptives_logistics_manual_gb.pdf">Contraceptives Logistics Manual GB</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/3_contraceptives_logistics_manual_fata/contraceptives_logistics_manual__fata.pdf">Contraceptives Logistics Manual FATA</a>
                                        </li>
                                                                             
                                    </ol>
                                    
<!--                                    <h2>Training Manuals</h2>
                                    <h4>cLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h4>vLMIS User & Training Manuals</h4>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual-Cold chain-Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/6_regions/4_training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_-_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>-->
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="training" class="tab-pane widget-body-regular">
                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>Training Manuals</h2>
                                    <h3>Contraceptive Logistics Management Information System User & Training Manuals</h3>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/clmis_user_&_training_manuals/clmis_facilitator_manual_updated.pdf">cLMIS Facilitator Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/clmis_user_&_training_manuals/clmis_participants_guide_updated.pdf">cLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/clmis_user_&_training_manuals/clmis_pwd_user_manual_updated.pdf">cLMIS PWD User Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/clmis_user_&_training_manuals/clmis_tot_manual_updated.pdf">cLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/clmis_user_&_training_manuals/clmis_user_manual_updated.pdf">cLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>

                                    <h3>Vaccines Logistics Management Information System User & Training Manuals</h3>
                                    <ol>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vaccines_logistics_manual-cold_chain-updated.pdf">Vaccines Logistics Manual Cold chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_-_administrators_manual_updated.pdf">vLMIS Administrators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_facilitators_manual_updated.pdf">vLMIS Facilitators Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_participants_guide_updated.pdf">vLMIS Participants Guide - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_tot_manual_updated.pdf">vLMIS TOT Manual - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_cold_chain_updated.pdf">vLMIS User Manual - Cold Chain - Updated</a>
                                        </li>
                                        <li> 
                                            <a  target="_blank"
                                                href="http://lmis.gov.pk/docs/training_manuals/vlmis_user_&_training_manuals/vlmis_user_manual_updated.pdf">vLMIS User Manual - Updated</a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                        <!-- // Tab content END -->





                    </div>
                </div>
            </div>
            <!-- // Tabs END -->
        </div>
    </div>
</div>