<style>
    h2 {
        font-family: "PT Sans Narrow",Helvetica,Arial,sans-serif;
        font-size: 22px;
        font-weight: normal;
        margin: 13px 0;
    }

    p {
        font-size: 13.5px;
        line-height: 150%;
        padding-bottom: 5px;
        text-align: left;
        margin: 0 0 10px;
    }

    a {
        font-size: 14.5px !important;
        color: #ffffff;
    }
    .thumbnail{
        width: 114px;
        height: 160px;
        border: solid #D3D3D3 1px;
    }


</style>

<!-- Tabs -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="innerLR">
            <div class="widget widget-tabs widget-tabs-double"  style=" border-bottom: 1px solid #77e588; border-right: 1px solid #77e588; border-top: 1px solid #77e588; margin-bottom: -2px;  ">

                <!-- Tabs Heading -->
                <div class="widget-head">
                    <ul>
                        <li class="active"><a class="glyphicons table"  href="#vaccines"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Vaccines</span></a></li>
                        <li><a   class="glyphicons table"  href="#courses"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Courses</span></a></li>


                    </ul>
                </div>
                <!-- // Tabs Heading END -->

                <div class="widget-body">
                    <div class="tab-content">

                        <!-- Tab content -->
                        <div id="vaccines" class="tab-pane active widget-body-regular">

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>vLMIS Training of Trainer&#39;s Manual   <a class="btn btn-primary input-sm" target="_blank"
                                                                                    href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_tot_manual.pdf">Download</a></h2>
                                    <p>The ToT manual is now being used to instruct and guide the trainers on technical procedures, 
                                        data entry, data validation, report generation and any other information related to vLMIS.
                                        This manuals clearly explains how the software operates and provide instructions to users on how to use it. 
                                        Data entry and validation concerns need extensive documentation to stay abreast of government’s regulations, 
                                        safety standards, and other issues legislated the stakeholders, 
                                        for which these manual provide step by step orientation </p>
                                </div>
                                <div class="col col-md-2">
                                    <a target="_blank" href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_tot_manual.pdf">
                                        <img src="http://lmis.gov.pk/images/manuals/training_of_trainers_manual.png" 
                                             alt="vLMIS Training of Trainer&#39;s Manual"
                                             class="thumbnail">
                                    </a>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>vLMIS Participant&#39;s Guide   <a class="btn btn-primary input-sm" target="_blank"
                                                                           href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_participants_guide.pdf">Download</a></h2>
                                    <p>The participants guide enables the users to understand the logistics process information system in detail. 
                                        Through this manual, the participants can relate the learning to the role of vLMIS in strengthening 
                                        the supply chain system. The manual will also assist the participants in improving, revising, designing, 
                                        and operating all or part of a logistics system and inventory control systems. 
                                        It offers guidance on how to assess the functioning of an entire logistics system 
                                        and how to continually monitor and improve. </p>
                                </div>
                                <div class="col col-md-2">
                                    <a target="_blank" href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_participants_guide.pdf">
                                        <img src="http://lmis.gov.pk/images/manuals/vlmis_participants_guide.png" 
                                             alt="vLMIS Training of Trainer&#39;s Manual"
                                             class="thumbnail">
                                    </a>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>vLMIS Facilitator Manual   <a class="btn btn-primary input-sm" target="_blank"
                                                                      href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_facilitators_manual.pdf">Download</a></h2>
                                    <p>A step by step guide for vLMIS facilitators to determine and explain responsibilities in 
                                        implementing system’s objectives by highlighting specific job roles. 
                                        Moreover, the manual aims to impart skills pertaining to the system and 
                                        strengthen facilitator’s capacity for its complete and thorough understanding. 
                                        Adherence to this step by step guide ensures, automated reporting of logistics data, 
                                        including inventory management of vaccines and cold chain equipment 
                                        and vaccine consumption reporting. Confirming considerable improvement 
                                        and advancement in vaccine logistics management 
                                        and also preventing stock-outs of vaccines 
                                        and cold chain equipment’s at district and facility levels. </p>
                                </div>
                                <div class="col col-md-2">
                                    <a target="_blank" href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_facilitators_manual.pdf">
                                        <img src="http://lmis.gov.pk/images/manuals/vlmis_fascilitator_manual.png" 
                                             alt="vLMIS Training of Trainer&#39;s Manual"
                                             class="thumbnail">
                                    </a>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>vLMIS User Manual(CAMPAIGNS)   <a class="btn btn-primary input-sm" target="_blank"
                                                                          href="#">Download</a></h2>
                                    <p>Among the strengths in the current vaccine logistics data is that key data items are collected, 
                                        such as consumption, stock balance, and storage capacity. 
                                        Some logistics-related key performance indicators have been defined and are tracked. 
                                        Data is collected routinely and there is a defined process 
                                        flow for reporting up the system. There are established forms 
                                        and spreadsheets used to collect data, 
                                        and a vaccine stock management software solution used at the National EPI Store. 
                                        There is a culture of compiling and analyzing data for logistics decision making. 
                                        The data on existing cold chain equipment (age, type, capacity, operability) 
                                        in the national cold chain inventory as well as facility profile data 
                                        has also been collected to help identify gaps in the cold chain storage capacity 
                                        and functionality that need to be addressed. </p>
                                </div>
                                <div class="col col-md-2">
                                    <a target="_blank" href="#">
                                        <img src="http://lmis.gov.pk/images/manuals/vlmis_user_manual_campaigns.png" 
                                             alt="vLMIS Training of Trainer&#39;s Manual"
                                             class="thumbnail">
                                    </a>
                                </div>
                            </div>                          

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>vLMIS Bar Code Scanner App – User Manual   <a class="btn btn-primary input-sm" target="_blank"
                                                                                      href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_barcode_scanner_app_manual.pdf">Download</a></h2>
                                    <p>This manual enables the  users to not only update data automatically but also punch data manually. 
                                        Manual data entry enables user to track the stock either with or without the barcode. 
                                        Since mandatory barcoding can hinder the availability of vaccines with right packing, 
                                        barcode scanning application is an optional enhancement according to the availability of scanners. 
                                        Barcode Scanning makes use of the database to store information about products, 
                                        its batch and expiry information in the barcode along-with the packing volume information in liters. </p>
                                </div>
                                <div class="col col-md-2">
                                    <a target="_blank" href="http://lmis.gov.pk/training_manuals/vlmis/vlmis_barcode_scanner_app_manual.pdf">
                                        <img src="http://lmis.gov.pk/images/manuals/bar_code_scanner_app_user_manual.png" 
                                             alt="vLMIS Training of Trainer&#39;s Manual"
                                             class="thumbnail">
                                    </a>
                                </div>
                            </div>             

                            <div class="row">
                                <div class="col col-md-10">
                                    <h2>vLMIS Administrator Manual   <a class="btn btn-primary input-sm" target="_blank"
                                                                        href="#">Download</a></h2>
                                    <p>The vLMIS administrator manual guides the user on roles and responsibilities 
                                        assigned to the users for managing cold-chain logistics activities. 
                                        This includes managing users and their roles, health facilities and products. 
                                        The manual explains the step-by-step instructions on getting started 
                                        with vLMIS as a cold-chain equipment management (CCEM) administrative 
                                        and how to managing activities as a CCEM administrative. </p>
                                </div>
                                <div class="col col-md-2">
                                    <a target="_blank" href="#">
                                        <img src="http://lmis.gov.pk/images/manuals/administrator_manual.png" 
                                             alt="vLMIS Training of Trainer&#39;s Manual"
                                             class="thumbnail">
                                    </a>

                                </div>
                            </div>      


                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="courses" class="tab-pane widget-body-regular">
                            <p>For the first time Health Services Academy (HSA) Islamabad offers
                                following courses, in conjunction with the USAID|DELIVER Project;


                            <ul>
                                <li>Three Credit Course for Supply Chain Management of Public
                                    Health Commodities</li>
                                <li>Certificate Course on Supply Chain Management of Health
                                    Commodities</li>
                            </ul>

                            <p>The courses will help to increase the participants&#39; understanding
                                of the fundamentals of logistics management and the relationship
                                between supply chain logistics and commodity security. It also will
                                strengthen the participants&#39; ability to implement improvements
                                to basic elements of their logistics systems.
                            </p>

                            <h2>Lecturer&#39;s Guide: Three Credit Course for Supply Chain
                                Management of Public Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                                            href="http://lmis.gov.pk/training_manuals/three_credit_lecturer_guide.pdf">Download</a></h2>
                            <p>The Lecture Guide for the Three Credit Course on Supply Chain
                                Management of Public Health Commodities is meant for lecturers who
                                are supposed to conduct the course. This curriculum is written
                                following Adult Learning Theory principles which emphasize more
                                interactive and participatory approaches than traditional teaching
                                techniques. Small group exercises are placed into the curriculum
                                and Lecturers are encouraged to run these activities as written
                                where ever possible. The curriculum not only provides basic
                                principles for running a logistic system but includes elements that
                                are Pakistan specific. For this course each major unit of learning
                                is referred to as a Session and each section within is referred to
                                as an Activity. This course has 17 different Sessions. Lecturers
                                are highly encouraged to read the Lecturer Preparation section at
                                the beginning of each session well before leading each session.
                                Note that Synthesis Questions are presented at the end of each
                                Session. These can be used to ensure students are grasping the key
                                concepts of each session. Unlike the Certificate course this course
                                is competency-based.</p>

                            <h2>Student Guide: Three Credit Course on Supply Chain Management of
                                Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                       href="http://lmis.gov.pk/training_manuals/three_credit_student_guide.pdf">Download</a></h2>
                            <p>The Guide is meant for use of three credit course students.</p>

                            <h2>Lecturer&#39;s Guide: Certificate Course on Supply Chain
                                Management of Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                                     href="http://lmis.gov.pk/training_manuals/certificate_course_lect_guide.pdf">Download</a></h2>

                            <p>The Lecture Guide for the Certificate Course on Supply Chain
                                Management of Public Health Commodities is meant for lecturers who
                                are supposed to conduct the course. This will become a three credit
                                course and likely expand to a larger offering in time. This
                                curriculum is written following Adult Learning Theory principles
                                which emphasize more interactive and participatory approaches than
                                traditional teaching techniques. Small group exercises are placed
                                into the curriculum and Lecturers are encouraged to run these
                                activities as written. The curriculum not only provides basic
                                principles for running a logistic system but includes elements that
                                are Pakistan specific. For this course each major unit of learning
                                is referred to as a Session and each part of a Session is referred
                                to as an Activity. This course has 16 different Sessions. Lecturers
                                are highly encouraged to read the &#39;Lecturer Preparation&#39;
                                section at the beginning of each session well before leading each
                                session.</p>

                            <h2>Student Handbook: Certificate Course on Supply Chain Management
                                of Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                                                          href="http://lmis.gov.pk/training_manuals/certificate_course_student_guide.pdf">Download</a></h2>

                            <p>The handbook is meant for use of certificate course students.</p>








                        </div>
                        <!-- // Tab content END -->





                    </div>
                </div>
            </div>
            <!-- // Tabs END -->
        </div>
    </div>
</div>