<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title row-br-b-wp"> <?php echo $this->translate("Welcome"); ?>, <span style="color:#009c00;"><?php echo $this->layout()->user_name; ?>!</span></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            Getting Started
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <img src="<?php echo $this->baseUrl(); ?>/images/logo-pak.png" alt="" style="float: right; position: relative; right: 68px;" />
                                <p>with Vaccine Logistics Managment Information System (vLMIS)</p>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>