<div style="width:100%; clear:both; margin-top:30px;">
    <table width="48%" cellpadding="5" style="float:left; border:2px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Received by</b> - Name: _________________________</td>
        </tr>
        <tr>
            <td>Designation: __________________________________</td>
        </tr>
        <tr>
            <td>Signature: ____________________________________</td>
        </tr>
    </table>

    <table width="48%" cellpadding="5" style="float:right; border:2px solid #E5E5E5 !important; border-collapse:collapse;">
        <tr>
            <td><b>Store In-charge</b> - Name: _____________________</td>
        </tr>
        <tr>
            <td>Designation: __________________________________</td>
        </tr>
        <tr>
            <td>Signature: ____________________________________</td>
        </tr>
    </table>
</div>