<!-- Content -->


<div class="page-content-wrapper">
    <div class="page-content">


        <?php if (isset($this->success)) { ?>
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                <strong>Success!</strong> <?php echo $this->success; ?>
            </div>
        <?php } ?>
        <?php if (isset($this->error)) { ?>
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                <strong>Error!</strong> <?php echo $this->error; ?>
            </div>
        <?php } ?>
        <h3 class="page-title">
            <?php echo $this->translate("Log book of children vaccinated from outside UCs"); ?>
        </h3>

        <form method="POST" name="log_book_add" id="log_book_add" action="" >

            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Log Book Form For "); ?>(<?php echo date('F', mktime(0, 0, 0, $this->mm)) . "-" . $this->yy; ?>)
                                <?php $this->mm; ?> <?php echo " - " . $this->warehouse_name ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>


                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="name">
                                                    <?php echo $this->translate("Name"); ?><span class="red">*</span>
                                                </label>

                                                <?php echo $this->form->name; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="father_name">
                                                    <?php echo $this->translate("Father name"); ?><span class="red">*</span>                                                 </label>
                                                <div class="input-icon right">
                                                    <i id="reference_tooltip" data-container="body" data-original-title="Name and Father name already exists. Click on 'Save' button if you want to continue?" class="fa fa-warning tooltips" style="display: none;"></i>
                                                    <?php echo $this->form->father_name; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-1">
                                            <div class="form-group">
                                                <label class="control-label" for="age">
                                                    <?php echo $this->translate("Age(m)"); ?><span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->age; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="form-group">
                                                <label class="control-label" for="gender">
                                                    Gender<span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->gender; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="contact">
                                                    <?php echo $this->translate("Contact (Phone No.)"); ?><span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->contact; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="province">
                                                    <?php echo $this->translate("Province"); ?><span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->province; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="district">
                                                    <?php echo $this->translate("District"); ?><span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->district; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="tehsil">
                                                    <?php echo $this->translate("Tehsil"); ?><!--  <span class="red">*</span> -->
                                                </label>
                                                <?php echo $this->form->tehsil; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="uc">
                                                    <?php echo $this->translate("Union Council"); ?><!--  <span class="red">*</span> -->
                                                </label>
                                                <?php echo $this->form->uc; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row" style="background-color: #D0E8D4; margin-left: 0px; margin-right: 0px; padding-left: 2px;  ">                                        
                                        <fieldset>
                                            <legend style="color: black;">Dose Number:</legend>

                                            <?php foreach ($this->items as $row) { ?>
                                                <div class="col-md-2">
                                                    <div class="form-group">
                                                        <label class="control-label" for="item_1">
                                                            <?php echo $row['description'] ?>                                                </label>
                                                        <input id="<?php echo $row['pk_id'] ?>" class="form-control dose" type="text" value="" 
                                                               name="dose_no_of[<?php echo $row['pk_id'] ?>]" 
                                                               min="<?php echo $row['starting_no'] ?>" max="<?php echo $row['number_of_doses'] ?>" 
                                                               onkeyup="function doseValidation()"
                                                               >
                                                    </div>
                                                </div>
                                            <?php } ?>
                                        </fieldset>

                                    </div>

                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="day">
                                                    <?php echo $this->translate("Vaccinated on (Day)"); ?> 
                                                </label>
                                                <select name="day" id="day" class="form-control valid">
                                                    <?php
                                                    $num_of_days = cal_days_in_month(CAL_GREGORIAN, $this->mm, $this->yy);
                                                    for ($day = 1; $day <= $num_of_days; $day++) {
                                                        ?>
                                                        <option value="<?php echo $day; ?>"><?php echo $day; ?></option>
                                                        <?php
                                                    }
                                                    ?>

                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="address">
                                                    <?php echo $this->translate("Address"); ?><span class="red">*</span>
                                                </label>
                                                <?php echo $this->form->address; ?>
                                            </div>
                                        </div>

                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label class="control-label" for="remarks">
                                                    <?php echo $this->translate("Remarks (max 300 characters)"); ?>                                                 </label>
                                                <?php echo $this->form->remarks; ?>
                                            </div>
                                        </div>
                                        <div class="col-md-1">
                                            <div class="form-group pull-right">
                                                <div style="height: 27px;"></div>
                                                <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="button">
                                                    <?php echo $this->translate("Save"); ?>
                                                </button>
                                            </div>

                                        </div>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="do" id="do" value="<?php echo $this->do; ?>" />

        </form>
        <div id="log_book_result">
            <?php if (count($this->query) > 0) { ?>
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box green">
                            <div class="portlet-title">
                                <div class="caption">
                                    Log Book
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <div class="col-md-12" style="overflow: auto;">

                                        <table class="table table-striped table-bordered table-condensed" id="sample_2">
                                            <!-- Table heading -->
                                            <thead>
                                                <tr>
                                                    <th rowspan="2" style="font-size:12px">
                                                        S.No                                                </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Name                                                </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Father Name                                         </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Age (Months)                                        </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Contact (Phone No.)                                 </th>

                                                    <th rowspan="2" style="font-size:12px">
                                                        District                                            </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Tehsil                                            </th>

                                                    <th rowspan="2" style="font-size:12px">
                                                        Union Council                                       </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Vaccination Date                                    </th>

                                                    <th class="center" colspan="5" style="font-size:12px" >
                                                        Dose No.                                            </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Address                                             </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Remarks                                                </th>
                                                    <th rowspan="2" style="font-size:12px">
                                                        Action                                                </th>

                                                </tr>

                                                <tr>
                                                    <?php foreach ($this->items as $row) { ?>
                                                        <th style="font-size:12px"><?php echo $row['description'] ?></th>
                                                    <?php } ?>

                                                </tr>
                                            </thead>

                                            <tbody>
                                                <?php
                                                $serial_num = 1;
                                                foreach ($this->query as $row) {
                                                    ?>
                                                    <tr>
                                                        <td align="center"><?php echo $serial_num ?></td>
                                                        <td><?php echo $row['name']; ?></td>
                                                        <td><?php echo $row['father_name']; ?></td>
                                                        <td align="right"><?php echo $row['age']; ?></td>
                                                        <td><?php echo $row['contact']; ?></td>
                                                        <td><?php echo $row['district']; ?></td>
                                                        <td><?php echo $row['tehsil']; ?></td>
                                                        <td><?php echo $row['uc']; ?></td>
                                                        <td align="center"><?php echo date("d/m/Y", strtotime($row['vaccination_date'])); ?></td>
                                                        <?php foreach ($this->monthlyConsumtion2()->logBook($row['pk_id']) as $row1) { ?>
                                                            <td style="font-size:12px" class="right">

                                                                <?php echo (strlen($row1['doses']) > 0) ? $row1['doses'] : ''; ?>
                                                            </td>
                                                            <?php
                                                        }
                                                        ?>
                                                        <td><?php echo $row['address']; ?></td>
                                                        <td><?php echo $row['remarks']; ?></td>

                                                        <td align="center"><span data-toggle="notyfy" id="<?php echo $row['pk_id']; ?>" data-type="confirm"
                                                                                 data-layout="top" class="fa fa-times cursor-hand"></span></td>
                                                    </tr>
                                                    <?php
                                                    $serial_num++;
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 right">
                        <a class="btn btn-success" href="javascript:void(0);" 
                           onclick="window.open('log-book-add-print?month=<?php echo $this->mm ?>&year=<?php echo $this->yy; ?>&wh_id=<?php echo $this->wh_id; ?>', '_blank', 'scrollbars=1');">
                               <?php echo $this->translate("Print"); ?>
                        </a>

                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>