<!-- Content -->

<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #e5e5e5;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #e5e5e5;
    }
    table#mytable tr th {
        border: 1px solid #e5e5e5;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page
    {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>


<?php
if ($this->result && count($this->result) > 0) {
    $monthNum = $this->m;
    $monthName = date("F", mktime(0, 0, 0, $monthNum, 10));
    ?>

    <table style="width:100%;">
        <tr>
            <td class="left"><b style="font-size: 16px;">EPI - Provincial Requirement Vs Issuance</b> </td>
        </tr> 
        <tr>
            <td class="left"><b style="font-size: 14px;"><?php echo $this->i_warehousename . " (January,  $this->y to $monthName, $this->y)" ?></b> </td>
        </tr>
    </table>

    <table id="mytable">
        <!-- Table heading -->
        <thead>
            <tr>
                <th>
                    <?php echo $this->translate("S.No"); ?>
                </th>
                <th>
                    <?php echo $this->translate("Product"); ?>
                </th>
                <th>
                    <?php echo $this->translate("Monthly Requirement"); ?>
                </th>
                <th>
                    <?php echo $this->m . $this->translate(" Month(s) Requirement"); ?>
                </th>
                <th>
                    <?php echo $this->translate("Issued To ") . $this->i_warehousename; ?>
                </th>
                <th>
                    <?php echo $this->translate("Remaining Balance") . " for " . $this->m . " month(s) $this->y"; ?>
                </th>



            </tr>


        </thead>
        <!-- // Table heading END -->

        <!-- Table body -->
        <tbody>

            <!-- Table row -->
            <?php
            $j = 1;
            foreach ($this->result as $row) {
                ?>
                <tr class="dynamic-rows">
                    <td class="serial" style="font-size:12px" align="center">
                        <?php echo $j; ?>
                    </td>
                    <td style="font-size:12px">
                        <?php echo $row['product'] ?>
                    </td>
                    <td style="font-size:12px" align="right">
                        <?php echo number_format($row['1_month_requirement']) ?>
                    </td>
                    <td style="font-size:12px"  align="right">
                        <?php echo number_format($row['n_month_requirement']) ?>
                    </td>
                    <td style="font-size:12px" align="right">
                        <?php echo number_format($row['issuance']) ?>
                    </td>
                    <td style="font-size:12px" align="right">
                        <?php echo number_format($row['n_month_balance']) ?>
                    </td>

                </tr>
                <?php
                $j ++;
            }
            ?>
            <!-- // Table row END -->
        </tbody>
        <!-- // Table body END -->                                      

    </table>
    

    <?php
}
?>
<div style="float:left;">
    <div class="col-md-12 left">
        <b>Printed By:</b> <?php echo $this->username ?><br> 
        <b>Print Date:</b> <?php echo date("d/m/Y"); ?>
    </div>
</div>
<div>
    <div class="widget-body right">
        <button name="print" id="print" value="1" type="button" class="btn btn-primary"><?php echo $this->translate("Print"); ?></button> 
    </div>
</div>  

