<form method="POST" name="transfer_stock" id="transfer_stock" action="<?php echo $this->baseUrl(); ?>/stock/save-transfer-stock" >
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label" for="product"><?php echo $this->translate("Product"); ?></label>
                <?php echo $this->form->item_pack_size_id; ?>
            </div>
        </div> 
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label" for="batchno"><?php echo $this->translate("Batch No"); ?></label>
                <?php echo $this->form->stock_batch_id; ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label" for="available_quantity"><?php echo $this->translate("Available Quantity"); ?></label>
                <?php echo $this->form->totqty; ?>
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>  
    <div class="row">  
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label" for="location"><?php echo $this->translate("Location"); ?><span class="red">*</span></label>
                <?php echo $this->form->non_ccm_location_id; ?>
            </div>
        </div> 
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label" for="quantity"><?php echo $this->translate("Quantity"); ?><span class="red">*</span></label>
                <?php echo $this->form->quantity; ?>
            </div>
        </div> 
        <div class="col-md-6"></div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group pull-right">
                <button class="btn btn-primary input-sm" type="submit" id="btn-transfer" name="transfer">Transfer</button>
            </div>
        </div>
    </div>

    <input type="hidden" id="bin_id" name="bin_id" value="<?php echo $this->bin_id; ?>">
    <input type="hidden" id="quantity_per_pack" name="quantity_per_pack" value="<?php echo $this->quantity_per_pack; ?>">
    <input type="hidden" id="totqty" name="totqty" value="<?php echo $this->totqty; ?>">
    <input type="hidden" id="non_ccm_id" name="non_ccm_id" value="<?php echo $this->non_ccm_id; ?>">
    <input type="hidden" id="area" name="area" value="<?php echo $this->area; ?>">
    <input type="hidden" id="level" name="level" value="<?php echo $this->level; ?>">
    <?php echo $this->form->id; ?>
</form>