<?php
/**
 *  phtml for Target Issuance
 */
/**
 * Target Issuance
 */
?>
<!-- Content -->

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            <?php
            echo $this->translate("User Click Path");
            ?>
        </h3>


        <?php if ($this->user_page_count && count($this->user_page_count) > 0) { ?>

            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-4">
                            <div class="dashboard-stat lightgreen">
                                <div class="visual" style="margin-left: 20px;">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> <?php echo $this->daily_users_count[0]['avg_user_count'] ?> </div>
                                    <div class="desc">Daily Active Users</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="dashboard-stat lightgreen">
                                <div class="visual" style="margin-left: 20px;">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> <?php echo $this->weekly_users_count[0]['user_count'] ?> </div>
                                    <div class="desc">Weekly Active Users</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="dashboard-stat lightgreen">
                                <div class="visual" style="margin-left: 20px;">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> <?php echo $this->monthly_users_count[0]['user_count'] ?> </div>
                                    <div class="desc">Monthly Active Users</div>
                                </div>
                            </div>
                        </div>
                       
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget" data-toggle="collapse-widget">
                            <div class="widget-head">
                                <h4 class="heading glyphicons cargo">
                                    <i></i>
                                    Page count per Role
                                </h4>
                            </div>
                            <div class="widget-body dashlets">
                                <?php
                                require_once 'FusionCharts/Code/PHP/Includes/FusionCharts.php';
                                FC_SetRenderer('javascript');
                                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Pie3D.swf", "", $this->xmlstore, 'PageCountPerRole', '100%', 300, false, false);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget" data-toggle="collapse-widget">
                            <div class="widget-head">
                                <h4 class="heading glyphicons cargo">
                                    <i></i>
                                    Page description
                                </h4>
                            </div>
                            <div class="widget-body dashlets" id="data14">
                                <?php
                                require_once 'FusionCharts/Code/PHP/Includes/FusionCharts.php';
                                FC_SetRenderer('javascript');
                                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Pie3D.swf", "", $this->xmlstore2, 'PagesForRole', '100%', 300, false, false);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>No data found</h4>
                </div>
            </div>
        <?php } ?>
        <div id="future_arrival_details"></div>

        <div class="row">
            <div class="col-md-12">
                <?php
                ?>
            </div>
        </div> 

    </div>






</div>




