<?php
/**
 *  phtml for Ajax Edit
 */
?>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Period"); ?> <span class="red">*</span></label>
                <div class="controls">
                    <?php echo $this->form->period_name_update; ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Period Code"); ?> <span class="red">*</span></label>
                <div class="controls">
                    <?php echo $this->form->period_code_update; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 margin-top-25">
        <div class="col-md-4">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Begin Month"); ?> <span class="red">*</span></label>
                <div class="controls">
                    <?php echo $this->form->begin_month; ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("End Month"); ?> <span class="red">*</span></label>
                <div class="controls">
                    <?php echo $this->form->end_month; ?>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php echo $this->form->pk_id; ?>
