<?php

/**
 * Model_HelpMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmal@deliver-pk.org>
 * @version    2.5.1
 */
class Model_HelpMessages extends Model_Base {

    /**
     *
     * @var type 
     */
    private $_table;

    const DEACTIVE = 0;
    const ACTIVE = 1;
    const DELETED = 2;

    /**
     * 
     */
    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('HelpMessages');
    }

    /**
     * 
     * @param type $order
     * @param type $sort
     * @return type
     */
    public function getBySearch($order = null, $sort = null) {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("hp.pkId, hp.description, hp.status, r.resourceName")
                ->from("HelpMessages", "hp")
                ->leftJoin('hp.resource', 'r');
        if (!empty($this->form_values['deleted'])) {
            $str_sql->where("hp.status = '" . Model_HelpMessages::DELETED . "' ");
        } else {
            $str_sql->where("hp.status <> '" . Model_HelpMessages::DELETED . "' ");
        }
        if (!empty($this->form_values['pkId'])) {
            $str_sql->andWhere("hp.pkId = '" . $this->form_values['pkId'] . "' ");
        }
        if (!empty($this->form_values['search_text'])) {
            $str_sql->andWhere("hp.description LIKE '%" . $this->form_values['search_text'] . "%'  ");
        }
        if (!empty($this->form_values['page_name'])) {
            $str_sql->andWhere("hp.resource = " . $this->form_values['page_name'] . "");
        }
        if ($order == 'sr_no') {
            $str_sql->orderBy("hp.pkId", $sort);
        }
        if ($order == 'title') {
            $str_sql->orderBy("hp.description", $sort);
        }
        if ($order == 'status') {
            $str_sql->orderBy("hp.status", $sort);
        }

        $row = $str_sql->getQuery()->getResult();
        return $row;
    }

}
