<?php

/**
 * Model_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author    Hannan mehmood <ajmal@deliver-pk.org>
 * @version    2.5.1
 */
class Model_Item extends Model_Base {

    /**
     *
     * @var type 
     */
    public $item_pack_size_id;

    /**
     *
     * @var type 
     */
    private $_table;

    /**
     * 
     */
    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Items');
    }

    /**
     * 
     * @return type
     */
    public function getProductList() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("ips.pkId,  ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->ORDERBY("ips.listRank");
        return $row = $str_sql->getQuery()->getResult();
    }

    /**
     * 
     * @return type
     */
    public function getProductByCategory() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("ips.pkId,  ips.itemName")
                ->from("ItemPackSizes", "ips")
                ->where("ips.itemCategory IN (1,2)");
        return $row = $str_sql->getQuery()->getResult();
    }

    /**
     * 
     * @return type
     */
    public function getAllItems() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("i.pkId, i.description")
                ->from("Items", "i");
        $row = $str_sql->getQuery()->getResult();

        return $row;
    }

}
