<?php

/**
 * Model_CcmAssetTypes
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Cold Chain
 * @author     Ajmal Hussain <ajmal@deliver-pk.org>
 * @version    2.5.1
 */
class Model_ItemCategories extends Model_Base {

    /**
     *
     * @var type 
     */
    private $_table;

    const VACCINES = 1;
    const NONVACCINES = 2;
    const DILUENT = 3;

    /**
     * 
     */
    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('ItemCategories');
    }

    /**
     * 
     * @return type
     */
    public function getAllCategories() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("ic.pkId,ic.itemCategoryName")
                ->from("ItemCategories", "ic");
        $rows = $str_sql->getQuery()->getResult();
        return $rows;
    }

    /**
     * 
     * @return type
     */
    public function getItemCategories() {
        $str_sql = $this->_em->createQueryBuilder()
                ->select("ic.pkId,ic.itemCategoryName")
                ->from("ItemCategories", "ic");
        if (!empty($this->form_values['item_category_name'])) {
            $str_sql->where("ic.itemCategoryName = '" . $this->form_values['item_category_name'] . "' ");
        }
        $rows = $str_sql->getQuery()->getResult();
        return $rows;
    }

    /**
     * 
     * @return type
     */
    public function checkItemCategory() {
        $form_values = $this->form_values;

        $str_sql = $this->_em->createQueryBuilder()
                ->select("i.pkId")
                ->from('ItemCategories', 'i')
                ->where("i.itemCategoryName = '" . $form_values . "' ");

        $rs = $str_sql->getQuery()->getResult();
        return $rs;
    }

}
