<?php

/**
 * Model_ReportOptions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmal@deliver-pk.org>
 * @version    2.5.1
 */
class Model_ReportOptions extends Model_Base {

    /**
     *
     * @var type 
     */
    private $_table;

    /**
     * 
     */
    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('ReportOptions');
    }

    /**
     * 
     * @return type
     */
    public function getReportDataSql() {
        return $this->_table->findOneBy(
                        array(
                            'reportStakeholder' => $this->form_values['stakeholder'],
                            'reportId' => $this->form_values['report_id'],
                            'reportComparision' => $this->form_values['report_comp']
                        )
        );
    }

}
