<?php
if ($this->data != false) {
    ?>
    <option value=""><?php echo $this->translate("Select"); ?></option>
    <?php
    foreach ($this->data as $row) {
        ?>
        <option value="<?php echo $row['pkId']; ?>"><?php echo $row['assetTypeName']; ?></option>
        <?php
    }
} else {
    ?>
    <option value=""><?php echo $this->translate("Select Asset Type First"); ?></option>
    <?php
}
?>